### ISSUE TITLE
issue mupx deploy

### ISSUE THREAD

**Issue by jujes** [arunoda/meteor-up-legacy#1001]
**some one know how fix it?**

nvm ls
          v4.4.4
          v5.11.1
->       v6.1.0

**if I use normal mode work...**

```
meteor create simple-todos && cd simple-todos
meteor npm install
meteor
```

**here my output**

```
mupx deploy
(node:22069) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /00/dev/up/simple-todos
Using buildOptions : {}
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Readable.<anonymous> (/home/jujes/.nvm/versions/node/v6.1.0/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by MasterJames** [comment]
Did you run mupx setup? (Not mup unless you using kadirahq/meteor-up)
Are you sure you updated graceful-fs if you're using it?

**Comment by bimmlerd** [comment]
I don't think it's related to graceful-fs, rather to node removing deprecated features: https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6. Using node 4.4 should work (using, for example, nvm).

**Comment by MasterJames** [comment]
Good eye. Version 6 won't work for another month or two hopefully sooner then later.

**Comment by DiesIrae** [comment]
Got the same error. Hope it will be resolved soon!

**Comment by Denhai** [comment]
So the temporary solution is to use a version of node older than 6.1 on your local machine?

**Comment by MasterJames** [comment]
It's just meteor itself that will eventually work with 6.
5 has been made to work but odd versions are more temporary and 4 is already going so 6 will be the new nodejs version that's bundled with meteor.
One can call 'meteor npm init' etc. and so that's different then the running the local installed version so then you end up with a problem... err something like that. Maybe someone else can rephrase that with more clarity.

[Prophetic Rant]
There is now days Meteor's multi integration route called Apollostack shaping up and typescript being adapted all over with GraphQL and Meteor popularity driving some of the legacy Type based devs (java minds) and their bigger corporate players coming on board to this lemmings level of madness we call the singularity to consider in all this.
Frankly I think it will collapse into something simple. Seems pretty ironic a non type based language that won the language wars is getting typed now but people have not learned to think like machines yet so ya lemmings at work. Chrome optimizes types in runtime now so if you remember not to cross your types in arrays it runs faster anyway.
Once the computer is taught to evolve the code through an iterative test driven process it will all crystallize into an open decentralized massive share folder aka quorum with a P2P Job-centric work flow but that might take another 40 years.
So ya better stick to 5 while you wait for 6 in Meteor and or learn to roll your own as I all too often have but it's a nice place to be.
BTW the DOM is already dead to me... long live OpenGL aka Vulkan or whatever they're calling it now.

Have you tried kadirahq/meteor-up? Both these versions here are pretty much depriciated by all the changes as there has been no updates here since pre-1.2.

**Comment by OptimisticLock** [comment]
Would be nice meanwhile to explicitly check for node version and give a meaningful error message.

**Comment by MasterJames** [comment]
Right I agree anyway all suggestion for future improvements need to be directed to the new version if still relavent. See kadirahq/meteor-up 
There is a DEBUG way to get more error detail and a mupx logs that uses docker logs to see internal docker container logs. 
But there are loads of pretty cryptic errors.

**Comment by atulmy** [comment]
If anyone using mac has same issue, working solution:

`brew unlink node`
`brew install homebrew/versions/node4-lts`
`node -v` // v4.4.5

and then you can `mupx deploy`

**Comment by slissner** [comment]
I was running in a similar error during `mupx deploy`

> buffer.js:106
>       throw new Error(
>       ^
> 
> Error: If encoding is specified then the first argument must be a string
>     at new Buffer (buffer.js:106:13)
>     at Readable.<anonymous> (/usr/local/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js:32:15)
>     at emitNone (events.js:91:20)
>     at Readable.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:926:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

A workaround is to open the file with your text editor (I use atom):
`atom /usr/local/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js`

And edit the variable that is used in line 32:15.

Meaning, go to line 22 and replace:

`var size = 0;`

with:

`var size = "0";`

See also, http://stackoverflow.com/questions/14835582/nodejs-first-argument-must-be-a-string-or-buffer-when-using-response-write-w

At least it is working now for me.

**Comment by velum** [comment]
> A workaround is to open the file with your text editor (I use atom):
> atom /usr/local/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js
> 
> And edit the variable that is used in line 32:15.
> 
> Meaning, go to line 22 and replace:
> 
> var size = 0;
> 
> with:
> 
> var size = "0";

I would not do that. If you look a few lines down in that file, you will find this line:

`size += chunk.length;`

If size is a sting, the above line will do a concatenation instead of a sum. Maybe a better solution would be to modify line 32, and add `.toString()` after `size`, like this:

`var buf = new Buffer(size.toString(), 'utf8');`

I did not need to change this code though using node v0.10.40

**Comment by momeni** [comment]
> > ```
> > A workaround is to open the file with your text editor (I use atom):
> > atom /usr/local/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js
> > 
> > And edit the variable that is used in line 32:15.
> > 
> > Meaning, go to line 22 and replace:
> > 
> > var size = 0;
> > 
> > with:
> > 
> > var size = "0";
> > ```
> 
> I would not do that. If you look a few lines down in that file, you will find this line:
> 
> size += chunk.length;
> 
> If size is a sting, the above line will do a concatenation instead of a sum. Maybe a better solution would be to modify line 32, and add .toString() after size, like this:
> 
> var buf = new Buffer(size.toString(), 'utf8');

Even the above change won't fix it because the Buffer constructor (when called with 'utf8' as its second argument) will create a buffer and fills it with the content which is provided as its first argument (this is why it now complains about the numeric argument).
And the code below it is filling the buffer in a foreach assuming that buffer has been allocated as large as indicated by the size (in bytes; not the content of size as a string).

So, it should be updated similar to the [archiver-utils](https://github.com/archiverjs/archiver-utils/blob/master/index.js) package by removing the second argument, like this:

`var buf = new Buffer(size);`

**Comment by derwaldgeist** [comment]
Just stumbled on this. What is the recommended way to fix this, now that Kadira has left the Meteor community? Should I update to kadirahq:meteor-up instead? Will this work with a Meteor 1.2 app?
