### ISSUE TITLE
Node error on first deploy

### ISSUE THREAD

**Issue by gavin-hall** [arunoda/meteor-up-legacy#1013]
Using buildOptions : {}
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Readable.<anonymous> (/usr/local/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by gavin-hall** [comment]
Running node 6.1.0 locally and tried putting 6.1.0 in mup.json as well as 0.10.43. Bit confused here.

**Comment by gavin-hall** [comment]
Solved by downgrading my Mac's local Node version from 6.1.0 to 4.4.4.

**Comment by MasterJames** [comment]
Nodejs 5 might work too. 6 should be coming to Meteor in a month or so hopefully.
