### ISSUE TITLE
mupx / fibres deployment problem

### ISSUE THREAD

**Issue by LaughingBubba** [arunoda/meteor-up-legacy#1015]
Hi I'm trying to deploy using mupx and I'm coming up with this error (see the log below).

Is this a problem with the version of npm withing the docker image being incompatible with my local version or something not quite right with the docker image per se?

What have I missed?

PS: I'm running meteor 1.3 on windows and npm 3.9
## The Log >>>

Configuration file : mup.json
Settings file      : settings.json

[123.45.67.89]     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)

[123.45.67.89]     at Module._compile (module.js:456:26)
[123.45.67.89] => Starting meteor app on port:80
[123.45.67.89]     at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)

**/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe**
              ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

`

**Comment by LaughingBubba** [comment]
I changed deploy wait time to 60 as per [#520 ](https://github.com/arunoda/meteor-up/issues/520)

works fine ... ARGH!
