### ISSUE TITLE
ERROR: Verifying deployment 

### ISSUE THREAD

**Issue by akaiworld** [arunoda/meteor-up-legacy#1019]
I get an error when deploying the app to the server:

`
MBP-Anton:EventsApp-MeteorUp antonioffe$ mupx setup
## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Started TaskList: Setup (linux)
[104.131.17.179] - Installing Docker
[104.131.17.179] - Installing Docker: SUCCESS
[104.131.17.179] - Setting up Environment
[104.131.17.179] - Setting up Environment: SUCCESS
[104.131.17.179] - Copying MongoDB configuration
[104.131.17.179] - Copying MongoDB configuration: SUCCESS
[104.131.17.179] - Installing MongoDB
[104.131.17.179] - Installing MongoDB: SUCCESS
MBP-Anton:EventsApp-MeteorUp antonioffe$ mupx deploy
## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /Users/antonioffe/Desktop/Документы/Web/MAMP/meteor/EventsApp
Using buildOptions : {}

Started TaskList: Deploy app 'meteor' (linux)
[104.131.17.179] - Uploading bundle
[104.131.17.179] - Uploading bundle: SUCCESS
[104.131.17.179] - Sending environment variables
[104.131.17.179] - Sending environment variables: SUCCESS
[104.131.17.179] - Initializing start script
[104.131.17.179] - Initializing start script: SUCCESS
[104.131.17.179] - Invoking deployment process
[104.131.17.179] - Invoking deployment process: SUCCESS
[104.131.17.179] - Verifying deployment
[104.131.17.179] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
 deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/bundle/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

`

Here are the latest logs:
`
MBP-Anton:EventsApp-MeteorUp antonioffe$ mupx logs --tail=50
## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

[104.131.17.179]     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[104.131.17.179]     at Module._compile (module.js:456:26)
[104.131.17.179]     at Object.Module._extensions..js (module.js:474:10)
[104.131.17.179]     at Module.load (module.js:356:32)
[104.131.17.179]     at Function.Module._load (module.js:312:12)
[104.131.17.179]     at Module.require (module.js:364:17)
[104.131.17.179]     at require (module.js:380:17)
[104.131.17.179]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[104.131.17.179]     at Module._compile (module.js:456:26)
[104.131.17.179]     at Object.Module._extensions..js (module.js:474:10)
[104.131.17.179] npm WARN deprecated This version of npm lacks support for important features,
[104.131.17.179] npm WARN deprecated such as scoped packages, offered by the primary npm
[104.131.17.179] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[104.131.17.179] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[104.131.17.179] npm WARN deprecated
[104.131.17.179] npm WARN deprecated   npm -g install npm@latest-2
[104.131.17.179] npm WARN deprecated
[104.131.17.179] npm WARN deprecated To upgrade to the latest stable version, run:
[104.131.17.179] npm WARN deprecated
[104.131.17.179] npm WARN deprecated   npm -g install npm@latest
[104.131.17.179] npm WARN deprecated
[104.131.17.179] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[104.131.17.179] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[104.131.17.179] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[104.131.17.179] npm WARN deprecated
[104.131.17.179] npm WARN deprecated If you're running the version of npm bundled with
[104.131.17.179] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[104.131.17.179] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[104.131.17.179] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[104.131.17.179] npm WARN deprecated semver behavior.
[104.131.17.179] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[104.131.17.179] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[104.131.17.179] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[104.131.17.179] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[104.131.17.179] => Starting meteor app on port:80
[104.131.17.179]
[104.131.17.179] /bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[104.131.17.179]    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
[104.131.17.179]          ^
[104.131.17.179] Error:`/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`is missing. Try reinstalling`node-fibers`?
[104.131.17.179]     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[104.131.17.179]     at Module._compile (module.js:456:26)
[104.131.17.179]     at Object.Module._extensions..js (module.js:474:10)
[104.131.17.179]     at Module.load (module.js:356:32)
[104.131.17.179]     at Function.Module._load (module.js:312:12)
[104.131.17.179]     at Module.require (module.js:364:17)
[104.131.17.179]     at require (module.js:380:17)
[104.131.17.179]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[104.131.17.179]     at Module._compile (module.js:456:26)
[104.131.17.179]     at Object.Module._extensions..js (module.js:474:10)
MBP-Anton:EventsApp-MeteorUp antonioffe$
`

When I start a new standart meteor app and try to deploy it with mupx deploy - i get error.
When I start a new standart meteor app and try to deploy it with mupx deploy, but first do mupx setup - it works well!

When i add needed packages and code - i get error again.
BUT!
When i just started trying to deploy the first time with the whole code it worked well, too!
Then i added body-parser with
meteor npm install body-parser
... and tryed Npm.require('body-parser') - I started to constantly get such errors. Event after rebuilding the whole app without body-parser.

Now I can not deploy the app... And can not fugire out where is the problem...

**Comment by akaiworld** [comment]
I changed   "deployCheckWaitTime" to 60 and deployment worked well again! 
Thanks https://github.com/arunoda/meteor-up/issues/305
https://github.com/arunoda/meteor-up/issues/905

**Comment by hems** [comment]
weird funny error that shows up for a lot of people and is fixed with waiting time on deploy..

that's realllllly weird //=

doesn't seem to solve my issue tough
