### ISSUE TITLE
mupx failed to deploy on new/bare server

### ISSUE THREAD

**Issue by acamarata** [arunoda/meteor-up-legacy#1027]
```
$ mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Setup (linux)
[188.166.190.228] - Installing Docker
[188.166.190.228] - Installing Docker: SUCCESS
[188.166.190.228] - Setting up Environment
[188.166.190.228] - Setting up Environment: SUCCESS
[188.166.190.228] - Copying MongoDB configuration
[188.166.190.228] - Copying MongoDB configuration: SUCCESS
[188.166.190.228] - Installing MongoDB
[188.166.190.228] - Installing MongoDB: SUCCESS

$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/acamarata/Sites/sunnah
Using buildOptions : {}

Started TaskList: Deploy app 'sunnah' (linux)
[188.166.190.228] - Uploading bundle
[188.166.190.228] - Uploading bundle: SUCCESS
[188.166.190.228] - Sending environment variables
[188.166.190.228] - Sending environment variables: SUCCESS
[188.166.190.228] - Initializing start script
[188.166.190.228] - Initializing start script: SUCCESS
[188.166.190.228] - Invoking deployment process
[188.166.190.228] - Invoking deployment process: SUCCESS
[188.166.190.228] - Verifying deployment
[188.166.190.228] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
     run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    > fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
    > node build.js || nodejs build.js

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------

$ mupx logs --tail=50

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[188.166.190.228] Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
[188.166.190.228]     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[188.166.190.228]     at Module._compile (module.js:456:26)
[188.166.190.228]     at Object.Module._extensions..js (module.js:474:10)
[188.166.190.228]     at Module.load (module.js:356:32)
[188.166.190.228]     at Function.Module._load (module.js:312:12)
[188.166.190.228]     at Module.require (module.js:364:17)
[188.166.190.228]     at require (module.js:380:17)
[188.166.190.228]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[188.166.190.228]     at Module._compile (module.js:456:26)
[188.166.190.228]     at Object.Module._extensions..js (module.js:474:10)
[188.166.190.228] npm WARN deprecated This version of npm lacks support for important features,
[188.166.190.228] npm WARN deprecated such as scoped packages, offered by the primary npm
[188.166.190.228] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[188.166.190.228] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[188.166.190.228] npm WARN deprecated 
[188.166.190.228] npm WARN deprecated   npm -g install npm@latest-2
[188.166.190.228] npm WARN deprecated 
[188.166.190.228] npm WARN deprecated To upgrade to the latest stable version, run:
[188.166.190.228] npm WARN deprecated 
[188.166.190.228] npm WARN deprecated   npm -g install npm@latest
[188.166.190.228] npm WARN deprecated 
[188.166.190.228] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[188.166.190.228] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[188.166.190.228] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[188.166.190.228] npm WARN deprecated 
[188.166.190.228] npm WARN deprecated If you're running the version of npm bundled with
[188.166.190.228] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[188.166.190.228] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[188.166.190.228] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[188.166.190.228] npm WARN deprecated semver behavior.
[188.166.190.228] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[188.166.190.228] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[188.166.190.228] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[188.166.190.228] => Starting meteor app on port:80
[188.166.190.228] 
[188.166.190.228] /bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[188.166.190.228]   throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
[188.166.190.228]         ^
[188.166.190.228] Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
[188.166.190.228]     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[188.166.190.228]     at Module._compile (module.js:456:26)
[188.166.190.228]     at Object.Module._extensions..js (module.js:474:10)
[188.166.190.228]     at Module.load (module.js:356:32)
[188.166.190.228]     at Function.Module._load (module.js:312:12)
[188.166.190.228]     at Module.require (module.js:364:17)
[188.166.190.228]     at require (module.js:380:17)
[188.166.190.228]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[188.166.190.228]     at Module._compile (module.js:456:26)
[188.166.190.228]     at Object.Module._extensions..js (module.js:474:10)
```

**Comment by MasterJames** [comment]
Try setting your node version to 0.10.40 
https://github.com/arunoda/meteor-up/issues/852
Also. ..
If you update to meteor 1.3.2.4+ it will also help and finally sometimes extending the deploy wait time to about 120 helps too at the final stage (but in this case it's not that initial assumption.)
