### ISSUE TITLE
Verifying deployment: FAILED

### ISSUE THREAD

**Issue by dominicarrojado** [arunoda/meteor-up-legacy#1036]
Hi I just encountered this error. I tried searching for the error, couldn't find a solution. How to fix this? Thank you!

```
[52.74.10.127] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    es/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.10.43
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    Build failed
    sh: 1: nodejs: not found

    npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
    npm ERR! Exit status 127
    npm ERR! 
    npm ERR! Failed at the fibers@1.0.8 install script.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node build.js || nodejs build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-74-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
    npm ERR! cwd /bundle/bundle/programs/server
    npm ERR! node -v v0.10.43
    npm ERR! npm -v 1.4.29
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

**Comment by tima101** [comment]
Same here. Today: Verifying deployment: Failed. But worked yesterday.

Changing "deployCheckWaitTime" does not help.

**Comment by dominicarrojado** [comment]
Somehow it was able to deploy now @tima101

**Comment by tima101** [comment]
@mroftalp I was able to deploy as well. Do you host on Digital Ocean?

**Comment by dominicarrojado** [comment]
No, host on AWS @tima101

**Comment by tima101** [comment]
@arunoda this deployment error occurs on some deployment attempts (not all).

```
[159.203.229.254] - Uploading bundle
[159.203.229.254] - Uploading bundle: SUCCESS
[159.203.229.254] - Sending environment variables
[159.203.229.254] - Sending environment variables: SUCCESS
[159.203.229.254] - Initializing start script
[159.203.229.254] - Initializing start script: SUCCESS
[159.203.229.254] - Invoking deployment process
[159.203.229.254] - Invoking deployment process: SUCCESS
[159.203.229.254] - Verifying deployment
[159.203.229.254] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    es/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.10.43
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    Build failed
    sh: 1: nodejs: not found

    npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
    npm ERR! Exit status 127
    npm ERR! 
    npm ERR! Failed at the fibers@1.0.8 install script.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node build.js || nodejs build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-85-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
    npm ERR! cwd /bundle/bundle/programs/server
    npm ERR! node -v v0.10.43
    npm ERR! npm -v 1.4.29
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

**Comment by lukeacl** [comment]
I've only started getting these issues today on a project that hasn't changed and on a Ubuntu server that hasn't changed. I've tried 20 ish times, it half deployed for one of them, by that I mean it spewed errors but the site appeared to be live. This is in the logs. Previously there were 404 errors.

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
[172.16.70.168] npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[172.16.70.168] npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[172.16.70.168] npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[172.16.70.168] npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[172.16.70.168] => Starting meteor app on port:80
[172.16.70.168] 
/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[172.16.70.168]     at Module.require (module.js:364:17)
    at require (module.js:380:17)
[172.16.70.168]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[172.16.70.168]     at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by MasterJames** [comment]
Maybe try and see if there is the same problem with the newer version at kadirahq/meteor-up

**Comment by aspin** [comment]
lol did we make an issue at right about the same time? just worked for me as well.

**Comment by tomtom87** [comment]
Hey guys getting this flavour of the error, just updated mupx and trying deployment on a meteor 1.3.2.4 project with mupx for first time on ubuntu host

```
mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/tom/web/trusu
Using buildOptions : {}

Started TaskList: Deploy app 'trusu' (linux)
[119.81.157.91] - Uploading bundle
[119.81.157.91] - Uploading bundle: SUCCESS
[119.81.157.91] - Sending environment variables
[119.81.157.91] - Sending environment variables: SUCCESS
[119.81.157.91] - Initializing start script
[119.81.157.91] - Initializing start script: SUCCESS
[119.81.157.91] - Invoking deployment process
[119.81.157.91] - Invoking deployment process: SUCCESS
[119.81.157.91] - Verifying deployment
[119.81.157.91] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
      npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    > fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
    > node build.js || nodejs build.js


    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

**Comment by tima101** [comment]
@tomtom87 Try increasing "deployCheckWaitTime" to 120 sec.

@MasterJames any comment for this error? Thanks.

```
    es/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.10.43
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    Build failed
    sh: 1: nodejs: not found
```

**Comment by tomtom87** [comment]
@tima101  I increased the deploy time and now get this error

```
DEBUG=* mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/myuser/web/trusu
Using buildOptions : {}

Started TaskList: Deploy app 'trusu' (linux)
[119.81.157.91] - Uploading bundle
  nodemiral:sess:119.81.157.91 copy file - src: /tmp/1de0599d-1413-4f40-a073-0ebeafb27b62/bundle.tar.gz, dest: /opt/trusu/tmp/bundle.tar.gz, vars: undefined +0ms
[119.81.157.91] - Uploading bundle: SUCCESS
[119.81.157.91] - Sending environment variables
  nodemiral:sess:119.81.157.91 copy file - src: /usr/local/lib/node_modules/mupx/templates/linux/env.list, dest: /opt/trusu/config/env.list, vars: {"env":{"ROOT_URL":"http://myproductionurl.com","MAIL_URL":"smtp://user:password@smtp.sendgrid.net:587","MONGO_URL":"mongodb://localhost:27017/appname","CLUSTER_ENDPOINT_URL":"http://my-server-ip:80"},"appName":"appname"} +26s
[119.81.157.91] - Sending environment variables: SUCCESS
[119.81.157.91] - Initializing start script
  nodemiral:sess:119.81.157.91 copy file - src: /usr/local/lib/node_modules/mupx/templates/linux/start.sh, dest: /opt/trusu/config/start.sh, vars: {"appName":"trusu","useLocalMongo":false,"port":80} +390ms
[119.81.157.91] - Initializing start script: SUCCESS
[119.81.157.91] - Invoking deployment process
[119.81.157.91] - Invoking deployment process: SUCCESS
[119.81.157.91] - Verifying deployment
[119.81.157.91] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    ounts-base/accounts_server.js:18:5)
        at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
        at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
        - - - - -
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
        at [object Object].emit (events.js:106:17)
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:458:13)

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

Trying `mup logs --tail=50` gives a usage error.

**Comment by aspin** [comment]
Be sure to do `mupx logs --tail=50` -- documentation needs to be updated for that. Not sure if I can help with your specific error though -- mine appeared to be some sort of intermittent one.

**Comment by tomtom87** [comment]
@aspin thanks for clearing that up man very appreciated

**Comment by tomtom87** [comment]
Yo guys, looks like meteor cannot connect to my mongo I specified on the local IP. 

```
 mupx logs --tail=50

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[119.81.157.91]     at process._tickCallback (node.js:458:13)
[119.81.157.91] => Starting meteor app on port:80
[119.81.157.91] npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)

/bundle/bundle/programs/server/node_modules/fibers/future.js:300
                        throw(ex);
                              ^
Error: failed to connect to [localhost:27017]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
```

What should I do to get this working?

**Comment by tomtom87** [comment]
`mup.json` env configuration:

```
"env": {
    "PORT": 80,
    "ROOT_URL": "http://production.mysite.com",
    "MAIL_URL": "smtp://username:pasword123@smtp.sendgrid.net:587",
    "MONGO_URL": "mongodb://localhost:27017/appname"
  },
```

Is this ok to use `MONGO_URL` in this manner with `mupx` ?

**Comment by MasterJames** [comment]
I think it's saying it couldn't connect to mongodb?
Maybe post settings and what is the target platform? only Ubuntu 14+ is supported.
Otherwise check the settings. If nothing was deployed before I suppose it doesn't roll back much so you should be able to ssh into the target and see what it did or didn't do via docker. Also check the firewall rules etc.

**Comment by MasterJames** [comment]
Oh whoa the message are flying here. 
Update everything and wipe node_modules and if still no dice try kadirahq/meteor-up to see if that makes any difference.

**Comment by tomtom87** [comment]
@MasterJames  yeh right, strange. I have ensured mongodb is running but it cannot connect, although `upstart` was working (I previously deployed on upstart) I couldn't get SSL working there so was referred to `mupx` as the best solution. 

Target platform: Ubuntu 14

I have ssh'd into the machine and taking a look around. What firewall rules need to be enabled?

I will try with the `kadriahq/meteor-up` then also. Thanks @MasterJames

**Comment by tomtom87** [comment]
Ok so now I tried with using `mongodb://127.0.0.1` instead of `mongodb://localhost` and specified `setupMongo` to true. Ran into another issue which I am creating a separate ticket for here (https://github.com/arunoda/meteor-up/issues/1037)

**Comment by PolGuixe** [comment]
I was getting this error: 

```
-----------------------------------STDERR-----------------------------------
     run:
    npm WARN deprecated
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    > fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
    > node build.js || nodejs build.js

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------

```

and I extended the   "deployCheckWaitTime" to  60 seconds.

Since then no errors
