### ISSUE TITLE
wait-for-mongo: failed to connect

### ISSUE THREAD

**Issue by dfischer** [arunoda/meteor-up-legacy#104]
Fresh install... doesn't work with mongo?

```
✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '107.170.25.49' (RSA) to the list of known hosts.
    stop: Unknown instance:

    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
    -----------------------------------STDOUT-----------------------------------
    .1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    ----------------------------------------------------------------------------
```

**Comment by poojabansal** [comment]
Seems like mongod is not running on the server.
Please check it as:
$ ps aux | grep mongod
If its not running, You can start it as:
$ mongod &

**Comment by davidrinnan** [comment]
I got same error and when I run mongod on the server I get 

> ERROR: dbpath (/data/db) does not exist.
> Create this directory or give existing directory in --dbpath.

**Comment by davidrinnan** [comment]
This is the complete error message: 

```
-----------------------------------STDERR-----------------------------------
ry',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/xx/.node-gyp/0.10.32',
gyp info spawn args   '-Dmodule_root_dir=/opt/xx/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/usr/local/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
    throw err;
          ^
Error: TIMEOUTED_WAIT_FOR_MONGO
    at null._onTimeout (/usr/local/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
-----------------------------------STDOUT-----------------------------------
.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
wait-for-mongo: failed to connect to [127.0.0.1:27017]
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'xx' (linux)

**Comment by poojabansal** [comment]
Did you try the solution at http://stackoverflow.com/questions/24599119/mongodb-not-working-error-dbpath-data-db-does-not-exist?

**Comment by davidrinnan** [comment]
I have now, didnt try before because I didnt want to risk setting up directories in any other way than how meteor-up intended. But I have tried now. 

I got a followup message when trying to run mongod. Too low diskspace for setting up journaling. I increased disk size and mongod now starts. I am wondering if maybe this was the original error? but meteor-up didnt have a way to handle it? 

I have now tried mup deploy and it works. Now just have to figure out if the auto start of mongo, etc, or anything else was bricked.

**Comment by davidrinnan** [comment]
ok.. final report. I tried rebooting the server and everything starts automatically, including mongod. 

I dont know why meteor-up didnt create the data/db directory. the problem with too low disk space for journaling doesnt come until after that directory exists so I have a hard time seeing that could be the issue. 

anyways everything runs smooth now, thanks for the help @poojabansal
