### ISSUE TITLE
mupx deploy error - keep getting npm@latest and fiber errors

### ISSUE THREAD

**Issue by lpatmo** [arunoda/meteor-up-legacy#1051]
I'm trying to deploy a meteor 1.3 app to DigitalOcean. I installed mupx.

When I run `mupx start`, I get this:

```
mupx start

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Starting Application (linux)
[198.199.114.30] - Starting app
[198.199.114.30] - Starting app: SUCCESS
[198.199.114.30] - Verifying deployment
[198.199.114.30] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
    npm WARN deprecated latest stable version. To upgrade to npm@2, run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest-2
    npm WARN deprecated 
    npm WARN deprecated To upgrade to the latest stable version, run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

Next, I run `npm -g install npm@latest`, but no matter how many times I try to install it I still get the same error.

When I run `mup logs -f`, I get the following error:

```
[198.199.114.30] npm WARN deprecated This version of npm lacks support for important features,
[198.199.114.30] npm WARN deprecated such as scoped packages, offered by the primary npm
[198.199.114.30] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[198.199.114.30] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[198.199.114.30] npm WARN deprecated 
[198.199.114.30] npm WARN deprecated   npm -g install npm@latest-2
[198.199.114.30] npm WARN deprecated 
[198.199.114.30] npm WARN deprecated To upgrade to the latest stable version, run:
[198.199.114.30] npm WARN deprecated 
[198.199.114.30] npm WARN deprecated   npm -g install npm@latest
[198.199.114.30] npm WARN deprecated 
[198.199.114.30] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[198.199.114.30] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[198.199.114.30] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[198.199.114.30] npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[198.199.114.30] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[198.199.114.30] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[198.199.114.30] npm WARN deprecated semver behavior.
[198.199.114.30] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[198.199.114.30] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[198.199.114.30] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[198.199.114.30] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[198.199.114.30] => Starting meteor app on port:80
[198.199.114.30] 
[198.199.114.30] /bundle/bundle/programs/server/node_modules/fibers/future.js:267
[198.199.114.30]                        throw(ex);
[198.199.114.30]                              ^
[198.199.114.30] Error: Match error: Expected string, got undefined in field username
    at exports.check (packages/check/match.js:34:1)
    at _createUser (packages/accounts-password/password_server.js:972:3)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1067:10)
    at server/server.js:28:25
    at /bundle/bundle/programs/server/boot.js:290:5
```

I took it to mean I should run `npm uninstall fiber` and `npm install fiber`, which I did, but I still keep getting the same error.

Finally, this is what my mup.json file looks like:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "100.100.100.10",
      "username": "root",
      "password": "password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      "pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      //"env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  //"setupMongo": true,

  // Application name (no spaces).
  "appName": "codebuddies",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": ".",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://100.100.100.10",
    "MONGO_URL": "mongodb://[user]:[password]@ds100000.mlab.com:10000/cbv2"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 120,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

Help appreciated!

**Comment by MasterJames** [comment]
Always backup of course.
Here are some things to try in order of possible solutions.
Update to Meteor 1.3.2.4+ and also 'update' all the rest of it.
Redo setup etc.
Use DEBUG=\* mupx deploy for possible extra logging
Basically the goal of the newer 1.3+ meteor version was not achieved until 1.3.2.4 which achieves the goals of properly building modules/packages on different targets.
The fiber error is a warning that an extra added node_module doesn't come withe the correct binaries needed for the target platform.
You can try removing packages or add them to a blank project that does deploy to find which ones are problematic.
Sometime people delete the node_modules directory to purge bogus binaries. A fresh deployment instance also comes to mind.
Lastly it's possible there's a nodejs version 6 which isn't supported and causes problems. Maybe try 5 if you find 6 somewhere. I know it's suppose to be that Meteor uses its own node and the settings needs 0.10.40 but it's a bit confusing so that might affect deployment.
Anyway hopefully something helps there or your error changes so come back with an update and maybe something else will help.
The deploy wait time looks sufficient.
Also poking around with SSH can help reveal where the fault lies. Ranging from firewall ingress ports to faulty network to failed downloading of npm modules etc.
