### ISSUE TITLE
Meteor 1.3 Deploy Error 

### ISSUE THREAD

**Issue by isAlmogK** [arunoda/meteor-up-legacy#1054]
Hi, 
I just updated to the latest version of Meteor 1.3.X and trying to deploy to Digital Ocean I'm getting the following error " Invoking deployment process: FAILED" and when I check the logs 

``` javascript
[104.131.207.244]     at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
```

Does anyone have any ideas?

**Comment by justindra** [comment]
I'm using Meteor 1.3.2.4 and it works fine deploying to AWS. Have you tried increasing the `deployCheckWaitTime` in `mup.json`?

**Comment by isAlmogK** [comment]
I have tried both increasing to 60 and 120 still getting the errors

**Comment by humbertocruz** [comment]
I'm using with digital ocean too and it´s all right but I'm using mupx
