### ISSUE TITLE
mupx deploy: Verifying deployment: FAILED. Error: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by desaiuditd** [arunoda/meteor-up-legacy#1062]
I'm failing to deploy my meteor app on AWS EC2 Ubuntu 14.04 Instance. Meteor version is 1.3.3
#### `package.json`

``` javascript
{
  "name": "verbose-report",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "body-parser": "^1.15.1",
    "freshbooks": "^1.0.1",
    "meteor-node-stubs": "~0.2.0"
  }
}
```
#### Deploy Log

```
ubuntu@ip-172-31-18-54:~/verbose-report/deploy$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /home/ubuntu/verbose-report
Using buildOptions : {}

Started TaskList: Deploy app 'verbose-report' (linux)
[52.40.86.78] - Uploading bundle
[52.40.86.78] - Uploading bundle: SUCCESS
[52.40.86.78] - Sending environment variables
[52.40.86.78] - Sending environment variables: SUCCESS
[52.40.86.78] - Initializing start script
[52.40.86.78] - Initializing start script: SUCCESS
[52.40.86.78] - Invoking deployment process
[52.40.86.78] - Invoking deployment process: SUCCESS
[52.40.86.78] - Verifying deployment
[52.40.86.78] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    ed 
    npm WARN deprecated To upgrade to the latest stable version, run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```
#### Error Log

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
[52.40.86.78] npm WARN deprecated If you're running the version of npm bundled with
[52.40.86.78] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[52.40.86.78] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[52.40.86.78] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[52.40.86.78] npm WARN deprecated semver behavior.
[52.40.86.78] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[52.40.86.78] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[52.40.86.78] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[52.40.86.78] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[52.40.86.78] => Starting meteor app on port:80
[52.40.86.78] 
[52.40.86.78] /bundle/bundle/programs/server/node_modules/fibers/future.js:280
[52.40.86.78]                       throw(ex);
[52.40.86.78]                             ^
[52.40.86.78] Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /bundle/bundle/programs/server/npm/node_modules/freshbooks/node_modules/libxmljs/build/Release/xmljs.node)
[52.40.86.78]     at Module.load (module.js:356:32)
[52.40.86.78]     at Module.Mp.load (/bundle/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/reify/node/runtime.js:16:23)
[52.40.86.78]     at Function.Module._load (module.js:312:12)
[52.40.86.78]     at Module.require (module.js:364:17)
[52.40.86.78]     at require (module.js:380:17)
[52.40.86.78]     at bindings (/bundle/bundle/programs/server/npm/node_modules/freshbooks/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)
[52.40.86.78]     at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/freshbooks/node_modules/libxmljs/lib/bindings.js:1:37)
[52.40.86.78]     at Module._compile (module.js:456:26)
[52.40.86.78]     at Object.Module._extensions..js (module.js:474:10)
[52.40.86.78]     at Module.load (module.js:356:32)
```

I've tried installing missing packages on my AWS instance (following from Stackoverflow suggestions), but it did not help.

Earlier I was trying to deploy from my Mac machine. So I thought it's the issue. So I also tried to deploy the app from another AWS EC2 Ubuntu 14.04 instance. But it gave me same results.

Any help would be good here.

P.S.: `freshbooks` package is making use of `node-gyp` which seems to be platform dependent.

**Comment by 55** [comment]
Same here.
Ubuntu 14.04. Meteor version is 1.3.3

```
    pm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    /bundle/bundle/programs/server/node_modules/fibers/future.js:267
                            throw(ex);
                                  ^
    Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at bindings (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
        at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
```

**Comment by gVolop** [comment]
same :( 

 => Starting meteor app on port:80

```
    /bundle/bundle/programs/server/node_modules/fibers/future.js:280
                                                    throw(ex);
                                                          ^
    Error: Cannot find module 'graylog2'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.Npm.require (/bundle/bundle/programs/server/boot.js:171:18)
        at Package (packages/wrap-graylog2/graylog2.js:1:1)
        at packages/wrap-graylog2/graylog2.js:1:1
        at packages/wrap-graylog2/graylog2.js:1:1
        at /bundle/bundle/programs/server/boot.js:297:10
        at Array.forEach (native)

    => Redeploying previous version of the app
```

**Comment by xanderv87** [comment]
I had exactly the same problem ( version `GLIBC_2.14' not found ).

In my case I was able to fix it by reinstalling Meteor from scratch, best guess for now is that the meteor 1.4beta toolchain was causing the issue.

**Comment by gVolop** [comment]
this post really helped me. [themeteorchef:using-npm-packages](https://themeteorchef.com/snippets/using-npm-packages/#tmc-adding-an-npm-package-with-a-meteor-package)  

i used [this option](https://themeteorchef.com/snippets/using-npm-packages/#tmc-adding-an-npm-package-with-meteorhacksnpm) - Adding an NPM package with meteorhacks:npm

**Comment by xanderv87** [comment]
And no the problem also occurs with a fresh install of meteor (1.3.4.4) ... any idea on where to look for a solution?

**Comment by gVolop** [comment]
oh no! the problem occurs again!!
any idea????

**Comment by janjackson** [comment]
got a similar issue. What do you think could be the reason? For me, I only added two packages and upgraded to meteor 1.4. After undoing these changes the problem persists. Any hint welcome :)

**Comment by gVolop** [comment]
for me - down to 1.3.4.1 version solved the problem.
i don't have an idea what can be the reason :(

**Comment by romaad** [comment]
I tried everything but still having this issues. any news ?

**Comment by gVolop** [comment]
nothing :(
keep away from meteor-update ...

**Comment by romaad** [comment]
for me I'm working on 3 meteor apps and collaborating with 2 other friends
two apps is meteor 1.3.5 and one is 1.3.4.
the weird thing is that they can upload the exact same code with the exact same nodejs/mupx version and I can't. and I can't upload a single app from the 3 :smiley:

**Comment by drrodio** [comment]
Hi all,

I had exactly the same problem. I think the problem is the compatibility between your local system and remote server.
In my case, I work with Ubuntu 15.10 and Debian server, I get GLIBC_2.14 problem.
Try to deploy the project directly from server, I think it works

Good luck

**Comment by gVolop** [comment]
for me, the problem occurred because the incompatible versions between node and meteor.
meteor 1.4 work with node 4.4.7, but node version installed by mupx is 0.10.34, different from meteor project version - same in local and remote,
so even if my local node version was 4.4.7 so it's works with meteor 1.4 project, when i tried to deployed - it crashed. 

the new mupx project solved this problem. 

[https://github.com/meteor/meteor/issues/7475](https://github.com/meteor/meteor/issues/7475)
