### ISSUE TITLE
Not currently working with 1.3.4

### ISSUE THREAD

**Issue by elie222** [arunoda/meteor-up-legacy#1069]
Not working with Meteor 1.3.4. Looks like npm needs to be updated:

```
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
```

**Comment by llqgit** [comment]
Yes, I got the same problem, GOD, why ~ ~.
Do you solve the problem ? It' s confused me for a long while.

**Comment by AbhinavMadahar** [comment]
+1

**Comment by elie222** [comment]
No. I just reverted back to 1.3.3.1. It's to do with the npm version.

**Comment by AbhinavMadahar** [comment]
I manually upgraded Node to 4.4.7 and NPM to the latest version, but it still gives me the same error

**Comment by elie222** [comment]
Meteor doesn't support Node 4 yet. That's Meteor 1.4

**Comment by AbhinavMadahar** [comment]
@elie222 what versions of Node and NPM are you on?

**Comment by elie222** [comment]
10.45 for node. And npm is whatever meteor is now on. I think it's in my
first message.

**Comment by tzapu** [comment]
anymore news on this? i can t deploy anymore since meteor 1.3.4 no matter what i try...

**Comment by elie222** [comment]
Nope. Seems like this project is dead, even though so many people rely on it

**Comment by crapthings** [comment]
its just propmt, you project is already running or you can try increment your "deployCheckWaitTime",

```
"deployCheckWaitTime": 120,
```

**Comment by tzapu** [comment]
i already have it at that, even tried 180

it s already running because i deployed it on some earlier 1.3.x i guess, in my case at least

**Comment by DerMarcus** [comment]
Hi,

this "npm WARN deprecated" error is reported pretty often. I am facing that issue now too.
Mostly the recommendation is to increase the "deployCheckWaitTime".

I did the same, but it was not working. After analyzing the issue further I found a simple reason on our side: the server does not have a connection to the internet.

Probably increasing the deployCheckWaitTime is helpfull for slow internet connections. But if your server does not have a internet connection the error is thrown for sure. I simple double checked that by plugin in and out the wire of our server.

Does somebody have a solution to deploy with mupx for ubuntu servers which are completely disconnected from the internet and only used company internal?

Thanks

ps. copy from other issue

**Comment by elie222** [comment]
> Does somebody have a solution to deploy with mupx for ubuntu servers which are completely offline?

How can you deploy a server that's offline?

**Comment by DerMarcus** [comment]
offline -> not connected to the internet. Because the server is only used company internal due to security reason.

**Comment by macrozone** [comment]
faceing also this issue with meteor 1.3.4.4

can't deploy anymore. It fails with:

```
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                              ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/react/lib/React.js:14:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (/bundle/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
```

Edit: I could solve it by deleting node_modules locally and reinstall from package.json. After that I `mupx deploy`ed and it worked.

**Comment by elie222** [comment]
Anyone know if this working for Meteor 1.3.5.1?

**Comment by tzapu** [comment]
stopped working at 1.3.4, doubtful ...

**Comment by elie222** [comment]
Yeah. I posted this. Sort of crazy that no one has fixed this yet. When I
get off work next week I'll try look into it more. Would be a massive shame
for mup to die

**Comment by sscaff1** [comment]
I had my "deployCheckWaitTime" set to 300 and was getting this error. I upped it again to 600 and now it works.

**Comment by macrozone** [comment]
checklist:
- try to delete your node_modules locally, and install from scratch from package.json
- set deployCheckWaitTime to something above 60
- verify that you use the right node-version for the current version of meteor (it changed from 1.3.3 to 1.3.4 afair)
