### ISSUE TITLE
Error: The APK file for the Android build was not found

### ISSUE THREAD

**Issue by jee1mr** [arunoda/meteor-up-legacy#1074]
```
$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Using buildOptions : {}
The iOS platform is not installed; skipping build for it.

/home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: The APK file for the Android build was not found.
    at findApkPath (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:970:11)
    at /home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:950:21
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:933:29)
    at Command.main.registerCommand._.extend.name [as func] (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:746:12)
    at /home/ubuntu/.meteor/packages/meteor-tool/.1.1.4.yvudr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23

=> Build Error. Check the logs printed above

```

**Comment by apratimankur** [comment]
getting the same error. 
mupx deploy uses meteor build under the hood...
