### ISSUE TITLE
Failing To Verify 1.4-beta.6

### ISSUE THREAD

**Issue by stolinski** [arunoda/meteor-up-legacy#1077]
This is with a long deploy check time. 

```
    -----------------------------------STDERR-----------------------------------
    pm WARN deprecated
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    => Redeploying previous version of the app
```

running logs gets me

```
de npm-rebuild.js (wd=/bundle/bundle/programs/server)
[45.55.254.221] => Starting meteor app on port:80
[45.55.254.221]
[45.55.254.221] assert.js:93
[45.55.254.221]   throw new assert.AssertionError({
[45.55.254.221]         ^
[45.55.254.221] AssertionError: "undefined" === "function"
[45.55.254.221]     at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
[45.55.254.221]     at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
[45.55.254.221]     at Module._compile (module.js:456:26)
[45.55.254.221]     at Object.Module._extensions..js (module.js:474:10)
[45.55.254.221]     at Module.load (module.js:356:32)
[45.55.254.221]     at Function.Module._load (module.js:312:12)
[45.55.254.221]     at Module.require (module.js:364:17)
[45.55.254.221]     at require (module.js:380:17)
[45.55.254.221]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
[45.55.254.221]     at Module._compile (module.js:456:26)
```

**Comment by elie222** [comment]
No idea, but did you get it working with 1.3.4.1?

https://github.com/arunoda/meteor-up/issues/1069

**Comment by bartspedden** [comment]
My app was working with 1.3.4 booth locally and in prod. Then I upgraded to meteor locally, everything worked. So next I did a "meteor reset" to use the new mongo version, started my app, then restored the data and everything worked. So I tried to do a "mupx deploy" and received the same error as above and had to rollback to 1.3.4.

I'm wondering if we need the mongodb container updated to use version 3.2.6? And possibly and update to node to 4.4.7 as well?

I say this because when we do a "meteor update" locally that's what happening behind the scenes and my guess is that the containers just aren't updated on the fly during a deploy.

**Comment by elie222** [comment]
Well now 1.4 has been officially released. Assuming this doesn't help you
though

**Comment by tomitrescak** [comment]
I got the same error "AssertionError: "undefined" === "function" ;( Running Meteor 1.4. 

Anyone made mupx work with Meteor 1.4 ?
