### ISSUE TITLE
Mupx - failed to deploy with "MONGO_URL" set to replica set

### ISSUE THREAD

**Issue by YosBD** [arunoda/meteor-up-legacy#1084]
Hi,

The "verifying deployment" part fails when I'm setting the MONGO_URL to a replica set.
Setting the MONGO_URL to each one of the servers under the replica set works fine.

I'm able to connect to the replica set when running locally.

Works with mupx:
mongodb://USER:PASSWORD@staging-shard-00-00-oafp7.mongodb.net:27017/admin?ssl=true

Works locally. Does not work with mupx:
mongodb://USER:PASSWORD@staging-shard-00-00-oafp7.mongodb.net:27017,staging-shard-00-01-oafp7.mongodb.net:27017,staging-shard-00-02-oafp7.mongodb.net:27017/admin?replicaSet=Staging-shard-0&ssl=true

mupx output:
[ec2-52-209-43-204.eu-west-1.compute.amazonaws.com] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
t new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:329:26
    at process._tickCallback (node.js:458:13)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

Thanks,
Yossi

**Comment by nisdis** [comment]
This might help, setup mup.json such:

```
 // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,
```

found the answer here: 
https://github.com/arunoda/meteor-up/issues/1073

Hope this helps.

**Comment by YosBD** [comment]
Thanks @nisdis.
"setupMongo" on mup.json is already set to false.
My problem is only with connecting to a replica set. Connecting to any of the databases under the replica set works fine.
