### ISSUE TITLE
mupx deployment : npm cannot find module

### ISSUE THREAD

**Issue by pdjenera** [arunoda/meteor-up-legacy#1089]
Running Meteor 1.3.5.1 and node version 0.10.46 and went to mupx deploy and have gotten this error 

```
-----------------------------------STDERR-----------------------------------
ckwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                              ^
Error: Cannot find module 'paypal-rest-sdk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/bundle/bundle/programs/server/boot.js:171:18)
    at Package (packages/19degrees_paypal-extended-secured-euf/paypal.js:131:1)
    at /bundle/bundle/programs/server/boot.js:304:5

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

My app builds fine and doesn't complain about this missing module. Anyone have any ideas?

**Comment by pdjenera** [comment]
Found the issue had to add it as an npm dependancy in the package
