### ISSUE TITLE
mup setup "Error: Cannot find module 'ssh2' "

### ISSUE THREAD

**Issue by vardhans** [arunoda/meteor-up-legacy#1099]
Hi
I am getting below when running "mup setup" from my build server.

```
Error: Cannot find module 'ssh2'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
```

Any idea why we are getting this error.?

**Comment by romaroma** [comment]
npm -g install ssh2

**Comment by vardhans** [comment]
I just found out that mup is updated to 1.x. Apparently, it uses ssh2.
I got this working my restricting my mup version.
`npm install -g mup@0.11.3`
