### ISSUE TITLE
Error with "DISABLE_WEBSOCKETS": true

### ISSUE THREAD

**Issue by SachaG** [arunoda/meteor-up-legacy#11]
```
$ mup reconfig

Meteor-UP : Production Quality Meteor Deployments
--------------------------------------------------


Started TaskList: Updating Configurations
[162.243.213.202] setting up env vars

/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:163
    throw new Error('can only evaluate arrays and objects');
          ^
Error: can only evaluate arrays and objects
    at TaskList._evaluateOptions (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:163:11)
    at TaskList._evaluateOptions (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:158:29)
    at TaskList._evaluateOptions (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:158:29)
    at TaskList._evaluateOptions (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:158:29)
    at runTask (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:89:26)
    at TaskList._runTaskQueue (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:82:3)
    at /usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:48:10
    at Array.forEach (native)
    at TaskList.run (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/taskList.js:47:27)
    at Actions.reconfig (/usr/local/lib/node_modules/mup/lib/actions.js:78:12)
```

**Comment by SachaG** [comment]
OK, so this seems to come from a problem with my environment variables. Not quite sure which one is the problem yet. 

But I also discovered another weird thing: interrupting the reconfig process with ctrl-c will **crash** my Mac. It just did it twice!

**Comment by arunoda** [comment]
Yes. That's an known issue with OSX with SSH deamons. fixed in newer OSX?
haven't you upgraded yet?

On Mon, Dec 23, 2013 at 11:59 AM, Sacha Greif notifications@github.comwrote:

> OK, so this seems to come from a problem with my environment variables.
> Not quite sure which one is the problem yet.
> 
> But I also discovered another weird thing: interrupting the reconfig
> process with ctrl-c will _crash_ my Mac. It just did it twice!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/11#issuecomment-31106021
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
The problem comes from the line `"DISABLE_WEBSOCKETS": true` in the environment variables. So I'll just remove it.

And no I haven't upgraded… I should do it, but I didn't want to take the risk of disturbing my work environment while I still had so much work to do :)

**Comment by arunoda** [comment]
I'm not saying to upgrade it :) My upgrade also quite buggy. Only good
feature is the dual screen fix.

On Mon, Dec 23, 2013 at 12:05 PM, Sacha Greif notifications@github.comwrote:

> Closed #11 https://github.com/arunoda/meteor-up/issues/11.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/11
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
BTW: This might be a bug, I'll look into this. You sent the config file no?
I'll check it.

On Mon, Dec 23, 2013 at 12:54 PM, Arunoda Susiripala <
arunoda.susiripala@gmail.com> wrote:

> I'm not saying to upgrade it :) My upgrade also quite buggy. Only good
> feature is the dual screen fix.
> 
> On Mon, Dec 23, 2013 at 12:05 PM, Sacha Greif notifications@github.comwrote:
> 
> > Closed #11 https://github.com/arunoda/meteor-up/issues/11.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/11
> > .
> 
> ## 
> 
> Arunoda Susiripala
> 
> @arunoda http://twitter.com/arunoda
> http://gplus.to/arunodahttps://github.com/arunoda
> http://www.linkedin.com/in/arunoda

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
I'm reopening this because Tom just had the same issue, just so we don't forget about it :)

**Comment by arunoda** [comment]
Yep. I know.

I can try using ssh2 module for ssh talking. It's pure js version. Hope it
will fix this. Need to try it.

Looking for some time to work on it. May be around next week.

On Friday, January 3, 2014, Sacha Greif wrote:

> I'm reopening this because Tom just had the same issue, just so we don't
> forget about it :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/11#issuecomment-31504624
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
Any news on this?
