### ISSUE TITLE
mupx Verifying deployment: FAILED after upgrading to Meteor 1.4

### ISSUE THREAD

**Issue by demiters** [arunoda/meteor-up-legacy#1105]
I have `"deployCheckWaitTime": 600` and still fail deployment after upgrading to Meteor 1.4!

```
[128.199.106.190] x Verifying deployment: FAILED

-----------------------------------STDERR-----------------------------------
package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------
```

**Comment by catin-black** [comment]
https://github.com/arunoda/meteor-up/issues/1091

**Comment by demiters** [comment]
Migrated to kadirahq/mup and dockerImage abernix/meteord:base to make this work.

**Comment by sferoze** [comment]
@demiters I am using `abernix/meteord:base` too with mupx to get deployment to work. I had to edit the start.sh file mupx uses. 

but I am just wondering @arunoda when mupx will be updated to use a compatible base image with the new meteor?

**Comment by vijayst** [comment]
I have some error after moving to kadirahq/mup:

> Error response from daemon: No such container: app-frontend
>   docker: Error response from daemon: driver failed programming external connectivity on endpoint app (3199bf831abd2ad4f74706ceac6db4f6ebc8da7a68597c9deab75b3dfc92422b): Bind for 0.0.0.0:80 failed: port is already allocated.
