### ISSUE TITLE
Error Deploy my app

### ISSUE THREAD

**Issue by juanfar** [arunoda/meteor-up-legacy#1121]
**Please someone help me, Im trying to deploy my app on a 1and1 server, but 'mupx setup' show me this error:**
## _Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Started TaskList: Setup (linux)
[74.208.236.57] - Installing Docker
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.208.236.57:22
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
![mupx](https://cloud.githubusercontent.com/assets/21966342/18349122/1ec729a8-7595-11e6-984f-1fd165d580dd.jpg)_

**this is my mup.js code:**

_{
  // Server authentication info
  "servers": [
    {
      "host": "74.208.236.57",
      "username": "root",
      "password": "password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      //"pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,

  // Application name (no spaces).
  "appName": "talkus",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "C:/Users/juanfar/chat",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://talkus.juanfar.com"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 60,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}_

**please help me I'm a amateur developer**

**Comment by kylepierce** [comment]
Have you tried increasing the deployCheckWaitTime to 120 or higher?
