### ISSUE TITLE
Upgraded 1.3.5.1 to 1.4 and mup to mupx

### ISSUE THREAD

**Issue by djayasinghe** [arunoda/meteor-up-legacy#1123]
[162.243.89.221] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

**Comment by djayasinghe** [comment]
I change the start.sh file meteorhacks/meteord:base to abernix/meteord:base but still not working

**Comment by hanshenrik** [comment]
+1

**Comment by boredland** [comment]
I changed the start.sh and still get 
`-----------------------------------STDERR-----------------------------------
    o README data
    npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80
    /bundle/bundle/programs/server/node_modules/fibers/future.js:280
                            throw(ex);
                            ^

```
TypeError: require(...).create is not a function
    at meteorInstall.phantom_runner.js (phantom_runner.js:1:31)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at /bundle/bundle/programs/server/app/app.js:578:1
    at /bundle/bundle/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:128:5
    at /bundle/bundle/programs/server/boot.js:344:5
    at Function.run (/bundle/bundle/programs/server/profile.js:480:12)`
```

**Comment by yanickrochon** [comment]
+1 - I also get this error.
