### ISSUE TITLE
unable to deploy with meteor 1.4.2

### ISSUE THREAD

**Issue by WayneUong** [arunoda/meteor-up-legacy#1135]
It hangs here:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Using custom configuration/settings file
Configuration file : mupx-settings/mup-staging-main.json
Settings file      : meteor-settings/settings-staging-main.json

Meteor app path    : /home/ubuntu/nfc-meteor
Using buildOptions : {"debug":true}

```

**Comment by PolGuixe** [comment]
in my case it throws this error: 

```
=> Starting meteor app on port:80

> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
/bundle/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^

Error: Can't find npm module 'react/lib/ReactComponentWithPureRenderMixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
    at options.fallback (packages/modules-runtime.js:445:18)
    at require (packages/modules-runtime.js:112:16)
    at meteorInstall.node_modules.react-addons-pure-render-mixin.index.js (packages/modules.js:17838:18)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (/bundle/bundle/programs/server/packages/react-meteor-data.js:234:256)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
```

**Comment by boostbob** [comment]
1.4.2

```
buffer.js:74
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:74:13)
    at Readable.<anonymous> (/Users/wangbo/.nvm/versions/node/v6.9.1/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by WayneUong** [comment]
I switch to kadira/mup, works fine now.

**Comment by njokusomto** [comment]
Hello @WayneUong, I seem to have the same issue. Mine's stuck at **Using buildOptions : {}**
Could you please post steps to your fix or how to switch to Kadira?
I'm fairly new to Meteor.

Thanks!

**Comment by WayneUong** [comment]
@njokusomto I'm using this now: https://github.com/kadirahq/meteor-up
It's pretty much exactly the same, you simply need to convert your mup settings from json to a javascript object. Check it out, it's a simple conversion.
