### ISSUE TITLE
deployment failure with bcrypt!

### ISSUE THREAD

**Issue by asyncink** [arunoda/meteor-up-legacy#1150]
I try to deploy meteor app with mupx. but got error after `mupx deploy` command. logs:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[138.68.88.155] npm WARN deprecated If you're running the version of npm bundled
 with
[138.68.88.155] npm WARN deprecated Node.js 0.10 LTS, be aware that the next ver
sion of 0.10 LTS
[138.68.88.155] npm WARN deprecated will be bundled with a version of npm@2, whi
ch has some small
[138.68.88.155] npm WARN deprecated backwards-incompatible changes made to `npm
run-script` and
[138.68.88.155] npm WARN deprecated semver behavior.
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No repository fiel
d.
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[138.68.88.155] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebui
ld.js (wd=/bundle/bundle/programs/server)
[138.68.88.155] => Starting meteor app on port:80
[138.68.88.155]
[138.68.88.155] /bundle/bundle/programs/server/node_modules/fibers/future.js:280

[138.68.88.155]                                                 throw(ex);
[138.68.88.155]                                                       ^
[138.68.88.155] Error: /bundle/bundle/programs/server/npm/node_modules/meteor/np
m-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: no
de_module_register
[138.68.88.155]     at Module.load (module.js:356:32)
[138.68.88.155]     at Module.Mp.load (/bundle/bundle/programs/server/npm/node_m
odules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
[138.68.88.155]     at Function.Module._load (module.js:312:12)
[138.68.88.155]     at Module.require (module.js:364:17)
[138.68.88.155]     at require (module.js:380:17)
[138.68.88.155]     at bindings (/bundle/bundle/programs/server/npm/node_modules
/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
[138.68.88.155]     at Object.<anonymous> (/bundle/bundle/programs/server/npm/no
de_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
[138.68.88.155]     at Module._compile (module.js:456:26)
[138.68.88.155]     at Object.Module._extensions..js (module.js:474:10)
[138.68.88.155]     at Module.load (module.js:356:32)
[138.68.88.155] npm WARN deprecated This version of npm lacks support for import
ant features,
[138.68.88.155] npm WARN deprecated such as scoped packages, offered by the prim
ary npm
[138.68.88.155] npm WARN deprecated registry. Consider upgrading to at least npm
@2, if not the
[138.68.88.155] npm WARN deprecated latest stable version. To upgrade to npm@2,
run:
[138.68.88.155] npm WARN deprecated
[138.68.88.155] npm WARN deprecated   npm -g install npm@latest-2
[138.68.88.155] npm WARN deprecated
[138.68.88.155] npm WARN deprecated To upgrade to the latest stable version, run
:
[138.68.88.155] npm WARN deprecated
[138.68.88.155] npm WARN deprecated   npm -g install npm@latest
[138.68.88.155] npm WARN deprecated
[138.68.88.155] npm WARN deprecated (Depending on how Node.js was installed on y
our system, you
[138.68.88.155] npm WARN deprecated may need to prefix the preceding commands wi
th `sudo`, or if
[138.68.88.155] npm WARN deprecated on Windows, run them from an Administrator p
rompt.)
[138.68.88.155] npm WARN deprecated
[138.68.88.155] npm WARN deprecated If you're running the version of npm bundled
 with
[138.68.88.155] npm WARN deprecated Node.js 0.10 LTS, be aware that the next ver
sion of 0.10 LTS
[138.68.88.155] npm WARN deprecated will be bundled with a version of npm@2, whi
ch has some small
[138.68.88.155] npm WARN deprecated backwards-incompatible changes made to `npm
run-script` and
[138.68.88.155] npm WARN deprecated semver behavior.
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No repository fiel
d.
[138.68.88.155] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[138.68.88.155] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebui
ld.js (wd=/bundle/bundle/programs/server)
[138.68.88.155] => Starting meteor app on port:80
```

**Comment by asyncink** [comment]
please help! what can I do ? what are possible solutions?
