### ISSUE TITLE
npm WARN package.json

### ISSUE THREAD

**Issue by KristerV** [arunoda/meteor-up-legacy#118]
Thank you, Arunoda, for a great program and specially thanks for the attention to detail. Specifically the rollback on deploy fail :)

So updated app to Meteor 0.9 and can't run the app (works great locally on 0.9). The steps I've done is following:

```
meteor update
npm install -g meteorite
mrt migrate-app // just in case, files area actually already updated
npm update mup -g
vim mup.json // To change node version to 0.10.31
mup setup
mup deploy
```

And this is the log from console

```
# mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------


Started TaskList: Setup (linux)
[meteor2] - Installing Node.js
[meteor2] ✔ Installing Node.js: SUCCESS
[meteor2] - Installing PhantomJS
[meteor2] ✔ Installing PhantomJS: SUCCESS
[meteor2] - Setting up Environment
[meteor2] ✔ Setting up Environment: SUCCESS
[meteor2] - Copying MongoDB configuration
[meteor2] ✔ Copying MongoDB configuration: SUCCESS
[meteor2] - Installing MongoDB
[meteor2] ✔ Installing MongoDB: SUCCESS
[meteor2] - Configuring upstart
[meteor2] ✔ Configuring upstart: SUCCESS
Completed TaskList: Setup (linux)
root@meteor2:/srv/deploy_ting# mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Bundling Started: /srv/ting/

Started TaskList: Deploy app 'ting' (linux)
[meteor2] - Uploading bundle
[meteor2] ✔ Uploading bundle: SUCCESS
[meteor2] - Setting up Environment Variables
[meteor2] ✔ Setting up Environment Variables: SUCCESS
[meteor2] - Invoking deployment process
[meteor2] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'meteor2' (ECDSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3002: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    .14` exists; testing
    Binary is fine; exiting
    fibers@1.0.1 node_modules/fibers

    > bcrypt@0.8.0 install /opt/ting/tmp/bundle/programs/server/node_modules/bcrypt
    > node-gyp rebuild

    make: Entering directory `/opt/ting/tmp/bundle/programs/server/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/ting/tmp/bundle/programs/server/node_modules/bcrypt/build'
    bcrypt@0.8.0 node_modules/bcrypt
    ├── bindings@1.0.0
    └── nan@1.3.0
    ting stop/waiting
    ting start/running, process 22508
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    ting stop/waiting
    ting start/running, process 22572
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'ting' (linux)
```

I have no idea what to do. Usually I'm able to fix my issues.

**Comment by KristerV** [comment]
in case you're wondering about my setup, I'm this guy http://code.krister.ee/hosting-multiple-instances-of-meteor-on-digitalocean/

**Comment by KristerV** [comment]
more info

```
# mup logs -f

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[meteor2] Warning: Permanently added 'meteor2' (ECDSA) to the list of known hosts.
[meteor2]     at require (module.js:380:17)
    at Object.<anonymous> (/opt/ting/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

**Comment by arunoda** [comment]
Hey I know you :)

Can you get more log output. Run `mup logs -n 400`?
And try to use [`meteorhacks:npm`](http://atmospherejs.com/meteorhacks/npm) which has the support for Meteor 0.9 and don't need `meteor-npm`.
(And I didn't tested `meteor-npm` for 0.9 as well)

**Comment by KristerV** [comment]
hey yeah, `mup logs -n 400` got me this info. I though tMeteor had Underscore installed in the default packages.

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/ting/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

reporting back in a second

**Comment by arunoda** [comment]
But if you are getting it with `Meteor.require`, you are getting it from a package. So, package needs to depend on `underscore` for that.

You may can use `Npm.require('underscore')`. BTW, why do you need underscore anyway? Can't you just use `_`.

**Comment by KristerV** [comment]
hmm `meteor add underscore` doesn't help, same error.

Uhmm. I'm a bit confused at your last comment. isn't `_` underscore? When I was developing my app I never installed Underscore and the `_.contains()` worked fine.

**Comment by arunoda** [comment]
Yes. That's why I am wondering. Check your code for `Meteor.require('underscore')`. Which is not needed?

**Comment by KristerV** [comment]
Searching for `Meteor.require('underscore')` returns no results.

So `meteorhacks:npm` wouldn't really help me, right?

**Comment by arunoda** [comment]
hmm. weird.

**Comment by KristerV** [comment]
also, running `meteor --port 4000` works fine on the same server.

**Comment by KristerV** [comment]
btw my app is here https://github.com/KristerV/ting/tree/t2

Trying to run the t2 branch.

**Comment by arunoda** [comment]
okay. I'll give it a try in few hours.

**Comment by KristerV** [comment]
wouldn't really want to spend your time. Perhaps there's something else I can try?

**Comment by digilord** [comment]
I am getting the same error on deploy as @KristerV reported.

```
[digilord@Cassiopeia inservice[master]]$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Bundling Started: /Users/digilord/projects/inservice/app

Started TaskList: Deploy app 'inservice' (linux)
[104.131.17.19] - Uploading bundle
[104.131.17.19] ✔ Uploading bundle: SUCCESS
[104.131.17.19] - Setting up Environment Variables
[104.131.17.19] ✔ Setting up Environment Variables: SUCCESS
[104.131.17.19] - Invoking deployment process
[104.131.17.19] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '104.131.17.19' (RSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ; exiting
    fibers@1.0.1 node_modules/fibers

    > bcrypt@0.8.0 install /opt/inservice/tmp/bundle/programs/server/node_modules/bcrypt
    > node-gyp rebuild

    make: Entering directory `/opt/inservice/tmp/bundle/programs/server/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/inservice/tmp/bundle/programs/server/node_modules/bcrypt/build'
    bcrypt@0.8.0 node_modules/bcrypt
    ├── bindings@1.0.0
    └── nan@1.3.0
    inservice stop/waiting
    inservice start/running, process 24503
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    inservice stop/waiting
    inservice start/running, process 24573
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'inservice' (linux)
```

**Comment by KristerV** [comment]
hey @digilord, cool nick :D

...back to the subject. what does `mup logs -n 400` give you?

**Comment by digilord** [comment]
I get infinite iterations of:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/inservice/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #5893
```

The app works fine in development mode locally.

**Comment by bradledford** [comment]
Add me to the list. 'mup deploy' worked perfectly until I just attempted to update my app to Meteor 0.9.0.  Here's the output of 'mup logs -n 400' for me (with IP addresses and app names redacted)...

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[xxx.xxx.xxx.xx] Warning: Permanently added 'xxx.xxx.xxx.xx' (RSA) to the list of known hosts.
[xxx.xxx.xxx.xx]     at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #7


...repeated 7 times...

          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/[myappname]/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #14

module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/[myappname]/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser

module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/[myappname]/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

... repeated 13 times...
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/[myappname]/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #14

module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/[myappname]/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

**Comment by arunoda** [comment]
I'm started to debug this issue. Let's see.

**Comment by arunoda** [comment]
Okay. I tried with ting. Do following:

Please update `mup` and setup mup again.

``` bash
npm i -g mup
mup setup
```

**Comment by bradledford** [comment]
Nope. I now get:

```
[xxx.xxx.xxx.xx] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'xxx.xxx.xxx.xx' (RSA) to the list of known hosts.
    sudo: node-gyp: command not found
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
    ----------------------------------------------------------------------------
```

**Comment by digilord** [comment]
Re-installation on client and server results in the following:

```
sudo npm install -g mup
Password:
npm http GET https://registry.npmjs.org/mup
npm http 200 https://registry.npmjs.org/mup
npm http GET https://registry.npmjs.org/mup/-/mup-0.6.4.tgz
npm http 200 https://registry.npmjs.org/mup/-/mup-0.6.4.tgz
npm http GET https://registry.npmjs.org/cjson
npm http GET https://registry.npmjs.org/nodemiral
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/uuid
npm http 200 https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/cjson
npm http 200 https://registry.npmjs.org/nodemiral
npm http GET https://registry.npmjs.org/jsonlint/1.6.0
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/ejs
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/ejs
npm http 200 https://registry.npmjs.org/jsonlint/1.6.0
npm http GET https://registry.npmjs.org/jsonlint/-/jsonlint-1.6.0.tgz
npm http 200 https://registry.npmjs.org/handlebars
npm http 200 https://registry.npmjs.org/jsonlint/-/jsonlint-1.6.0.tgz
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/JSV
npm http GET https://registry.npmjs.org/nomnom
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/JSV
npm http 200 https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/nomnom
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/has-color
npm http 200 https://registry.npmjs.org/strip-ansi
npm http 200 https://registry.npmjs.org/has-color
npm http 200 https://registry.npmjs.org/ansi-styles
/Users/digilord/.nvm/v0.10.25/bin/mup -> /Users/digilord/.nvm/v0.10.25/lib/node_modules/mup/bin/mup
mup@0.6.4 /Users/digilord/.nvm/v0.10.25/lib/node_modules/mup
├── colors@0.6.2
├── uuid@1.4.1
├── nodemiral@0.3.11 (debug@0.7.4, ejs@0.8.8, handlebars@1.0.12)
└── cjson@0.3.0 (jsonlint@1.6.0)
[digilord@Cassiopeia app[master*]]$ ssh ten8dev
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue Sep  2 16:18:51 EDT 2014

  System load:  0.11               Processes:           70
  Usage of /:   12.4% of 19.56GB   Users logged in:     0
  Memory usage: 21%                IP address for eth0: 104.131.17.19
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

Last login: Tue Sep  2 13:42:27 2014 from wsip-72-215-203-34.ph.ph.cox.net
[inservice@ten8dev ~]$ sudo npm install -g mup
/usr/bin/mup -> /usr/lib/node_modules/mup/bin/mup
mup@0.6.4 /usr/lib/node_modules/mup
├── colors@0.6.2
├── uuid@1.4.1
├── cjson@0.3.0 (jsonlint@1.6.0)
└── nodemiral@0.3.11 (debug@0.7.4, ejs@0.8.8, handlebars@1.0.12)
[inservice@ten8dev ~]$ logout
Connection to 104.131.17.19 closed.
[digilord@Cassiopeia app[master*]]$ cd ../
[digilord@Cassiopeia inservice[master*]]$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Bundling Started: /Users/digilord/projects/inservice/app

Started TaskList: Deploy app 'inservice' (linux)
[104.131.17.19] - Uploading bundle
[104.131.17.19] ✔ Uploading bundle: SUCCESS
[104.131.17.19] - Setting up Environment Variables
[104.131.17.19] ✔ Setting up Environment Variables: SUCCESS
[104.131.17.19] - Invoking deployment process
[104.131.17.19] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '104.131.17.19' (RSA) to the list of known hosts.
    sudo: node-gyp: command not found
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'inservice' (linux)

```

**Comment by arunoda** [comment]
Oh! I forgot to mention, you need to do `mup setup` once again as well.

**Comment by bradledford** [comment]
Yes!!! I'm back in business. Thanks Arunoda.

**Comment by arunoda** [comment]
Awesome.

**Comment by digilord** [comment]
New error:

```
mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------


Started TaskList: Setup (linux)
[104.131.17.19] - Installing PhantomJS
[104.131.17.19] ✘ Installing PhantomJS: FAILED

    -----------------------------------STDERR-----------------------------------
    ....... .......... .......... .......... .......... 98%  105M 0s
     12700K .......... .......... .......... .......... .......... 99%  807K 0s
     12750K .......... .......... .......... .......... .......... 99% 12.6M 0s
     12800K .......... .......... .......... .......... .......... 99% 53.3M 0s
     12850K ..                                                    100% 5580G=5.0s

    2014-09-02 19:58:03 (2.50 MB/s) - ‘phantomjs-1.9.7-linux-x86_64.tar.bz2.3’ saved [13161396/13161396]


    bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
    bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

    It is possible that the compressed file(s) have become corrupted.
    You can use the -tvv option to test integrity of such files.

    You can use the `bzip2recover' program to attempt to recover
    data from undamaged sections of corrupted files.

    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------
Completed TaskList: Setup (linux)
```

**Comment by arunoda** [comment]
oops. Seems like phantom error (may be network). 
For temporary purpose set `"setupPhantom": false` inside your `mup.json`

**Comment by digilord** [comment]
That worked. Deploy succeeded.

**Comment by arunoda** [comment]
Nice.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KristerV** [comment]
everybody is good now? Ironic that Arunoda tested with my app, because

```
npm i -g mup
mup setup
mup deploy
```

or

```
npm install -g mup
mup setup
mup deploy
```

did not work for me. They did not even change the error message... I'm not sure what am I doing differently. My output of the update was the same as @digilord reported (the part after `ssh ten8dev`).

**Comment by arunoda** [comment]
Yep. Both are the same.
Hmm. Weird.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KristerV** [comment]
how do I check mup version? Perhaps I should uninstall - reinstall?

**Comment by KristerV** [comment]
i also tried setting PhantomJS to false, just in case, no luck.

**Comment by KristerV** [comment]
```
ll ~/.npm/mup/
0.5.3/       0.6.4/       .cache.json
```

I guess I've got 0.6.4 installed..

**Comment by KristerV** [comment]
well I reinstalled mup and used a fresh `mup init` (with node 0.10.29 instead of 0.10.31) and still the same error. What a drag :(

**Comment by arunoda** [comment]
Can you please try with a complete new box.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KristerV** [comment]
yep, works on a fresh box. I noticed, that `mup init` created a `mup.jon` with node 0.10.31, not 29 as with previous fresh install. why could this be?

omg I don't get it... Meteor and mup are the same versions on both.. Do I have to migrate all my shit to a clean server?

**Comment by arunoda** [comment]
I don't get it also. Normally, it should work without a fresh install.
I am updating node version on mup, when a new Meteor version comes.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KristerV** [comment]
well.... This may actually be some random DigitalOcean bug. I remember I've have to go to a fresh install before. Got any hosting providers to suggest?

**Comment by arunoda** [comment]
DO is good. Linode is quite good as well.
We use both.
DO 14.04 box has some issues.
We use 12.04.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KristerV** [comment]
okay. I'll give Linode a go.

**Comment by KristerV** [comment]
anyway closing this topic. I'm going for a fresh install - thus not reproducible.

**Comment by Viktorminator** [comment]
Hi hubers! I have some cloud server and couldn't deploy my telescope app via mup:

1st try: I tried with settings "setupNode": true & "setupPhantom": true - it gave me Setting up error
2nd try: I installed Node.js via SSH and tried with both settings false - it gave me next error:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Started TaskList: Setup (linux)
[http://46.8.12.30/] - Setting up Environment
[http://46.8.12.30/] ✘ Setting up Environment: FAILED

    -----------------------------------STDERR-----------------------------------
    /tmp/DBBJtlPm788hQ4PZp: line 1: syntax error near unexpected token `('
    /tmp/DBBJtlPm788hQ4PZp: line 1: `sshpass -p mypass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@http://46.8.12.30/ "bash -s" < /tmp/j1Krf5EonfuLBlvHz'
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------
Completed TaskList: Setup (linux)
```

So, I've been wondering what are the requirements to remote server? I mean should it have some ssh or some specific settings to make things happen fluently? Thanks.

**Comment by KristerV** [comment]
try enabling swap on your server. I think this fixed many of my issues with deployment.
