### ISSUE TITLE
Mup deploy failing for meteor 0.9.1

### ISSUE THREAD

**Issue by bitspook** [arunoda/meteor-up-legacy#125]
Hey, 

Mup deploy for meteor 0.9.1 is failing. It was working for 0.8.3 just fine. I have tried restarting the server, mup setup and all I could think of. Here's the error that shows up:

```
[54.215.253.100] - Uploading bundle
[54.215.253.100] ✔ Uploading bundle: SUCCESS
[54.215.253.100] - Setting up Environment Variables
[54.215.253.100] ✔ Setting up Environment Variables: SUCCESS
[54.215.253.100] - Invoking deployment process
[54.215.253.100] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    _dir=/home/ubuntu/.node-gyp/0.10.31',
    gyp info spawn args   '-Dmodule_root_dir=/opt/celebvidy/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    elease/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/celebvidy/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.1 install /opt/celebvidy/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    source-map-support@0.2.5 node_modules/source-map-support
    └── source-map@0.1.29 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    celebvidy stop/waiting
    celebvidy start/running, process 3058
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 50 seconds while app is booting up
    Checking is app booted or not?
    celebvidy stop/waiting
    celebvidy start/running, process 3212
    ----------------------------------------------------------------------------
```

I did mup logs -m 200 and here's the log:

```
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/celebvidy/app/programs/server/boot.js:88:18)
    at app/server/google.js:3:21
    at app/server/google.js:[54.215.253.100] 35:3
    at /opt/celebvidy/app/programs/server/boot.js:161:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/celebvidy/app/programs/server/node_modules/underscore/underscore.js:79:11)
error: Forever detected script exited with code: 8
error: Script restart attempt #18

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/celebvidy/app/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
    at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:20:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8

```

I SSHed into the AWS server and did `npm install -g request` but no help. Any ideas what might be trying to be funny?

**Comment by arunoda** [comment]
have you updated mup with `npm i -g mup`.
Then do mup setup once and deploy

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by bitspook** [comment]
Hey Arunoda, 

Thanks for reply. Yes I have done that multiple times. Just tried doing it again. Still getting the same issue.

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by arunoda** [comment]
okay. send me a reproducible app. Let me see what I can do.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by gldnlab** [comment]
Having similar issues, but Meteor .0.9.0.1 using Telescope.

**Comment by gldnlab** [comment]
```
port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ease/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/musichunt/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.1 install /opt/musichunt/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    source-map-support@0.2.5 node_modules/source-map-support
    └── source-map@0.1.29 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    musichunt stop/waiting
    musichunt start/running, process 22527
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    musichunt stop/waiting
    musichunt start/running, process 22629
```

**Comment by gldnlab** [comment]
And when I run 

```
npm i -g mup
```

I notice the Node version doesn't update to 0.10.31 in the mup.json file...

**Comment by jakobdamjensen** [comment]
I'm getting the same - was working fine the other day.

Tried to update mup and setup which worked fine. But can't deploy...

**Comment by jakobdamjensen** [comment]
Well now it's working just fine again.. Weird... Could be it be because I installed node via NVM on the server?

**Comment by gldnlab** [comment]
Still having this issue. Any word @arunoda?

**Comment by arunoda** [comment]
@jakobdamjensen that's possible. But I'm not exactly sure. I didn't tested for that.

**Comment by arunoda** [comment]
@engagr If you can send me a sample repo. I can test it with my own. Otherwise, it's pretty hard to debug.

**Comment by gldnlab** [comment]
It's on bitbucket - is there an email for you I can add there (or email the code to)?

**Comment by arunoda** [comment]
add me with arunoda.susiripala [at] gmail.com.
I'll check somewhere around today.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by gldnlab** [comment]
Thanks so much. Added you - branch is 'mup-fix'.

**Comment by arunoda** [comment]
okay.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Batistleman** [comment]
I'm having the same issues, let me know if I need to verify something on my app.

**Comment by Batistleman** [comment]
In my case the application itself was not starting properly:

```
/opt/azumuta/app/programs/server/node_modules/fibers/future.js:173
                    throw(ex);
                          ^
TypeError: Cannot set property 'customer' of undefined
    at Template.adminTemplate.helpers.isAdminUser (app/common/common.js:17:23)
```

It had nothing todo with the mup deploy, after fixing the other bug the deploy went flawless - as we are used to with mup ;-).

(found the bug by: mup logs -n 300)

**Comment by arunoda** [comment]
Hi,

I ran your app against a new digital ocean server. Everything worked fine
as expected.
Let me check with a aws server too.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by gldnlab** [comment]
@Batistleman how'd you fix that bug?

**Comment by gldnlab** [comment]
is the node version in the mup.json file supposed to update when you run `npm i -g mup` ?

**Comment by arunoda** [comment]
no. You need to do it manually.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by krstffr** [comment]
I'm getting this error as well.

Also updated mup, updated nodeVersion to 0.10.31, ran mup setup and mup deploy.

**Comment by krstffr** [comment]
OK, so the error for me was that I had a Kadria.connect() in the code and also had kadira.appId and kadira.appSecret set in the settings.json. Having them set in the settings will auto-connect to Kadira, and the "extra" Kadria.connect() will make the app crash (as it's already connected).

At least that's what I think was the error. 95 % sure :)

**Comment by krstffr** [comment]
Also: I found the error by checking the logs while deploying the app. 

So open up another terminal window and run `map logs -f` while you're deploying and you might be able to see what's wrong.

**Comment by krstffr** [comment]
Also: if you run the latest version of Kadira you'll see the error in those logs. Also: now I'm 100 % certain what the problem was :)

![The error in Kadira](http://cl.ly/XRXX/Ska%CC%88rmavbild%202014-09-09%20kl.%2016.04.21.png)

Sorry for all the comments by the way. I'll stop now.

**Comment by Batistleman** [comment]
I have the impression this error is a false positive. I mean, there is an underlaying reason for why the application does not start, but it has nothing todo with mup.

Perhaps we could find a way to check if the error is really an installation problem? Or rather a startup problem?

**Comment by bitspook** [comment]
Hey! 

Sorry I could't make a demo app available for replicating the issue. 

I found the issue. Problem is with bcrypt package, and apparently occur when we deploy from a Mac. That's what I suppose the issue is. Correct me if I am wrong. I think the bcrypt package got bundled with the app, and on server removing `/opt/<my_app>/app/programs/server/npm/npm-bcrypt/node-modules/bcrypt` and installing bcrypt by hand on the server (`npm install bcrypt`) solved the deployment problem.

This is what I did to get my app deployed successfully.
- I extracted bundle.tar.gz and copied it to `/opt/<my_app>/app` (after backing up my old app as old_app)
- I tried to run the app there with `node main.js` which failed with the similar error as I've pasted above in my first comment
- I removed `/opt/<my_app>/app/programs/server/npm/npm-bcrypt/node-modules/bcrypt` and installed it by hand
- Then on running the app, I got error about environment variables. So I manually `export`ed the env settings I wanted
- I tried running the app again. It still failed complaining with same errors (`request` module not found) etc
- I installed request module and tried again
- Got greeted with similar errors about modules not found and ended up installing many modules by hand ( request, qs, bl, node-uuid, mime-types, tunnel-agent, json-stringify-safe, caseless, forever-agent)

The app ran successfully and is using version 0.9.1.1 (verified as it has my new changes and MeteorRelease in page html).

Is it a bug or is this something I might be doing wrong in my project? Same project without any changes used to get deployed just fine before meteor 0.9.1.

**Comment by furley** [comment]
I'm having the same issue. Is there a less manual fix?

**Comment by arunoda** [comment]
I am working on this today. Trying to find the issue and fix it.

On Monday, September 22, 2014, furley notifications@github.com wrote:

> I'm having the same issue. Is there a less manual fix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/125#issuecomment-56309889.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by bitspook** [comment]
Hey Arunoda, 

Sorry I didn't reply back in email thread. The issue here is not that mup is not rebuilding binary modules, it's doing that just fine. Issue is using `Npm.require('request')` and such. May be earlier Meteor used to bundle these modules itself or something, I really don't know, but now this is causing the issue. 

To get rid of all that manual work, I forked mup and have created another setting in mup.json `additionalNpmModules`, which install the additional modules required inside my app. Like this in deploy.sh

``` sh
sudo tar xvzf bundle.tar.gz > /dev/null

cd ${BUNDLE_DIR}
sudo npm install <%= additionalNpmModules %>

# rebuilding fibers
cd ${BUNDLE_DIR}/programs/server
```

**Comment by arunoda** [comment]
If so, you don't need to fork mup.
Use meteor npm https://github.com/meteorhacks/npm project

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by seiyria** [comment]
I think I'm having this problem as well, I'm using nvm, is that a problem?

**Comment by MaximDubrovin** [comment]
Have the same issue on deploying. Meteor 0.8.3. Tried changing node version in mup.json 10.29-10.32, different mup versions from latest to 0.5.3. Same error. Didn't touch server at all. Created fresh digital ocean droplet and mup setup, deploy after that.

**Comment by seiyria** [comment]
I ended up getting mine to work somehow... I was originally trying to deploy from the droplet, to the droplet. I tried again from my local linux install and it worked just fine. Not sure what changed to be honest.

**Comment by MaximDubrovin** [comment]
**Update:**

I updated Meteor to 0.9.3 and mup to latest version. 

Created a fresh DO droplet, not even SSH into it. 

From my mac:

Ran `mup setup` (node version 0.10.32) - success

Ran`mup deploy`. Still has this error:

``` bash
[192...] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    _dir=/root/.node-gyp/0.10.32',
    gyp info spawn args   '-Dmodule_root_dir=/opt/alpheratz/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 58080: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    t/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/alpheratz/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.1 install /opt/alpheratz/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    fibers@1.0.1 node_modules/fibers

    source-map-support@0.2.5 node_modules/source-map-support
    └── source-map@0.1.29 (amdefine@0.1.0)
    alpheratz start/running, process 11011
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'alpheratz' (linux)
```

**Comment by Batistleman** [comment]
Can you add the output of

   mup logs -n 300

I don't think the deploy is failing, it might just be the application start.

**Comment by MaximDubrovin** [comment]
My fault.

I fixed and now `mup deploy` and app works without errros.

Problem:

I checked logs and found that there was some problems with connection to mongodb (compose.io)

There was 3(!) mistakes: wrong pass for oplogger, typo mistake, and oplogger user on compose.io should not only have oplog access but also be read only.

**Comment by nicksergeant** [comment]
I am getting this same error, and can reproduce it every time by simply including a call to `Npm.require()` anywhere in my code. Once I remove the call, the deploy succeeds. It seems mup does not work when using the [offical](https://www.meteor.com/blog/2013/04/04/meteor-060-brand-new-distribution-system-app-packages-npm-integration) usage of npm with Meteor.

**Comment by arunoda** [comment]
That seems pretty weird. May be something possible with the servers node
setup.
All this issues will get fix soon.
I moving mup's runtime into docker.
It's already being created: https://github.com/meteorhacks/meteord

Only thing left is to integrate with mup CLI. Once it's done.
We won't have issues like this.

**Comment by nicksergeant** [comment]
Hmm, gotcha. FWIW, this is with installing the `node-uuid` package. In fact, a completely fresh Ubuntu 14.04 and the following commands produce the error every time:
1. `mup setup`
2. `mup deploy`

Output:

```
> mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[siftie.com] - Installing Node.js
[siftie.com] ✔ Installing Node.js: SUCCESS
[siftie.com] - Installing PhantomJS
[siftie.com] ✔ Installing PhantomJS: SUCCESS
[siftie.com] - Setting up Environment
[siftie.com] ✔ Setting up Environment: SUCCESS
[siftie.com] - Copying MongoDB configuration
[siftie.com] ✔ Copying MongoDB configuration: SUCCESS
[siftie.com] - Installing MongoDB
[siftie.com] ✔ Installing MongoDB: SUCCESS
[siftie.com] - Configuring upstart
[siftie.com] ✔ Configuring upstart: SUCCESS
Completed TaskList: Setup (linux)

> mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: .

Started TaskList: Deploy app 'siftie' (linux)
[siftie.com] - Uploading bundle
[siftie.com] ✔ Uploading bundle: SUCCESS
[siftie.com] - Setting up Environment Variables
[siftie.com] ✔ Setting up Environment Variables: SUCCESS
[siftie.com] - Invoking deployment process
[siftie.com] ✘ Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
        e_root_dir=/root/.node-gyp/0.10.31',
        gyp info spawn args   '-Dmodule_root_dir=/opt/siftie/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        stop: Unknown instance:
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        App did not pick up! Please check app logs.
        -----------------------------------STDOUT-----------------------------------
        les/bcrypt/build'
          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
          SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
          SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
          COPY Release/bcrypt_lib.node
        make: Leaving directory `/opt/siftie/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

        > fibers@1.0.1 install /opt/siftie/tmp/bundle/programs/server/node_modules/fibers
        > node ./build.js

        `linux-x64-v8-3.14` exists; testing
        Binary is fine; exiting
        underscore@1.5.2 node_modules/underscore

        semver@2.2.1 node_modules/semver

        source-map-support@0.2.5 node_modules/source-map-support
        └── source-map@0.1.29 (amdefine@0.1.0)

        fibers@1.0.1 node_modules/fibers
        Waiting for MongoDB to initialize. (5 minutes)
        connected
        siftie start/running, process 21110
        Waiting for 15 seconds while app is booting up
        Checking is app booted or not?
        ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'siftie' (linux)
```

That said, glad to see you're moving to a Docker-based architecture!

**Comment by nicksergeant** [comment]
Solved this by switching to `meteorhacks:npm` for npm modules.
