### ISSUE TITLE
Error: TIMEOUTED_WAIT_FOR_MONGO -> wait-for-mongo: auth fails

### ISSUE THREAD

**Issue by golojads** [arunoda/meteor-up-legacy#126]
Deployment fails to Digital Ocean(DO). 
Meteor 0.9.1.1
MONGO_URL in mup.json points to mongohq.
1) Even it says "auth fails", I still can connect with this user/pass to MongoDB from DO server and from local Mongo Client.
2) Also I noticed that Environment Variable MONGO_URL is not set in DO, however during deployment script reported "✔ Setting up Environment Variables: SUCCESS"

Any ideas?
Thank you.

Started TaskList: Deploy app 'testApp' (linux)
[178.62.139.45] - Uploading bundle
[178.62.139.45] ✔ Uploading bundle: SUCCESS
[178.62.139.45] - Setting up Environment Variables
[178.62.139.45] ✔ Setting up Environment Variables: SUCCESS
[178.62.139.45] - Invoking deployment process
[178.62.139.45] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added '178.62.139.45' (RSA) to the list of known hosts.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/usr/local/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
    throw err;
          ^
Error: TIMEOUTED_WAIT_FOR_MONGO
    at null._onTimeout (/usr/local/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
-----------------------------------STDOUT-----------------------------------

wait-for-mongo: auth fails
wait-for-mongo: auth fails
wait-for-mongo: auth fails
    .....
```

**Comment by iboxgithub** [comment]
I had the same issue that I solved by checking Mongo access from my terminal (case sensitivity) after that normally, if it works from your server terminal it will work from mup

**Comment by Kikobeats** [comment]
same problem here with digitalocean too...

**Comment by whohags** [comment]
How did you fix it exactly?

**Comment by iboxgithub** [comment]
Actually it was not a "fix" properly speaking, I just connected via meteor command, it took more time than usual (all of this is subjective maybe it was something else), I copy pasted user/pass and it worked...no clue what happened but it happened twice and the first time was the classical mistake in my password..newbie one

**Comment by iboxgithub** [comment]
if you wanna send me your config files I can compare it to mine (of course take off you passwords) and I will check it with my server

**Comment by pmalbu** [comment]
I am still having issues... could someone please help?
Here is my config with the important parts (I have node and mongo installed on my DigitalOcean VPS already and can connect to mongodb remotely using RoboMongo):

// Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "4.4.2",

 // Configure environment
  "env": {
    "ROOT_URL": "http://localhost",
    "PORT": 3000,
    "MONGO_URL": "mongodb://dbuser:dbpass@127.0.0.1:27017/tastetest"
  },

"deployCheckWaitTime": 150
