### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by cristiandley** [arunoda/meteor-up-legacy#140]
Hi guys, im using Meteor 0.9.2.2, Node 0.10.32 and mongohq.

Im using CFS (collectionfs - filestorage) package

Im getting a weird error when i deploy. The thing is, when i try to upload a little file of 2kb or even a bigger one... i get this error:

```
GET http://myurl.com/sockjs/info?cb=wlja9hwpnn net::ERR_CONNECTION_REFUSED 0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:9
```

```
PUT http://myurl.com/cfs/files/Promociones/2Cojfiz7AeYa7tNnQ?chunk=0&fil…VG9rZW4iOiJNYjZwWThqT1JiM3VUclZKLVpNT3NXcUlIN2JWYjVhUmpBd3Z3eklGVmZJIn0%3D net::ERR_CONNECTION_REFUSED 0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:22
```

```
Error: "Queue" network [undefined], Error
    at http://myurl.com/0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:22:21189
    at http://myurl.com/0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:22:18559
    at http://myurl.com/0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:1:8368
    at XMLHttpRequest.v.onreadystatechange (http://myurl.com/0dd37bf1d599f391467b93f80b4eeb1fb92d409b.js:22:19866) 
```

**Comment by cristiandley** [comment]
I feel an idiot, 
meteor add cfs:micro-queue
 was the solution
