### ISSUE TITLE
node-gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by nyxynyx** [arunoda/meteor-up-legacy#142]
I'm trying to mup deploy my app from OSX to an arm-based linux system, but it's throwing an error `gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp` as seen below. Deploying works until I started adding npm modules to the app.

How can we define `<(module_name)`? Is that the problem?

```
$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Bundling Started: .

Started TaskList: Deploy app 'my-test-app' (linux)
[192.168.1.114] - Uploading bundle
[192.168.1.114] ✔ Uploading bundle: SUCCESS
[192.168.1.114] - Setting up Environment Variables
[192.168.1.114] ✔ Setting up Environment Variables: SUCCESS
[192.168.1.114] - Invoking deployment process
[192.168.1.114] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    gyp info spawn args   '-Dmodule_root_dir=/opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
    gyp ERR! System Linux 3.12.28+
    gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport
    gyp ERR! node -v v0.10.32
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'serialport' of package 'npm-container'
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'my-test-app' (linux)
```

**bindings.gyp**

```
{
  'targets': [
    {
      'target_name': 'serialport',
      'sources': [
        'src/serialport.cpp',
      ],
      'include_dirs': [
        '<!(node -e "require(\'nan\')")'
      ],
      'conditions': [
        ['OS=="win"',
          {
            'sources': [
              'src/serialport_win.cpp',
              'src/win/disphelper.c',
              'src/win/enumser.cpp',
            ],
            'msvs_settings': {
              'VCCLCompilerTool': {
                'ExceptionHandling': '2',
                'DisableSpecificWarnings': [ '4530', '4506' ],
              },
            },
          },
        ],
        ['OS=="mac"',
          {
            'sources': [
              'src/serialport_unix.cpp',
              'src/serialport_poller.cpp',
            ],
            'xcode_settings': {
              'OTHER_LDFLAGS': [
                '-framework CoreFoundation -framework IOKit'
              ]
            }
          }
        ],
        ['OS!="win"',
          {
            'sources': [
              'src/serialport_unix.cpp',
              'src/serialport_poller.cpp',
            ],
          }
        ],
      ],
    },
    {
      "target_name": "action_after_build",
      "type": "none",
      "dependencies": [ "<(module_name)" ],
      "copies": [
        {
          "files": [ "<(PRODUCT_DIR)/<(module_name).node" ],
          "destination": "<(module_path)"
        }
      ]
    }
  ],
}
```

**Comment by arunoda** [comment]
this module(serialport) is not arm compatible may be.
talk to them.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by nyxynyx** [comment]
@arunoda Have yet to check with them. But I first tried `mup deploy` to a fresh Ubuntu 14.04 server and encountered the same error!

**Comment by arunoda** [comment]
seems like <module_name> gyp variable is the issue.
Not sure, that's available with 0.10.x .

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by nyxynyx** [comment]
@arunoda Do you think that instead of `sudo node-gyp rebuild` [right here](https://github.com/arunoda/meteor-up/blob/44daf0152a859ebecc6ef1e9f445d20db5bc7ad7/templates/linux/deploy.sh#L9) it needs to be `npm install` which will dispatch to `node-pre-gyp rebuild`?

https://github.com/TooTallNate/node-gyp/issues/508#issuecomment-62621963

**Comment by joaopiopedreira** [comment]
Hi @arunoda, I've been fighting with this error for two days now, without results. Use mup to deploy my app (developed in MAC OS and deployed to ubuntu 14.04 on EC2). Had no problems for months. Yesterday I've installed a new npm module (osrm). In my MAC it works just fine. When I deploy it to ubuntu/EC2, have the following error (similar to the one reported above):

```
 ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    info spawn args   '-Dmodule_root_dir=/opt/RoutesDirect/tmp/bundle/programs/server/npm/npm-container/node_modules/osrm',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: Call to 'pkg-config libosrm --variable=prefix' returned exit status 1. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-36-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/RoutesDirect/tmp/bundle/programs/server/npm/npm-container/node_modules/osrm
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    aph_edge.o
      SOLINK_MODULE(target) Release/obj.target/profiler.node
      SOLINK_MODULE(target) Release/obj.target/profiler.node: Finished
      COPY Release/profiler.node
    make: Leaving directory `/opt/RoutesDirect/tmp/bundle/programs/server/npm/meteorhacks:kadira-binary-deps/node_modules/v8-profiler/build'
    => re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
    make: Entering directory `/opt/RoutesDirect/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/RoutesDirect/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
    => re-installing binary npm module 'osrm' of package 'npm-container'
    ----------------------------------------------------------------------------
```

**binding.gyp** (from [osrm](https://github.com/Project-OSRM/node-osrm) node module)

```
{
'includes': [ 'common.gypi' ],
'variables': {
  'std%':'ansi',
  'runtime_link%':'static',
  "module_name":"<!(node -e \"console.log(require('./package.json').binary.module_name)\")",
  "module_path":"<!(node -e \"console.log(require('./package.json').binary.module_path)\")",
},
'targets': [
{
  'target_name': '<(module_name)',
  'include_dirs': [
      '<!@(pkg-config libosrm --cflags)',
      './src/'
  ],
  'libraries': [
    '<!@(pkg-config libosrm --libs)'
  ],
  'conditions': [
    [ 'OS=="linux"', {
      'cflags_cc' : [
          '-std=c++11',
      ],
      'libraries':[
          '-Wl,-rpath=<!@(pkg-config libosrm --variable=prefix)/lib',
          '-lboost_program_options',
          '-lboost_regex'
      ]}
    ],
    ['runtime_link == "static"', {
        'libraries': [
            '<!@(pkg-config libosrm --libs --static)'
         ]
    }],
    ['OS=="mac"', {
      'xcode_settings': {
        'OTHER_CPLUSPLUSFLAGS':['-std=c++11','-stdlib=libc++'],
        'OTHER_CPLUSPLUSFLAGS':['-stdlib=libc++'],
        'OTHER_LDFLAGS':['-stdlib=libc++'],
        'CLANG_CXX_LANGUAGE_STANDARD':'c++11',
        'MACOSX_DEPLOYMENT_TARGET':'10.7'
      }
    }
    ]
  ],
  'sources': [
    "src/node_osrm.cpp"
  ],
  'cflags_cc!': ['-fno-rtti', '-fno-exceptions'],
  'xcode_settings': {
    'OTHER_CPLUSPLUSFLAGS':['-Wno-unneeded-internal-declaration', '-Wno-unknown-pragmas'],
    'GCC_ENABLE_CPP_RTTI': 'YES',
    'GCC_ENABLE_CPP_EXCEPTIONS': 'YES'
  }
},
{
  'target_name': 'action_after_build',
  'type': 'none',
  'dependencies': [ '<(module_name)' ],
  'copies': [
      {
        'files': [ '<(PRODUCT_DIR)/<(module_name).node' ],
        'destination': '<(module_path)'
      }
  ]
 }
]
}
```

I'm on an extremely tight schedule to deliver an app to a customer and really need to solve this. Have tried a deploy to a fresh ubuntu server and have the same error.

Any hints would be highly appreciated.

**Comment by arunoda** [comment]
Check their Readme. https://github.com/Project-OSRM/node-osrm

You need to have Ubuntu 14.04 or higher.

**Comment by joaopiopedreira** [comment]
Have Ubuntu 14.04 and checked all the dependencies they mention on their site (osrm). Can you give me some guidance on what else to check? Thanks

**Comment by valiafetisov** [comment]
Hi @nyxynyx, I was able to temporary fix this issue with serialport npm package by replacing

``` shell
sudo node-gyp rebuild 
```

with

``` shell
if test "$npmModule" = "./serialport"
then
  sudo node-pre-gyp rebuild
else
  sudo node-gyp rebuild
fi
```

inside the deploy script used by `mup deploy` 
`/usr/local/lib/node_modules/mup/templates/linux/deploy.sh`

seems like `mup` should check every npm package for the `bundledDependencies` like [here](https://github.com/voodootikigod/node-serialport/blob/master/package.json#L52), but can't figure out how to do that properly

**Comment by arunoda** [comment]
Actually we should use _npm install *instead of *node-pre-gyp rebuild_
But I got some issues with that. That's why I didn't make it published yet!

**Comment by camelCaseD** [comment]
For those with a sqlite3 npm dependency the following modification to my deploy.sh script fixed the issue for me:

``` shell
if test "$npmModule" = "./sqlite3"
then
  sudo npm install
else
   sudo node-gyp rebuild
fi
```

**Comment by joaopiopedreira** [comment]
This also did it for me (using npm package [osrm](https://www.npmjs.com/package/osrm)):

```
if test "$npmModule" = "./osrm"
then
  sudo npm install
else
  sudo node-gyp rebuild
fi
```

**Comment by arunoda** [comment]
Check now. With the latest Meteor UP  version, it also used `npm install`.
So, you don't need to worry about forking mup to add support to your npm modules.

Give it a try.

**Comment by arunoda** [comment]
Here's the related commit: https://github.com/arunoda/meteor-up/commit/b977847bab07ef068113a699b497dbe83fd96b29

**Comment by neppi** [comment]
Hi @valiafetisov,

your patch worked for me very well. I was trying to deploy an app with serialport to an RaspberryPi II  running Ubuntu 14.04 LTS

```
    "architecture": "armv7l",
    "node_version": "v0.10.38",
    "node_gyp_version": v3.0.1,
    "npm_version": "1.4.28",
```

Thanks for sharing this hotfix.

Neppi

**Comment by Makoehle** [comment]
For anyone coming across this error message with Github Actions I was to solve it by reducing the `node-version` from `16` to `14` and having `runs-on: ubuntu-20.04`
