### ISSUE TITLE
deployed twice worked well and now throwing errors

### ISSUE THREAD

**Issue by sasikanth513** [arunoda/meteor-up-legacy#149]
I have deployed to my ip twice with this and worked fine, and now I've added anothe npm package phantom to my app and now when I try to deploy it ,it is throwing some error

```
✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-container/node_modules/phantom/node_modules/dnode/node_modules/weak',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    s/dnode/node_modules/weak/build'
      CXX(target) Release/obj.target/weakref/src/weakref.o
      SOLINK_MODULE(target) Release/obj.target/weakref.node
      SOLINK_MODULE(target) Release/obj.target/weakref.node: Finished
      COPY Release/weakref.node
    make: Leaving directory `/opt/meteor/tmp/bundle/programs/server/npm/npm-container/node_modules/phantom/node_modules/dnode/node_modules/weak/build'

    > fibers@1.0.1 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    source-map-support@0.2.5 node_modules/source-map-support
    └── source-map@0.1.29 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    meteor stop/waiting
    meteor start/running, process 30029
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    meteor stop/waiting
    meteor start/running, process 30169
```

Anyone Have idea abou this? ANy suggestions welcome

**Comment by sasikanth513** [comment]
Got this error while checking logs

```
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteorus
```

**Comment by iboxgithub** [comment]
I have the same kind of logs with stepping down to gid:meteoruser, don't know what it means, I will let you know if I find something

**Comment by arunoda** [comment]
EACCES mean permission and your app is not allowed to start on the given port.

**Comment by domarty** [comment]
I just ran into a similar problem -- after a couple of days of hair pulling, figured out the problem was that my application was taking more than 15 seconds to initialize.  I changed deployCheckWaitTime in mup.json from 15 seconds to 120 seconds, and voila, everything worked perfectly.
