### ISSUE TITLE
MUP deployment problem on meteor 1.0

### ISSUE THREAD

**Issue by geekyme** [arunoda/meteor-up-legacy#163]
Got this after running mup deploy

```
[128.199.150.165] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    = -1) throw new Error("database
                                                              ^
    Error: database names cannot contain the character '.'
        at validateDatabaseName (/usr/lib/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/db.js:222:59)
        at new Db (/usr/lib/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/db.js:96:3)
        at connectFunction (/usr/lib/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:246:29)
        at Function.MongoClient.connect (/usr/lib/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:316:5)
        at connectAgain (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:25:17)
        at waitForMongo (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:23:3)
        at Object.<anonymous> (/usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:12:1)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/microscope-1.0/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    source-map-support@0.2.5 node_modules/source-map-support
    └── source-map@0.1.29 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    microscope-1.0 start/running, process 12052
    Waiting for MongoDB to initialize. (5 minutes)
    ----------------------------------------------------------------------------

```

**Comment by geekyme** [comment]
sorry i realized my error. I named my appName microscope-1.0, too anxious to try 1.0 :)
