### ISSUE TITLE
latest version of mup looks for a .versions file in .meteor folder

### ISSUE THREAD

**Issue by pronamc** [arunoda/meteor-up-legacy#166]
This file does not exist in my project. I am running meteor 0.8.3. 

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------


fs.js:438
 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
             ^
Error: ENOENT, no such file or directory '.meteor/versions'
at Object.fs.openSync (fs.js:438:18)
at Object.fs.readFileSync (fs.js:289:15)
at Actions._showKadiraLink (/usr/local/lib/node_modules/mup/lib/actions.js:65:21)
at Actions.deploy (/usr/local/lib/node_modules/mup/lib/actions.js:91:8)
at runActions (/usr/local/lib/node_modules/mup/bin/mup:42:28)
at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:34:5)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
```

**Comment by arunoda** [comment]
good point. I'll make a fix.

**Comment by arunoda** [comment]
fixed with a new release. 0.6.12

**Comment by pronamc** [comment]
Awesome! I was planning to close this as I could get around with using a previous version of mup.
