### ISSUE TITLE
DO Questions and error-> ```wait-for-mongo: failed to connect to

### ISSUE THREAD

**Issue by KyleKing** [arunoda/meteor-up-legacy#170]
I have a :
- digital ocean droplet setup for Ubuntu 14.10 x64
- for DNS, I have the Address field and three ns1.digitalocean.com name servers filled
  - do I need a subdomain?
  - is the Address field relevant to mup?
- I ran `mup init` in a separate directory and then included the path to the meteor directory in my mup.json file (password is obscured cause security):

``` js
{
    // Server authentication info
    "servers": [{
        "host": "104.236.25.149",
        "username": "root",
        "password": "<password>"
    }],

    // Install MongoDB in the server, does not destroy local MongoDB on future setup
    "setupMongo": true,

    // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
    "setupNode": true,

  // WARNING: nodeVersion defaults to 0.10.31 if omitted. Do not use v, just the version number.
  "nodeVersion": "0.10.31",

    // Install PhantomJS in the server
    "setupPhantom": true,

    // Application name (No spaces)
    "appName": "testProject",

    // Location of app (local directory)
    "app": "/Users/kyleking/Documents/Developer/testProject/",

      // Configure environment
      "env": {
        "PORT": 80,
        "ROOT_URL": "http://teamBikes.me",
        "MONGO_URL": "mongodb://root:<password>@teamBikes/testProject"
      },

    // Meteor Up checks if the app comes online just after the deployment
    // before mup checks that, it will wait for no. of seconds configured below
    "deployCheckWaitTime": 5
}
```
- I get all successful messages from mup setup, but
- after running mup deploy, I keep getting this warning (I used DEBUG*=):

``` term
source-map-support@0.2.5 node_modules/source-map-support
└── source-map@0.1.29 (amdefine@0.1.0)
testProject stop/waiting
testProject start/running, process 16283
Waiting for MongoDB to initialize. (5 minutes)
wait-for-mongo: failed to connect to [teamBikes:27017]
    ................
wait-for-mongo: failed to connect to [teamBikes:27017]
        stderr +5.1m Warning: Permanently added '104.236.25.149' (RSA) to the list of known hosts.
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.31 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/testProject/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.31/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.31',
gyp info spawn args   '-Dmodule_root_dir=/opt/testProject/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
    throw err;
          ^
Error: TIMEOUTED_WAIT_FOR_MONGO
    at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

[104.236.25.149] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.31',
    gyp info spawn args   '-Dmodule_root_dir=/opt/testProject/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    -----------------------------------STDOUT-----------------------------------
    es:27017]
    wait-for-mongo: failed to connect to [teamBikes:27017]
    ................
    wait-for-mongo: failed to connect to [teamBikes:27017]
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'testProject' (linux)
```
- How do I know the mongo port?

Any advice would be appreciated! I think this is the most relevant output, so let me know if I should add anything! - Kyle

**Comment by arunoda** [comment]
Where do you host your mongo? pre-installed by mup.
Then leave the MONGO_URL empty.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by KyleKing** [comment]
Thanks for the swift reply! I removed the mongo url and I finally got `[104.236.25.149] ✔ Invoking deployment process: SUCCESS`. How long until the site will be accessible? I still get a blank page at: http://teambikes.me

**Comment by KyleKing** [comment]
Using terminal, I only see one tmp folder with no contents. Shouldn't there be several folders in my droplet for meteor-up?

**Comment by arunoda** [comment]
see: http://104.236.25.149/

Your app has been deployed!
Did you setup DNS for the domain.
If so, it'll take a while.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by KyleKing** [comment]
Thanks! I just fixed the address field (it should have been '@') and now it works!
