### ISSUE TITLE
meteor-tool bunding error

### ISSUE THREAD

**Issue by dasmodel** [arunoda/meteor-up-legacy#208]
I'm having an issue deploying with Mup. I can't seem to figure out what is going wrong. Here is the error message after I `mup deploy`

Any hints as to how to fix would be great. I am running the latest meteor release. Let me know if you need more info

```
Building Started: .
Bundling Error: code=1, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
r-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
  at /Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:536:24
  at runWithEnvironment (/Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:136:21)
  at /Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:143:14
  at /Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:549:11

/usr/local/lib/node_modules/mup/lib/build.sh: line 42: cd: /tmp/b47bd338-c403-4a29-b060-e35a51ae39be: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
```

**Comment by arunoda** [comment]
Try to run your meteor app, before doing _mup deploy_.

**Comment by dasmodel** [comment]
I am able to run my meteor app fine without any errors. However I still get this same error when running mup deploy
Thank you for the quick response.

**Comment by dasmodel** [comment]
here are my mup logs:

```
error:   script /opt/myApp/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/myApp/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/myApp/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/myApp/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/myApp/app/main.js does not exist.
```

**Comment by arunoda** [comment]
Mup logs are fine, since app is not deployed yet.

Try invoking meteor build
to get the bundle. See if there's an error.

Is this a cordova app?

**Comment by dasmodel** [comment]
This isn’t a cordova app. I think meteor just has something related to cordova in their core library since all the cordova stuff is in .meteor/ . Running `meteor build` threw a huge error. Here’s a snippet since the error output is enormous:

```
/Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
            throw(ex);
                  ^
Error: RangeError: Maximum call stack size exceeded
  at Object.Future.wait (/Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:323:16)
  at /Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:556:31
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at /Users/dm/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:554:9
```

**Comment by arunoda** [comment]
Hmm.

I'm not sure why this error caused.
Could you submit into meteor's issue list?

**Comment by dasmodel** [comment]
will do. thank you for taking a look.

**Comment by arunoda** [comment]
no problem at all.

**Comment by dasmodel** [comment]
Ok I was able to find the cause of the meteor build error by creating a fresh project and adding back components individually. The file that broke the build was a 3rd party plugin that I had commented out completely because it was being executed when not in use. Deleting it did the trick.

However, when I try to deploy I now run into this error:

```
[104.236.100.163] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    oot_dir=/root/.node-gyp/0.10.33',
    gyp info spawn args   '-Dmodule_root_dir=/opt/packaging/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    e
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/packaging/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.1 install /opt/packaging/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.2
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    packaging start/running, process 21211
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'packaging' (linux)
```

I will keep looking into it but let me know if u have any ideas. thanks

**Comment by arunoda** [comment]
Check logs.
