### ISSUE TITLE
`mup deplay` related issue

### ISSUE THREAD

**Issue by tenzan** [arunoda/meteor-up-legacy#218]
When I ran `mup deploy` it's giving error:

```
[example.com] - Setting up Environment Variables
undefined:24
  throw err;
        ^
TypeError: ejs:8
    6| #it is possible to override above env-vars from the user-provided values
    7| <% for(var key in env) { %>
 >> 8|   export <%- key %>=<%- env[key].replace(/./ig, '\\$&') %>
    9| <% } %>
    10|

Object 80 has no method 'replace'
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:363)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:435)
    at /usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:250:15
    at /usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:229:55
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by arunoda** [comment]
Make sure to set strings in the env vars. I will fix the issue.

**Comment by tenzan** [comment]
Hi Arunoda!
I'm very new to it and can't get where these env vars are set.
If you mean `settings.json` which were generated by `mup init`, the initial file have only:

```
{
  "public": {

  }
}
```

**Comment by arunoda** [comment]
it's not settings. It's in the mup.json files. object with the field name
"env".

**Comment by tenzan** [comment]
The `env` part of `mup.json`:

```
 "env": {
        "PORT": 80,
        "ROOT_URL": "http://example.com",
        "MONGO_URL": "mongodb://user:password@<domain>:27017/<dbname>"
  }
```

**Comment by arunoda** [comment]
Update mup now to: v0.7.4
I've made a fix.

**Comment by tenzan** [comment]
```
askar@macbook:~/microscope-deploy$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /path/to/the/app
Bundling Error: code=-1, error:spawn ENOENT
-------------------STDOUT-------------------

-------------------STDERR-------------------
```

**Comment by tenzan** [comment]
Thanks Arunoda. It worked now. :)
I also found out I was pointing to the wrong app directory
`"app": "~/work/meteor/microscope"`

**Comment by arunoda** [comment]
Great. Hope we can close the issue now.

**Comment by tenzan** [comment]
Yes! Thanks a lot!
