### ISSUE TITLE
in mup.json env.PORT should be a string not integer

### ISSUE THREAD

**Issue by lc3t35** [arunoda/meteor-up-legacy#220]
I had this message with "PORT": 3000

```
mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /Users/laurent/dev/meteor/yo-battle

Started TaskList: Deploy app 'yo-battle' (linux)
[146.185.134.77] - Uploading bundle
[146.185.134.77] ✔ Uploading bundle: SUCCESS
[146.185.134.77] - Setting up Environment Variables

undefined:24
  throw err;
        ^
TypeError: ejs:8
    6| #it is possible to override above env-vars from the user-provided values
    7| <% for(var key in env) { %>
 >> 8|   export <%- key %>=<%- env[key].replace(/./ig, '\\$&') %>
    9| <% } %>
    10| 

Object 3000 has no method 'replace'
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:363)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:435)
    at /usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:250:15
    at /usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:229:55
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

If i correct "PORT": "3000" in mup.json

```
mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /Users/laurent/dev/meteor/yo-battle

Started TaskList: Deploy app 'yo-battle' (linux)
[146.185.134.77] - Uploading bundle
[146.185.134.77] ✔ Uploading bundle: SUCCESS
[146.185.134.77] - Setting up Environment Variables
[146.185.134.77] ✔ Setting up Environment Variables: SUCCESS
[146.185.134.77] - Invoking deployment process
```

OSX 10.8.5 deploying to Ubuntu server 3.2.0-23

**Comment by arunoda** [comment]
Update mup now to: v0.7.4
I've made a fix.
