### ISSUE TITLE
telescope deploy failed

### ISSUE THREAD

**Issue by bruceyongli** [arunoda/meteor-up-legacy#225]
I don't know why I can't deploy my telescope app. Can someone help me?

```
mup logs -n 300

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[130.111.111.111] Warning: Permanently added '130.111.111.111' (RSA) to the list of known hosts.
[130.111.111.111] error: Script restart attempt #27983
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27984
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27985
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27986
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27987
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27988
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27989
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27990
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27991
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27992
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27993
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27994
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27995
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27996
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27997
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27998
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #27999
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28000
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28001
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28002
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28003
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28004
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28005
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28006
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28007
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28008
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28009
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28010
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28011
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28012
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28013
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28014
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28015
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28016
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28017
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28018
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28019
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28020
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28021
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28022
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28023
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28024
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28025
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28026
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28027
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28028
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28029
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28030
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28031
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28032
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28033
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28034
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28035
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28036
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28037
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28038
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28039
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28040
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28041
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28042
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28043
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28044
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28045
Meteor requires Node v0.10.33 or[130.211.118.166]  later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28046
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28047
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28048
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28049
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28050
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28051
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28052
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28053
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28054
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28055
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28056
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28057
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28058
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28059
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28060
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28061
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28062
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28063
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28064
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28065
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28066
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28067
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28068
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28069
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28070
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28071
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28072
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28073
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28074
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28075
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28076
Meteor requires Node v0.10.33 or later.
error: Forever detected sc[130.211.118.166] ript exited with code: 1
error: Script restart attempt #28077
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28078
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #28079
Exception in callback of async function: MongoError: auth fails
    at Object.toError (/opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1128:31
    at /opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/opt/myapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at [object Object].emit (events.js:98:17)
```

My database is compose,
I tried deployCheckWaitTime form 30 to 300，
tried node version 0.10.33 and 0.10.35,
and I tried deploy on degitalocean and google cloud compute, and they both got the sam error as blow:

```
[130.111.111.111] - Uploading bundle
[130.111.111.111] ✔ Uploading bundle: SUCCESS
[130.111.111.111] - Setting up Environment Variables
[130.111.111.111] ✔ Setting up Environment Variables: SUCCESS
[130.111.111.111] - Invoking deployment process
[130.111.111.111] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    ibrary',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/myname/.node-gyp/0.10.35',
    gyp info spawn args   '-Dmodule_root_dir=/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    -----------------------------------STDOUT-----------------------------------

    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    wait-for-mongo: auth fails
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'myapp' (linux)

```

**Comment by bruceyongli** [comment]
Problem solved by first deploy original telescope app, then deploy modified version with the same settings.
