### ISSUE TITLE
nodejs error after successful mup install to ec2: at process._tickCallback (node.js:419:13)

### ISSUE THREAD

**Issue by tintoverano** [arunoda/meteor-up-legacy#237]
hello guys,

I get this error after success with mup deploy to ec2, mongo is running checked on remote:

```
at [object Object].<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

any ideas what is wrong here?

thanks,

tinto

**Comment by tintoverano** [comment]
hi,

I had an issue with CollectionFS (https://github.com/CollectionFS/Meteor-CollectionFS/issues/519) earlier which I fixed, but it seems mup update didn't replace the app on the remote server for some reason

is there any way to reinstall the complete app?

thanks,

tinto

**Comment by davidrinnan** [comment]
I am not sure exactly what you mean but you could remove the app-name-folder on the server and do a new deploay or change the app name in MUP and do a new deploy as a separate test, if you want to make sure you have a fresh app-install. 

is it a clean new installed ubuntu server or have you used for other stuff before

**Comment by tintoverano** [comment]
yes it is a clean install, only used for this app so far, I'm doing a new install the way you described

**Comment by tintoverano** [comment]
delete remote app folder reinstall server and app did the trick

thanks for the support!
