### ISSUE TITLE
mup deploy error

### ISSUE THREAD

**Issue by rdewolff** [arunoda/meteor-up-legacy#244]
Hi all

Am trying to update my mup meteor app but am having the following error :

```
tarted TaskList: Deploy app 'emp-manager' (linux)
[178.62.169.235] - Uploading bundle
[178.62.169.235] ✔ Uploading bundle: SUCCESS
[178.62.169.235] - Setting up Environment Variables
[178.62.169.235] ✔ Setting up Environment Variables: SUCCESS
[178.62.169.235] - Invoking deployment process
[178.62.169.235] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '178.62.169.235' (RSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/emp-manager/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    chalk@0.5.1 node_modules/chalk
    ├── escape-string-regexp@1.0.2
    ├── ansi-styles@1.1.0
    ├── supports-color@0.2.0
    ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
    └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    emp-manager stop/waiting
    emp-manager start/running, process 1275
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    emp-manager stop/waiting
    emp-manager start/running, process 1334
    ----------------------------------------------------------------------------
```

Anyone could help me?

Cheers!

**Comment by rdewolff** [comment]
My config file looks like this :

```
➜  .deploy git:(master) cat mup.json
{
  // Server authentication info
  "servers": [
    {
      "host": "IP",
      "username": "login",
      "password": "xxPasswordxx"
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.31 by default. Do not use v, only version number.
  "nodeVersion": "0.10.32",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": "emp-manager",

  // Location of app (local directory)
  "app": "/Users/rdewolff/Projets/emp-manager",

  // Configure environment
  "env": {
    "ROOT_URL": "http://178.62.169.235",
    "PORT": 80
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

The server is a simple OceanCloud server.

**Comment by rdewolff** [comment]
The `mup logs` command shows the following : 

```
➜  .deploy git:(master) mup logs

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[178.62.169.235] Warning: Permanently added '178.62.169.235' (RSA) to the list of known hosts.
[178.62.169.235] Meteor requires Node v0.10.33 or later.
Kadira.connect('piiNRAMR9ibQ7fcqh', '24e2d148-c1b9-468d-8f26-0e5caa95467d')
error: Forever detected script exited with code: 1
error: Script restart attempt #11
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #12
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

**Comment by mstn** [comment]
I have a similar problem. Deploy used to work. I do not know what is changed.

```
     -----------------------------------STDERR-----------------------------------
    y=default',
   gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/demo/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
   Latest deployment failed! Reverted back to the previous version.
```

mup logs

```
   Session terminated, terminating shell... ...terminated.
   Kadira: completed instrumenting the app
   Kadira: successfully authenticated
   error: Forever detected script exited with code: null
   error: Script restart attempt #1
   Kadira: completed instrumenting the app
   Kadira: successfully authenticated
   error: Forever detected script exited with code: null
   error: Script restart attempt #2
   Kadira: completed instrumenting the app
   Kadira: successfully authenticated
```

Meteor version METEOR@1.0.3.1
NodeJS version 0.10.33
MUP version 0.7.6

**Comment by mstn** [comment]
Hi there. I solved my problem. I am not sure but I think in my case versions were messed up. Maybe an old version of bcrypt not working with more recent meteor version? I stopped all services, uninstalled all npm packages, updated mup, ran mup setup again, redeployed the application.

**Comment by umbezt** [comment]
This has not worked for me. I am still getting the error.

**Comment by davidrinnan** [comment]
Whenever this has happened to me. 9.5 times out of 10 it is an issue with
the node version being too low.
This is usually due to another, non-MUP-managed installation of Node.

In terminal on the target server, write node -v to see which version you
are running.

and if you are not using MUP to install node, and the error states that
node 0.10.33 is needed update it. Can be done via NPM.

**Comment by umbezt** [comment]
@davidrinnan I am using digitalocean ubuntu 14.04 LTS VM. my node version is already 0.10.35 at the target machine. I uninstalled all npm packages and updated mup and then ran the setup, and deployed. But I am still get that Error but when i check my logs I don't get any data except the one from my cron which is running every 2 minutes.

**Comment by davidrinnan** [comment]
ok I referred to the log from rdewolff which stated: 
Meteor requires Node v0.10.33 or later.

@umbezt which error are you getting. there are a couple of different in this issue. 

do you have any errors in browser client console when you run meteor locally.

**Comment by umbezt** [comment]
[XXX.XXX.XX.XXX] - Uploading bundle
[XXX.XXX.XX.XXX] ✔ Uploading bundle: SUCCESS
[XXX.XXX.XX.XXX] - Setting up Environment Variables
[XXX.XXX.XX.XXX] ✔ Setting up Environment Variables: SUCCESS
[1XXX.XXX.XX.XXX] - Invoking deployment process
[XXX.XXX.XX.XXX] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Dnode_root_dir=/root/.node-gyp/0.10.35',
gyp info spawn args   '-Dmodule_root_dir=/opt/ssssss/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    hed
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/ssssss/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/ssssss/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

semver@4.1.0 node_modules/semver

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
ssssss stop/waiting
ssssss start/running, process 22941
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
ssssss stop/waiting
ssssss start/running, process 22974
----------------------------------------------------------------------------
```

I dont have any errors when am running locally

**Comment by davidrinnan** [comment]
I am not involved in the development of MUP I just try to remember from the top of my  mind the various errors I stumbled across in my MUP using days. 

The error you get seems very similar to the one you would get when you have a node version issue. That would however usually be apparent in the tail of your log. 

I've not only had issues with node but also npm. 

I found this from the author that might be interesting on a issue very similar to yours 
https://github.com/arunoda/meteor-up/issues/201#issuecomment-67991759

**Comment by umbezt** [comment]
Thank you @davidrinnan it looks like the issue was 'deployCheckWaitTime' was causing it. I just increased it and now evveryone is happy :).

**Comment by aykutyaman** [comment]
Thank you @umbezt

**Comment by arunoda** [comment]
Sure.

**Comment by MichaelErmer** [comment]
This also happens if you have a syntax error in an iron router {only: "server"} route.
To test agains such try run "meteor --production" first.

**Comment by bomb-on** [comment]
I was struggling with this problem also for some time until I red @umbezt post here. After I increased `deployCheckWaitTime` from default 15 to 60, suddenly everything worked perfectly fine.

I don't understand why was this failing, because looking at [this file](https://github.com/arunoda/meteor-up/blob/master/templates/linux/deploy.sh), the application is restarted and after `deployCheckWaitTime` seconds you try to `curl` it. Does it mean that (sometimes) it takes more than 15 seconds to start an app?

I use this opportunity to suggest to change default setting for `deployCheckWaitTime` to 30 or 60 and maybe even to consider renaming that particular setting to something like:

    // magic happens here
    "magic": 60

:)

Also, thanks for this nice tool and keep up the good work!

**Comment by cafe4it** [comment]
``` javascript
Started TaskList: Deploy app 'toioidungso' (linux)
[xemcungnhau.com] - Uploading bundle
[xemcungnhau.com] - Uploading bundle: SUCCESS
[xemcungnhau.com] - Setting up Environment Variables
[xemcungnhau.com] - Setting up Environment Variables: SUCCESS
[xemcungnhau.com] - Invoking deployment process
[xemcungnhau.com] x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    _root_dir=/root/.node-gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=/opt/toioidungso/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ode
    make: Leaving directory `/opt/toioidungso/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.5 install /opt/toioidungso/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    toioidungso stop/waiting
    toioidungso start/running, process 15201
    Waiting for 120 seconds while app is booting up
    Checking is app booted or not?
    toioidungso stop/waiting
    toioidungso start/running, process 15248
    ----------------------------------------------------------------------------
```

File : /etc/hosts

``` javascript
127.0.0.1   toioidungso
127.0.1.1   ubuntu

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

```

Edit file : /etc/hosts, comment ipv6 lines and reboot vps.

``` javascript
127.0.0.1   toioidungso
127.0.1.1   ubuntu

# The following lines are desirable for IPv6 capable hosts
#::1     localhost ip6-localhost ip6-loopback
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters
```

**Worked perfect.Sorry about my English.**

**Comment by ghost** [comment]
Hey after 1/2 year of growing fond of mup and its smooth deploys, we have just started getting this same result:
works fine on localhost
deploy using mup and get no errors except for the 2 uncaught TypeErrors on browser console:
    Uncaught TypeError: Cannot read property 'helpers' of undefined
    Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined

only iron:router main page background displays. Basic initialization of app appears to be running, but no display?????

I have created new AWS EC2 instance to insure that the server is clear of any conflicting node or bcrypt versions and still getting only iron:router main page background displays.

We are using ubuntu 14.04.2 LTS with node v0.10.36 on this instance.
matb33:collection-hooks 0.7.13 Extends Mongo.Collection with before/after hooks for insert/update/remove/fi...
meteor-platform 1.2.2 Include a standard set of Meteor packages in your app
meteorhacks:kadira 2.20.2\* Performance Monitoring for Meteor
meteorhacks:kadira-profiler 1.1.0 CPU Profiler for Kadira
meteorhacks:ssr 2.1.2 Server Side Rendering for Meteor with Blaze
mizzao:bootboxjs 4.4.0 Programmatic dialog boxes using Twitter's bootstrap modals
mizzao:bootstrap-3 3.3.1_1 HTML, CSS, and JS framework for developing responsive, mobile first project...
mizzao:user-status 0.6.4 User connection and idle state tracking for Meteor
momentjs:moment 2.10.3 Moment.js (official): parse, validate, manipulate, and display dates - offic...
mrt:accounts-t9n 0.0.13 Translations for the meteor account's error messages
mrt:accounts-ui-bootstrap-3 0.3.3 Bootstrap styled version of login widgets
and other packages

Any ideas would be great!!!!!
We are attempting to lock down our product for demonstrations to customers and then this issue has definitely caused some concern. Thank you

**Comment by arunoda** [comment]
Could you run your app locally with `meteor --production`

**Comment by ghost** [comment]
Yes we could/can run on localhost, thanks for your prompt reply. 
Our issue was fixed by replacing deprecated Route.map with Route.route.

**Comment by arunoda** [comment]
Okay. Got it.

**Comment by shawnmmatthews** [comment]
I've recently run into an error while deploying. I can run locally using meteor --production without problems. For whatever reason I'm receiving a type error that I can't seem to hunt down.

mup logs -n 300 looks as follows.

TypeError: Cannot call method 'slice' of null
    at Meteor.absoluteUrl.options (packages/meteor/url_server.js:11:1)
    at /opt/urbansim/app/programs/server/packages/meteor.js:1098:4
    at /opt/urbansim/app/programs/server/packages/meteor.js:1240:3
    at /opt/urbansim/app/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/urbansim/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/urbansim/app/programs/server/boot.js:117:5
error: Forever detected script exited with code: 8
error: Script restart attempt #112

/opt/urbansim/app/programs/server/boot.js:263
}).run();

I've tried tinkering with the node version and deployCheckWaitTime on serveral different VM's to no avail.

Any help would be EXTREMELY appreciated.

Cheers,
Shawn

**Comment by MasterJames** [comment]
If you could post your packages (file) you have installed currently. Maybe there's a conflict or one you could remove that's not needed? 
Otherwise I guess you could post your mup settings.
Also note if you find mup is not cutting it for you please try the development branch mupx.

**Comment by MasterJames** [comment]
Oh also the restart loop suggest running setup again too. The database can get locked I had added a way to clear it in my unutilized PR for adding Mongo backup & restore.

**Comment by shawnmmatthews** [comment]
So mupx fired right up. Is the configuration regarding Nginx much different between the two? I see that Mupx uses a docker instance that im guessing is preconfigured?

**Comment by MasterJames** [comment]
Yes mup uses stud as I recall so totally different.
The newer version under developed at kadirahq looks like people are trying to use it already! But I don't think it's safe from breaking changes yet. I imagine it's like mupx and nginx and docker centric but more customizable with the ability to replace docker images etc.
