### ISSUE TITLE
/opt folder and running the app

### ISSUE THREAD

**Issue by abtx** [arunoda/meteor-up-legacy#254]
Hi Arunoda, 
first of all a massive thanks for this wonderful program my life would be more dreadful without :) I did the first deployment to my server and all is good, I find my app living in /opt folder, which is exactly what the docs say. My rookie question is, how do I get access to the app? This isn't usual var/htdocs situation that I'm used to. I've specified ROOT_URL, but this just leads to empty folder on my server (yes, I pointed the app to an empty folder in htdocs). I'm bit confused as what to do now, can you help please? Thanks.

**Comment by rhyslbw** [comment]
What did you do here: "yes, I pointed the app to an empty folder in htdocs" ?

**Comment by abtx** [comment]
I did set the ROOT URL to a folder in www/htdocs, as in http://myDomain/folder/emptyFolder/ (that's in mup.json).I've set METEOR_ENV to production as well.

I also noticed a readme file in the /opt folder, trying to run what it says: 
 " $ (cd programs/server && npm install)
   $ export MONGO_URL='mongodb://user:password@host:port/databasename'
   $ export ROOT_URL='http://example.com'
   $ export MAIL_URL='smtp://user:password@mailhost:port/'
   $ node main.js ".

Now, I try to execute this part ssh'ed to my server, but I'm getting this error at npm install: 
"npm WARN package.json meteor-dev-bundle@0.0.0 No description
 npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
 npm WARN package.json meteor-dev-bundle@0.0.0 No README data"

No clue where to go next, googling for these errors doesn't get lead to anything interesting here..

**Comment by davidrinnan** [comment]
I dont know if the root_url matters that much but mine is set to the domain that is used on the server. E.g. http://mymupapp.microsoft.com

**Comment by abtx** [comment]
Does setting up http://mymupapp.microsoft.com as your url in mup.json makes the app automatically available at that url for you then?

**Comment by davidrinnan** [comment]
Not for me at least. As far as I use it, it is basically just making sure that any links that I create, let's say in an email that is sent to the user, has the correct URL. To make meteor aware under which domain it is working. 

Personally I am fronting my mup installs with nginx so any domain translation/forwarding is handled at that level. 

But maybe it is used for more, under the hood, I've just never heard of anyone writing a directory path. Usually it is an IP adress or domain. 

Do you get any more useful error messages if you check 
mup logs -n 400 
you do that in the same directory where you run mup deploy 

In your mup.json file what have you written for port? 
  // Configure environment
  "env": {
    "PORT": 3000,
    "ROOT_URL": "http://microsoft.com",

if you have the above you would access it via http://microsoft.com:3000
If you happen to own that domain name and it points to your servers IP adress. (if you have defined 3000 as the port for your app in mup.json that is)

If you haven't pointed a domain to the server you would use your servers IP address instead. 

if you access your server terminal via ssh and write 
curl localhost:3000 
you should get the HTML output from the meteor app in your terminal.

**Comment by abtx** [comment]
Yes, I've got the port set up correctly, the url I use is a subdomain, as in IPAddress/dev/projectName/, thus cannot access it with port number appended.. It would make sense to use some tool to manage DNS (I'm really no expert here), and point my domain name to the right physical directory where the app lives (which happens to be in the /opt folder, I reckon). 
Another thing is that my /opt folder contains my app after deployment, but the app folder contains just main.js, programs folder, readme, server folder and start.json. Really not sure what's going on. 
Luckily, mup logs -n 400 throws some errors I've noticed now. It's bunch of variations for the following:

"Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #125".

Quick search says the port number is already in use. 

I'd really like to find some good tutorials leading through this, but there seem to be nothing detailed out there, nothing for complete novices like myself. I really enjoy working with Meteor; it delivers with front/backend solutions,  but deployment seems to be quite a tricky thing for myself.

**Comment by davidrinnan** [comment]
The port u r using seems to be in use
fre 6 feb 2015 kl. 19:27 skrev abtx notifications@github.com:

**Comment by rizkysyazuli** [comment]
same question here. still unclear about what happen after a `mup deploy`. is it live yet? how do we access the app?

**Comment by protometa** [comment]
The app will be available at the host and port you setup.

**Comment by rizkysyazuli** [comment]
@protometa i want to upload it to a subdomain. what should i do? changing the host and root url setting to `sub.domain.com` doesn't work. the subdomain still shows the default index page.

here's my settings:

```
{
  "servers": [
    {
      "host": "app.mysite.com",
      "username": "ubuntu",
      "pem": "~/path/to/app.pem"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.36",
  "setupPhantom": true,
  "appName": "AppName",
  "app": "/local/path/to/app",
  "env": {
    "ROOT_URL": "http://app.mysite.com/"
  },
  "deployCheckWaitTime": 15
}
```

**Comment by rizkysyazuli** [comment]
i finally managed to get my app up and running. but i still haven't found a way to deploy to a a sub-folder or a sub-domain. any ideas?
