### ISSUE TITLE
Add me to the list of Mup Deploy sudden errors..

### ISSUE THREAD

**Issue by etmarch** [arunoda/meteor-up-legacy#257]
2 Days ago I was deploying fine, and now I keep getting this output: 
```Started TaskList: Deploy app 'insonic' (linux)
[104.131.43.58] - Uploading bundle
[104.131.43.58] ✔ Uploading bundle: SUCCESS
[104.131.43.58] - Setting up Environment Variables
[104.131.43.58] ✔ Setting up Environment Variables: SUCCESS
[104.131.43.58] - Invoking deployment process
[104.131.43.58] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
node_root_dir=/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/insonic/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/insonic/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/insonic/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
insonic stop/waiting
insonic start/running, process 4782
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
insonic stop/waiting
insonic start/running, process 4886
```

```
```

The only thing I can think of is that I worked with compose.io to migrate my database into the same region as my Digital Ocean droplet - but Im still almost positive im setting everything right in settings.json: 

```
{
  // Server authentication info
  "servers": [
    {
      "host": "111.111.111",
      "username": "xxxx",
      "password": "xxxx"
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
  "nodeVersion": "0.10.33",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": "insonic",

  // Location of app (local directory)
  "app": ".",

  // Configure environment
  "env": {
    "ROOT_URL": "http://111.11.111.111/",
    "MONGO_URL": "mongodb://xxx:xxx@c210.capital.1.mongolayer.com:10210,c207.capital.0.mongolayer.com:10207/insonicdev?replicaSet=set-54d2a455cd5fdf50f4000b72",
    "MONGO_OPLOG_URL": "mongodb://xxx:xxx@c210.capital.1.mongolayer.com:10210,c207.capital.0.mongolayer.com:10207/local?authSource=insonicdev"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 30
}
```

**Comment by arunoda** [comment]
Please check mup logs.

**Comment by etmarch** [comment]
Logs output:

```
MongoError: Index with pattern: { username: 1 } already exists with different options
    at Object.Future.wait (/opt/insonic/app/programs/server/node_modules/fibers/future.js:326:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:689:1)
    at packages/aldeed:collection2/collection2.js:61:1
    at /opt/insonic/app/programs/server/boot.js:212:5
    - - - - -
    at Object.toError (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1286:26
    at Server.Base._callHandler (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/opt/insonic/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
error: Forever detected script exited with code: 8
error: Scr[104.131.43.58] ipt restart attempt #12
=> GraphicsMagick found

/opt/insonic/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Cannot find module './errors_api_rejection'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/opt/insonic/app/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/node_modules/bluebird/js/main/promise.js:54:20)
    at Object.<anonymous> (/opt/insonic/app/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/node_modules/bluebird/js/main/bluebird.js:24:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
=> GraphicsMagick found
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
Kadira: completed instrumenting the app
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
```

Should I drop all of my collections in my compose.io database and then setup again?

**Comment by etmarch** [comment]
I figured out what it was - I had set unique:true on the User Schema I wrote with the package Aldeed:simple-schema. The deploy worked! Thanks for your help as always Arunoda
