### ISSUE TITLE
Codeship deployment (to digitalocean) issue with meteorhacks:npm

### ISSUE THREAD

**Issue by yubozhao** [arunoda/meteor-up-legacy#284]
Hi @arunoda 

Thank you for the awesome package.   

Right now I am deploying to digitalocean through Codeship, everything is fine until I add meteorhacks:npm   

I have been deploying fine with meteorhacks:npm from my local.

The error message throwed at me is 

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: .
Bundling Error: code=2, error:
-------------------STDOUT-------------------
npm-container: updating npm dependencies -- winston, winston-papertrail...

-------------------STDERR-------------------
64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:317:26)
at /home/rof/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:536:24
at runWithEnvironment (/home/rof/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:139:21)
at /home/rof/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:146:14
at /home/rof/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:549:11

/home/rof/src/github.com/yubozhao/umi/node_modules/mup/lib/build.sh: line 42: cd: /tmp/eaf71a3b-d5cc-4b9f-8f6a-c0a936ff48bc: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

**Comment by arunoda** [comment]
Not exactly sure, may be some bundling issue. Try to do meteor build inside
codeship.

You can ssh into their build box and try out.
