### ISSUE TITLE
Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by bisserof** [arunoda/meteor-up-legacy#285]
Deploy failed with node v0.12.0 on server.
Rolling back to older node version helped me.

```
    -----------------------------------STDERR-----------------------------------
    t end of input
    ../src/bcrypt_node.cc:85:13: warning: 'void crypto_lock_init()' defined but not used [-Wunused-function]
    ../src/bcrypt_node.cc:95:13: warning: 'void crypto_lock_cb(int, int, const char*, int)' defined but not used [-Wunused-function]
    ../src/bcrypt_node.cc:105:22: warning: 'long unsigned int crypto_id_cb()' defined but not used [-Wunused-function]
    make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
    gyp ERR! System Linux 2.6.32-34-pve
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /usr/local/battle/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
    make: Entering directory `/usr/local/battle/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
    make: Leaving directory `/usr/local/battle/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
    ----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
Meteor do not support 0.12.x yet. Use 0.10.x

**Comment by jonwhittlestone** [comment]
I'm also getting this message and I'm on - v0.10.35

**Comment by woniesong92** [comment]
@arunoda How do you specify node version? In `Mup.json` I have `"nodeVersion": "0.10.28",` but I also get the same error.

**Comment by arunoda** [comment]
May be your server comes with 0.12.x

**Comment by woniesong92** [comment]
You were absolutely right. Thank you!
1. ssh into your server
2. downgrade node on the server to 0.10.28
3. mup setup
4. mup deploy

However, I am still facing some errors.

`Failed to connect to localhost port 80: Connection refused`

**Comment by arunoda** [comment]
Now do `mup logs -n 300` and check logs.
