### ISSUE TITLE
Error: listen EADDRINUSE[104.131.xxx]  and high CPU usage

### ISSUE THREAD

**Issue by madshargreave** [arunoda/meteor-up-legacy#294]
Hey

I have an meteor app deployed on DigitalOcean using mup. That app is working fine when visiting its IP, but I noticed through Kadira, that it constantly runs at 90% CPU usage, even though it's fairly simple and currently has no users.

I then noticed that when I run mup logs -a, I get the following

error: Script restart attempt #27
[104.131.113.12] Kadira: successfully authenticated
[104.131.113.12] Kadira: completed instrumenting the app
[104.131.113.12] Error: listen EADDRINUSE[104.131.113.12] 
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)[104.131.113.12] 
    at listen (net.js:1064:10)
    at net.js:1146:9
[104.131.113.12]     at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 7
error: Script restart attempt #28
[104.131.113.12] Kadira: successfully authenticated[104.131.113.12] 
Kadira: completed instrumenting the app
[104.131.113.12] Error: listen EADDRINUSE[104.131.113.12] 
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
[104.131.113.12]     at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 7
error: Script restart attempt #29

I tried to SSH onto the server and run 'ps ax' to see if any other meteor instance was occupying port 80, but there wasn't. 

I have tried restarting the server 'sudo reboot', running mup setup/deploy,restart,stop, start etc... but nothing works

**Comment by jhmacdon** [comment]
I am getting the exact same issue. I even removed all the remote folders and everything. Incredibly annoying...

**Comment by sasi513** [comment]
same issue here, I had to manually deploy to same servers to make it work normally

Here is the image from EC2 dashboard
![screen shot 2015-07-07 at 7 21 53 am](https://cloud.githubusercontent.com/assets/6647092/8538752/01459836-248f-11e5-9e09-aa162d9c386c.png)

**Comment by arunoda** [comment]
I suggest you to move to mupx where we fixed this kind of issues.

**Comment by sasi513** [comment]
Okay thx...
