### ISSUE TITLE
Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by kuaikuaikim** [arunoda/meteor-up-legacy#296]
when i use "mup deploy"  to deploy my app, the mup occured an error. I dont know how to fix this.can somebody has any idea. @arunoda. The following stderr message:

Warning: Permanently added '' (ECDSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:3000; Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

```
> fibers@1.0.1 install /opt/uzitv/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@2.2.1 node_modules/semver

source-map-support@0.2.5 node_modules/source-map-support
└── source-map@0.1.29 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
uzitv stop/waiting
uzitv start/running, process 25755
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
uzitv stop/waiting
uzitv start/running, process 25986
----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
Check for `mup logs -n 300`

**Comment by kuaikuaikim** [comment]
Thanks @arunoda , i have done as you said and figure out some message:. do you know how to fix it? maybe i lose some module.

at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/uzitv/app/programs/server/boot.js:95:18)
    at cmd (packages/mrt:server-eval/helpers.js:116)
    at /opt/uzitv/app/programs/server/packages/mrt_server-eval.js:850:4
    at /opt/uzitv/app/programs/server/packages/mrt_server-eval.js:906:3
    at /opt/uzitv/app/programs/server/boot.js:168:10
    at Array.forEach (native)
error: Forever detected script exited with code: 8
error: Script restart attempt #213

/opt/uzitv/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by dan335** [comment]
I'm getting a similar error.  The logs aren't helping.

```
Error: listen EACCES
at errnoException (net.js:904:11)
at Server._listen2 (net.js:1023:19)
at listen (net.js:1064:10)
at net.js:1146:9
at dns.js:72:18
at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #8

events.js:72
    throw er; // Unhandled 'error' event
          ^
Error: listen EACCES
at errnoException (net.js:904:11)
at Server._listen2 (net.js:1023:19)
at listen (net.js:1064:10)
at net.js:1146:9
at dns.js:72:18
at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #9
```
