### ISSUE TITLE
Error when deploying to digitalocean

### ISSUE THREAD

**Issue by yanndebelgique** [arunoda/meteor-up-legacy#302]
Hello,

This is what I get from mup logs -n 300. I don't know why this is. Last commit I had no errors so probably I have a bug in my code but the errors don't tell me where to look :(

Its weird because these errors don't prevent the server to run but I do get  an error : 

Started TaskList: Deploy app 'lightnow' (linux)
[178.62.241.102] - Uploading bundle
[178.62.241.102] ✔ Uploading bundle: SUCCESS
[178.62.241.102] - Setting up Environment Variables
[178.62.241.102] ✔ Setting up Environment Variables: SUCCESS
[178.62.241.102] - Invoking deployment process
[178.62.241.102] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ode_root_dir=/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/lightnow/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    elease/bcrypt_lib.node
    make: Leaving directory `/opt/lightnow/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/lightnow/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

semver@4.1.0 node_modules/semver

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
lightnow stop/waiting
lightnow start/running, process 31517
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
lightnow stop/waiting
lightnow start/running, process 31553
```

/opt/lightnow/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
TypeError: Cannot call method 'toUppe[178.62.241.102] rCase' of undefined
    at Object.later.parse.cron (/opt/lightnow/app/programs/server/npm/percolatestudio:synced-cron/node_modules/later/later.js:1022:18)
    at Object.SyncedCron.add.schedule (packages/insight-scheduler/insight-scheduler.js:26:1)
    at scheduleEntry (packages/percolatestudio:synced-cron/synced-cron-server.js:57:1)
    at packages/percolatestudio:synced-cron/synced-cron-server.js:92:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at packages/percolatestudio:synced-cron/synced-cron-server.js:91:1
    at /opt/lightnow/app/programs/server/boot.js:212:5
error: Forever detected script exited with code: 8
error: Script restart attempt #1

/opt/lightnow/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Cannot find module 'qs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lightnow/app/programs/server/npm/mrt:mailchimp/node_modules/mailchimp/lib/mailchimp/MailChimpWebhook.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #2

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/lightnow/app/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
    at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:20:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by yanndebelgique** [comment]
Ok there was an error in production... Sorry false alarm! I found out about my problem while running production mode locally and actually see what was being excecuted.

**Comment by ghost** [comment]
I'm using Digital Ocean, Ubuntu 14.04.4 x64.

! I got it working by resizing the Droplet from 512MB to 1GB !

I also:

updated node and npm to the latest version (1.4.28 npm and v4.4.0 node)
in my mup.json "setupMongo": true, "setupNode": true, "nodeVersion": "0.10.40",
