### ISSUE TITLE
Deploy failure from different machine

### ISSUE THREAD

**Issue by aykutyaman** [arunoda/meteor-up-legacy#311]
I can deploy from the machine which I have used for first deploy.
When I want to deploy my app from a different machine, `mup deploy` gives me this error:

```
Started TaskList: Deploy app 'kureselonline' (linux)
 - Uploading bundle
 ✔ Uploading bundle: SUCCESS
 - Setting up Environment Variables
 ✔ Setting up Environment Variables: SUCCESS
- Invoking deployment process
 ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    epth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm ERR! Error: EACCES, mkdir '/home/ubuntu/.npm/glob/4.5.3'
    npm ERR!  { [Error: EACCES, mkdir '/home/ubuntu/.npm/glob/4.5.3']
    npm ERR!   errno: 3,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/home/ubuntu/.npm/glob/4.5.3',
    npm ERR!   parent: 'tap' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! System Linux 3.13.0-44-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! cwd /opt/kureselonline/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    npm ERR! node -v v0.10.33
    npm ERR! npm -v 1.4.28
    npm ERR! path /home/ubuntu/.npm/glob/4.5.3
    npm ERR! code EACCES
    npm ERR! errno 3
    npm ERR! stack Error: EACCES, mkdir '/home/ubuntu/.npm/glob/4.5.3'
    npm ERR! not ok code 0
    -----------------------------------STDOUT-----------------------------------
     > ./bcrypt: npm install due to binary npm modules
    make: Entering directory `/opt/kureselonline/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/kureselonline/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'kureselonline' (linux)
```

**Comment by arunoda** [comment]
Try updating mup.

**Comment by dan335** [comment]
I just got a similar one.  Mup is updated.

```
[107.170.238.196] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
       'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-43-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/dominus/tmp/bundle/programs/server/npm/meteorhacks_cluster/node_modules/mongodb/node_modules/kerberos
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok 
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'bson' of package 'meteorhacks_cluster'
    make: Entering directory `/opt/dominus/tmp/bundle/programs/server/npm/meteorhacks_cluster/node_modules/mongodb/node_modules/bson/build'
      CXX(target) Release/obj.target/bson/ext/bson.o
      SOLINK_MODULE(target) Release/obj.target/bson.node
      SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
      COPY Release/bson.node
    make: Leaving directory `/opt/dominus/tmp/bundle/programs/server/npm/meteorhacks_cluster/node_modules/mongodb/node_modules/bson/build'
    => re-installing binary npm module 'kerberos' of package 'meteorhacks_cluster'
    make: Entering directory `/opt/dominus/tmp/bundle/programs/server/npm/meteorhacks_cluster/node_modules/mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    make: Leaving directory `/opt/dominus/tmp/bundle/programs/server/npm/meteorhacks_cluster/node_modules/mongodb/node_modules/kerberos/build'
    ----------------------------------------------------------------------------
```

**Comment by dan335** [comment]
Using meteorhacks:cluster 1.5 instead of 1.6 fixed my error.

**Comment by arunoda** [comment]
Try to update mup and deploy again.
I've fixed some issues with our NPM build logic.

@dan335 you don't need to downgrade cluster.

**Comment by aykutyaman** [comment]
Thank you @arunoda

**Comment by riendaamen** [comment]
First: thanks for mup, works great!
Only in my new project, after a few updates I got this problem on deployment.
(mup and meteor are up to date)

[185.66.249.219] - Uploading bundle
[185.66.249.219] ✔ Uploading bundle: SUCCESS
[185.66.249.219] - Setting up Environment Variables
[185.66.249.219] ✔ Setting up Environment Variables: SUCCESS
[185.66.249.219] - Invoking deployment process
[185.66.249.219] ✘ Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
    gyp ERR! System Linux 3.13.0-48-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/think-dementia/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
    gyp ERR! node -v v0.10.33
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok
    -----------------------------------STDOUT-----------------------------------
    erver/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
      CXX(target) Release/obj.target/bson/ext/bson.o
      SOLINK_MODULE(target) Release/obj.target/bson.node
      SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
      COPY Release/bson.node
    make: Leaving directory `/opt/think-dementia/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
    => re-installing binary npm module 'kerberos' of package 'vsivsi_file-collection'
    make: Entering directory `/opt/think-dementia/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    make: Leaving directory `/opt/think-dementia/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
    ----------------------------------------------------------------------------
```

**Comment by riendaamen** [comment]
Problem solved with help from Arunoda, thanks.

When upgrading Meteor and/or mup, allways make sure to mup init again, because of Node version dependency.

**Comment by radiegtya** [comment]
I am using node version 0.10.36, and having similar issue now. I also have been updating mup version.

**Comment by giggioz** [comment]
Solved:

In your server install

```
apt-get install libkrb5-dev
```

**Comment by ownagedj** [comment]
Thanks @giggioz this worked for me :+1: . Ubuntu 15.04 x64

**Comment by Vrchz** [comment]
@giggioz Thanks !!!
Same applies to xubuntu 15.04 install Mongodb.

**Comment by danjudex** [comment]
Thanks  @giggioz ubuntu 14.04 under lxc without this library

**Comment by karthikeayan** [comment]
apt-get install libkrb5-dev
solves my problem.
