### ISSUE TITLE
Parse error on mup setup

### ISSUE THREAD

**Issue by disqvr** [arunoda/meteor-up-legacy#312]
Hi guys,

I get the following error on executing mup setup:

/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:221
        throw err;
              ^
Error: Parse error on line 6:
...,      "username": "disqvr“,      "pas
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'"
File: "/Users/Sophie/GitHub/Telescope/mup.json"
    at Object.parseError (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:88:28)
    at Object.load (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:218:24)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:12:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

Still, I think that the data in my mup.json file are correct - I can't figure out, why there is a parsing error.
My mup.json file looks as following: 

{
  // Server authentication info
  "servers": [
    {
      "host": "betelgeuse.uberspace.de",
      "username": "disqvr“,
      "password": “pwd“
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
  "nodeVersion": "0.10.33",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": „techregate“,

  // Location of app (local directory)
  "app": „.“,

  // Configure environment
  "env": {
    "ROOT_URL": "http://disqvr.betelgeuse.uberspace.de"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

Any ideas what could be the problem?
Any help is highly appreciated!
Thanks!

**Comment by arunoda** [comment]
Quotation for username is wrong. Double check that.

**Comment by hichana** [comment]
Hi - I have a similar issue and I have no idea what to do. Please help!

Last login: Sat Apr 11 10:54:17 on ttys000
Matthews-MBP-2:~ matthewchana$ cd telescope
Matthews-MBP-2:telescope matthewchana$ mup setup

## Meteor Up: Production Quality Meteor Deployments

/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:221
        throw err;
              ^
Error: Parse error on line 33:
.../pipeline.io/"    "MONGO_URL": "mongod
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'"
File: "/Users/matthewchana/Telescope/mup.json"
    at Object.parseError (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:88:28)
    at Object.load (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:218:24)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:12:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
Matthews-MBP-2:telescope matthewchana$

**Comment by hichana** [comment]
Ah, I figured out my own problem. I needed to add a comma after my ROOT_URL which would allow the second line of code not not blend in.
So instead of:
"ROOT_URL": "http://pipeline.io/"

I needed:
"ROOT_URL": "http://pipeline.io/",
