### ISSUE TITLE
Mup cannot deploy on Meteor 1.0.4.1 

### ISSUE THREAD

**Issue by patrickml** [arunoda/meteor-up-legacy#321]
MUP Deployment is failing after upgrading to version 1.0.4

 ✘ Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    Dnode_root_dir=/root/.node-gyp/0.10.34',
    gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        inished
          COPY Release/bcrypt_lib.node
        make: Leaving directory '/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
    > fibers@1.0.5 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
    └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    meteor stop/waiting
    meteor start/running, process 471
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    meteor stop/waiting
    meteor start/running, process 531
    ----------------------------------------------------------------------------
```

**Comment by JeremySaks** [comment]
I am encountering this same error. It appears to be having trouble connecting to the db.

```
[104.236.42.68] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    ibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=/opt/finishers-admin/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    -----------------------------------STDOUT-----------------------------------
    -mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
    wait-for-mongo: auth failed
```

I have added the results of `mup logs -n 100` below.

```
MongoError: auth failed
    at Object.Future.wait (/opt/finishers-admin/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /opt/finishers-admin/app/programs/server/packages/accounts-base.js:243:4
    at /opt/finishers-admin/app/programs/server/packages/accounts-base.js:1659:3
    at /opt/finishers-admin/app/programs/server/boot.js:222:10
    - - - - -
    at Object.toError (/opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1194:31
    at /opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
    at [object[104.236.42.68]  Object].<anonymous> (/opt/finishers-admin/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #368
```

The steps I took prior to this deploy were to upgrade to Meteor 1.0.4.1; npm update mup -g; upgrade the node version in mup.json to 0.10.36; run 'mup setup`and`mup deploy`. I also upgraded my remote database on Compose from Mongo 2.4.12 to 2.6.8 and upgraded the user authorization format to 2.6 as well.

I have not changed any mup env settings for `MONGO_URL` or `MONGO_OPLOG_URL` in `mup.json` and I can log in with both via the shell - would either of these settings need to change to connect?

**Comment by arunoda** [comment]
@patrickml check mup logs with `mup logs -n 400`.

@JeremySaks It's hard to say without looking at the Mongo URL. If possible try to paste your `MONGO_URL` here. (remove username and password. And change the hostname)

**Comment by JeremySaks** [comment]
Here are the mongo_url and mongo_oplog_url formats (with private details changed) that I am using in `mup json`. I have not changed them from Meteor 1.0.3. 

```
"MONGO_URL": "mongodb://'admin':'fakepass'@capital.3.mongolayer.com:11111,capital.2.mongolayer.com:22222/dbname",
"MONGO_OPLOG_URL": "mongodb://'oplogger':'fakepass'@capital.2.mongolayer.com:22222,capital.3.mongolayer.com:11111/local?authSource=dbname"
```

I was trying to determine if they needed to change based on this comment in the release notes to 1.0.4:

```
The MongoDB command needed to set up user permissions for the oplog observe driver is slightly different in MongoDB 2.6; see https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver for details.
```

But I could not tell if they need to change. I am able to log in with 'admin' and 'oplogger' from the shell but MUP is having trouble authorizing I think.

**Comment by arunoda** [comment]
I can't see any issues with this. 
We are using a tool called wait-for-mongo to check MongoDB's state: https://www.npmjs.com/package/wait-for-mongo

And try to log into your server and check the env vars at: `/opt/<appName>/config/env.sh`. 
May be there'll be some issues with that. If so, let's try to fix it.

**Comment by JeremySaks** [comment]
Hmmm, `/opt/<appName>/config/env.sh` looks to be well-formatted although I might not know if something was off. It contains all the environment variables in `mup.json`.

Also, the env variables seem to be getting set up correctly:

```
$ mup setup
Started TaskList: Setup (linux)
[104.236.42.68] - Installing Node.js
[104.236.42.68] ✔ Installing Node.js: SUCCESS
[104.236.42.68] - Installing PhantomJS
[104.236.42.68] ✔ Installing PhantomJS: SUCCESS
[104.236.42.68] - Setting up Environment
[104.236.42.68] ✔ Setting up Environment: SUCCESS
[104.236.42.68] - Configuring upstart
[104.236.42.68] ✔ Configuring upstart: SUCCESS
Completed TaskList: Setup (linux)

$ mup deploy
Started TaskList: Deploy app 'myApp' (linux)
[104.236.42.68] - Uploading bundle
[104.236.42.68] ✔ Uploading bundle: SUCCESS
[104.236.42.68] - Setting up Environment Variables
[104.236.42.68] ✔ Setting up Environment Variables: SUCCESS
[104.236.42.68] - Invoking deployment process
[104.236.42.68] ✘ Invoking deployment process: FAILED
```

I'm not sure where else I might want to check.

**Comment by arunoda** [comment]
Then try wait-for-mongo with that env variable. Weird.

**Comment by mmoyles87** [comment]
I just had the same issue, make sure you are using the min. version of node
for the new version of Meteor.

I had to change my mup.json to

  "nodeVersion": "0.10.36",

On Wed, Mar 18, 2015 at 9:39 PM, Arunoda Susiripala <
notifications@github.com> wrote:

> Then try wait-for-mongo with that env variable. Weird.
> 
> On Thu, Mar 19, 2015 at 7:07 AM Jeremy Saks notifications@github.com
> wrote:
> 
> > Hmmm, /opt/<appName>/config/env.sh looks to be well-formatted although I
> > might not know if something was off. It contains all the environment
> > variables in mup.json.
> > 
> > Also, the env variables seem to be getting set up correctly:
> > 
> > $ mup setup
> > Started TaskList: Setup (linux)
> > [104.236.42.68] - Installing Node.js
> > [104.236.42.68] ✔ Installing Node.js: SUCCESS
> > [104.236.42.68] - Installing PhantomJS
> > [104.236.42.68] ✔ Installing PhantomJS: SUCCESS
> > [104.236.42.68] - Setting up Environment
> > [104.236.42.68] ✔ Setting up Environment: SUCCESS
> > [104.236.42.68] - Configuring upstart
> > [104.236.42.68] ✔ Configuring upstart: SUCCESS
> > Completed TaskList: Setup (linux)
> > 
> > $ mup deploy
> > Started TaskList: Deploy app 'myApp' (linux)
> > [104.236.42.68] - Uploading bundle
> > [104.236.42.68] ✔ Uploading bundle: SUCCESS
> > [104.236.42.68] - Setting up Environment Variables
> > [104.236.42.68] ✔ Setting up Environment Variables: SUCCESS
> > [104.236.42.68] - Invoking deployment process
> > [104.236.42.68] ✘ Invoking deployment process: FAILED
> > 
> > I'm not sure where else I might want to check.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arunoda/meteor-up/issues/321#issuecomment-83252680.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/321#issuecomment-83253293.

## 

Matt Moyles
http://mattmoyles.com

**Comment by mmoyles87** [comment]
And after changing that setting re-run mup setup

On Wed, Mar 18, 2015 at 9:44 PM, Matt Moyles mattmoyles@gmail.com wrote:

> I just had the same issue, make sure you are using the min. version of
> node for the new version of Meteor.
> 
> I had to change my mup.json to
> 
>   "nodeVersion": "0.10.36",
> 
> On Wed, Mar 18, 2015 at 9:39 PM, Arunoda Susiripala <
> notifications@github.com> wrote:
> 
> > Then try wait-for-mongo with that env variable. Weird.
> > 
> > On Thu, Mar 19, 2015 at 7:07 AM Jeremy Saks notifications@github.com
> > wrote:
> > 
> > > Hmmm, /opt/<appName>/config/env.sh looks to be well-formatted although I
> > > might not know if something was off. It contains all the environment
> > > variables in mup.json.
> > > 
> > > Also, the env variables seem to be getting set up correctly:
> > > 
> > > $ mup setup
> > > Started TaskList: Setup (linux)
> > > [104.236.42.68] - Installing Node.js
> > > [104.236.42.68] ✔ Installing Node.js: SUCCESS
> > > [104.236.42.68] - Installing PhantomJS
> > > [104.236.42.68] ✔ Installing PhantomJS: SUCCESS
> > > [104.236.42.68] - Setting up Environment
> > > [104.236.42.68] ✔ Setting up Environment: SUCCESS
> > > [104.236.42.68] - Configuring upstart
> > > [104.236.42.68] ✔ Configuring upstart: SUCCESS
> > > Completed TaskList: Setup (linux)
> > > 
> > > $ mup deploy
> > > Started TaskList: Deploy app 'myApp' (linux)
> > > [104.236.42.68] - Uploading bundle
> > > [104.236.42.68] ✔ Uploading bundle: SUCCESS
> > > [104.236.42.68] - Setting up Environment Variables
> > > [104.236.42.68] ✔ Setting up Environment Variables: SUCCESS
> > > [104.236.42.68] - Invoking deployment process
> > > [104.236.42.68] ✘ Invoking deployment process: FAILED
> > > 
> > > I'm not sure where else I might want to check.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/arunoda/meteor-up/issues/321#issuecomment-83252680
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arunoda/meteor-up/issues/321#issuecomment-83253293.
> 
> ## 
> 
> Matt Moyles
> http://mattmoyles.com

## 

Matt Moyles
http://mattmoyles.com

**Comment by arunoda** [comment]
So @dubvfan87 you got it fixed?

**Comment by JeremySaks** [comment]
When you say 'using the min. version of node' I'm not sure what that entails @dubvfan87. Can you explain? I've got `"nodeVersion": "0.10.36"` in `mup.json`.

**Comment by patrickml** [comment]
@arunoda I ran the logs and it was because Meteor Changed their min. version to 10.36

Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1

I was running 10.34 

For anyone else with this issue this is how I fixed it

npm cache clean -f
npm install -g n
n 0.10.36

then check it with this 
node -v

**Comment by arunoda** [comment]
Oh. You don't need to do that.
Just change the nodeVersion in `mup.json` and do mup setup.

**Comment by patrickml** [comment]
@arunoda I'v tried that everytime meteor updates their required version and its never worked for me.

**Comment by arunoda** [comment]
Hmm. Weird.

**Comment by patrickml** [comment]
@arunoda It might just be me tho, also on a side note while i have your attention have you ever thought of making MUP deploy from using a Repo and building the application on the production server in order to cut out the upload time?

**Comment by arunoda** [comment]
Building it on the server causes a lot of issues for some. I'd not like to
do it.
If you are worry about the deploy time. Try to use Circle CI or CodeShip to
invoke mup deploy after every git push.

We do it for Kadira UI.

**Comment by JeremySaks** [comment]
@patrickml my global node version is 0.12.0 but I was under the impression that didn't matter b/c Meteor is managing it internally. I shouldn't have to revert node backwards for this purpose should I?

**Comment by patrickml** [comment]
@JeremySaks yeh version 12 doesnt work for some reason running the commands i posted will revert it back for you

**Comment by JeremySaks** [comment]
Really. Ok I'll try that, thank you.

**Comment by patrickml** [comment]
@arunoda okay thank you I will check them out for sure.

**Comment by mmoyles87** [comment]
I'm not sure if we were experiencing the exact same problem, but updating
my node version and re-running

mup setup
mup deploy

Fixed the issue for me. If you run

DEBUG=\* mup setup

you can get some extra info, also check the logs with the mup logs command

Also make sure that you are always using the newest version of mup, which
you can upgrade on your dev machine with

npm install -g mup

On Wed, Mar 18, 2015 at 10:05 PM, Patrick Lewis notifications@github.com
wrote:

> @arunoda https://github.com/arunoda okay thank you I will check them
> out for sure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/321#issuecomment-83265458.

## 

Matt Moyles
http://mattmoyles.com

**Comment by JeremySaks** [comment]
It seems I have a separate issue because I still get `wait-for-mongo: auth failed` using 0.10.36. Using `wait-for-mongo` from the command line as @arunoda suggests also shows `auth failed` for me. So I will play around with the formatting and see if I can get authorized from there first.

I'm not sure what changed but I suspect it relates to Mongo 2.4.12 > 2.6.7 and not the node version.

**Comment by JeremySaks** [comment]
I'm still trying to figure out if I have malformed syntax somewhere as I cannot connect via `wait-for-mongo` from the command line.

Where username is 'user', password is 'pass' and db is 'myDb' I am able to connect via the shell with:

```
mongo capital.3.mongolayer.com:10046/myDb -u 'user' -p 'pass'
```

But I receive `wait-for-mongo: auth failed` when I run:

```
wait-for-mongo "mongodb://'user':'pass'@capital.3.mongolayer.com:10046,capital.2.mongolayer.com:10043/myDb"
```

Any ideas as to what might cause this? I cannot see an issue but it is preventing deployment.

UPDATE:

I was able to get this working - the issue was a character in my password that Mongo 2.6 did not like.

**Comment by thpoul** [comment]
I can confirm that I got mup working with 1.0.4.1 with the following process:
- updated mup with `npm update mup -g` 
- changed node version to `"nodeVersion": "0.10.36"`
- setup the environment `mup setup`
- and finally deployed `mup deploy`

**Comment by arvi** [comment]
Hi @thpoul @arunoda. I'm experiencing this same issue. **Will _mup setup_ delete the existing database?** We already have data in our deployed app and would just like to deploy again after making some changes.

We never had issue with mup deploy until we updated to Meteor 1.0.4.2 coming from 1.0.3.2.

BTW, here is the error

``` shell
Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    e_root_dir=/home/ubuntu/.node-gyp/0.10.33',
    gyp info spawn args   '-Dmodule_root_dir=/opt/projapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    t_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/projapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.5 install /opt/projapp/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    projapp stop/waiting
    projapp start/running, process 23305
    Waiting for 300 seconds while app is booting up
    Checking is app booted or not?
    projapp stop/waiting
    projapp start/running, process 24105
    ----------------------------------------------------------------------------

```

Thanks for your help.

**Comment by thpoul** [comment]
@arvi check your logs with `mup logs -n 300` for more detailed errors

**Comment by gokhanbaydar** [comment]
@arvi 
backup your mongoldb on the target machine for the worst case scenario:
mongodump -h 127.0.0.1 -d [ApplicationName]

change setupMongo to false and nodeVersion to 0.10.36 in your mup.json, than 

mup setup
mup deploy

everything works fine.

**Comment by arvi** [comment]
@thpoul @gokhanbaydar 

Thank you so much guys! It finally worked. Got stuck in trying to backup remote db and restore it locally since I have no experience with mongodb prior to meteor :smile: 
1. Backup remote and restore in local app... thanks to http://goo.gl/IYfZm5

``` shell
#create backup on remote machine and output in remote's /tmp/database-dump
> ssh myhostalias 'cd /tmp && mongodump --out database-dump --db projapp'

#copy to local machine in backup directory
> scp -r myhostalias:/tmp/database-dump ~/srv/database-dump/remote-database-dump

#restore per collection on local machine app; for some reason I can't restore entire collection
> mongorestore -h 127.0.0.1 --port 3001 --db meteor --collection centers ~/srv/database-dump/remote-database-dump/projapp/centers.bson
```
1. Update mup with `npm update mup -g`
2. Change node version to `"nodeVersion": "0.10.36"`
3.  Setup mongo to: `"setupMongo": false`
4. `mup setup`
5. `mup deploy`

No need to restore to remote since it didn't delete our existing database! :smile:

**Comment by griv** [comment]
I was having similar issues here. Could deploy fine with just MONGO_URL set but adding MONGO_OPLOG_URL was failing. As @JeremySaks mentioned it was an issue with characters in my password. Thanks!

**Comment by abzaloid** [comment]
I solved this problem once I ran `mup logs -f` and got that the minimum required version of `node` is `0.10.40`, and I also extended "deployCheckWaitTime" to `150`.

I am using METEOR@1.2.1

**Comment by tunamin** [comment]
@arunoda  i have finish for mup setup and mup deploy but my app still same. what the problem? tq
