### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by townmulti** [arunoda/meteor-up-legacy#322]
Will someone please list the steps to update a deployed site? I have searched a long time and didn't find a solution. I re-ran 'mup setup' and 'mup deploy' but it did not update my site to my latest app changes. I also did make sure my changes were saved. Any responses is appreciated!

**Comment by PierreGabioud** [comment]
Same problem here. Successful mup deploy but changes are not pushed to server (digital ocean)

**Comment by davidrinnan** [comment]
check the logs. It might be that the code reverted to previous version due
to an error. It has happened to me that an error occurs but the deploy
routine comes back stating everything is ok.

**Comment by PierreGabioud** [comment]
I checked the logs and I have a EADDRINUSE error, similar to issue #294. Looks like I have another node process running on the port but it's my only app on this droplet so I don't understand.

```
Error: listen EADDRINUSE
   at errnoException (net.js:905:11)
   at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
error: Forever detected script exited with code: 7
 error: Script restart attempt #1180
```

**Comment by PierreGabioud** [comment]
Solved, I realised that I change the name of my app once in mup.json so I had the old app running with the old name and the new app never running since the port was taken.

Thanks

**Comment by townmulti** [comment]
It's working for me now. I had to change servers and when I re-installed it was working. I am not running the meteor latest version though. I hope mup now works good with the new meteor upgrade.
