### ISSUE TITLE
Error when invoking deployment process

### ISSUE THREAD

**Issue by nicklewers** [arunoda/meteor-up-legacy#323]
```
-----------------------------------STDERR-----------------------------------
 (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

**Comment by arunoda** [comment]
Please invoke mup logs -n 400.

**Comment by nicklewers** [comment]
Error: /opt/Genres/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/Genres/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/Genres/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8

**Comment by davidcittadini** [comment]
I have also had a connection problem as follows:

-----------------------------------STDERR-----------------------------------
    gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    rypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.5 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

fibers@1.0.5 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)
Waiting for MongoDB to initialize. (5 minutes)
connected
meteor start/running, process 17386
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
meteor stop/waiting
meteor start/running, process 17413
----------------------------------------------------------------------------
```

The logs say:

[192.168.33.10] Warning: Permanently added '192.168.33.10' (ECDSA) to the list of known hosts.
[192.168.33.10]     at net.js:834:16
    at process._tickCallback (node.js:442:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser

**Comment by delvedor** [comment]
Hi!
I have the same issue.

```
✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    odules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /opt/app/tmp/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    Build failed
    npm ERR! Linux 3.13.0-43-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! fibers@1.0.5 install: `node ./build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /opt/app/tmp/bundle/programs/server/npm-debug.log
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.5 install /opt/app/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'app' (linux)
```

I have node 0.12.0 and I'm not using Mongo.

**Comment by zevsuld** [comment]
I have same issue too, Ubuntu server 14.04 , node v.0.10.37, meteor version 1.0.3.2

[webserver] - Uploading bundle
[webserver] ✔ Uploading bundle: SUCCESS
[webserver] - Setting up Environment Variables
[webserver] ✔ Setting up Environment Variables: SUCCESS
[webserver] - Invoking deployment process
[webserver] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
t_dir=/home/mceuser/.node-gyp/0.10.37',
gyp info spawn args   '-Dmodule_root_dir=/opt/mce/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
stop: Unknown instance: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    rget/bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/mce/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/mce/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

fibers@1.0.1 node_modules/fibers

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)
Waiting for MongoDB to initialize. (5 minutes)
connected
mce start/running, process 2711
Waiting for 45 seconds while app is booting up
Checking is app booted or not?
----------------------------------------------------------------------------
```

**Comment by pronevich** [comment]
The same issue Ubuntu 14.04 , node 0.10.36, meteor 1.0.4.1

**Comment by zevsuld** [comment]
mup log shows this, I am using tedious (https://github.com/pekim/tedious) 

/opt/web-mce/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Cannot find module 'tedious'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/web-mce/app/programs/server/boot.js:129:18)
    at app/server/mssql.js:35:22
    at app/server/mssql.js:606:3
    at /opt/web-mce/app/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/web-mce/app/programs/server/node_modules/underscore/underscore.js:79:11)
error: Forever detected script exited with code: 8
error: Script restart attempt #57

**Comment by zevsuld** [comment]
UPDATE: updated mup, npm,ubuntu. Installed npm tedious package globally, no luck

**Comment by delvedor** [comment]
UPDATE:
I've changed  in mup.json

``` json
"setupNode": false,
```

to

``` json
"setupNode": true,
```

With node version 0.12.0 and now all works correctly.

**Comment by zevsuld** [comment]
successfully deployed :) 
It was my mistake, I am using meteorhacks:npm ,but I was wrapping npm package Npm.require("tedious") instead of Meteor.npmRequire("tedious"). It was working locally fine, but when to deploy it could not find, tedious packages from app folder. 
npm tedious package works async, I am  not using meteorhacks:async, but Npm.require("fibers.future"). On the server side using fibers/future in order to tedious works async inside Meteor.methods. After deployment app seems working fine, but kind of worried that my fibers/future related code might be cause a break.
 I am wondering is it okey to use fibers/futures with meteorhacks:npm package? It works though

**Comment by brylie** [comment]
Ah, my mup.json specified an older version of node `0.10.33`. I manually changed the node version to `0.10.36`

**Comment by c9s** [comment]
I forked this repo and started a new project from this basis,  the deploy script will fix the bcrypt issue automatically. You can just install the mup from here https://github.com/c9s/meteor-up
