### ISSUE TITLE
Can't deploy to Server

### ISSUE THREAD

**Issue by zimt28** [arunoda/meteor-up-legacy#332]
I've just updated Meteor, installed node@0.12.0 on the server (and set it in my mup.json file) and updated mup. I did then run `mup setup`. This is what I get:

```
tarted TaskList: Deploy app 'app' (linux)
[XXX.XX.XXX.XX] - Uploading bundle
[XXX.XX.XXX.XX] ✔ Uploading bundle: SUCCESS
[XXX.XX.XXX.XX] - Setting up Environment Variables
[XXX.XX.XXX.XX] ✔ Setting up Environment Variables: SUCCESS
[XXX.XX.XXX.XX] - Invoking deployment process
[XXX.XX.XXX.XX] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    k
    child_process: customFds option is deprecated, use stdio instead.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    child_process: customFds option is deprecated, use stdio instead.
    child_process: customFds option is deprecated, use stdio instead.
    ../src/coroutine.cc: In function 'void* find_thread_id_key(void*)':
    ../src/coroutine.cc:90:3: warning: 'thread_id' may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (tls == thread_id) {
       ^
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    bj.target/fibers.node
      SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
      COPY Release/fibers.node
    make: Leaving directory `/opt/app/tmp/bundle/programs/server/node_modules/fibers/build'
    Installed in `/opt/app/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
    underscore@1.5.2 node_modules/underscore

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    semver@4.1.0 node_modules/semver

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    app start/running, process 12129
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    app stop/waiting
    app start/running, process 12185
    ----------------------------------------------------------------------------
```

I then did a `mup logs -n 300` which gives me

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[XXX.XX.XXX.XX] Warning: Permanently added 'XXX.XX.XXX.XX' (RSA) to the list of known hosts.
[XXX.XX.XXX.XX] Error: `/opt/app/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/opt/app/app/programs/server/node_modules/fibers/fibers.js:13:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/app/app/programs/server/boot.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
error: Forever detected script exited with code: 1
error: Script restart attempt #264
/opt/app/app/programs/server/node_modules/fibers/fibers.js:13
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
```

It seems to be a problem with node fibers but I don't know what to do here. Any idea?

**Comment by zimt28** [comment]
It works now, I downgraded to 0.10.36 which is the oldest node version supported by Meteor. Maybe we could add a comment to the upgrade section in the readme, telling that if there are errors, people should try the [min node version supported](https://github.com/meteor/meteor/blob/16d0fa2470db83e5f1b7d8c9d76ddfdd1e38db9f/tools/main.js#L530).

**Comment by ograycode** [comment]
Had the same problem, fixed via updating mup.json, then `mup setup` which then allowed `mup deploy` to work.

```
diff --git a/mup.json b/mup.json
index 9b78859..89f65eb 100644
--- a/mup.json
+++ b/mup.json
@@ -15,7 +15,7 @@
   "setupNode": true,

   // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
-  "nodeVersion": "0.10.33",
+  "nodeVersion": "0.10.36",

   // Install PhantomJS in the server
   "setupPhantom": true,
```

**Comment by geekyme** [comment]
getting the same problem too. Had to downgrade node. @arunoda any suggestions? because i think node 0.12.x contains major fixes for cluster api to make it more stable. I think that is crucial if we want to use meteorhacks:cluster smart package

**Comment by arunoda** [comment]
Meteor does not support for 0.12.x for couple of reasons.

1) Fibers is not yet supported for 0.12.x or iojs. That's due to some
internal change in V8
2) Meteor needs to come up with a better plan on dealing with binary modules

About Cluster.

Yes. It has a better cluster module and that does not benefit Meteor at
all. `meteorhacks:cluster` does not depends on nodejs `cluster` module at
all. It uses low level node apis with a round robin algo. It works with
0.10.x and 0.12.x alike.

**Comment by geekyme** [comment]
Ah thanks for letting us know Arunoda!:)

**Comment by jhohlfeld** [comment]
Thanks a lot! I managed to get `mup deploy` to work again after reading this post. By bringing both my local and the server's node version down to 0.10.38 thing got cured and now work smoothly. Phew, what a mess ;)
