### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by luglio7** [arunoda/meteor-up-legacy#342]
After a failed deploy i got this error after a mup logs -n 400
How can I reinstall the node module ?

`
Error:`/opt/mountain_theme_support/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`is missing. Try reinstalling`node-fibers`?
    at Object.<anonymous> (/opt/mountain_theme_support/app/programs/server/node_modules/fibers/fibers.js:13:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/mountain_theme_support/app/programs/server/boot.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
error: Forever detected script exited with code: 1
error: Script restart attempt #245
/opt/mountain_theme_support/app/programs/server/node_modules/fibers/fibers.js:13
    throw new Error('`'+ modPath+ '.node`is missing. Try reinstalling`node-fibe`
`

**Comment by arunoda** [comment]
You need to use NodeJS version 0.10.x.
Check whether that's the issue or not.

**Comment by luglio7** [comment]
That worked! Does the apt tool updates the node package ?
