### ISSUE TITLE
Errors after deployment

### ISSUE THREAD

**Issue by gibex** [arunoda/meteor-up-legacy#343]
Deployment is SUCCESSful, but when I run the app (DigitalOcean hosting) , I get same error (mup logs -n 400).
On localhost (OSX) works fine. 

error: Script restart attempt #151
/opt/ies-dispatcher/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Could not load the bindings file. Tried:
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.1/linux/x64/bcrypt_lib.node
    at bindings (/opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/ies-dispatcher/app/programs/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 1
error: Script restart attempt #152
/opt/ies-dispatcher/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Could not load the bindings file. Tried:
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/b[192.241.211.15] crypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.1/linux/x64/bcrypt_lib.node
    at bindings (/opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/ies-dispatcher/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/ies-dispatcher/app/programs/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 1

**Comment by gibex** [comment]
Not a bug, I had node 0.12.1 on hosting, all good now once I switched to 0.10.36
