### ISSUE TITLE
Breaks `meteor run ios`

### ISSUE THREAD

**Issue by lorensr** [arunoda/meteor-up-legacy#365]
Sequence of events:

```
$ meteor reset 
$ meteor run ios
```

This works fine. Then I stop the dev server and run `mup deploy` twice. The first time it fails, the second works:

```
$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /Users/me/parlay
Bundling Error: code=1, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
cordova/node_modules/q/q.js:749:13)
at
/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush
(/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:442:13)


Creating firefoxos project...
Project Path platforms/firefoxos
Package Name me.parlaywith.parlay
Project Name Parlay
Installing "com.ionic.keyboard" for firefoxos
Installing "com.meteor.cordova-update" for firefoxos
Installing "com.verso.cordova.clipboard" for firefoxos
Installing "nl.x-services.plugins.launchmyapp" for firefoxos


/usr/local/lib/node_modules/mup/lib/build.sh: line 42: cd: /tmp/92a58b0a-4ec7-43c4-ada8-45c4ff334224: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.


$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /Users/me/parlay

Started TaskList: Deploy app 'parlay' (linux)
[parlay.io] - Uploading bundle
[parlay.io] ✔ Uploading bundle: SUCCESS
[parlay.io] - Setting up Environment Variables
[parlay.io] ✔ Setting up Environment Variables: SUCCESS
[parlay.io] - Invoking deployment process
[parlay.io] ✔ Invoking deployment process: SUCCESS
Completed TaskList: Deploy app 'parlay' (linux)
```

Now I try: `meteor run ios` again, but this time I get:

```
Error while running for mobile platforms: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Failed to install 'nl.x-services.plugins.launchmyapp':Error: Variable(s) missing: URL_SCHEME
at
/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:442:13)
Error: Variable(s) missing: URL_SCHEME
at
/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:442:13)


Creating android project...
Creating Cordova project for the Android platform:
Path: platforms/android
Package: me.parlaywith.parlay
Name: Parlay
Android target: android-19
Copying template files...
Project successfully created.
Installing "com.ionic.keyboard" for android
Installing "com.meteor.cordova-update" for android
Installing "com.verso.cordova.clipboard" for android
Installing "nl.x-services.plugins.launchmyapp" for android
```

When I do `meteor reset`, then `meteor run ios` works again. But I have to do this every time I use `mup deploy`, which is annoying :) 

Note that the URL_SCHEME variable mentioned in the error is in `mobile-config.js`:

```
App.configurePlugin('nl.x-services.plugins.launchmyapp', {
  URL_SCHEME: 'parlay'
});
```

**Comment by lorensr** [comment]
Note that if the standard was not using the same directory as dev, this is not a problem. Eg it would be nice to have mup running on a CI server with a Github hook that auto-pulled and deployed on every commit to a certain branch :D

**Comment by arunoda** [comment]
Try the newer version of mup. I won't change your platform files.

**Comment by lorensr** [comment]
I have verified that this is now fixed, thank you!

```
$ npm ls mup -g
/usr/local/lib
└── mup@0.10.1 
```
