### ISSUE TITLE
deploy error (bcrypt)

### ISSUE THREAD

**Issue by pablovg2** [arunoda/meteor-up-legacy#370]
Meteor 1.1.0.2

I installed node v0.12.1, but I have changed it with nvm to node 0.10.36, but when I execute deploy it continues getting the version 0.12.1

localhost: Node v0.10.36 (using nvm)
server: Node v0.10.36 (using nvm)

trace error:

``` javascript
Building Started: .

Started TaskList: Deploy app 'tipi' (linux)
[45.55.165.0] - Uploading bundle
[45.55.165.0] ✔ Uploading bundle: SUCCESS
[45.55.165.0] - Setting up Environment Variables
[45.55.165.0] ✔ Setting up Environment Variables: SUCCESS
[45.55.165.0] - Invoking deployment process
[45.55.165.0] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    yp ERR! node -v v0.12.1
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    child_process: customFds option is deprecated, use stdio instead.
    child_process: customFds option is deprecated, use stdio instead.
    ../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
    ../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (tls == thread_id) {
       ^
    stop: Unknown instance: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    LE(target) Release/obj.target/fibers.node
      SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
      COPY Release/fibers.node
    make: Leaving directory `/opt/tipi/tmp/bundle/programs/server/node_modules/fibers/build'
    Installed in `/opt/tipi/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    tipi start/running, process 12918
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    tipi stop/waiting
    tipi start/running, process 13059
    ----------------------------------------------------------------------------

```

mup logs

``` javascript
error: Forever detected script exited with code: 1
error: Script restart attempt #3
/opt/tipi/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Could not load the bindings file. Tried:
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.1/linux/x64/bcrypt_lib.node
    at bindings (/opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/tipi/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/tipi/app/programs/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 1
error: Script restart attempt #4
```

**Comment by zimt28** [comment]
Hey @pablovg2, can you tell how you fixed the problem?

**Comment by pablovg2** [comment]
Hi @zimt28, it looked like, I had some errors in my environment so I tried with a clean new environment installing node from scratch.  I suggest you use a new clean environment.

**Comment by rtalwar26** [comment]
bcrypt has lot of issues with different versions of node, i faced same issue with node v0.12.9 but did note face with node v0.12.7
