### ISSUE TITLE
deploy error with bcrypt,  I think!

### ISSUE THREAD

**Issue by pablovg2** [arunoda/meteor-up-legacy#374]
Meteor 1.1.0.2
localhost: Node v0.10.36 
server: Node v0.10.36

the trace I get from mup deploy

``` javascript
✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    -Dmodule_root_dir=/opt/tipi/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    js-bson: Failed to load c++ bson extension, using pure JS version
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
     fibers@1.0.5 install /opt/tipi/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    fibers@1.0.5 node_modules/fibers

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)
    Waiting for MongoDB to initialize. (5 minutes)
    [Error: /usr/local/lib/node_modules/wait-for-mongo/node_modules/mongodb/node_modules/bson/build/Release/bson.node: undefined symbol: node_module_register]
    connected
    tipi stop/waiting
    tipi start/running, process 7864
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    tipi stop/waiting
    tipi start/running, process 7968
    ----------------------------------------------------------------------------

```

From logs

``` javascript
ReferenceError: exports is not defined
    at app/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:27:1
    at app/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:109:3
    at /opt/tipi/app/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/tipi/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/tipi/app/programs/server/boot.js:117:5
error: Forever detected script exited with code: 8
error: Script restart attempt #23

/opt/tipi/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
ReferenceError: exports is not defined
    at app/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:27:1
    at app/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:109:3
    at /opt/tipi/app/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/tipi/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/tipi/app/programs/server/boot.js:117:5
error: Forever detected script exited with code: 8
error: Script restart attempt #24


```

**Comment by pablovg2** [comment]
With a fresh install of meteor, server and localhost it run. Thx
