### ISSUE TITLE
MUP deploy error

### ISSUE THREAD

**Issue by ijidau** [arunoda/meteor-up-legacy#383]
I'm getting a deployment error which I'm unsure how to solve:

```
✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    node_root_dir=/root/.node-gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=/opt/msrealm/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/msrealm/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.5 install /opt/msrealm/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
    └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    msrealm stop/waiting
    msrealm start/running, process 11788
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    msrealm stop/waiting
    msrealm start/running, process 11843
    ----------------------------------------------------------------------------
```

I'm not really sure what any of this means.

I'm trying to deploy on a fresh Digital Ocean droplet (Ubuntu 14.04 x64) and using Compose.IO for MongoDB. MUP setup runs fine. App runs fine locally.

**Comment by ijidau** [comment]
Ok, I ran `mup logs -n 400` and got this:

```
MongoError: not authorized for query on local.oplog.rs
    at Object.Future.wait (/opt/msrealm/app/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
    at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
    at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1)
    at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:812:1)
    at [object Object].MongoConnection.findOne (packages/mongo/mongo_driver.js:718:1)
    at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:226:1)
    at new OplogHandle (packages/mongo/oplog_tailing.js:81:1)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:1)
    - - - - -
    at Object.toError (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:714:54
    at Cursor.close (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at commandHandler (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:714:21)
    at /opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/msrealm/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
```

So that tells me it's my 'mup.json' 'MONGO_URL' or 'MONGO_OPLOG_URL':

```
"MONGO_URL": "mongodb://msrealm:REDACTED@galaga.0.mongolayer.com:10330,c326.galaga.1.mongolayer.com:10326,galaga.1.mongolayer.com:10326/msrealm?replicaSet=set-55319b74f46d33f64f00070f",
 "MONGO_OPLOG_URL":"mongodb://msrealm:REDACTED@galaga.0.mongolayer.com:10330,c326.galaga.1.mongolayer.com:10326,galaga.1.mongolayer.com:10326/local?authSource=msrealm"
```

Have I set these variables incorrectly?

**Comment by ijidau** [comment]
I managed to get it working like this:

```
"MONGO_URL": "mongodb://system:REDACTED@galaga.0.mongolayer.com:10330,c326.galaga.1.mongolayer.com:10326,galaga.1.mongolayer.com:10326/msrealm?replicaSet=set-55319b74f46d33f64f00070f"
```

But how do I enable Oplog support, what should my `MONGO_OPLOG_URL` look like?

**Comment by arunoda** [comment]
Check this: https://github.com/meteor/meteor/issues/2036
Updating to the newer version of Meteor will fix this.

**Comment by tdbs** [comment]
i have the latest version, and i still get this error.
This project is already at Meteor 1.1.0.2, the latest release.

Also, everything worked before, it was after an update that i got this error.

**Comment by bsbechtel** [comment]
I got this same issue after updating to the latest release.

**Comment by bsbechtel** [comment]
Never mind, my error was different. Had an old version of node on my machine.

**Comment by cbwheadon** [comment]
I'm getting a similar oplog issue: MongoError: not authorized for query on local.system.replset
Meteor 1.0.3.2  using Mongo v2.4.10 hosted by compose.io . Everything was fine before a meteor update.

**Comment by cbwheadon** [comment]
Turns out I had to upgrade to v2.6.9 and delete then re-add the oplog user.

**Comment by sferoze** [comment]
I am getting this error today. My MongoDB is on compose.io running at 3.0.1 and I have updated to Meteor 1.1.0.2. 

I have added oplog_url with local?authSource=mydb

still get the error. What else can I try?

**Comment by sferoze** [comment]
It works without the MONGO_OPLOG_URL

I am getting the error: MongoError: Authentication failed.

I created a new user for oplog in compose.io with oplog access as described here: https://docs.compose.io/common-questions/getting-oplog-access.html

But still I get the same error

I am using the latest Meteor with MongoDb 3.0.1

**Comment by sferoze** [comment]
I finally got it to work on compose.io! So here it what my oplog url ended up looking like:

"MONGO_OPLOG_URL": "mongodb://username:password@single.18.mongolayerhost.com:1111/local?authSource=myDB"

I keep the MONGO_URL exactly the same as the URL compose.io provides with ?replicaSet

But for the OPLOG_URL you can only use a single host, not multiple. So you have to edit the URL compose.io gives you to only have one host. And you can't end the oplog with ?replicaSet. you can only have the ?replicaSet in the MONGO_URL. 

It deployed just fine, but I wonder if not having ?replicaSet in the OPLOG_URL is an issue?
