### ISSUE TITLE
bcrypt issue

### ISSUE THREAD

**Issue by berkaytheunicorn** [arunoda/meteor-up-legacy#385]
mup logs

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
[xx] Warning: Permanently added 'xxxxx' (RSA) to the list of known hosts.
[xx]     at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/xxx/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/xxx/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #9230
```

deploy error

```
[xx] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'xxxx' (RSA) to the list of known hosts.
    -----------------------------------STDOUT-----------------------------------
     > ./bcrypt: npm install due to binary npm modules
    ----------------------------------------------------------------------------
```

I tried to install bcrypt manually to server but no luck. any workaround ?

**Comment by kenken17** [comment]
I have the same issue. Anyone got a fix for this?

**Comment by joaopiopedreira** [comment]
This has most probably nothing to do with bcrypt.

See this: https://github.com/arunoda/meteor-up/issues/377

Enviado do meu iPhone

No dia 20/04/2015, às 05:32, Ken notifications@github.com escreveu:

**Comment by kenken17** [comment]
Indeed. I was using 0.10.36 and 0.12.2. But both no luck. Then I run again on 0.10.36, it works! Logs are helpful, `mup logs -n 100`, show 100 lines then maybe can get some clue.

**Comment by berkaytheunicorn** [comment]
some how still getting these on new apps old apps are deploying fine but (without a mup setup) server has 0.10.36. last time some how I manage to deploy. any ideas to get rid of this for good. a new server maybe?
