### ISSUE TITLE
MUP Deploy Stuck on Uploading Bundle

### ISSUE THREAD

**Issue by SdShadab** [arunoda/meteor-up-legacy#397]
Hello everyone, 

I have an instance of a meteor app running on this url: http://make-a-difference.rahimafrooz.com/ which was set up with MUP. Now that I am trying to push again, it is not working. I have the same mup.json file running but it is stuck on 'Uploading Bundle'

I have Node version 0.10.36 running on my server. 

Here is my mup logs:

```
[106.185.49.203] Warning: Permanently added '106.185.49.203' (ECDSA) to the list of known hosts.
[106.185.49.203] spiderable: phantomjs failed: null
spiderable: phantomjs failed: null
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/shs.png'","time":{"$date":1430215157080},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/gift.png'","time":{"$date":1430215157085},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/visit.png'","time":{"$date":1430215157087},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/shs.png'","time":{"$date":1430215157090},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/gift.png'","time":{"$date":1430215157124},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/ra10.png'","time":{"$date":1430215157139},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/visit.png'","time":{"$date":1430215157163},"level":"error"}
{"line":"413","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/opt/rahimafrooz/app/programs/web.browser/app/img/ra10.png'","time":{"$date":1430215157194},"level":"error"}
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #2
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #3
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #4
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #5
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #6
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #7
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #8
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #9
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #10
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #11
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #12
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #13

module.js:340
    throw err;
          ^
Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/rahimafrooz/app/programs/server/boot.js:6:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
[MailChimp] Error: MailChimp Options have not been set in your settings.json file.
1
SyncedCron: scheduled "Schedule newsletter" next run @Tue Apr 28 2015 09:59:34 GMT+0000 (UTC)
AccountsTemplates - WARNING: showForgotPasswordLink set to true, but MAIL_URL is not configured!
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
spiderable: phantomjs failed: null
spiderable: phantomjs failed: null
spiderable: phantomjs failed: null
```

What can I do to sort this thing out?

**Comment by arunoda** [comment]
Is this an old log? (node version requires thing?)

If this does not help, try to deploy your app into a fresh server.

**Comment by SdShadab** [comment]
Yup, that is an older log. An new server is a difficult option, because I cannot update the A record to the new IP address very easily. I am running verbose to see the kind of results I get.

**Comment by SdShadab** [comment]
This is where it is getting stuck

```
[106.185.49.203] - Uploading bundle
  nodemiral:sess:106.185.49.203 copy file - src: /tmp/9c2cf40a-bb1b-4131-a94b-17cc1106969a/bundle.tar.gz, dest: /opt/rahimafrooz/tmp/bundle.tar.gz, vars: undefined +0ms
  nodemiral:sess:106.185.49.203 spawning command- sshpass -p //password// scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/9c2cf40a-bb1b-4131-a94b-17cc1106969a/bundle.tar.gz root@106.185.49.203:/opt/rahimafrooz/tmp/bundle.tar.gz +0ms

```

**Comment by SdShadab** [comment]
okay so I got this output

```
Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
                                                                  ^
    In file included from /usr/include/netinet/in.h:23:0,
                     from /usr/include/arpa/inet.h:22,
                     from http-server.h:31,
                     from http-server.c:22:
    /usr/include/x86_64-linux-gnu/sys/socket.h:243:12: note: expected ‘socklen_t * restrict’ but argument is of type ‘size_t *’
     extern int accept (int __fd, __SOCKADDR_ARG __addr,
                ^
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    4, http-signature@0.10.1, tough-cookie@1.0.0, hawk@2.3.1, har-validator@1.6.1)

    expresso@0.9.2 node_modules/expresso

    > fibers@1.0.5 install /opt/rahimafrooz/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    rahimafrooz stop/waiting
    rahimafrooz start/running, process 31190
    Waiting for 300 seconds while app is booting up
    Checking is app booted or not?
    rahimafrooz stop/waiting
    rahimafrooz start/running, process 424
```
