### ISSUE TITLE
mup setup throws an error after updating to the latest version of mup 

### ISSUE THREAD

**Issue by tigransloyan** [arunoda/meteor-up-legacy#399]
`````` /usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/ssh.js:133
        options.onStderr(data);
                ^
TypeError: Property 'onStderr' of object #<Object> is not a function
    at Readable.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/ssh.js:133:17)
    at Readable.emit (events.js:95:17)
    at Readable.<anonymous> (_stream_readable.js:765:14)
    at Readable.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Readable.push (_stream_readable.js:128:10)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/Channel.js:228:26)
    at SSH2Stream.emit (events.js:98:17)```
``````

**Comment by arunoda** [comment]
It should be a dependancy issue. I've updated mup and try now.

**Comment by tigransloyan** [comment]
cool fixed thanks, for anyone else who runs into this, FYI just `npm update mup -g` doesn't help... you need to remove and add mup back.
