### ISSUE TITLE
Getting "Timed out while waiting for handshake" error

### ISSUE THREAD

**Issue by rnarayan** [arunoda/meteor-up-legacy#401]
I have successfully deployed meteor app before using mup. But this time, I am getting time-out error. I am trying to deploy an app to a new digital ocean server. I can successfully login to the server using the cli command ssh -i id_rsa -p 12345 my_user@45.55.147.87

Following is the error message and my mup json file.

Error: 
trusty:~/meteor/my_app/config/production$ ls
id_rsa  id_rsa.pub  mup.json  settings.json  settings.md
trusty:~/meteor/my_app/config/production$ mup setup
## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.147.87] - Installing Node.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

 mup.json file:
{
  "servers": [
    {
      "host": "45.55.147.87",
      "username": "my_user",
      "pem": "id_rsa",
      "sshOptions": { "Port" : 12345 }
    }
  ],
  "setupMongo": false,
  "setupNode": true,
  "nodeVersion": "0.10.36",
  "setupPhantom": false,
  "appName": "meteor",
  "app": "~/meteor/my_app",
  "env": {
    "ROOT_URL": "http://myapp.com"
  },
  "deployCheckWaitTime": 15
}

**Comment by arunoda** [comment]
May be try to use sshOptions as {port: 12345}. That'll work.

**Comment by rnarayan** [comment]
Arunoda, Thanks for the prompt response. It doesn't seem like that's the error. "port" within strings has worked before. Nonetheless, I tried {port: 12345} and I got the following error from mup.

...
Error: Parse error on line 8:
...    "sshOptions": { Port : 12345 }    }
-----------------------^
Expecting 'STRING', '}', got 'undefined'
...

I am getting strange errors with mup, on things that worked before. I wonder if the new version of mup is causing these issues. To troubleshoot, I spun a new digital server. This time I did not use my standard ubuntu snapshot which has some basic security configured. I started adding security one by one to my new server and after every change, I would run "mup setup" and watch out for error.

This is what I found. mup errors out if the port is not 22 and also the user is not root. I had set my_user and made the recommended changes in /etc/sudoers as suggested by you. Still, mup failed.

Thus, when I use root and port 22, mup works fine but fails  if these two are changed. Please note that for every configuration change, I tested that ssh -i id_rsa -p 12345 user@12.34.567.89 worked.

**Error when port is 12345 and user is root**
trusty:~/meteor/my_app/config/production$ mup setup

## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.133.89] - Installing Node.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete](net.js:896:19)

**Error when port is 22 but the user is "my_user", user is added to sudo group**
_/etc/sudoers file has this line - %sudo ALL=(ALL) NOPASSWD:ALL_

trusty:~/meteor/my_app/config/production$ mup setup

## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.133.89] - Installing Node.js
[45.55.133.89] - Installing Node.js: SUCCESS
[45.55.133.89] - Setting up Environment
[45.55.133.89] - Setting up Environment: SUCCESS
[45.55.133.89] - Configuring upstart
[45.55.133.89] x Configuring upstart: FAILED
    Permission denied
Completed TaskList: Setup (linux)

**Comment by arunoda** [comment]
There is an additional } in sshOptions.

**Comment by rnarayan** [comment]
I think the error message picked the additional } from the next line. This is the version of mup.json file when I tested with port without strings.
  "servers": [
    {
      "host": "45.55.133.89",
      "username": "root",
      "pem": "id_rsa",
      "sshOptions": { Port : 12345 }
    }
  ],
...
...

**Comment by rnarayan** [comment]
Arunoda,

I think I resolved the Port issue. I guess you use npm package ssh2 under the hood. I went through its code and found that, in their config option, its spelled all in lower case - port and not Port. ( https://github.com/mscdex/ssh2/blob/master/lib/client.js )

So when I changed the line to read - "sshOptions": { "port" : 12345 }, I was able to successfully connect.

Please note that your documentation states port with a capital P - //"sshOptions": { "Port" : 49154 }. Please correct this.

Having said that, I am still confused by the error since this is my third time setting up servers using mup and everytime, I copied your example mup.json file which has port with a capital P and it worked. Today, it failed.

**Comment by arunoda** [comment]
Actually, we moved to ssh2 recently. That was the issue.

**Comment by arunoda** [comment]
Shall we close this issue then?

**Comment by rnarayan** [comment]
There is another issue in my initial post - using a custom user and not root. Let me quickly test that again and if successful, we can close this issue.

**Comment by rnarayan** [comment]
Arunoda,

Though the port issue is resolved, I am still getting the following error when I use a custom user. The error is rather strange because it installs Node and set up environment variables successfully but fails to set-up upstart. Any idea what could be happening. My new user is part of sudo group and Sudoers file has the "No Password" option set - in accordance with your documention.

**Error:**
trusty:~/meteor/my_app/config/production$ mup setup

## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.133.89] - Installing Node.js
[45.55.133.89] - Installing Node.js: SUCCESS
[45.55.133.89] - Setting up Environment
[45.55.133.89] - Setting up Environment: SUCCESS
[45.55.133.89] - Configuring upstart
[45.55.133.89] x Configuring upstart: FAILED
    Permission denied
Completed TaskList: Setup (linux)

**Comment by arunoda** [comment]
Not sure, what's wrong here. 
We are testing deployments with AWS EC2 for sudo users and it worked pretty well with the current version.

**Comment by levino** [comment]
I also had the issue with using a non standard port. Before it all worked fine. After updating to the last version i could not use my encrypted private key anymore and mup would not respect my .ssh/config file (where I set the non-standard ssh port). Would be nice if it worked again at some point. Can work around with the above for the time being and decrypting the private key.

**Comment by rnarayan** [comment]
Arunoda,

It seems that the second error I described - using a non-root user is a fake error. "mup setup" works correctly with a non-root user but it still spits out an error message. After running, "mup setup", I ran "mup logs" and it showed me a log that "script /opt/meteor/app/main.js does not exist.Cannot start forever". Of course ../app/main.js does not exist because "mup deploy" hasn't been run yet. So, I ran "mup deploy" and the website was installed correctly and I could access the website at the ip address.

**Conclusion: That error is misleading.**

**Log:**
**Step 1: Run mup setup as a non-root user**
trusty$ mup setup

## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.133.89] - Installing Node.js
[45.55.133.89] - Installing Node.js: SUCCESS
[45.55.133.89] - Setting up Environment
[45.55.133.89] - Setting up Environment: SUCCESS
[45.55.133.89] - Configuring upstart
[45.55.133.89] x Configuring upstart: FAILED
    Permission denied
Completed TaskList: Setup (linux)

**Step 2: Run mup logs**

## Meteor Up: Production Quality Meteor Deployments

[45.55.133.89] error:   Cannot start forever
error:   script /opt/meteor/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteor/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteor/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteor/app/main.js does not exist.

**Step 2: Run mup deply** - no error

## Meteor Up: Production Quality Meteor Deployments

Building Started: /home/newgeek/meteor/allthingsl

Started TaskList: Deploy app 'meteor' (linux)
[45.55.133.89] - Uploading bundle
[45.55.133.89] - Uploading bundle: SUCCESS
[45.55.133.89] - Setting up Environment Variables
[45.55.133.89] - Setting up Environment Variables: SUCCESS
[45.55.133.89] - Invoking deployment process
[45.55.133.89] - Invoking deployment process: SUCCESS
Completed TaskList: Deploy app 'meteor' (linux)

**Comment by rnarayan** [comment]
A little doubt on my post above. I checked for the processes runnning on the server and I am not sure if upstart is running for the meteor app. Here is what I see on the server.

my_user@test:~$ ps ax | grep node
 4646 ?        Sl     0:00 node /usr/bin/forever -c userdown --minUptime 2000 --spinSleepTime 1000 app/main.js
 4653 ?        Sl     0:02 node /usr/bin/userdown /opt/meteor/app/main.js
 4736 pts/1    S+     0:00 grep --color=auto node
my_user@test:~$ ps ax | grep forever
 4646 ?        Sl     0:00 node /usr/bin/forever -c userdown --minUptime 2000 --spinSleepTime 1000 app/main.js
 4738 pts/1    S+     0:00 grep --color=auto forever
my_user@test:~$ ps ax | grep upstart
  336 ?        S      0:00 upstart-udev-bridge --daemon
  615 ?        S      0:00 upstart-socket-bridge --daemon
  774 ?        S      0:00 upstart-file-bridge --daemon
 4740 pts/1    S+     0:00 grep --color=auto upstart

**Comment by edu2969** [comment]
Changin public IP address in mup.json (mupx) for internat IP address (like 192.168.x.xxx), resolve the issue in my app.

Debian 8, node 4.6.2, meteor 1.4.2.3
