### ISSUE TITLE
Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by giggioz** [arunoda/meteor-up-legacy#413]
hi, getting this error multiple times (i tried also to update mup)

```
Started TaskList: Deploy app 'billy' (linux)
[178.62.183.206] - Uploading bundle
[178.62.183.206] - Uploading bundle: SUCCESS
[178.62.183.206] - Setting up Environment Variables
[178.62.183.206] - Setting up Environment Variables: SUCCESS
[178.62.183.206] - Invoking deployment process
[178.62.183.206] x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    npm WARN excluding symbolic link browser -> dist/browser
    npm WARN deprecated github-flavored-markdown@1.0.1: This project is long out of date. Use 'marked' instead.
    npm WARN deprecated tap-assert@0.0.10: this is merged into the 'tap' module now
    -----------------------------------STDOUT-----------------------------------
     > ./mongodb: npm install due to binary npm modules

    > kerberos@0.0.9 install /opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

    make: Entering directory `/opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    make: Leaving directory `/opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'

    > bson@0.2.21 install /opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

    make: Entering directory `/opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build'
      CXX(target) Release/obj.target/bson/ext/bson.o
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'billy' (linux)
```

By the way, thank you for this great deployment system :)

**Comment by giggioz** [comment]
Update: 

builderror.log shows

```
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/billy/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

searching for **gssapi/gssapi.h: No such file or directory** i've found #311 but i do not fully understand what it means :
"Problem solved with help from Arunoda, thanks.

When upgrading Meteor and/or mup, allways make sure to mup init again, because of Node version dependency."

If i try to `mup init` in an existing project i get : A Project Already Exists

**Comment by giggioz** [comment]
Solved:

In your server install

```
apt-get install libkrb5-dev
```
