### ISSUE TITLE
Error during MUP setup

### ISSUE THREAD

**Issue by maj8614** [arunoda/meteor-up-legacy#422]
Whenever I try to run mup setup, I get the following authentication error:

---

MacBook-Air:Telesc$ mup setup

Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[45.55.217.26] - Installing Node.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:469:5)
    at SSH2Stream.emit (events.js:110:17)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3588:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read](_stream_transform.js:179:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)

---

Any suggestion(s) on how to fix?

**Comment by dpatte** [comment]
i upgraded nodejs - solved

**Comment by maj8614** [comment]
Thanks @dpatte , but I am running the latest version of node.js already (0.12.2). It doesn't seem to solve the issue.

**Comment by meonkeys** [comment]
This solved it for me: https://github.com/arunoda/meteor-up/issues/409#issuecomment-104130596

**Comment by pociej** [comment]
any solution for this? 
I have same issue with node 0.12.7 , deploying from OS X Yosemite 10.10.4 to ubuntu 14.04 on DO.
