### ISSUE TITLE
Error: Initialization failed     at new DiffieHellman (crypto.js:438:21)

### ISSUE THREAD

**Issue by greenwolfe** [arunoda/meteor-up-legacy#427]
I'm using mup for the first time, and I frequently and intermittently get the following error when using mup deploy to my Ubuntu 14.10 32 server at digital ocean. 

Error: Initialization failed at new DiffieHellman (crypto.js:438:21)

With no changes to my meteor project or mup.json file, it resolves sometimes by just running mup deploy again, when that fails sometimes by mup stop followed by mup deploy, and when that fails by running mup setup and then mup deploy again.  Persistence with these three eventually pays off with a successful deployment, but it ought to work consistently.

Has anyone else encountered this problem?  Any suggestions?

**Comment by greenwolfe** [comment]
I was using node >= 0.11.x and that caused the problem.  Reverting to 0.10.36 fixed it.
