### ISSUE TITLE
No log file created

### ISSUE THREAD

**Issue by psyfreak** [arunoda/meteor-up-legacy#436]
First of all thank you for your work :).

I tried to use meteor-up on Azure (Ubuntu 14.04 LTS).
I installed mup (npm view say that I am using v0.10.7 of mup).
Init, and Setup work fine while deploy do not work. And to identify the error I would like to access the log files, but I got this error (xxx = anonymized):
[xxx.cloudapp.net] tail: [xxx.cloudapp.net] cannot open '/var/log/upstart/list.log' for reading[xxx.cloudapp.net] : No such file or directory[xxx.cloudapp.net]
[xxx.cloudapp.net] tail: [xxx.cloudapp.net] no files remaining[xxx.cloudapp.net] 

I needed to create the directory "upstart" in /var/log before, but there is no file when I look locally via ssh.
I also created an empty file with dummy text init, this prints out the dummy, while no additional is written into this file.

If you need further information please let me know.

**Comment by arunoda** [comment]
Try the new mupx branch. It has a newer version of mup and it's much stable than this. 

It won't have this issue.

**Comment by psyfreak** [comment]
Thank you for your quick advice. I am able to retrieve the log file now with your mupx branch, which is good, after another error (had to add PYTHON variable to environment) I ran into the following error during the verification of the deployment.

Your help would be much appreciated.

## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

[xxx] npm ERR! not with npm itself.
[xxx] npm ERR! Tell the author that this fails on your system:
[xxx] npm ERR!     node ./build.js
[xxx] npm ERR! You can get their info via:
[xxx] npm ERR!     npm owner ls fibers
[xxx] npm ERR! There is likely additional logging output above.
[xxx] npm ERR! System Linux 3.19.0-15-generic
[xxx] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx] npm ERR! cwd /bundle/bundle/programs/server
[xxx] npm ERR! node -v v0.10.36
[xxx] npm ERR! npm -v 1.4.28
[xxx] npm ERR! code ELIFECYCLE
[xxx] npm ERR! not ok code 0
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[xxx]
[xxx] > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
[xxx] > node ./build.js
[xxx]
[xxx] gyp ERR! configure error
[xxx] gyp ERR! stack Error: spawn EACCES
[xxx] gyp ERR! stack     at errnoException (child_process.js:1011:11)
[xxx] gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
[xxx] gyp ERR! System Linux 3.19.0-15-generic
[xxx] gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
[xxx] gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
[xxx] gyp ERR! node -v v0.10.36
[xxx] gyp ERR! node-gyp -v v1.0.1
[xxx] gyp ERR! not ok
[xxx] Build failed
[xxx]
[xxx] npm ERR! fibers@1.0.5 install: `node ./build.js`
[xxx] npm ERR! Exit status 1
[xxx] npm ERR!
[xxx] npm ERR! Failed at the fibers@1.0.5 install script.
[xxx] npm ERR! This is most likely a problem with the fibers package,
[xxx] npm ERR! not with npm itself.
[xxx] npm ERR! Tell the author that this fails on your system:
[xxx] npm ERR!     node ./build.js
[xxx] npm ERR! You can get their info via:
[xxx] npm ERR!     npm owner ls fibers
[xxx] npm ERR! There is likely additional logging output above.
[xxx] npm ERR! System Linux 3.19.0-15-generic
[xxx] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx] npm ERR! cwd /bundle/bundle/programs/server
[xxx] npm ERR! node -v v0.10.36
[xxx] npm ERR! npm -v 1.4.28
[xxx] npm ERR! code ELIFECYCLE
[xxx] npm ERR! not ok code 0

**Comment by arunoda** [comment]
We should not this kind of issues?
What's the python env var?
That may be the issue.

Could you tell more about that?

**Comment by psyfreak** [comment]
I defined python env variable in mup.json in the env section and not in "servers" where "env" is also defined (is there any difference btw.?)
"env": {
    "PORT": 80,
    "ROOT_URL": "http://www.xxx.cloudapp.net",
    "PYTHON": "/usr/bin"  
  },
On my system python v2.7 is used.
Last but not least what is not clear for me as well if your predefined settings.json can be used with your default configuration. In an earlier version of mup I needed to remove this file..

**Comment by arunoda** [comment]
Remove this Python env var. that is the cause the issue. You don't need to
worry about Python, now all that take care in the docker image.

**Comment by psyfreak** [comment]
but if I do not use it I got an error that python is missing and that Python should be set. I will print you the log.

**Comment by psyfreak** [comment]
I got the following error w/o setting the python variable:

***\* mupx deploy error (btw. the log info statement is not updated to mupx in the bottom)****

[xxx] x Verifying deployment: FAILED
-----------------------------------STDERR-----------------------------------
5-generic
gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
Build failed

```
    npm ERR! fibers@1.0.5 install: `node ./build.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the fibers@1.0.5 install script.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.19.0-15-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
    npm ERR! cwd /bundle/bundle/programs/server
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

********\* log *********

## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

[xxx] npm ERR!     npm owner ls fibers
[xxx] npm ERR! There is likely additional logging output above.
[xxx] npm ERR! System Linux 3.19.0-15-generic
[xxx] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx] npm ERR! cwd /bundle/bundle/programs/server
[xxx] npm ERR! node -v v0.10.36
[xxx] npm ERR! npm -v 1.4.28
[xxx] npm ERR! code ELIFECYCLE
[xxx] npm ERR! not ok code 0
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[xxx] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[xxx]
[xxx] > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
[xxx] > node ./build.js
[xxx]
[xxx] gyp ERR! configure error
[xxx] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[xxx] gyp ERR! stack     at failNoPython (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:103:14)
[xxx] gyp ERR! stack     at /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:42:11
[xxx] gyp ERR! stack     at F (/opt/nodejs/lib/node_modules/npm/node_modules/which/which.js:43:25)
[xxx] gyp ERR! stack     at E (/opt/nodejs/lib/node_modules/npm/node_modules/which/which.js:46:29)
[xxx] gyp ERR! stack     at /opt/nodejs/lib/node_modules/npm/node_modules/which/which.js:57:16
[xxx] gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
[xxx] gyp ERR! System Linux 3.19.0-15-generic
[xxx] gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
[xxx] gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
[xxx] gyp ERR! node -v v0.10.36
[xxx] gyp ERR! node-gyp -v v1.0.1
[xxx] gyp ERR! not ok
[xxx] Build failed
[xxx]
[xxx] npm ERR! fibers@1.0.5 install: `node ./build.js`
[xxx] npm ERR! Exit status 1
[xxx] npm ERR!
[xxx] npm ERR! Failed at the fibers@1.0.5 install script.
[xxx] npm ERR! This is most likely a problem with the fibers package,
[xxx] npm ERR! not with npm itself.
[xxx] npm ERR! Tell the author that this fails on your system:
[xxx] npm ERR!     node ./build.js
[xxx] npm ERR! You can get their info via:
[xxx] npm ERR!     npm owner ls fibers
[xxx] npm ERR! There is likely additional logging output above.
[xxx] npm ERR! System Linux 3.19.0-15-generic
[xxx] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx] npm ERR! cwd /bundle/bundle/programs/server
[xxx] npm ERR! node -v v0.10.36
[xxx] npm ERR! npm -v 1.4.28
[xxx] npm ERR! code ELIFECYCLE
[xxx] npm ERR! not ok code 0

**Comment by psyfreak** [comment]
Actually I got it working  with mupx on Ubuntu 14.x and 15.x :+1 in azure, while I could not get working mup...
