### ISSUE TITLE
Verifying Deployment:Failed

### ISSUE THREAD

**Issue by thikari** [arunoda/meteor-up-legacy#443]
Anyone has an idea why I got this error?

[46.101.169.249] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
nderscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:117:5
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------
```

**Comment by arunoda** [comment]
Closing. This is the same as #441
