### ISSUE TITLE
mupx deploy in DO/ubuntu issue

### ISSUE THREAD

**Issue by vmusulainen** [arunoda/meteor-up-legacy#453]
Thank for beautiful tool!

I tried to use meteor-up for installing my meteor application on Digital Ocean server and faced withg th following issue.

mupx init - success
mups setup - success

mupx deploy - failed on 'Verifying deployment' step

```
Started TaskList: Deploy app 'predictions' (linux)
[45.55.232.216] - Uploading bundle
[45.55.232.216] - Uploading bundle: SUCCESS
[45.55.232.216] - Sending environment variables
[45.55.232.216] - Sending environment variables: SUCCESS
[45.55.232.216] - Initializing start script
[45.55.232.216] - Initializing start script: SUCCESS
[45.55.232.216] - Invoking deployment process
[45.55.232.216] - Invoking deployment process: SUCCESS
[45.55.232.216] - Verifying deployment
[45.55.232.216] x Verifying deployment: FAILED

-----------------------------------STDERR-----------------------------------
0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80

/bundle/bundle/programs/server/boot.js:263
}).run();
   ^
Error: ENOENT, no such file or directory '/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/Types/mime.Types'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Mime.load (/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/mime.js:54:20)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/mime.js:90:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------`
```

mupx logs --tail=50 gave me the following log

```
[45.55.232.216] Error: ENOENT, no such file or directory '/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/Types/mime.Types'
[45.55.232.216]     at Object.fs.openSync (fs.js:439:18)
[45.55.232.216]     at Object.fs.readFileSync (fs.js:290:15)
[45.55.232.216]     at Mime.load (/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/mime.js:54:20)
[45.55.232.216]     at Object.<anonymous> (/bundle/bundle/programs/server/npm/webapp/node_modules/send/node_modules/mime/mime.js:90:6)
[45.55.232.216]     at Module._compile (module.js:456:26)
[45.55.232.216]     at Object.Module._extensions..js (module.js:474:10)
[45.55.232.216]     at Module.load (module.js:356:32)
[45.55.232.216]     at Function.Module._load (module.js:312:12)
[45.55.232.216]     at Module.require (module.js:364:17)
[45.55.232.216]     at require (module.js:380:17)
[45.55.232.216] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[45.55.232.216] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[45.55.232.216] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[45.55.232.216] => Starting meteor app on port:80
```

**Comment by arunoda** [comment]
Are you on windows?

**Comment by vmusulainen** [comment]
No, It's macos (OS X Yosemito 10.10.3)

**Comment by arunoda** [comment]
Hmm.
What's your OS version? Which Ubuntu Version? 32 or 64 bit?
And send me your `.meteor/versions` and `.meteor/packages` files.

**Comment by vmusulainen** [comment]
My OS OS X Yosemito 10.10.3
DO droplet with Ubuntu 14.04 x64

.meteor/packages

```
meteor-platform
insecure
iron:router
autopublish
twbs:bootstrap 
momentjs:moment
ian:accounts-ui-bootstrap-3
accounts-password
tsega:bootstrap3-datetimepicker
mizzao:bootboxjs
nooitaf:colors
```

.meteor/versions

```
accounts-base@1.2.0
accounts-password@1.1.0
anti:i18n@0.4.3
autopublish@1.0.3
autoupdate@1.2.0
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.0
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
ian:accounts-ui-bootstrap-3@1.2.59
id-map@1.0.3
insecure@1.0.3
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
meteor@1.1.5
meteor-platform@1.2.2
minifiers@1.1.4
minimongo@1.0.7
mizzao:bootboxjs@4.4.0
mobile-status-bar@1.0.3
momentjs:moment@2.10.3
mongo@1.1.0
nooitaf:colors@0.0.2
npm-bcrypt@0.7.8_1
observe-sequence@1.0.5
ordered-dict@1.0.3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.5
srp@1.0.3
stylus@1.0.7
templating@1.1.0
tracker@1.0.6
tsega:bootstrap3-datetimepicker@4.7.14_4
twbs:bootstrap@3.3.4
ui@1.0.6
underscore@1.0.3
url@1.0.4
webapp@1.2.0
webapp-hashing@1.0.3
```

**Comment by arunoda** [comment]
Okay. This seems pretty weird.
I'll setup an app based on these tonight and give it a try

**Comment by vmusulainen** [comment]
In addition

I got same error when I created clean application with `meteor create testApp` and tried to install it

**Comment by arunoda** [comment]
Okay. Then that's pretty weird.
Is it possible for you to share the VM with me.
Then I can do a test and find out the reason.

**Comment by vmusulainen** [comment]
Hm, probably, I can build docker container. Is it suitable?

**Comment by arunoda** [comment]
I tried, but I couldn't get this issue.
That's why I am trying use your VM

**Comment by vmusulainen** [comment]
I got same error when deploy project to meteor.com with `meteor deploy myapp.meteor.com`
The issue is gone away. I haven't ideas what it was be.
P.S. I reinstall autopublish package, but I don't think that it can related with the issue.
