### ISSUE TITLE
Mup setup error events.js:72 at errnoException (dns.js:37:11)

### ISSUE THREAD

**Issue by pcuci** [arunoda/meteor-up-legacy#470]
Both `mup` and `mupx` fail with no clear error message - any hints re: `at errnoException (dns.js:37:11)` error I'm getting?

```
$ DEBUG=* mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[aminy-test] - Installing Docker

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

and with `mup`

```
$ DEBUG=* mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[aminy-test] - Installing Node.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

My `mup.json`:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "aminy-test",
      "username": "ubuntu",
      "pem": "~/.ssh/id_aminy-test"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.38",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "aminy-app-test",

  // Location of app (local directory)
  "app": "../../app",

  // Configure environment
  "env": {
    "ROOT_URL": "http://test.aminy.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

**Comment by pcuci** [comment]
I found this lead, not sure how it relates to mup yet

http://stackoverflow.com/questions/15527775/getaddrinfo-enoent-error-from-http-request-on-node-js

Apparently, this error means Domain Name System failed to find the address (dns.js is for NAPTR queries).

Which address is mup trying to get to?

**Comment by pcuci** [comment]
Fixed

Changed "host" to fully qualified domain name

It used to work such that it picked up the shortened hostname from ~/.ssh/config - but no more

**Comment by DenisGorbachev** [comment]
@pcuci Just ran into the same issue, thanks for sharing the solution!
