### ISSUE TITLE
[mupx] custom SSH port ignored - Dockr setup timeout error

### ISSUE THREAD

**Issue by thomasf1** [arunoda/meteor-up-legacy#475]
Update: Turns out, the custom SSH port ("sshOptions": { "port" : 12345 }, config) is being ignored when "Port" is in capital letter, something that worked with mup. Truly strange case.

When trying to setup mupx with "mupx setup", we get a dockr setup error.

We initially tried with the VM that hosted mup before, reusing that config.
Then tried a new VM. Same error. The VM Image is "Ubuntu-14_04_1-LTS-amd64-server". 

```
> mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[rentkitbeta.cloudapp.net] - Installing Docker
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by thomasf1** [comment]
Installing Dockr manually via "wget -qO- https://get.docker.com/ | sh" + "sudo usermod -aG docker mup" and then running mupx setup doesn't seem to help either...

**Comment by dkmooers** [comment]
+1

Got the same error on Ubuntu 15.04 via Linode

**Comment by dkmooers** [comment]
:facepalm: - forgot to boot my Linode first. Works fine now!

**Comment by thomasf1** [comment]
The error is still there in 1.5.1, probably a connection error, we´re using pem authentication + a custom SSH port (though that´s also in the "mupx init" default mup.json - so we thought that´s supported).

**Comment by thomasf1** [comment]
Ah, figured it out... the custom SSH port is being ignored currently.

**Comment by thomasf1** [comment]
Turns out, the issue is that our old configuration said "Port" (which works with mup), mupx seems to require it as lowercase though (which is better style anyway). Kinda hard to track down.
