### ISSUE TITLE
mup doesn't work with continuous deployment

### ISSUE THREAD

**Issue by ffxsam** [arunoda/meteor-up-legacy#477]
I'm using mup in conjunction with Jenkins. The issue arises during deployment, because the progress meter tries to use a function that doesn't exist since we're not in a real terminal:

```
Started TaskList: Deploy app 'todos' (linux)[22m[39m
[36m[35m[108.61.207.152] [39m- Uploading bundle[39m

/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168
    this.stream.clearLine();
                ^
TypeError: undefined is not a function
    at ProgressBar.terminate (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168:17)
    at ProgressBar.tick (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:91:10)
    at ProgressBar.update (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:157:8)
    at Object.putFileOptions.onProgress (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:119:13)
    at sendProgressInfo (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/ssh.js:56:17)
    at writeCb (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1016:23)
    at state.requests.(anonymous function).cb (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:924:15)
    at SFTPStream._transform (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:352:17)
    at SFTPStream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SFTPStream._read (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:160:15)
    at SFTPStream.Transform._write (_stream_transform.js:167:12)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Any suggested fixes for this?

**Comment by arunoda** [comment]
Yes. Turn off progressBar. See enableUploadProgressBar option.

**Comment by ffxsam** [comment]
Oops! Thanks, I just now saw that going through the mup json.
