### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by ffxsam** [arunoda/meteor-up-legacy#482]
When running `mup deploy` I get this:

```
[34m[1m
Meteor Up: Production Quality Meteor Deployments[22m[39m
[34m[1m------------------------------------------------
[22m[39m
Building Started: ..

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I can't tell exactly what's going on here.

**Comment by ffxsam** [comment]
I should point out this only happens when doing a build via Jenkins CI. If I log into the box via ssh and run `mup deploy` manually, it works.

**Comment by ffxsam** [comment]
Ah, found a bug. Though you can specify `meteorBinary` in `mup.json`, that isn't actually used in the `build.js` file:

https://github.com/arunoda/meteor-up/blob/master/lib/build.js#L19
