### ISSUE TITLE
Deploy failure : fibers

### ISSUE THREAD

**Issue by parhelium** [arunoda/meteor-up-legacy#49]
Cannot deploy app to server:

```
Started TaskList: Deploying meteor App
[188.226.181.67] uploading bundle
[188.226.181.67] uploading bundle: SUCCESS
[188.226.181.67] setting up env vars
[188.226.181.67] setting up env vars: SUCCESS
[188.226.181.67] invoking deployment process
[188.226.181.67] invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '188.226.181.67' (ECDSA) to the list of known hosts.
    npm http GET https://registry.npmjs.org/fibers
    npm http 304 https://registry.npmjs.org/fibers
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    fibers@1.0.1 node_modules/fibers
    meteor stop/waiting
    meteor start/running, process 29147
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    meteor stop/waiting
    meteor start/running, process 29207
    ----------------------------------------------------------------------------
```

I have added package `npm` ( `mrt add npm` ) and filled package.json with:

```
{
  "parseUri":"1.2.3-2"
}
```

mup@0.4.3

Any idea what is going on ?

**Comment by arunoda** [comment]
Get the logs with `mup logs -n 300`

Also try increasing deployWaitTime value: https://github.com/arunoda/meteor-up#deploy-wait-time

**Comment by parhelium** [comment]
Logs:

```
Meteor requires Node v0.10.26 or later.
```

I updated `mup.json` with:

```
...
 "nodeVersion":"0.10.26",
...
```

Later, I executed: `mup setup` and `mup deploy` works back again.

Thanks @arunoda  for your hard work. Impressive !

**Comment by arunoda** [comment]
cool.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by zenmatt** [comment]
I've having the same issue, but my nodeVersion was already set to 0.10.26. Have deployed to 2 different machines for a few weeks without an issue, this morning one of the machines is fine and the other is getting a similar error.

```
[23.239.25.56] Invoking deployment process: FAILED ✘ 

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '23.239.25.56' (ECDSA) to the list of known hosts.
    npm http GET https://registry.npmjs.org/fibers
    npm http 304 https://registry.npmjs.org/fibers
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/timelined/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    fibers@1.0.1 node_modules/fibers
    timelined stop/waiting
    timelined start/running, process 8763
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    timelined stop/waiting
    timelined start/running, process 8800
    ----------------------------------------------------------------------------
```

Errors:

```
[23.239.25.56] Warning: Permanently added '23.239.25.56' (ECDSA) to the list of known hosts.
[23.239.25.56] Error: url must be a relative URL: http://z.nixipdb.com/
    at _.extend.classify (packages/routepolicy/routepolicy.js:103)
    at appUrl (packages/webapp/webapp_server.js:162)
    at Object.handle (packages/webapp/webapp_server.js:437)
    at next (/opt/timelined/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
    at next (/opt/timelined/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:192:9)
    at Object.next (/opt/timelined/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:127:23)
    at Utils.extend.onRouteNotFound (packages/iron-router/lib/server/router.js:59)
    at IronRouter.dispatch (packages/iron-router/lib/router.js:275)
    at packages/iron-router/lib/server/router.js:37
Failed to load c++ bson extension, using pure JS version
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Failed to load c++ bson extension, using pure JS version
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Failed to load c++ bson extension, using pure JS version
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteor user

```

**Comment by arunoda** [comment]
Seems like this is due to one of your IR server side routes. Can you disable them and try.

**Comment by zenmatt** [comment]
I don't think it is, we are deploying to another staging server without any issues (which makes this all the more confusing). Both Ubuntu 14.04, with very similar setup/config. The only thing different is a second person tried to deploy to the machine above and I'm wondering if that might be contributing to the issue? I've tried a mup setup prior to deploy and that doesn't help either.

**Comment by zenmatt** [comment]
Problem solved on my end, silly issue.

**Comment by zenmatt** [comment]
localhost was not set in /etc/hosts.

**Comment by gldnlab** [comment]
@zenmatt could you expand on the fix for this? been having trouble with this exact problem using mup on digital ocean.

**Comment by skarborg** [comment]
Check your mup logs? (well app logs via mup). I had other app errors
causing same symptoms.

**Comment by gldnlab** [comment]
@scarbies I'm a very mediocre coder so I'm a bit rookie on interpreting errors. This was only thread that felt directly related to what I'm seeing (Error: url must be a relative URL: http://httpheader.net)

The app seems to deploy fine, actually. I noticed a problem when trying to login does nothing at all, and went to logs and saw this error.

**Comment by gldnlab** [comment]
Error: url must be a relative URL: http://httpheader.net
    at _.extend.classify (packages/routepolicy/routepolicy.js:103)
    at appUrl (packages/fast-render/lib/server/inject.js:94)
    at Object.RouteController [as handle](packages/fast-render/lib/server/inject.js:108)
    at next (/opt/musichunt/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle](/opt/musichunt/app/programs/server/npm/fast-render/main/node_modules/connect/lib/middleware/cookieParser.js:65:5)
    at next (/opt/musichunt[107.170.235.251] /app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle](packages/spiderable/spiderable.js:126)
    at next (/opt/musichunt/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
    at middleware (packages/oauth/oauth_server.js:72)
    at packages/oauth/oauth_server.js:61
Error: url must be a relative URL: http://httpheader.net
    at _.extend.classify (packages/routepolicy/routepolicy.js:103)
    at appUrl (packages/webapp/webapp_server.js:153)
    at Object.handle (packages/webapp/webapp_server.js:486)
    at next (/opt/musichunt/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
    at next (/opt/musichunt/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:192:9)
    at Object.next (/opt/musichunt/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:127:23)
    at Utils.extend.onRouteNotFound (packages/iron-router/lib/server/router.js:59)
    at IronRouter.dispatch (packages/iron-router/lib/router.js:275)
    at packages/iron-router/lib/server/router.js:37

**Comment by steve-dobbs** [comment]
Having a very similar issue. would very much appreciate some guidance.

Here's the mup transcript

Bundling Started: /Users/mattthink/Sites/gleamers

Started TaskList: Deploy app 'Gleamers' (linux)
[128.199.222.80] - Uploading bundle
[128.199.222.80] ✔ Uploading bundle: SUCCESS
[128.199.222.80] - Setting up Environment Variables
[128.199.222.80] ✔ Setting up Environment Variables: SUCCESS
[128.199.222.80] - Invoking deployment process
[128.199.222.80] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added '128.199.222.80' (RSA) to the list of known hosts.
npm http GET https://registry.npmjs.org/fibers
npm http 304 https://registry.npmjs.org/fibers
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    y is fine; exiting
    fibers@1.0.1 node_modules/fibers

```
> bcrypt@0.8.0 install /opt/Gleamers/tmp/bundle/programs/server/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/opt/Gleamers/tmp/bundle/programs/server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/opt/Gleamers/tmp/bundle/programs/server/node_modules/bcrypt/build'
bcrypt@0.8.0 node_modules/bcrypt
├── bindings@1.0.0
└── nan@1.3.0
Gleamers stop/waiting
Gleamers start/running, process 3651
Waiting for MongoDB to initialize. (5 minutes)
connected
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
Gleamers stop/waiting
Gleamers start/running, process 3714
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'Gleamers' (linux)

**Comment by steve-dobbs** [comment]
and the mup logs to go along with it 

js-bson: Failed to load c++ bson extension, using pure JS version
[128.199.222.80]  >> stepping down to gid: meteoruser[128.199.222.80]
[128.199.222.80]  >> stepping down to uid: meteoruser
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1
[128.199.222.80] error: Script restart attempt #1
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #2
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #3
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #4
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #5[128.199.222.80]
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #6[128.199.222.80]
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #7[128.199.222.80]
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #8
[128.199.222.80] Meteor requires Node v0.10.29 or later.
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #9
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1
[128.199.222.80] error: Script restart attempt #10
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #11[128.199.222.80]
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] error: Script restart attempt #12[128.199.222.80]
[128.199.222.80] Meteor requires Node v0.10.29 or later.[128.199.222.80]
[128.199.222.80] error: Forever detected script exited with code: 1[128.199.222.80]
[128.199.222.80] Failed to load c++ bson extension, using pure JS version
[128.199.222.80] *\* You've set up some data subscriptions with Meteor.publish(), but[128.199.222.80]
[128.199.222.80] *\* you still have autopublish turned on. Because autopublish is still[128.199.222.80]
*\* on, your Meteor.publish() calls won't have much effect. All data
*\* will still be sent to all clients.
[128.199.222.80] **
*\* Turn off autopublish by removing the autopublish package:
**
*\*   $ meteor remove autopublish
**
*\* .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
*\* for each collection that you want clients to see.

[128.199.222.80] js-bson: Failed to load c++ bson extension, using pure JS version[128.199.222.80]
[128.199.222.80]  >> stepping down to gid: meteoruser

> > stepping down to uid: meteoruser
> > [128.199.222.80] Error: url must be a relative URL: http://www.google.com/[128.199.222.80]
> >     at _.extend.classify (packages/routepolicy/routepolicy.js:103)
> > [128.199.222.80]     at appUrl (packages/webapp/webapp_server.js:165)
> > [128.199.222.80]     at Object.handle (packages/webapp/webapp_server.js:455)
> >     at next (/opt/Gleamers/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:190:15)
> > [128.199.222.80]     at next (/opt/Gleamers/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:192:9)
> >     at Object.next (/opt/Gleamers/app/programs/server/npm/webapp/main/node_modules/connect/lib/proto.js:127:23)
> >     at Utils.extend.onRouteNotFound (packages/iron-router/lib/server/router.js:59)
> >     at IronRouter.dispatch (packages/iron-router/lib/router.js:275)
> >     at packages/iron-router/lib/server/router.js:37

**Comment by arunoda** [comment]
update nodeVersion in the mup.json to 0.10.29 and do mup setup

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by steve-dobbs** [comment]
Cheers @arunoda I'll let you know if that works fine.

**Comment by steve-dobbs** [comment]
cheers worked perfectly

**Comment by gldnlab** [comment]
Why's this happen? Still a problem - Node v 0.10.29. 

Error: url must be a relative URL: http://hotel.qunar.com/render/hoteldiv.jsp?&__jscallback=XQScript_4
    at _.extend.classify (packages/routepolicy/routepolicy.js:103)

**Comment by ghost** [comment]
When I am using Meteor Up to deploy my app to a Digital Ocean Droplet, I am receiving the same errors preventing the app from deploying. I have the exact same deployment on a different Droplet with no such issue. According to my research online, this is a known issue caused by bots trying to make a GET request on the server, apparently attempting to use the server as a proxy. No known solutions yet, though. :(

http://stackoverflow.com/questions/27031100/bots-preventing-meteor-server-from-deploying-on-digital-ocean-with-meteor-up

**Comment by ghost** [comment]
I tried updating mup, but it still doesn't work. The errors from the bots certainly don't seem to be the culprit. Unfortunately, the logs are saying anything to help. I have posted more details on SO if anyone is interested: http://stackoverflow.com/questions/27329103/mup-deploy-killed-on-do-droplet-but-no-errors-in-logs

**Comment by lsunsi** [comment]
Any help? I'm getting the exact same problem as @strilliams .
Node version is set to 0.10.36 on mup.json

**Comment by MasterJames** [comment]
Update meteor to 1.2+ and set to use 0.10.40 for node rerun setup and deploy.
Noted: the dev branch mupx is newer and resolves many issues.
