### ISSUE TITLE
Deploy Issues, NodeJS or MongoDB

### ISSUE THREAD

**Issue by sweetticket** [arunoda/meteor-up-legacy#498]
I'm getting this error:

```
Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    e-map-0.1.32.tgz
    npm http 304 https://registry.npmjs.org/ansi-regex
    npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
    child_process: customFds option is deprecated, use stdio instead.
    npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
    npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
    ../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
    ../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (tls == thread_id) {
       ^
    js-bson: Failed to load c++ bson extension, using pure JS version
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
```

When I run mup logs:

```
[45.55.71.79]     at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 1
error: Script restart attempt #276
```

When I run mup logs -n 300:

```
[xx.xx.xx.xx] /opt/meteor/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Could not load the bindings file. Tried:
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.2/linux/x64/bcrypt_lib.node
    at bindings (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 1
error: Script restart attempt #79
```

**Comment by jasonVeld** [comment]
Getting the same error. Using NodeJS 12.5, Mongo 2.6.10, on Ubuntu 14.04.2 LTS, 'trusty'.   

Looks the same as this issue of April, 'deploy error (bcrypt)', https://github.com/arunoda/meteor-up/issues/370.

Not sure whether cause is more to do with bindings load in log, or the port error.   Guessing port error.  Maybe that's why #370 was closed without comment, some server config issue.

**Comment by rtalwar26** [comment]
bcrypt has lot of issues with different versions of node, i faced same issue with node v0.12.9 but did note face with node v0.12.7
