### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by artiparty** [arunoda/meteor-up-legacy#503]
I'm trying to 'mup deploy' Telescope v0.21 to DigitalOcean with Ubuntu Mongo DB 2.6.7 on 14.04 and getting this error:

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    root_dir=/root/.node-gyp/0.10.33',
    gyp info spawn args   '-Dmodule_root_dir=/opt/myapp.com/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    make: Leaving directory `/opt/myapp.com/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.5 install /opt/myapp.com/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    fibers@1.0.5 node_modules/fibers

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    myapp.com stop/waiting
    myapp.com start/running, process 4815
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    myapp.com stop/waiting
    myapp.com start/running, process 4918
    ----------------------------------------------------------------------------
```

**Comment by zimt28** [comment]
Same error here, at least similar. Does @arunoda know why?

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    ss.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-52-generic
    gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/app/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    js-bson: Failed to load c++ bson extension, using pure JS version
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    rypt_lib/src/blowfish.o
    make: Leaving directory `/opt/app/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.5 install /opt/app/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    connected
    app start/running, process 12213
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
```

**Comment by zimt28** [comment]
Here are the logs:

```
/opt/myApp/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Could not load the bindings file. Tried:
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.10.36/linux/x64/bcrypt_lib.node
    at bindings (/opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/myApp/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/myApp/app/programs/server/boot.js:142:18)
    at Package (packages/npm-bcrypt/wrapper.js:1:1)
error: Forever detected script exited with code: 8
error: Script restart attempt #262
```

**Comment by zimt28** [comment]
#498 seems to be the same problem.

**Comment by arunoda** [comment]
What's the node version? try to select v0.10.26

If not use mupx, that's why we built it. It's pretty hard to deal with these kind of platform level issues.

**Comment by zimt28** [comment]
Have `0.10.26` running on the server and set in the config file. Used the `0.12.5` DO droplet and `n` to downgrade node `0.10.26`, should work I guess .. Just wondering as it's a really basic setup.

> If not use mupx

Ok thanks, will try that!

**Comment by arunoda** [comment]
Hmm. That's might be the issue.
Try to use a plain ubuntu server.

**Comment by zimt28** [comment]
I've now created a plain ubuntu server and deployed with mupx, works great. Thank you!
I guess as it's using Docker under the hood, I'd have to install any software deps into docker.
So right now I'd like to use [PDFtk](https://www.pdflabs.com/tools/pdftk-server/#download), how would I do that? Might be worth having such info in the readme :)

**Comment by arunoda** [comment]
That's not yet supported. If that's the case, I think still using plain
Ubuntu box with mup will work.

**Comment by zimt28** [comment]
I'll just try a DO droplet without preinstalled node and let you know if that works. Will mupx support third party software on the server in the future?

**Comment by arunoda** [comment]
Yes.

**Comment by aadamsx** [comment]
I'm getting this error today, when everything worked yesterday on a AWS Ubuntu instance:

Invoking deployment process: FAILED

	-----------------------------------STDERR-----------------------------------
	ailed https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
	npm ERR! Error: 502 Bad Gateway
	npm ERR!     at WriteStream.<anonymous> (/opt/nodejs/lib/node_modules/npm/lib/utils/fetch.js:57:12)
	npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
	npm ERR!     at fs.js:1598:14
	npm ERR!     at /opt/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
	npm ERR!     at Object.oncomplete (fs.js:107:15)
	npm ERR! If you need help, you may report this *entire* log,
	npm ERR! including the npm and node versions, at:
	npm ERR!     <http://github.com/npm/npm/issues>

	npm ERR! System Linux 3.13.0-36-generic
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
	npm ERR! cwd /opt/application_name/tmp/bundle/programs/server
	npm ERR! node -v v0.10.26 < -- [I had v0.10.36 before and it didn't work either!!]
	npm ERR! npm -v 1.4.3
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     /opt/application_name/tmp/bundle/programs/server/npm-debug.log
	npm ERR! not ok code 0
	-----------------------------------STDOUT-----------------------------------
	 > ./bcrypt: npm install due to binary npm modules
	bindings@1.0.0 node_modules/bindings

	nodeunit@0.9.1 node_modules/nodeunit
	└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, runforcover@0.0.2, glob@4.5.3)
	make: Entering directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
	  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
	  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
	  COPY Release/bcrypt_lib.node
	make: Leaving directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
	----------------------------------------------------------------------------

**Comment by aadamsx** [comment]
I'm getting this error today, when everything worked yesterday on a AWS Ubuntu instance:

Invoking deployment process: FAILED

	-----------------------------------STDERR-----------------------------------
	ailed https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
	npm ERR! Error: 502 Bad Gateway
	npm ERR!     at WriteStream.<anonymous> (/opt/nodejs/lib/node_modules/npm/lib/utils/fetch.js:57:12)
	npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
	npm ERR!     at fs.js:1598:14
	npm ERR!     at /opt/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
	npm ERR!     at Object.oncomplete (fs.js:107:15)
	npm ERR! If you need help, you may report this *entire* log,
	npm ERR! including the npm and node versions, at:
	npm ERR!     <http://github.com/npm/npm/issues>

	npm ERR! System Linux 3.13.0-36-generic
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
	npm ERR! cwd /opt/application_name/tmp/bundle/programs/server
	npm ERR! node -v v0.10.26 < -- [I had v0.10.36 before and it didn't work either!!]
	npm ERR! npm -v 1.4.3
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     /opt/application_name/tmp/bundle/programs/server/npm-debug.log
	npm ERR! not ok code 0
	-----------------------------------STDOUT-----------------------------------
	 > ./bcrypt: npm install due to binary npm modules
	bindings@1.0.0 node_modules/bindings

	nodeunit@0.9.1 node_modules/nodeunit
	└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, runforcover@0.0.2, glob@4.5.3)
	make: Entering directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
	  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
	  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
	  COPY Release/bcrypt_lib.node
	make: Leaving directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
	----------------------------------------------------------------------------

**Comment by artiparty** [comment]
@arunoda I tried to change the Node version, it didn't help. Now I try to use mupx and I'm getting this error:

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Error response from daemon: no such id: appname-frontend
    Error: failed to remove containers: [appname-frontend]
    Error response from daemon: Cannot start container 6fee7d96ce14cfbc683e60f812c024a736a729a9d131534ed78bff323d67b743: Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
    -----------------------------------STDOUT-----------------------------------
    appname
    base: Pulling from meteorhacks/meteord
    7a3e804ed6c0: Already exists
    b96d1548a24e: Already exists
    1953b0d94d9e: Already exists
    0307189ae014: Already exists
    3a879b77613d: Already exists
    28ec607335d2: Already exists
    fbe72745ee57: Already exists
    a3db5bad3029: Already exists
    a3db5bad3029: Already exists
    Digest: sha256:b48132937b3e624f654dd1516e447253cdd29b1e473afd80985c7b078e2de6e1
    Status: Image is up to date for meteorhacks/meteord:base
    6fee7d96ce14cfbc413e60f812c024a736a729a9d131534ed78bff323d67b743

```

**Comment by aadamsx** [comment]
@artiparty what instructions did you follow?

**Comment by artiparty** [comment]
@aadamsx http://telescope.readme.io/docs/deploying#option-3-meteorup--digital-ocean--composeio

**Comment by aadamsx** [comment]
Right, I got mup working on a AWS EC2 Ubuntu instance, but now I'm looking at mupx.

**Comment by arunoda** [comment]
This is because there is another app running on port 80. I suggest to
remove it. Read the mupx documentation for the migration.

Or better use a new clean Ubuntu server.

**Comment by artiparty** [comment]
I just tried to use a brand new DigitalOcean droplet for a deploy and I'm getting the same error:

```
 x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Error response from daemon: no such id: appname-frontend
    Error: failed to remove containers: [appname-frontend]
    Error response from daemon: Cannot start container 741a2d73355758ee0c82397ae912997c675b9ca9580bb35793132046cc7c9cd2: Bind for 0.0.0.0:80 failed: port is already allocated
    -----------------------------------STDOUT-----------------------------------
    appname
    base: Pulling from meteorhacks/meteord
    7a3e804ed6c0: Already exists
    b96d1548a24e: Already exists
    1953b0d94d9e: Already exists
    0307189ae014: Already exists
    3a879b77613d: Already exists
    28ec607335d2: Already exists
    fbe72745ee57: Already exists
    a3db5bad3029: Already exists
    a3db5bad3029: Already exists
    Digest: sha256:b48132937b3e624f654dd1516e797253cdd29b1e473afd80985c7b078e2de6e1
    Status: Image is up to date for meteorhacks/meteord:base
    741a2d73355758ee0c82317ae912997c475b9ca9580bb35793132046cc7c9cd2
    ----------------------------------------------------------------------------
```

**Comment by zimt28** [comment]
I tried `mup` on a new DO instance with node preinstalled, and then downgraded the node version, which doesn't work. Using a new DO instance without node and letting mup install it, doesn't work either.

**Comment by dnprock** [comment]
I had no error in mup logs. Besides making sure node is 0.10.x, I increased my deployCheckWaitTime to 120 seconds (from 15 seconds). This works for me.

**Comment by akshaykmr** [comment]
I had the same error on amazon EC2, using mupx instead fixed it.

**Comment by andruschka** [comment]
I went with mup and just changed "nodeVersion":    to ->  "0.10.40",!
Dont forget NOT to use "v" in "0.10.40".
