### ISSUE TITLE
Mup deploy refuse to work

### ISSUE THREAD

**Issue by stonetwig** [arunoda/meteor-up-legacy#513]
```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:469:5)
    at SSH2Stream.emit (events.js:110:17)
    at parsePacket (/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3649:10)
    at SSH2Stream._transform (/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

I have tried using both node and io.js and not any of them seems to work. `mup setup`works brilliantly

Config:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "somedomain.tld",
      "username": "root",
      "password": "xxx"
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.12.2",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "theapp",

  // Location of app (local directory)
  "app": "/home/someuser/theapp/",

  // Configure environment
  "env": {
    "ROOT_URL": "http://theapp.tld",
    "PORT": "3337"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 30
}
```

**Comment by MasterJames** [comment]
I think you have to figure out the correct username still.
It says All configured ~ User Auth failed.

**Comment by stonetwig** [comment]
I'm confident that it is the correct username (root) and password.
It does say `All configured authentication methods failed` and not user auth?

And I used the same configs for the setup part which worked just fine.

**Comment by MasterJames** [comment]
Can you ssh into the server with those settings?
The error suggests to me it was unable to gain access every way possible.

Anyway can you try migration to mupx?

**Comment by stonetwig** [comment]
Yes I too read the error that way, but I verified that SSH:ing in worked flawlessly before I added the credentials to the config. But I simply solved the problem by packaging the app myself but since I am now running it in a a screen it would be good to have this tool working since it simplifies the process so much.

**Comment by MasterJames** [comment]
Great thats good to hear congratulations! Are you able to suggest a fix or provide a pull request for someone to review? Or is this to be closed?

**Comment by alemur** [comment]
Not sure thiscan beuseful to anyone,but I solved this like:

  "servers": [
    {
      "host": "ec2-52-6-249-225.compute-1.amazonaws.com",
      "username": "ec2-user",
      "pem": "/Users/alemur/.ssh/aws.pem"
    }
  ],

**Comment by akmur** [comment]
The "throw er; // Unhandled 'error' event" error went away when I did 

 "servers": [
    {
      "host": "ec2-52-6-249-225.compute-1.amazonaws.com",
      "username": "ec2-user",
      "pem": "/Users/alemur/.ssh/aws.pem"
    }
  ],

But then I noticed I was not using an Ubuntu instance! :) I'm gonna try again
