### ISSUE TITLE
Error: Can't find npm module 'connect'.

### ISSUE THREAD

**Issue by toddsundsted** [arunoda/meteor-up-legacy#519]
Hey Arunoda, Max Savin here working with Todd. We're having an issue using MUP to deploy a Meteor application. It works fine on Mac and Linux locally, and the old version works fine in production. The new version, which is only changes on the front-end, throws an issue during deployment:

We've tried reconfiguring MUP, etc, with no luck. We've also tinkered with the node version without any luck. I'm hoping you can help us figure out how to solve this.

``` javascript

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #1

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #2

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #3

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #4

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #5

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #6

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #7

/opt/meteor/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'connect'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:113:17)
    at Package (packages/iron:router/lib/server/router.js:1)
    at /opt/meteor/app/programs/server/packages/iron_router.js:1380:4
    at /opt/meteor/app/programs/server/packages/iron_router.js:1429:3
    at /opt/meteor/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
Kadira: completed instrumenting the app
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
```

**Comment by toddsundsted** [comment]
Managed to fix this by doing a `meteor update` which then got us a more useful set of error message on the server. Upgrade the version of node and everything worked. Closing.

```
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #2
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #3
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #4
```
