### ISSUE TITLE
mupx deploying from Windows fails

### ISSUE THREAD

**Issue by illuminaut** [arunoda/meteor-up-legacy#520]
Most of the time (but not always), when I try to deploy from my Windows development machine, I'm getting the following error. This is using mupx 1.5.0 on Windows 7 x64

```
=> Starting meteor app on port:80
 /bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
              ^
 Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
     at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
     at Module._compile (module.js:456:26)
     at Object.Module._extensions..js (module.js:474:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:312:12)
     at Module.require (module.js:364:17)
     at require (module.js:380:17)
     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
     at Module._compile (module.js:456:26)
     at Object.Module._extensions..js (module.js:474:10)
```

**Comment by illuminaut** [comment]
This appears to be similar to this issue: https://github.com/arunoda/meteor-up/issues/441
which was only closed by the filer because he switched from Windows to Linux.

**Comment by mistriel** [comment]
Having this issue too :-(
Can you please assist ?

**Comment by ericterpstra** [comment]
Make sure you have node.js installed, and install the node-gyp package globally with `npm i -g node-gyp`

You might also need to install Microsoft's C/C++ build tools, which are included in the Visual Studio Community edition (free).

**Comment by oanylund** [comment]
I stopped getting this error when i changed the "deployCheckWaitTime" in mup.json from 15 to 60. Running on Windows 10.

**Comment by lapsule** [comment]
same error on Mac

**Comment by LaughingBubba** [comment]
thanks to @oanylund, wait time fixed my problem. Cheers!
