### ISSUE TITLE
[mupx] Deployment fails after restoring Google Cloud Engine snapshot

### ISSUE THREAD

**Issue by dkmooers** [arunoda/meteor-up-legacy#524]
So I had a GCE instance up and running perfectly using mupx. My app worked just fine, could deploy updates no problem.

So before going live with my app, I'm testing snapshot backups to make sure I can restore if necessary. So I took a snapshot of my GCE instance, and then I restored the snapshot to a new instance.

I put the new instance's IP in mup.json, then did `mupx start`, and got the following error:

```
Started TaskList: Starting Application (linux)
[104.154.93.116] - Starting app
[104.154.93.116] - Starting app: SUCCESS
[104.154.93.116] - Verifying deployment
[104.154.93.116] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    ectionDriver (packages/underscore/underscore.js:750:1)
        at new Mongo.Collection (packages/mongo/collection.js:98:1)
        at packages/accounts-base/accounts_common.js:141:1
        at /bundle/bundle/programs/server/packages/accounts-base.js:243:4
        at /bundle/bundle/programs/server/packages/accounts-base.js:1659:3
        at /bundle/bundle/programs/server/boot.js:222:10
        - - - - -
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
        at [object Object].emit (events.js:106:17)
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:442:13)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

Something's weird. Mongo's not started?

So I ran `docker ps` and got this:

```
CONTAINER ID        IMAGE                             COMMAND                CREATED              STATUS                            PORTS                        NAMES
d28d624527af        meteorhacks/mup-frontend-server   "/start.sh"            About a minute ago   Up About a minute                 0.0.0.0:443->443/tcp         perennial-frontend   
38c123d7d0df        meteorhacks/meteord:base          "/bin/sh -c 'bash $M   About a minute ago   Restarting (8) 13 seconds ago     0.0.0.0:80->80/tcp           perennial            
518c6831fb11        mongo                             "/entrypoint.sh mong   About a minute ago   Restarting (100) 38 seconds ago   127.0.0.1:27017->27017/tcp   mongodb 
```

The Meteor and Mongo docker images never actually start up. They stay stuck at "Restarting" forever.

Any idea what's going on?

Should I use mup instead of mupx for a production app?

**Comment by dkmooers** [comment]
I just tried this same process with mup (not mupx) and it works fine:
- deploy to GCE instance using mup
- take snapshot of instance
- restore snapshot to another instance
- works automatically! (no mup commands required) as would be expected from mup features/docs, I guess!

**Comment by dkmooers** [comment]
Weird... I'm unable to duplicate the issue with mupx now. I tried restoring from a snapshot and it worked fine. I must have buggered the original snapshot/restore process somehow, not sure what happened. Mupx seems to work fine with GCE instances now - hard reset, stop/start, restore to another instance from a snapshot - all good.

Closing for now.
