### ISSUE TITLE
MUP not working inside Codeship

### ISSUE THREAD

**Issue by malsher** [arunoda/meteor-up-legacy#525]
Hi.

Firstly, thanks for bringing MUP to the Meteor community. It's clean, tidy and does exactly what it claims to do.

The issue I'm having is how to get it working inside Codeship.

The error is similar to having an invalid path in the mup.json file. However, all variants to point to the correct path appear to fail.

`events.js:72`
`throw er; // Unhandled 'error' event`
`^`
`Error: spawn ENOENT`
`at errnoException (child_process.js:988:11)`
`at Process.ChildProcess._handle.onexit (child_process.js:779:34)`

Using the console in Codeship I can see the code exists and is in the correct location. I can try running MUP inside the console just as I would locally, but always with the same error.

The path in the mup.json file appears ok, as I've tried all physical and linked path variants to the same location.

Has anyone successfully used MUP inside Codeship and if so, are they willing to share the secret?

Thanks
John

**Comment by zacharynevin** [comment]
+1 I have the exact same issue

**Comment by nathanlippi** [comment]
+1 Same problem.

**Comment by nathanlippi** [comment]
@malsher @zacharynevin: I think I've found the solution.
1. I SSH'd into a CodeShip debug instance, for faster debugging.
2. Eventually I tried `meteor build` and it said it didn't recognize `meteor`.
3. I added `meteor` to my path, like so: `PATH=$PATH:/$HOME/.meteor`

Let me know if it helps!
