### ISSUE TITLE
Deploy Error: Initialization failed

### ISSUE THREAD

**Issue by ipstas** [arunoda/meteor-up-legacy#532]
Any idea?

```
mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /srv/www/meteor/london
.write(string, encoding, offset, length) is deprecated. Use write(string, offset, length, encoding) instead.

Started TaskList: Deploy app 'ufg' (linux)
[placetee.us] - Uploading bundle

crypto.js:431
    this._binding = new binding.DiffieHellman(sizeOrKey);
                    ^
Error: Initialization failed
    at new DiffieHellman (crypto.js:431:21)
    at Object.DiffieHellman (crypto.js:424:12)
    at onKEXDH_GEX_GROUP (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2349:22)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:191:36)
    at SSH2Stream.EventEmitter.emit (events.js:106:17)
    at parse_KEX (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3856:14)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3731:12)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
```

**Comment by MasterJames** [comment]
First fix the depreciated write, although it shouldn't be a problem.
second try mupx.

**Comment by ipstas** [comment]
not sure where that 'write' comes from, but the error is about ssl/ssh
and mupx gives the exact same error.
What puzzles me, sometimes it goes through

**Comment by MasterJames** [comment]
Did you try following the instructions to upgrade meaning you'very done a clean mupx install?

**Comment by ipstas** [comment]
Yes, I have created the new folder and run mupx init, setup and tried deploy
The only difference as I can see is the mup.json. And the only difference in mup.json is

```
<   "enableUploadProgressBar": true,
<
<       "buildOptions": {
<               // build with the debug mode on
<               "debug": true
<       }
< }
```

It looks like there is timeout error with ssh, the strange thing sometimes it goes OK, but mostly it fails before I see the progress bar.

**Comment by MasterJames** [comment]
How about running 'npm updates'?
Maybe node needs updating. What version of node is installed? 
Can you test ssh is working as expected?

**Comment by ipstas** [comment]
```
npm version
{ http_parser: '1.0',
  node: '0.11.8-pre',
  v8: '3.20.17',
  uv: '0.11.13',
  zlib: '1.2.3',
  modules: '13',
  openssl: '1.0.1e',
  npm: '1.3.11' }
```

I have tried ssh as the first possible issue. No problem, ssh connects instantly

Stupid of me, the latest npm is 2.13.1
`npm install npm -g` works

So I have updated it, still it did not fix the error, I keep getting

```
mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /srv/www/meteor/london
Using buildOptions : {"debug":true}
.write(string, encoding, offset, length) is deprecated. Use write(string, offset, length, encoding) instead.

Started TaskList: Deploy app 'placetee' (linux)
[www.placetee.us] - Uploading bundle

crypto.js:431
    this._binding = new binding.DiffieHellman(sizeOrKey);
                    ^
Error: Initialization failed
    at new DiffieHellman (crypto.js:431:21)
    at Object.DiffieHellman (crypto.js:424:12)
    at onKEXDH_GEX_GROUP (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2349:22)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:191:36)
    at SSH2Stream.EventEmitter.emit (events.js:106:17)
    at parse_KEX (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3856:14)
    at parsePacket (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3731:12)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mupx/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
```

**Comment by MasterJames** [comment]
Okay maybe this link will help...
https://github.com/arunoda/meteor-up/issues/427
it says they reverted back a version.

**Comment by ipstas** [comment]
Thanks! I think that was it.

```
npm install -g n
n 0.12.7
```

0.12.7 - the latest ad greatest, I had 0.11 before (0.10.something works too), 0.11 has something broken

And now it flies
