### ISSUE TITLE
Invoking deployment error

### ISSUE THREAD

**Issue by pavanputhra** [arunoda/meteor-up-legacy#545]
Hi @arunoda 

Am getting following error while deploying to Ubuntu 14.04 LTS server

``` bash
[Ip.add.re.ss] x Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
        pm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        ../src/coroutine.cc: In function `void* find_thread_id_key(void*)':
        ../src/coroutine.cc:64:53: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
          for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; --ii) {
                                                             ^
        ../src/coroutine.cc:90:3: warning: `thread_id' may be used uninitialized in this function [-Wmaybe-uninitialized]
           if (tls == thread_id) {
           ^
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 9009: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        target/fibers.node: Finished
          COPY Release/fibers.node
        make: Leaving directory `/opt/car-sales/tmp/bundle/programs/server/node_modules/fibers/build'
        Installed in `/opt/car-sales/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
        underscore@1.5.2 node_modules/underscore

        eachline@2.3.3 node_modules/eachline
        └── type-of@2.0.1

        chalk@0.5.1 node_modules/chalk
        ├── ansi-styles@1.1.0
        ├── escape-string-regexp@1.0.3
        ├── supports-color@0.2.0
        ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
        └── has-ansi@0.1.0 (ansi-regex@0.2.1)

        semver@4.1.0 node_modules/semver

        source-map-support@0.2.8 node_modules/source-map-support
        └── source-map@0.1.32 (amdefine@0.1.0)

        fibers@1.0.5 node_modules/fibers
        Waiting for MongoDB to initialize. (5 minutes)
        connected
        car-sales stop/waiting
        car-sales start/running, process 30290
        Waiting for 15 seconds while app is booting up
        Checking is app booted or not?
        car-sales stop/waiting
        car-sales start/running, process 30317
        ----------------------------------------------------------------------------
```

Upon checking mup logs I got following error.

``` bash
[ip.add.re.ss] Error: `/opt/car-sales/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibe
rs`?[ip.add.re.ss]
[ip.add.re.ss]     at Object.<anonymous> (/opt/car-sales/app/programs/server/node_modules/fibers/fibers.js:16:8)[ip.add.re.ss]
[ip.add.re.ss]     at Module._compile (module.js:456:26)[ip.add.re.ss]
[ip.add.re.ss]     at Object.Module._extensions..js (module.js:474:10)[ip.add.re.ss]
[ip.add.re.ss]     at Module.load (module.js:356:32)[ip.add.re.ss]
[ip.add.re.ss]     at Function.Module._load (module.js:312:12)[ip.add.re.ss]
[ip.add.re.ss]     at Module.require (module.js:364:17)[ip.add.re.ss]
[ip.add.re.ss]     at require (module.js:380:17)[ip.add.re.ss]
[ip.add.re.ss]     at Object.<anonymous> (/opt/car-sales/app/programs/server/boot.js:1:75)[ip.add.re.ss]
[ip.add.re.ss]     at Module._compile (module.js:456:26)[ip.add.re.ss]
[ip.add.re.ss]     at Object.Module._extensions..js (module.js:474:10)[ip.add.re.ss]
[ip.add.re.ss] error: Forever detected script exited with code: 8[ip.add.re.ss]
[ip.add.re.ss] error: Script restart attempt #4695[ip.add.re.ss]
[ip.add.re.ss]
[ip.add.re.ss] /opt/car-sales/app/programs/server/node_modules/fibers/fibers.js:16[ip.add.re.ss]
[ip.add.re.ss]       [ip.add.re.ss] throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe[ip.add.re.ss]
[ip.add.re.ss]       [ip.add.re.ss]  [ip.add.re.ss]  [ip.add.re.ss]  [ip.add.re.ss]  [ip.add.re.ss]  [ip.add.re.ss]  [ip.add.re.ss] ^[ip.add.re.ss]
```

As error says its missing following directory

```
/opt/car-sales/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14
```

But it has 

```
/opt/car-sales/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28
```

How to resolve this issue?

**Comment by MasterJames** [comment]
What happens if you rename the folder? 
How about reinstall fiber packages with the requested version via...
npm install <package>@<version>
or alter the dependency to match.

**Comment by MasterJames** [comment]
npm install package@version
silly square brackets didn't take reposting.
