### ISSUE TITLE
 Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by namsouth** [arunoda/meteor-up-legacy#552]
Any Idea ?

Started TaskList: Deploy app 'iLearner' (linux)
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] - Uploading bundle
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] - Uploading bundle: SUCCESS
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] - Setting up Environment Variables
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] - Setting up Environment Variables: SUCCESS
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] - Invoking deployment process
[ec2-52-74-101-224.ap-southeast-1.compute.amazonaws.com] x Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    node-gyp/node_modules/which/which.js:75:29)
    gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:83:16
    gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
    gyp ERR! System Linux 3.13.0-44-generic
    gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /opt/iLearner/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------

**Comment by namsouth** [comment]
I have solve this issue, as my workmate remove python on the server (ubuntu linux),
reinstall python, mup working normally
