### ISSUE TITLE
events.js:72    throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by sgerstenzang** [arunoda/meteor-up-legacy#556]
Hello, running "mup setup" and getting the follow error. Any ideas? Thanks!

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Packet corrupt
    at onDISCONNECT (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2034:15)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:179:5)
    at SSH2Stream.EventEmitter.emit (events.js:106:17)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3464:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read](_stream_transform.js:180:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:168:12)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)

**Comment by daslicht** [comment]
navigate to /etc and look in the hostname file.
Do you used that hostname in the setup file ?

**Comment by sgerstenzang** [comment]
Yep! They match.

**Comment by daslicht** [comment]
:/

**Comment by sgerstenzang** [comment]
The problem ended up being I was running an older version of Node. Thanks!

**Comment by daslicht** [comment]
:+1:

**Comment by digz6666** [comment]
@sgerstenzang What's the version of your nodejs? Mine is 0.12.7-x64 and still getting this error.
