### ISSUE TITLE
mup setup throws error on Phantom.js 

### ISSUE THREAD

**Issue by daslicht** [arunoda/meteor-up-legacy#557]
Hello,
when I run mup setup I get : 

```
mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[hostname] - Installing PhantomJS
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND hostname
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

any idea whats wrong?, please

**Comment by daslicht** [comment]
In the above example I have set install node to false.
If I set phanton to false I get another error:

```
mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[hostname] - Setting up Environment
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND hostname
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

```

**Comment by daslicht** [comment]
navigate to /etc and look in the hostname file :)
I used the wrong hostname
