### ISSUE TITLE
spiderble not working , internal server error

### ISSUE THREAD

**Issue by daslicht** [arunoda/meteor-up-legacy#562]
When i run my meteor project with **_meteor**_ on my server the spiderable package is working

When I start it with **_mup**_ I get

```
 internal server error
```

any idea whats going on?

**Comment by MasterJames** [comment]
Describe spiderable package? 
Permissions maybe? 
Tried mupx? 
Maybe you have a way to provide more detailed logs?

**Comment by daslicht** [comment]
Hello,
the spiderable package is used to make Meteor.js apps indexable by Google
https://atmospherejs.com/meteor/spiderable
Thats why you have this option in your mup.json: 

```
// Install PhantomJS in the server
  "setupPhantom": true,

```

Which Permissions should I check ? Without mup  anything works great.

mupx also seam to have an issue with mupx :
https://github.com/meteorhacks/meteord#spiderable-not-working-but-have-a-fix

**Comment by daslicht** [comment]
Thats what I get when I try to deploy (another app) with mupx:
https://github.com/arunoda/meteor-up/issues/565

**Comment by MasterJames** [comment]
Okay right thanks phantomjs.
maybe you have a similar problem in mup as described for mupx with it.
there was lots to think about and try in...
https://github.com/meteor/meteor/issues/2429

**Comment by daslicht** [comment]
yeh that seams to be the fix : 
https://github.com/meteorhacks/meteord#spiderable-not-working-but-have-a-fix

but I dont get it deployed with mupx :/

**Comment by tgienger** [comment]
Actually it does work with mupx.

**Comment by ipstas** [comment]
doesnt work with mupx for me

```
[www.placetee.us] spiderable: phantomjs failed: null
[www.placetee.us] stderr:
[www.placetee.us] spiderable: phantomjs failed: Error: Command failed: Can't open '/dev/stdin'

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
stderr: Can't open '/dev/stdin'
```

However if i remove fast-render  it works. I am not sure how it is connected

**Comment by select** [comment]
I had the same error on mupx and could solve it by switching from the package `spiderable` to `ongoworks:spiderable`
