### ISSUE TITLE
mupx deploy failed

### ISSUE THREAD

**Issue by daslicht** [arunoda/meteor-up-legacy#565]
Hello,
when I try to deploy my meteor app with mupx deploy I get:
Any idea how to fix? please

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    17)
        at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown job: ansolas-mupx
    start: Unknown job: ansolas-mupx
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (56) Recv failure: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    es
    bindings@1.0.0 node_modules/bindings

    nodeunit@0.9.1 node_modules/nodeunit
    └── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, glob@4.5.3, runforcover@0.0.2)

    > fibers@1.0.5 install /opt/ansolas-mupx/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------

```

**Comment by daslicht** [comment]
second try : 

```
/bundle/bundle/programs/server/node_modules/fibers/future.js:245
                            throw(ex);
                                  ^
    Error: MONGO_URL must be set in environment
        at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
        at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
        at new Mongo.Collection (packages/mongo/collection.js:98:1)
        at packages/accounts-base/accounts_common.js:141:1
        at /bundle/bundle/programs/server/packages/accounts-base.js:243:4
        at /bundle/bundle/programs/server/packages/accounts-base.js:1659:3
        at /bundle/bundle/programs/server/boot.js:222:10
        at Array.forEach (native)
        at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
        at /bundle/bundle/programs/server/boot.js:117:5

    => Redeploying previous version of the app

```

**Comment by daslicht** [comment]
Looks like the futures are broken, if I would know where mupx deploy the app I could try to manually built it

**Comment by MasterJames** [comment]
Use the environment variables to set your mongo location.
so not a setting in json but in the Shell?

**Comment by MasterJames** [comment]
See 
http://stackoverflow.com/questions/11198014/meteor-custom-mongodb-during-development

**Comment by MasterJames** [comment]
Previous comment suggest /opt is where to look for deployment folder as your app name.

**Comment by daslicht** [comment]
even if i set tghe proper environment vars , the **_fibers**_ are still broken

**Comment by MasterJames** [comment]
Okay let's see your settings. Maybe including a port number if omitted first.
other thing people tinker with is updating all packages of node and or down grading a version or two of node.

**Comment by daslicht** [comment]
```
{
  "servers": [
    {
      "host": "myservershostname",
      "username": "root",
      "password": "mypass",
      "env": {}
    }
  ],

  "setupMongo": false, //already have mongodb installed
  "appName": "daslicht-mupx",


  "app": "/root/my.tld",

  "env": {
    "PORT": 3000,
    "ROOT_URL": "http://my.tld"
  },


  "deployCheckWaitTime": 15,

  "enableUploadProgressBar": true
}
```

**Comment by daslicht** [comment]
to much trouble we are currently rethinking if we really like to continue using meteor at all

**Comment by MasterJames** [comment]
Well im sorry to here that meteor will be providing Galaxy soon so maybe that will be easier for you.
Also maybe try the default example and see with your path to app and Mongo where the problem lies.

**Comment by arunoda** [comment]
Hi  @daslicht 

If you've your own mongo setup, use that into the MONGO URL.
For an example, if you've mongodb running on your server.

Use: `MONGO_URL="mongodb://localhost:27017/myapp"`

If you mark `setupMongo` false, then you must provide a `MONGO_URL`

**Comment by arunoda** [comment]
@daslicht 

MUP is not the only deployment solution Meteor has. You can use something like modulus.io as well.

**Comment by daslicht** [comment]
The MONGO URL is not the main problem and is easy to solve.
The Fibers issue is much more serious.

I managed to run the project by using demeteorize but unfortunately the spiderable packagage is nearby useless. 
for example to to call the following url without js enabled, it will return NOTHING:
http://www.manuel-schoebel.com/?_escaped_fragment_=about
But I dont care anymore , we have meanwhile started the project with a better mature technology.
