### ISSUE TITLE
Deploy error 

### ISSUE THREAD

**Issue by isAlmogK** [arunoda/meteor-up-legacy#566]
Just ran the deploy it looked like everything was fine but when I checked my app URL noting loaded I ran mup logs -f

and got the following 

[104.131.207.244]     at MongoClient.connect (/opt/linkly/app/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/lib/mongo_client.js:95:16)
    at packages/meteor/helpers.js:118:1
    at new FileCollection (packages/vsivsi:file-collection/src/gridFS_server.coffee:32:16)
    at FileCollection (packages/vsivsi:file-collection/src/gridFS_server.coffee:21:24)
    at __coffeescriptShare (packages/ryw:blog/collections/files.coffee:4:15)
    at packages/ryw:blog/collections/files.coffee:4:1
    at packages/ryw:blog/router.coffee:1:1
    at /opt/linkly/app/programs/server/boot.js:222:10
error: Forever detected script exited with code: 8
error: Script restart attempt #102

**Comment by isAlmogK** [comment]
This had something to do with ryw:blog package once removed it was fine - https://atmospherejs.com/ryw/blog
