### ISSUE TITLE
[mupx] [nginx] 502 Bad Gateway on Mailgun Webhook

### ISSUE THREAD

**Issue by thomasf1** [arunoda/meteor-up-legacy#571]
We´re having some issues and we´re not quite sure if it´s nginx/mupx or iron router server side routes.

Our setup:
Mailgun receives a incoming email and triggers a webhook on our server which we stripped down to the bare minimum:

``` coffeescript
Router.route("/webhooks/mailgun", {where: 'server'}).post ->
  console.log "*** /webhooks/mailgun"
```

Then, our server trows this error: (no console.log):

```
[rentkitbeta.cloudapp.net] Error: request aborted
[rentkitbeta.cloudapp.net]     at makeError (/bundle/bundle/programs/server/npm/iron_router/node_modules/body-parser/node_modules/raw-body/index.js:154:15)
[rentkitbeta.cloudapp.net]     at IncomingMessage.onAborted (/bundle/bundle/programs/server/npm/iron_router/node_modules/body-parser/node_modules/raw-body/index.js:252:10)
[rentkitbeta.cloudapp.net]     at IncomingMessage.emit (events.js:92:17)
[rentkitbeta.cloudapp.net]     at abortIncoming (http.js:1916:11)
[rentkitbeta.cloudapp.net]     at Socket.serverSocketCloseListener (http.js:1928:5)
[rentkitbeta.cloudapp.net]     at Socket.emit (events.js:117:20)
[rentkitbeta.cloudapp.net]     at TCP.close (net.js:466:12)
```

And Mailgun reports a "502 Bad Gateway" error on the webhook and schedules it to try again.

One noteable thing is a maybe 30-60 second lag from Mailgun getting the message to the Error being thrown, maybe pointing towards some sort of timeout / missing data.

We assume that nginx somehow fails but are not quite sure on how to debug it...

**Comment by thomasf1** [comment]
More specifically: The content type: "multipart/mixed; boundary="------------020601070403020003080006"" seems to work, multipart/alternative; boundary="001a11343832b64b18051bf42125" seem to break.

**Comment by thomasf1** [comment]
Pretty sure at this point that it´s an Iron Router issue...
