### ISSUE TITLE
Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by JamesLM** [arunoda/meteor-up-legacy#578]
Hi there. I'm a bit new to this so hopefully someone can help.

I've followed the screencast tutorial for deploying a meteor app to an Ubuntu server on digitalocean. I'm using Windows 8.1 and followed this mini-tutorial for Windows:
https://forums.meteor.com/t/deploy-meteor-apps-via-windows-with-meteor-up/3479

 I get the following error: 

```
Building Started: .

Started TaskList: Deploy app 'mydemo' (linux)
[178.62.91.175] - Uploading bundle
[178.62.91.175] - Uploading bundle: SUCCESS
[178.62.91.175] - Setting up Environment Variables
[178.62.91.175] - Setting up Environment Variables: SUCCESS
[178.62.91.175] - Invoking deployment process
[178.62.91.175] x Invoking deployment process: FAILED

        -----------------------------------STDERR-------------------------------
----
        ge-json/read-json.js:119:21)
        npm ERR!     at parseJson (/opt/nodejs/lib/node_modules/npm/node_modules
/read-package-json/read-json.js:87:17)
        npm ERR!     at /opt/nodejs/lib/node_modules/npm/node_modules/read-packa
ge-json/read-json.js:59:33
        npm ERR!     at evalmachine.<anonymous>:272:14
        npm ERR!     at /opt/nodejs/lib/node_modules/npm/node_modules/graceful-f
s/graceful-fs.js:102:5
        npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
        npm ERR! If you need help, you may report this *entire* log,
        npm ERR! including the npm and node versions, at:
        npm ERR!     <http://github.com/npm/npm/issues>

        npm ERR! System Linux 3.13.0-57-generic
        npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
        npm ERR! cwd /opt/mydemo/tmp/bundle/programs/server
        npm ERR! node -v v0.10.36
        npm ERR! npm -v 1.4.28
        npm ERR! type non_object_property_load
        npm ERR!
        npm ERR! Additional logging details can be found in:
        npm ERR!     /opt/mydemo/tmp/bundle/programs/server/npm-debug.log
        npm ERR! not ok code 0
        -----------------------------------STDOUT-------------------------------
----
         > ./bcrypt: npm install due to binary npm modules
        bindings@1.0.0 node_modules/bindings

        nodeunit@0.9.1 node_modules/nodeunit
        └── tap@0.7.1 (buffer-equal@0.0.1, inherits@2.0.1, slide@1.1.6, deep-equ
al@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, glob@4.5.3, ru
nforcover@0.0.2)
        make: Entering directory `/opt/mydemo/tmp/bundle/programs/server/npm/np
m-bcrypt/node_modules/bcrypt/build'
          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
          SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
          COPY Release/bcrypt_lib.node
        make: Leaving directory `/opt/mydemo/tmp/bundle/programs/server/npm/npm
-bcrypt/node_modules/bcrypt/build'
        ------------------------------------------------------------------------
----

```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink /usr/bin/node
5 error TypeError: Cannot read property 'scripts' of null
5 error     at gypfile (/opt/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:148:29)
5 error     at /opt/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:120:33
5 error     at Array.forEach (native)
5 error     at extras (/opt/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:119:21)
5 error     at parseJson (/opt/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:87:17)
5 error     at /opt/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:59:33
5 error     at evalmachine.<anonymous>:272:14
5 error     at /opt/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
5 error     at Object.oncomplete (evalmachine.<anonymous>:108:15)
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Linux 3.13.0-57-generic
8 error command "/usr/bin/node" "/usr/bin/npm" "install"
9 error cwd /opt/mydemo/tmp/bundle/programs/server
10 error node -v v0.10.36
11 error npm -v 1.4.28
12 error type non_object_property_load
13 verbose exit [ 1, true ]
```

Any help is greatly appreciated.

**Comment by elie222** [comment]
there's a problem with mup 0.11.1

revert back to 0.11.0 and it'll work:
`sudo npm install mup@0.11.0 -g`
