### ISSUE TITLE
Meteor requires Node v0.10.26 or later

### ISSUE THREAD

**Issue by ericwikman** [arunoda/meteor-up-legacy#58]
I just setup a brand new Ubuntu 14.04 server, and am using Meteor 0.8.1.2 and tried to deploy by way of MUP, and the process fails, "invoking deployment process: FAILED" and when I went to the log file /var/log/upstart/appname.log I found that it was full of the message "Meteor requires Node v0.10.26 or later". I upgraded Node by way of "sudo npm install n -g" "sudo n stable" and rebooted the server and now MUP works. So I think you need to update to Node v0.10.26 or newer (I went with 0.10.28).

**Comment by arunoda** [comment]
BTW: You can set your own Node Version:
https://github.com/arunoda/meteor-up#example-file

Yeah! I should update the default version. Thanks.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by arunoda** [comment]
Yep. Add the nodeVersion to the mup config and setup again.

On Wednesday, May 21, 2014, Sacha Greif notifications@github.com wrote:

> Sure:
> 
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 8 time
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 9 time
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 10 time
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 11 time
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 12 time
> Meteor requires Node v0.10.26 or later.
> error: Forever detected script exited with code: 1
> error: Forever restarting script for 13 time
> 
> module.js:340
>     throw err;
>           ^
> Error: Cannot find module '/opt/meteor/app/main.js'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
>     at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:20:27)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
> error: Forever detected script exited with code: 8
> Warning: Native modules not compiled.  XOR performance will be degraded.
> Warning: Native modules not compiled.  UTF-8 validation disabled.
> SYSLOG: 0 users(0 new), 0.3398 loadavg, 64 RAM
> LISTENING
> 
> > > stepping down to gid: meteoruser
> > > stepping down to uid: meteoruser
> > > APM has completed intrumenting the app!
> > > SYSLOG: 67 users(67 new), 0.5527 loadavg, 86 RAM
> > > SYSLOG: 80 users(13 new), 0.5884 loadavg, 105 RAM
> > > SYSLOG: 143 users(63 new), 0.5415 loadavg, 115 RAM
> > > SYSLOG: 173 users(30 new), 0.5781 loadavg, 139 RAM
> > > SYSLOG: 180 users(7 new), 0.5317 loadavg, 148 RAM
> 
> Looks like it might be the Node version problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/58#issuecomment-43727964
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by kainlite** [comment]
Meteor 0.8.2 requires node 0.10.28, maybe a new default would be useful

**Comment by arunoda** [comment]
already added. Please update mup via npm.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
