### ISSUE TITLE
Deployment fail (meteor -up to Ubuntu 14.04 Digital ocean)

### ISSUE THREAD

**Issue by joyobject** [arunoda/meteor-up-legacy#618]
> Started TaskList: Deploy app 'simapleCMS' (linux)
> [104.131.53.116] - Uploading bundle
> [104.131.53.116] - Uploading bundle: SUCCESS
> [104.131.53.116] - Setting up Environment Variables
> [104.131.53.116] - Setting up Environment Variables: SUCCESS
> [104.131.53.116] - Invoking deployment process
> [104.131.53.116] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ldProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/simapleCMS/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
child_process: customFds option is deprecated, use stdio instead.
../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tls == thread_id) {
   ^
bash: line 127: wait-for-mongo: command not found
-----------------------------------STDOUT-----------------------------------
ase/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory `/opt/simapleCMS/tmp/bundle/programs/server/node_modules/fibers/build'
Installed in `/opt/simapleCMS/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
```

**Comment by semikolon** [comment]
Yup, getting this as well!

**Comment by louwers** [comment]
It works brilliantly for me (same host, same OS)!
Let the script install Node and the rest via `mup setup`.

**Comment by katopz** [comment]
Perfectly fine here https://medium.com/@katopz/digital-ocean-meteor-bec33e75522d

**Comment by vinamelody** [comment]
I'm getting this error too...
Digging some old thread from google says
- increase deployCheckWaitTime to 120, done but no effect
