### ISSUE TITLE
Can not deploy to another server, always

### ISSUE THREAD

**Issue by harlyluyar** [arunoda/meteor-up-legacy#628]
Hi, 

I was able to deploy to server-1.
Later I want to deploy to another server, server-2, and changed the mup.json file accordingly, (ip, etc).
It failed in mup deploy:

[52.8.0.76] - Uploading bundle
[52.8.0.76] - Uploading bundle: SUCCESS
[52.8.0.76] - Setting up Environment Variables
[52.8.0.76] - Setting up Environment Variables: SUCCESS
[52.8.0.76] - Invoking deployment process
[52.8.0.76] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
mver/-/semver-4.1.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
npm http 304 https://registry.npmjs.org/chalk/0.5.1
npm http 200 https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
npm http GET https://registry.npmjs.org/type-of
npm http 304 https://registry.npmjs.org/type-of
npm http GET https://registry.npmjs.org/type-of/-/type-of-2.0.1.tgz
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
npm http 200 https://registry.npmjs.org/type-of/-/type-of-2.0.1.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
eam@0.0.4, caseless@0.11.0, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, bl@1.0.0, combined-stream@1.0.5, form-data@1.0.0-rc3, qs@4.0.0, node-uuid@1.4.3, mime-types@2.1.5, http-signature@0.11.0, hawk@3.1.0, har-validator@1.8.0, tough-cookie@2.0.0)

integra@0.1.8 node_modules/integra
├── mkdirp@0.5.1 (minimist@0.0.8)
├── escodegen@1.1.0 (estraverse@1.5.1, esutils@1.0.0, source-map@0.1.43)
├── esprima@1.0.4
└── handlebars@2.0.0-alpha.1 (optimist@0.3.7, uglify-js@2.3.6)

bson@0.2.22 node_modules/bson
└── nan@1.8.4

markdown@0.3.1 node_modules/markdown
 > ./bcrypt: npm install due to binary npm modules
bindings@1.0.0 node_modules/bindings

nodeunit@0.9.1 node_modules/nodeunit
└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, glob@4.5.3, runforcover@0.0.2)

> fibers@1.0.5 install /opt/Ucar/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js
```

What should I do for this?

Looking forward to hearing some answers

Thanks

**Comment by MasterJames** [comment]
I found this info which might help...
http://plaidzooks.tumblr.com/post/36894116867/using-nodejs-on-debianubuntu-systems
seems it's called "nodejs" and not "node"? I'd guess a link would do it.
Sounds like it might be a different instance your server2 is trying to deploy to then server1?

**Comment by harlyluyar** [comment]
Thanks Master. I installed nodejs-legacy, and the node error disappear.
But new error showed up:

"
- Setting up Environment Variables: SUCCESS
- Invoking deployment process
  x Invoking deployment process: FAILED
  
  -----------------------------------STDERR-----------------------------------
  pm http 304 https://registry.npmjs.org/escape-string-regexp
  npm http 304 https://registry.npmjs.org/ansi-styles
  npm http 304 https://registry.npmjs.org/type-of
  npm http GET https://registry.npmjs.org/ansi-regex
  npm http GET https://registry.npmjs.org/ansi-regex
  npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
  npm http 304 https://registry.npmjs.org/ansi-regex
  npm http 304 https://registry.npmjs.org/ansi-regex
  npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
  npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
  npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
  js-bson: Failed to load c++ bson extension, using pure JS version
  
  /usr/local/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
      throw err;
            ^
  Error: TIMEOUTED_WAIT_FOR_MONGO
      at null._onTimeout (/usr/local/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
      at Timer.listOnTimeout [as ontimeout](timers.js:110:15)
  -----------------------------------STDOUT-----------------------------------
  .1:27017]
  wait-for-mongo: failed to connect to [127.0.0.1:27017]
  "

**Comment by MasterJames** [comment]
Still it seems something is different from server1's image then 2's ?! It sounds like an incompatible version somewhere.
Did you try extending this mupx setting
"deployCheckWaitTime": 15
Upto maybe 120 even?

**Comment by harlyluyar** [comment]
Thanks, Master. I am using mup, not mupx.
Do I need to migrate to mupx?

I am using waitTime = 15. Will try 120.

**Comment by harlyluyar** [comment]
Master, it would be great if there exist some example of using meter-up in a few well known servers, like aws, digital-ocean, etc, so that the users just need to follow the instruction, not need to repeat & struggle the same errors.

**Comment by MasterJames** [comment]
There are a few tuts/examples out there but this
https://www.npmjs.com/package/mupx
Should provide enough if follow closely, and stick to supported versions migration etc.

Meteor's Galaxy is only available to big companies for now. I suspect this is somewhat tied to AWS's EFS also in private beta.
It will get easier in time but the more you know underneath the hood the better. For now the advantage is to those that perserver and prevail.

Yes it seems mupx is the better route but none of it is official safe for production I don't think because we are missing a few things from Mongo like syncing via oplogs and larger data size limits or something like that too apparently. 
I suppose it's a topic for another thread but if anyone can add to that please enlighten us.
I'm sure it's excellent for many projects.
