### ISSUE TITLE
Error: All configured authentication methods failed (SOLVED)

### ISSUE THREAD

**Issue by maxnathaniel** [arunoda/meteor-up-legacy#632]
Hi,

**_SOLUTION**_ - Increased deployCheckWaitTime from 15 to 60

I followed this set of instructions - http://meteortips.com/deployment-tutorial/digitalocean-part-1/

I followed everything to a Tee except that I used mupx instead of mup as recommended by the good folks here.

I configured the settings and performed -

```
mupx setup
```

But it threw the following error - 

```
[IP ADDRESS] - Installing Docker
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: All configured authentication methods failed
    at tryNextAuth     (C:\Users\user\AppData\Roaming\npm\node_modules\mupx\node_modules\nodemiral\node_modul    es\ssh2\lib\cli
ent.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE     (C:\Users\user\AppData\Roaming\npm\node_modules\mupx\node_modules\nodemiral\node_mo
dules\ssh2\lib\client.js:469:5)
    at SSH2Stream.emit (events.js:110:17)
    at parsePacket     (C:\Users\user\AppData\Roaming\npm\node_modules\mupx\node_modules\nodemiral\node_modul    es\ssh2\node_mo
dules\ssh2-streams\lib\ssh.js:3649:10)
    at SSH2Stream._transform     (C:\Users\user\AppData\Roaming\npm\node_modules\mupx\node_modules\nodemiral\node_modul    es\ss
h2\node_modules\ssh2-streams\lib\ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read     (C:\Users\user\AppData\Roaming\npm\node_modules\mupx\node_modules\nodemiral\node_modul    es\ssh2\no
de_modules\ssh2-streams\lib\ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

mup.json file

```
{
  // Server authentication info
  "servers": [
    {
      "host": "IP Address",
      "username": "root",
      //"password": "password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      "pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
     // "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.36",
  "setupPhantom": true,

  // Application name (no spaces).
  "appName": "atommprojects",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": ".",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://IP ADDRESS"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

**Comment by MasterJames** [comment]
It says authentication error. Maybe try it with a password and no pem file first?

**Comment by maxnathaniel** [comment]
Hi,

I tried it with password, and I was able to perform

```
mupx setup
```

But when I performed 

```
mupx deploy
```

It threw another error 

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : C:\Users\user\Desktop\max\JavaScript\property\propertyapp
Using buildOptions : {}

Started TaskList: Deploy app 'atommprojects' (linux)
[128.199.239.49] - Uploading bundle
[128.199.239.49] - Uploading bundle: SUCCESS
[128.199.239.49] - Sending environment variables
[128.199.239.49] - Sending environment variables: SUCCESS
[128.199.239.49] - Initializing start script
[128.199.239.49] - Initializing start script: SUCCESS
[128.199.239.49] - Invoking deployment process
[128.199.239.49] x Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
        config/start.sh: line 11: docker: command not found
        config/start.sh: line 14: docker: command not found
        config/start.sh: line 18: docker: command not found
        config/start.sh: line 22: docker: command not found
        -----------------------------------STDOUT-----------------------------------
        ----------------------------------------------------------------------------
```

**Comment by maxnathaniel** [comment]
I installed docker on my Ubuntu on DO.

But when I did a deploy, it threw another error

```
[128.199.134.246] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        ceived % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (56) Recv failure: Connection reset by peer
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (56) Recv failure: Connection reset by peer
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data

        > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
        > node ./build.js

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------
```

**Comment by maxnathaniel** [comment]
I also just tried installing npm on my Ubuntu.

Another error. 

```
[128.199.134.246] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        : 'thread_id' may be used uninitialized in this function [-Wmaybe-uninitialized]
          CC(target) Release/obj.target/fibers/src/libcoro/coro.o
          SOLINK_MODULE(target) Release/obj.target/fibers.node
          SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
          COPY Release/fibers.node
        make: Leaving directory `/bundle/bundle/programs/server/node_modules/fibers/build'
        Installed in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
        underscore@1.5.2 node_modules/underscore

        semver@4.1.0 node_modules/semver

        chalk@0.5.1 node_modules/chalk
        ├── ansi-styles@1.1.0
        ├── escape-string-regexp@1.0.3
        ├── supports-color@0.2.0
        ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
        └── has-ansi@0.1.0 (ansi-regex@0.2.1)

        eachline@2.3.3 node_modules/eachline
        └── type-of@2.0.1

        source-map-support@0.2.8 node_modules/source-map-support
        └── source-map@0.1.32 (amdefine@0.1.0)

        fibers@1.0.5 node_modules/fibers
        => Starting meteor app on port:80

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------
```

**Comment by maxnathaniel** [comment]
I changed deployCheckWaitTime from 15 to 60, it shows a success message.

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : C:\Users\user\Desktop\max\JavaScript\property\propertyapp
Using buildOptions : {}

Started TaskList: Deploy app 'atommprojects' (linux)
[128.199.134.246] - Uploading bundle
[128.199.134.246] - Uploading bundle: SUCCESS
[128.199.134.246] - Sending environment variables
[128.199.134.246] - Sending environment variables: SUCCESS
[128.199.134.246] - Initializing start script
[128.199.134.246] - Initializing start script: SUCCESS
[128.199.134.246] - Invoking deployment process
[128.199.134.246] - Invoking deployment process: SUCCESS
[128.199.134.246] - Verifying deployment
[128.199.134.246] - Verifying deployment: SUCCESS
```

However, when I go over to my url, it shows webpage unavailable message.

**Comment by maxnathaniel** [comment]
Ok, i got it up and running!

**Comment by MasterJames** [comment]
Awesome Max well done. Maybe close any still open tickets (with any extra useful solutions not already mentioned thanks).

**Comment by maxnathaniel** [comment]
**_SOLUTION**_ - Increased deployCheckWaitTime from 15 to 60
