### ISSUE TITLE
connect ETIMEDOUT error, when doing mup setup/deploy

### ISSUE THREAD

**Issue by jtalloen** [arunoda/meteor-up-legacy#643]
I tried to deploy my website using Meteor Up.  I configured my mup.json file as follows:

{
  // Server authentication info
  "servers": [
    {
      "host": "ec2-52-24-95-147.us-west-2.compute.amazonaws.com",
      "username": "ubuntu",
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "C:/Users/Joachim/meteor.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.35",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "Homepage",

  // Location of app (local directory)
  "app": "C:/website",

  // Configure environment
  "env": {
    "ROOT_URL": "ec2-52-24-95-147.us-west-2.compute.amazonaws.com",
    "PORT": 80,
    "METEOR_ENV": "production"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

the error that it is displaying is the following:

throw er; // Unhandled 'error' event
 ^

Error: connect ETIMEDOUT {public IP from AWS}:22
    at Object.exports._errnoExcpetion (util.js:837:11)
    at exports._excpetionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1060:14)

does anyone have any idea what is going on?

**Comment by Xample** [comment]
Same kind of problem here, this appeared overnight, I suspect the package server to be unavailable for some reason. I am not using mup for this project but the error I get is:

```
=> Errors while initializing project:

While downloading agershun:alasql@0.2.0...:
error: connect ETIMEDOUT

While downloading alanning:roles@1.2.13...:
error: connect ETIMEDOUT

While downloading angular:angular@1.4.5...:
error: connect ETIMEDOUT

While downloading angularui:angular-ui-router@0.2.15...:
error: connect ETIMEDOUT

While downloading aramk:tinycolor@1.1.0_1...:
error: connect ETIMEDOUT
```

The server is not behind a firewall and has full access however using a different internet provider solved my problem, (some ip seems unreachable with my regular one) using a VPN could also have been an option (better this way than connecting from a phone / other internet provider…).

This may be related to : https://github.com/meteor/meteor/issues/2961
