### ISSUE TITLE
Connecting to remote mongo

### ISSUE THREAD

**Issue by ccorcos** [arunoda/meteor-up-legacy#650]
I want to connect to my remote mongo database locally but its proving challenging.

I sshed into my server and went into the mongo shell

```
$ mongo --authenticationDatabase admin
```

I created an admin user

```
> db.createUser({user:'USERNAME', pwd:'PASSWORD', roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]})
```

I edited `/etc/mongod.config` like this:

```
dbpath=/var/lib/mongodb
logpath=/var/log/mongodb/mongod.log
logappend=true
port = PORT
bind_ip = IP_ADDRESS
auth = true
httpinterface = true
```

Now I can enter the mongo shell from anywhere like this:

```
mongo --host IP_ADDRESS --port PORT -u USERNAME -p PASSWORD
```

I can do it locally and on the server.

Now I run meteor connecting to the server:

```
$ MONGO_URL=mongodb://MONGO:PASSWORD@IP_ADDRESS:PORT/ meteor 
```

When I go into the shell

```
$ meteor shell

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

> new Mongo.Collection('tmp')
MongoError: auth failed
    at Object.Future.wait (/Users/chet/.meteor/packages/meteor-tool/.1.1.4.1uijw63++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at repl:1:2
    at /Users/chet/Code/meteor/empty/.meteor/local/build/programs/server/shell-server.js:243:23
    - - - - -
    at Object.toError (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1194:31
    at /Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
```

Lame, right? No idea whats going on. Any ideas?

**Comment by ccorcos** [comment]
I figured it out. I hope someone finds this useful!

The key is 

```
$ mongo APP_NAME
> db.createUser({user:'USERNAME', pwd:'PASSWORD', roles: [ { role: "dbOwner", db: "APP_NAME" } ]})
```

**Comment by joadr** [comment]
Awesome, this worked for me, just had to add that you must add the mongo url in the "MONGO_URL" enviroment variable otherwise you are going to get errors relating to authentication. Also in the mongodb configuration in bind_ip, you must add the ip address of the computer that is connecting to the database, for allowing any ip just set it to 0.0.0.0 which is not recommended for security issues.

**Comment by avishaan** [comment]
:+1:
