### ISSUE TITLE
mupx - failed verification doesn't roll back previous version

### ISSUE THREAD

**Issue by markshust** [arunoda/meteor-up-legacy#652]
Given the following:

```
Marks-MacBook-Air:app markshust$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /Users/markshust/Sites/app
Using buildOptions : {}

Started TaskList: Deploy app 'app' (linux)
[104.197.81.124] - Uploading bundle
[104.197.81.124] - Uploading bundle: SUCCESS
[104.197.81.124] - Sending environment variables
[104.197.81.124] - Sending environment variables: SUCCESS
[104.197.81.124] - Initializing start script
[104.197.81.124] - Initializing start script: SUCCESS
[104.197.81.124] - Invoking deployment process
[104.197.81.124] - Invoking deployment process: SUCCESS
[104.197.81.124] - Verifying deployment
[104.197.81.124] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    eor app on port:80

    /bundle/bundle/programs/server/node_modules/fibers/future.js:245
                            throw(ex);
                                  ^
    TypeError: Cannot read property 'MAIL_URL' of undefined
        at app/server/startup/mail.js:2:49
        at /bundle/bundle/programs/server/boot.js:229:5
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80

    /bundle/bundle/programs/server/node_modules/fibers/future.js:245
                            throw(ex);
                                  ^
    TypeError: Cannot read property 'MAIL_URL' of undefined
        at app/server/startup/mail.js:2:49
        at /bundle/bundle/programs/server/boot.js:229:5
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

As you can see, I forgot to specify the settings.json file. If I specify, all is ok.

However, as you can see above, an err'd out deploy should redeploy previous version of app:
`Redeploying previous version of the app`

That said, this doesn't seem to be happening, as the site is crashed on production and not rolled back.

**Comment by markshust** [comment]
This is still happening on the latest version of mupx. The `Redeploying previous version of the app` doesn't work. On a failed deploy, the previous version isn't redeployed -- the process just dies.
