### ISSUE TITLE
Digital Ocean: mup deploy fails wait-for-mongo: failed to connect

### ISSUE THREAD

**Issue by arvi** [arunoda/meteor-up-legacy#658]
Suddenly, I'm getting this error when deploying a meteor app to my digital ocean UBUNTU 14.04 droplet:

```
~/s/h/d/deploy-project ❯❯❯ DEBUG=* mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: /Users/Name/srv/http/meteor/sample


Started TaskList: Deploy app 'sample' (linux)
[128.199.190.128] - Uploading bundle
  nodemiral:sess:128.199.190.128 copy file - src: /var/folders/q6/gppg73jj40gbgpsqt3pqqnl00000gn/T/20a33746-468a-4a9a-a976-e6b9414f8658/bundle.tar.gz, dest: /opt/sample/tmp/bundle.tar.gz, vars: undefined +0ms
[128.199.190.128] - Uploading bundle: SUCCESS
[128.199.190.128] - Setting up Environment Variables
  nodemiral:sess:128.199.190.128 copy file - src: /usr/local/lib/node_modules/mup/templates/linux/env.sh, dest: /opt/sample/config/env.sh, vars: {"env":{"ROOT_URL":"http://sample.arvi.io","PORT":3010,"METEOR_SETTINGS":"{\"public\":{}}","CLUSTER_ENDPOINT_URL":"http://128.199.190.128:3010"},"appName":"sample"} +3.4m
[128.199.190.128] - Setting up Environment Variables: SUCCESS
[128.199.190.128] - Invoking deployment process
[128.199.190.128] x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    ules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-52-generic
    gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /opt/sample/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data

    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    -----------------------------------STDOUT-----------------------------------
    .1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    ----------------------------------------------------------------------------
```

**Comment by MasterJames** [comment]
It seems 
https://www.npmjs.com/package/wait-for-mongo
is failing to find mongo.
Is it possible to login via SSH and see if mongo is running?
via typing this in the app path or similar
    meteor mongo
another way...
http://docs.mongodb.org/master/tutorial/getting-started-with-the-mongo-shell/

**Comment by Lowellr** [comment]
I am also having a problem deploying to a digital ocean UBUNTU 14.04 droplet: ( I've never been successful, so I might be missing something simple. I did login via SSH and mongo is not running. Any help would be appreciated. (I'm just learning).

## Meteor Up: Production Quality Meteor Deployments

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: .

Started TaskList: Deploy app 'simple-todos' (linux)
[104.131.129.37] - Uploading bundle
[104.131.129.37] - Uploading bundle: SUCCESS
[104.131.129.37] - Setting up Environment Variables
[104.131.129.37] - Setting up Environment Variables: SUCCESS
[104.131.129.37] - Invoking deployment process
[104.131.129.37] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
stop: Unknown instance: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    de ./build.js

```
`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
ansi-regex@0.2.1 node_modules/ansi-regex

ansi-styles@1.1.0 node_modules/ansi-styles

escape-string-regexp@1.0.3 node_modules/escape-string-regexp

chalk@0.5.1 node_modules/chalk

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

has-ansi@0.1.0 node_modules/has-ansi

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

meteor-promise@0.4.8 node_modules/meteor-promise

underscore@1.5.2 node_modules/underscore

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
simple-todos start/running, process 11244
Waiting for 60 seconds while app is booting up
Checking is app booted or not?
----------------------------------------------------------------------------
```

**Comment by MasterJames** [comment]
Try this long wait time in your settings.

```
"deployCheckWaitTime": 120
```

If people have problems with mup it's often suggested to try the development branch mupx version and see if that helps, otherwise of either of those ideas don't help please post your settings files.

**Comment by katopz** [comment]
@Lowellr In case you never success before, please try rebuild your droplet from scratch and follow my guide precisely it should work https://medium.com/@katopz/digital-ocean-meteor-bec33e75522d
