### ISSUE TITLE
Meteor Up deploy failing: "couldn't connect to host"

### ISSUE THREAD

**Issue by SachaG** [arunoda/meteor-up-legacy#66]
Just ran into a strange error that's happening on EC2 but not on my Digital Ocean staging server:

https://gist.github.com/SachaG/c340ce5fbe14ee5d3291

Seems like the server isn't able to get the Fibers package? Any idea what could be causing it?

**Comment by arunoda** [comment]
Hey,

Can you check the server logs with

mup logs -n 400

On Wednesday, May 21, 2014, Sacha Greif notifications@github.com wrote:

> Just ran into a strange error that's happening on EC2 but not on my
> Digital Ocean staging server:
> 
> https://gist.github.com/SachaG/c340ce5fbe14ee5d3291
> 
> Seems like the server isn't able to get the Fibers package? Any idea what
> could be causing it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/66
> .

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by SachaG** [comment]
Sure:

```
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 8 time
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 9 time
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 10 time
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 11 time
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 12 time
Meteor requires Node v0.10.26 or later.
error: Forever detected script exited with code: 1
error: Forever restarting script for 13 time

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/meteor/app/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
    at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:20:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
SYSLOG: 0 users(0 new), 0.3398 loadavg, 64 RAM
LISTENING
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
APM has completed intrumenting the app!
SYSLOG: 67 users(67 new), 0.5527 loadavg, 86 RAM
SYSLOG: 80 users(13 new), 0.5884 loadavg, 105 RAM
SYSLOG: 143 users(63 new), 0.5415 loadavg, 115 RAM
SYSLOG: 173 users(30 new), 0.5781 loadavg, 139 RAM
SYSLOG: 180 users(7 new), 0.5317 loadavg, 148 RAM
```

Looks like it might be the Node version problem?

**Comment by SachaG** [comment]
Perfect, it worked :)
