### ISSUE TITLE
mup setup failing at Node install

### ISSUE THREAD

**Issue by JustinWestphal** [arunoda/meteor-up-legacy#675]
I can't make heads or tails of the errors it's returning. This is everything that happens after running mup setup. Mup init went fine, and my mup.json file has all the settings filled in (should be) correctly.

``` console
Justins-MacBook-Air-3:lasso justinwestphal$ mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[52.88.45.124] - Installing Node.js

/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:144
      var end = str.indexOf(close, i)
                    ^
TypeError: Object #!/bin/bash

# Remove the lock
set +e
sudo rm /var/lib/dpkg/lock > /dev/null
sudo rm /var/cache/apt/archives/lock > /dev/null
sudo dpkg --configure -a
set -e

# Required to update system
sudo apt-get update

# Install Node.js - either nodeVersion or which works with latest Meteor release
<% if (nodeVersion) { %>
  NODE_VERSION=<%= nodeVersion %>
<% } else {%>
  NODE_VERSION=0.10.36
<% } %>

ARCH=$(python -c 'import platform; print platform.architecture()[0]')
if [[ ${ARCH} == '64bit' ]]; then
  NODE_ARCH=x64
else
  NODE_ARCH=x86
fi

sudo apt-get -y install build-essential libssl-dev git curl

NODE_DIST=node-v${NODE_VERSION}-linux-${NODE_ARCH}

cd /tmp
wget http://nodejs.org/dist/v${NODE_VERSION}/${NODE_DIST}.tar.gz
tar xvzf ${NODE_DIST}.tar.gz
sudo rm -rf /opt/nodejs
sudo mv ${NODE_DIST} /opt/nodejs

sudo ln -sf /opt/nodejs/bin/node /usr/bin/node
sudo ln -sf /opt/nodejs/bin/npm /usr/bin/npm
 has no method 'indexOf'
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:144:21)
    at Object.exports.compile (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:224:15)
    at Session._applyTemplate (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:181:27)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

**Comment by JustinWestphal** [comment]
Solved!
- First I completely uninstalled and reinstalled node on my computer with help from [this article](http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x).
- Then, I reinstalled MUP, as I made sure to delete any MUP files I found while uninstalling node.
- I think this was part of the problem: The default Node version in the MUP settings is 0.10.36. When I ran `node -v` in my console, it showed 4.1.1. I made sure to update that value.
- Everything is running peachy now!
