### ISSUE TITLE
[mupx] Meteor iOS platform build errors

### ISSUE THREAD

**Issue by thomasf1** [arunoda/meteor-up-legacy#676]
After upgrading to the latest mupx and Meteor 1.2, there are some build errors with other platforms added to the project... (iOS in this case)

Shouldn´t just the web platform be build for mupx?

The build error is a bug in the iOS build that relates to git/npm not handling a Facebook modules symlinks well...

We usually fix that afterwards...

```
=> Errors executing Cordova commands:

   While building Cordova app for platform iOS:
   Error:
   /Users/tom/Dev/rentkit/.meteor/local/cordova-build/platforms/ios/cordova/build:
   Command failed with exit code 2 Error output:
   ** BUILD FAILED **


   The following build commands failed:
   CompileC
   build/RentKit.build/Release-iphonesimulator/RentKit.build/Objects-normal/i386/FacebookConnectPlugin.o
   RentKit/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m
   normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
   (1 failure)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/tom/Dev/rentkit/.meteor/local/cordova-build/platforms/ios/cordova/build-release.xcconfig,-project,RentKit.xcodeproj,ARCHS=i386,-target,RentKit,-configuration,Release,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/tom/Dev/rentkit/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/tom/Dev/rentkit/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.whenDone
   (/Users/tom/.meteor/packages/meteor-tool/.1.1.8.55v4q6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)
```

**Comment by sathishc** [comment]
Did you find any workaround / solutions? I get this error on a normal meteor build with the ios platform added.

**Comment by daisythephoenix** [comment]
Does anyone have a solution to this? I'm running into the same problem.

**Comment by MasterJames** [comment]
Don't you just temporily remove ios and android and then deploy (and add them back later)? https://github.com/arunoda/meteor-up/issues/629

**Comment by MasterJames** [comment]
Anyway a new additional commit to my PR
https://github.com/arunoda/meteor-up/pull/736
now fixes/addresses this problem by overwriting .meteor/platforms with 'server' and 'browser' only if no mobileSettings is found in the conf's buildOptions.

@arunoda Please consider or provide feedback on the PR in general (or take what you will), thanks.

**Comment by daisythephoenix** [comment]
Thanks @MasterJames . Yes, removing the ios solved the problem. (If you receive notification of my previous comment, I apologizing for mixing up hosting services. There are so many things going on all at the same time!)
