### ISSUE TITLE
errors with npm modules containing binaries

### ISSUE THREAD

**Issue by Tarang** [arunoda/meteor-up-legacy#7]
How does meteor up handle npm modules? Does it automatically install them like `meteor` on its own does or upload the project with the `.npm` directory?

I ran into this

```
[app]     at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/ursa/main/node_modules/ursa/lib/ursa.js:18:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

The npm module referenced is ursa from https://github.com/Obvious/ursa

If I run the app ordinarily it works. It could be because the file referenced on that line is a binary node file

I ran `npm install ursa` in `/opt/meteor/app/programs/server/npm/ursa/main` on the server then ran `mup deploy` on my local machine to fix it

I also had a new `npm-debug.log` file in the project which had this at the end:

```
38 info install ursa@0.8.0 into /usr/local/lib
39 info installOne ursa@0.8.0
40 verbose from cache /Users/tarang/.npm/ursa/0.8.0/package/package.json
41 info /usr/local/lib/node_modules/ursa unbuild
42 verbose read json /usr/local/lib/node_modules/ursa/package.json
43 verbose tar unpack /Users/tarang/.npm/ursa/0.8.0/package.tgz
44 silly lockFile ac5c3594--usr-local-lib-node-modules-ursa tar:///usr/local/lib/node_modules/ursa
45 verbose lock tar:///usr/local/lib/node_modules/ursa /Users/tarang/.npm/ac5c3594--usr-local-lib-node-modules-ursa.lock
46 silly lockFile c54ede5e-arang-npm-ursa-0-8-0-package-tgz tar:///Users/tarang/.npm/ursa/0.8.0/package.tgz
47 verbose lock tar:///Users/tarang/.npm/ursa/0.8.0/package.tgz /Users/tarang/.npm/c54ede5e-arang-npm-ursa-0-8-0-package-tgz.lock
48 silly gunzTarPerm modes [ '755', '644' ]
49 error Error: EACCES, mkdir '/usr/local/lib/node_modules/ursa'
49 error  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/ursa']
49 error   errno: 3,
49 error   code: 'EACCES',
49 error   path: '/usr/local/lib/node_modules/ursa',
49 error   fstream_type: 'Directory',
49 error   fstream_path: '/usr/local/lib/node_modules/ursa',
49 error   fstream_class: 'DirWriter',
49 error   fstream_stack:
49 error    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
49 error      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
49 error      'Object.oncomplete (fs.js:107:15)' ] }
50 error Please try running this command again as root/Administrator.
51 error System Darwin 13.0.0
52 error command "node" "/usr/local/bin/npm" "install" "-g" "ursa"
53 error cwd /Users/tarang/Desktop/Zebra/zebra-core
54 error node -v v0.10.11
55 error npm -v 1.2.30
56 error path /usr/local/lib/node_modules/ursa
57 error fstream_path /usr/local/lib/node_modules/ursa
58 error fstream_type Directory
59 error fstream_class DirWriter
60 error code EACCES
61 error errno 3
62 error stack Error: EACCES, mkdir '/usr/local/lib/node_modules/ursa'
63 error fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
63 error fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
63 error fstream_stack Object.oncomplete (fs.js:107:15)
64 verbose exit [ 3, true ]
```

Not too sure why it wanted to install it globally though.

**Comment by arunoda** [comment]
When does this happens, in the server or while bundling. If this is
bundling meteor-up does meteor bundle.

May be this is because of the c++ addon. Which is not working at the moment
due to the use of bundle.

I've some plans to incorporate add some helper to re-install binary modules
at the server, but not so soon.

On Wed, Dec 18, 2013 at 1:57 PM, Tarang Patel notifications@github.comwrote:

> How does meteor up handle npm modules? Does it automatically install them
> like meteor on its own does or upload the project with the .npm directory?
> 
> I ran into this
> 
> [app]     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/opt/meteor/app/programs/server/npm/ursa/main/node_modules/ursa/lib/ursa.js:18:18)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
> 
> The npm module referenced is ursa from https://github.com/Obvious/ursa
> 
> If I run the app ordinarily it works. It could be because the file
> referenced on that line is a binary node file
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/7
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Tarang** [comment]
The project wont deploy it gives back STDERR.

If I check the logs with `mup logs` the output comes back as what is above.

Its likely because of the C++ addon. Maybe a good idea would be to use demeteorizer instead of `meteor bundle` and then run `npm install` to install the modules on the server side it might be easier than implementing it separately just for binary modules

**Comment by arunoda** [comment]
Yes. I got it.
Oh! demeteorizer is a bad idea. With that, we can't have diff modules for
different packages. It's better to do the bundle locally, as possibly as we
can. We should not depend on the npm for the deploy time.

Anyway, something working than nothing is better. I'll try to work on this,
but I'm too busy with a project.

On Wed, Dec 18, 2013 at 3:00 PM, Tarang Patel notifications@github.comwrote:

> The project wont deploy it gives back STDERR.
> 
> If I check the logs with mup logs the output comes back as what is above.
> 
> Its likely because of the C++ addon. Maybe a good idea would be to use
> demeteorizer and then run npm update to install the modules on the server
> side?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/7#issuecomment-30827636
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
