### ISSUE TITLE
MUPX - Failed to connect to local MongoDB on `localhost:27017`

### ISSUE THREAD

**Issue by tomitrescak** [arunoda/meteor-up-legacy#712]
Hi, I'm not sure what I am doing wrong.
The deployment keep failing on connection to MongoDB (see below).

In my setup, I am running Mongo on the server where application is being deployed.
Mongo is installed on the server, not in a docker container.
Any idea what may cause this issue?

EDIT: Mup works just fine on the same config (I am probably missing something ...)

Thanks

```
[hugo.scem.uws.edu.au] Error: failed to connect to [localhost:27017]
[hugo.scem.uws.edu.au]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
[hugo.scem.uws.edu.au]     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
[hugo.scem.uws.edu.au]     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
[hugo.scem.uws.edu.au]     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
[hugo.scem.uws.edu.au]     at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
[hugo.scem.uws.edu.au]     at new Mongo.Collection (packages/mongo/collection.js:98:1)
[hugo.scem.uws.edu.au]     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
[hugo.scem.uws.edu.au]     at new AccountsServer (accounts_server.js:16:5)
[hugo.scem.uws.edu.au]     at Package (globals_server.js:5:12)
[hugo.scem.uws.edu.au]     at /bundle/bundle/programs/server/packages/accounts-base.js:1813:4
[hugo.scem.uws.edu.au]     - - - - -
[hugo.scem.uws.edu.au]     at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
[hugo.scem.uws.edu.au]     at [object Object].emit (events.js:106:17)
[hugo.scem.uws.edu.au]     at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
[hugo.scem.uws.edu.au]     at [object Object].emit (events.js:98:17)
[hugo.scem.uws.edu.au]     at Socket.<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
[hugo.scem.uws.edu.au]     at Socket.emit (events.js:95:17)
[hugo.scem.uws.edu.au]     at net.js:441:14
[hugo.scem.uws.edu.au]     at process._tickCallback (node.js:448:13)
```

Here si my config

```
{
  // Server authentication info
  "servers": [
    {
      "host": "xxx",
      "username": "tomas"
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,

  // Application name (no spaces).
  "appName": "PlayTest",

  // Location of app (local directory)
  "app": "~/Documents/Programming/GitHub/Play",

  // Configure environment
  "env": {
    "PORT": 3010,
    "ROOT_URL": "http://xxx",
    "MONGO_URL": "mongodb://localhost:27017/PlayTest",
    "MAIL_URL": "smtp://xxx:25/",
    "UPLOAD_DIR": "/opt/PlayTest/Uploads"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading.
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

**Comment by MasterJames** [comment]
Is it possible the docker version running meteor is disconnected from the mongod running outside it?
I think I'm saying localhost (aka Mongo) maybe isolated and not reachable in a container that meteor is running.
I'm thinking if you check the connection to
"MONGO_URL": "mongodb://localhost:27017/PlayTest",
from inside the container that runs meteor, that it's not reachable.
Maybe setting this value above to the IP where mongo is reachable would make the difference.
There might be a need to make that connection/route possible, or run a Proxy.

Also noting:
https://docs.docker.com/userguide/dockerlinks/

**Comment by DiesIrae** [comment]
Same thing here! I resolved it by pointing it to the public IP of the machine, and configuring my firewall to authorize only itself on the public IP for the mongo port, but it doesn't seem like good practice. :-)

**Comment by c9s** [comment]
Same here.

**Comment by agenciapolaire** [comment]
@DiesIrae Hi, i'm trying to do the same thing that you told above, but is not workig, mup is show me error, and when i disable the firewall works great, so i think that is something wrong with my ufw config, i allow my public IP, i don't know what more i need to do.

**Comment by DiesIrae** [comment]
Still no luck with last mup version, same dirty workaround.

I don't know ufw @agenciapolaire but you could look for firewall interaction problems. Docker seems to modify my iptables config.

**Comment by agenciapolaire** [comment]
@DiesIrae here works using the internal ip of docker images, so i put this ips on ufw allow and set mongo bind to 0.0.0.0 and it works, only docker ips have access to mongo.
