### ISSUE TITLE
mup setup error

### ISSUE THREAD

**Issue by dvzrd** [arunoda/meteor-up-legacy#716]
Hey,

I started getting this error as soon as I run mup setup:

```
/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:223
        throw err;
        ^

SyntaxError: Unexpected token ' ' at 1:2
{ 
 ^
File: "/Users/username/Projects/mtr-app/private/mup.json"
    at SyntaxError (native)
    at Object.parseJSON (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:732:13)
    at Object.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/json-parse-helpfulerror/index.js:10:13)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:90:28)
    at Object.load (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:220:24)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:12:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Any ideas what this could mean? Thanks!

**Comment by cupideias** [comment]
I'm getting some similar. I run `mupx init` and got this error:

```
Errors prevented startup:
While building the application:
error: Syntax error in mup.json
```

Anything I did work.

**Comment by MasterJames** [comment]
You should post your settings files here. It sounds like either a control character was typed maybe your newlines have carriage returns or something. CR vs LF?
You can also try cutting your file in repeated halfs to isolate the offending line(s). Similarly put one line/word/char at a time into a working file until you get the error and isolate the bad character.
Sometimes even notepad can help to purify or detect non Ascii chars in a text file.

**Comment by cupideias** [comment]
Thanks @MasterJames, the solution was rewriting and removing all comments, just removing comments didn't work.

**Comment by dvzrd** [comment]
Here's an example of my mup file:

```
{ 
  "servers": [ 
    { 
      "host": "1.1.1.1.1", 
      "username": "root", 
      "password": "password"
    } 
  ], 
  "setupMongo": true, 
  "setupNode": true, 
  "nodeVersion": "0.10.40", 
  "setupPhantom": true, 
  "appName": "app", 
  "app": "/Users/username/Projects/mtr-app", 
  "env": { 
    "ROOT_URL": "http://app.com"
  }, 
  "deployCheckWaitTime": 120 
}
```

**Comment by MasterJames** [comment]
I'm thinking you should be able to remove the square box characters.
I know Webstorm has a way to set the CR vs LF vs CR/LF (carrage return /r, line feed /n) per file.
