### ISSUE TITLE
mup deploy sucessful to EC2, but web page is not available 

### ISSUE THREAD

**Issue by ahmedrabie** [arunoda/meteor-up-legacy#717]
Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/committeemanager/app/programs/server/boot.js:117:17)
    at assert (packages/iron:router/lib/body_parser_server.js:1:1)
    at /opt/committeemanager/app/programs/server/packages/iron_router.js:1269:4
    at /opt/committeemanager/app/programs/server/packages/iron_router.js:1455:3
    at /opt/committeemanager/app/programs/server/boot.js:175:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/committeemanager/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/committeemanager/app/programs/server/boot.js:86:5

**Comment by MasterJames** [comment]
Others report reinstalling meteor may resolve this.

**Comment by ahmedrabie** [comment]
reinstalling meteor  from remote server ? or local ?

**Comment by MasterJames** [comment]
If you fix the local and then deploy it that should fix both. If that doesn't do it try deploying to a fresh instance if possible.

**Comment by ahmedrabie** [comment]
local is working fin   .but instance  have a problem  but  when run command meteor  on  instance  result command not found   why ?

**Comment by ahmedrabie** [comment]
and i'm already  run new instance and problem exiting

**Comment by ahmedrabie** [comment]
----------------------------------STDERR-----------------------------------
    on meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80

```
/bundle/bundle/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/bundle/bundle/programs/server/boot.js:117:17)
    at assert (packages/iron:router/lib/body_parser_server.js:1:1)
    at /bundle/bundle/programs/server/packages/iron_router.js:1269:4
    at /bundle/bundle/programs/server/packages/iron_router.js:1455:3
    at /bundle/bundle/programs/server/boot.js:175:10
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:86:5
```

**Comment by MasterJames** [comment]
You should try mupx just to see if that works better for you. Otherwise I'm wondering if your deploying to a compatible environment Ubuntu 14+?

**Comment by ahmedrabie** [comment]
yes  i am using mupx

**Comment by ahmedrabie** [comment]
compatible environment Ubuntu 14+    ? 
 node js 0.1.40 
npm  1.3.10

**Comment by ahmedrabie** [comment]
i wounder should install meteor manual  in instance or  not ?

**Comment by MasterJames** [comment]
It might help to debug but generally it should work without getting manual.
So your on AWS with a large enough instance (sometimes larger RAM is worth trying).
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html
using mupx to deploy.

Here is a discussion suggesting to reinstall.
https://github.com/iron-meteor/iron-router/issues/1113

I'm uncertain this would help or not...
meteor add meteorhacks:npm

I am also thinking just to run
npm update 

I get these currently.
node -v
v4.2.1

npm -v 
2.14.7

**Comment by ahmedrabie** [comment]
meteor add meteorhacks:npm  in local  or  instance ?

**Comment by MasterJames** [comment]
Well it's just something to try.
Again do it local because mupx deploys to instance reliably.

**Comment by ahmedrabie** [comment]
same error  
i try using following command 
1- meteor add meteorhacks:npm
2- mupx setup
3- mupx deploy

**Comment by MasterJames** [comment]
Okay thanks for trying that npm you can undo it i suppose.
Well it might reveal something more if you post you're settings files mup.json 
And the full (single run) DEBUG =\* mupx deploy logs
https://github.com/arunoda/meteor-up/blob/mupx/README.md#verbose-output

Did you try updating those versions with npm update?

**Comment by ahmedrabie** [comment]
it's working now 
to solve this ptogram you  must update meteor last veriosn and  usr mupx
