### ISSUE TITLE
multiple app on single server

### ISSUE THREAD

**Issue by berkaytheunicorn** [arunoda/meteor-up-legacy#727]
hey, Im using digital ocean Ubuntu 14.04 x64 and three meteor deployment is working fine (although I didn't deploy recently on any of them ) and forth was working fine also until I re-deploy. now no matter I do I get 

```
Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    js-bson: Failed to load c++ bson extension, using pure JS version
    stop: Unknown instance: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3034: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    .0 node_modules/ansi-styles

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    chalk@0.5.1 node_modules/chalk

    has-ansi@0.1.0 node_modules/has-ansi

    strip-ansi@0.3.0 node_modules/strip-ansi

    supports-color@0.2.0 node_modules/supports-color

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    connected
    xxxx start/running, process 8250
    Waiting for 60 seconds while app is booting up
    Checking is app booted or not?
    xxxx stop/waiting
    xxxx start/running, process 8403

```

node version 0.10.40
meteor version 1.2.0.2 
mup version 0.11.3

**Comment by berkaytheunicorn** [comment]
now after another deploy
I got this

```
Error: /opt/xxxx/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[46.101.145.104] 
[46.101.145.104]     at Module.load (module.js:356:32)[46.101.145.104] 
[46.101.145.104]     at Function.Module._load (module.js:312:12)[46.101.145.104] 
[46.101.145.104]     at Module.require (module.js:364:17)[46.101.145.104] 
[46.101.145.104]     at require (module.js:380:17)[46.101.145.104] 
[46.101.145.104]     at bindings (/opt/xxxx/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[46.101.145.104] 
[46.101.145.104]     at Object.<anonymous> (/opt/xxxx/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[46.101.145.104] 
[46.101.145.104]     at Module._compile (module.js:456:26)[46.101.145.104] 
[46.101.145.104]     at Object.Module._extensions..js (module.js:474:10)[46.101.145.104] 
[46.101.145.104]     at Module.load (module.js:356:32)[46.101.145.104] 
[46.101.145.104]     at Function.Module._load (module.js:312:12)[46.101.145.104] 
[46.101.145.104] error: Forever detected script exited with code: 8[46.101.145.104] 
[46.101.145.104] error: Script restart attempt #22[46.101.145.104] 
```

**Comment by MasterJames** [comment]
If you've updated to meteor 1.2.\* you should configure mup.json to use node 0.10.40 (assuming it's Ubuntu 14+). Otherwise maybe post your settings file.

**Comment by berkaytheunicorn** [comment]
It is actually 0.10.40 and I created new droplet on digital ocean and can able deploy there without any issue.

```
{
  "servers": [
    {
      "host": "xxxxxx",
      "username": "root",
      "pem": "~/.ssh/id_rsa"
    }
  ],
  "setupMongo": false,
  "setupNode": true,
  "nodeVersion": "0.10.40",
  "setupPhantom": false,
  "appName": "xxxx",
  "app": ".",
  "env": {
    "PORT": 30xx,
    "UPSTART_UID": "meteoruser",
    "ROOT_URL": "http://xxxxxxxx",
    "MONGO_URL":"xxxxxxxxxxxxxxx"
  },
  "deployCheckWaitTime": 120
}

```

**Comment by MasterJames** [comment]
I next would have thought to extend the wait time but 120 seems plenty.
I wondered if you're using mup or have tried mupx.
Another thing to check is that your own Mongo Deployment is connectable from the machine.
If you could SSH into the target machine and see if there's anything running there via curl etc. It could even be a firewall port issue.

**Comment by berkaytheunicorn** [comment]
actually other apps are also connect to same mongo db and some how only one time I could make this work on this server too. and I didn't mupx. Is mupx support multiple apps in same server.

**Comment by MasterJames** [comment]
When mup isn't working it's usually a little easier to try mupx then to trouble shooting mup.
With mupx the "docker host" gets a Mongo container installed during setup but it puts the database locally in /var/lib/mongodb which is linked into the Mongo container in /data/db it won't overwrite rerunning setup. When you deploy it will transfer the database itself. My point is its a bit unintuitive and important to understand in more complicated setups and perfect for what you suggested (1 DB for many meteor). 
You can add many servers in mup.json but I think they share one database currently, which can be overridden with different mongo_urls but those have to be deployed manually as far as I currently understand it. I'll try to reconfirm and report if found to function otherwise. You basically use multiple mup.json settings files to achieve multiple deployments but it takes some port and dns finessing.
Here is one example ...
https://forums.meteor.com/t/how-do-i-deploy-multiple-meteor-apps-to-the-same-digital-ocean-droplet-using-mupx-docker-and-using-multiple-domain-names/7289/4

**Comment by berkaytheunicorn** [comment]
yeah I use different ports and handle those with nginx in server side. but I don't need mongo because I use a remote db on compose. so you suggest even I don't use mongo should I install in on server?

**Comment by MasterJames** [comment]
Well using docker or even a kubernetes pod would provide better failure protection and scalability etc. But yes you can go more manual by disabling Mongo installation in mup.json and point to a database provider instance or what have you.

**Comment by berkaytheunicorn** [comment]
ok on my next project I will try to use mupx then :) just a quick question? can mupx deployment handle different versions of meteor and node in single server. I guess on some point mup doesn't handle this on every cases?

**Comment by c9s** [comment]
I forked this repo and started a new project from this basis,  the deploy script will fix the bcrypt issue automatically

You can just install the mup from here https://github.com/c9s/meteor-up
