### ISSUE TITLE
Failed to find 'ANDROID_HOME' environment variable

### ISSUE THREAD

**Issue by 55** [arunoda/meteor-up-legacy#730]
Having this error when trying to deploy using mupx.
The thing is that I am not using any buildOptions for android.

Before Meteor 1.2 update everything worked fine.

``` console
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /home/xxx
Using buildOptions : {}
=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error:
   /home/xxx/.meteor/local/cordova-build/platforms/android/cordova/build:
   Command failed with exit code 2 Error output:
   [Error: Failed to find 'ANDROID_HOME' environment variable. Try setting
   setting it manually.
   Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to
   include path to valid SDK directory.]
   at ChildProcess.whenDone
   (/home/.meteor/packages/meteor-tool/.1.1.9.hz7xuf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Process.ChildProcess._handle.onexit (child_process.js:833:5)


=> Build Error. Check the logs printed above.

```

**Comment by 55** [comment]
Solved by 

```
meteor remove-platform android
```
