### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by sachinkrishna** [arunoda/meteor-up-legacy#731]
Hi everyone, Im getting the following error on 

"mup deploy"
## Meteor Up: Production Quality Meteor Deployments

Building Started: ./

/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: ENOENT, readdir '/private/var/root/serw-final-udpate-error/.meteor/local/cordova-build/platforms/android/ant-build'
    at Object.Future.wait (/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper (/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
    at findApkPath (/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:965:30)
    at /private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21
    at Array.forEach (native)
    at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29)
    at Command.main.registerCommand._.extend.name [as func](/private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
    at /private/var/root/.meteor/packages/meteor-tool/.1.1.4.6w57pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
    - - - - -

=> Build Error. Check the logs printed above.

**Comment by sachinkrishna** [comment]
Figured out the issue. I had to remove the ".meteor/local" folder. And had to reset the ANDROID_HOME env var.
