### ISSUE TITLE
buildOptions mobileSettings failing to build

### ISSUE THREAD

**Issue by alekhurst** [arunoda/meteor-up-legacy#742]
It seems as adding the field "mobileSettings" in "buildOptions" fails no matter what you put in it.

For instance, I'm trying to do 

```
"buildOptions": {
    // mobile setting for cordova apps
    "mobileSettings": {
      "public": {
        "facebook": {
          "permissions": [
            "public_profile", 
            "email", 
            "user_friends"
          ]
        }
      }
    }
},
```

But even when I don't supply any settings to mobileSettings

```
"buildOptions": {
    // mobile setting for cordova apps
    "mobileSettings": {}
}
```

I get the error:

```
Error: ENOENT, open '{}'
    at Object.Future.wait (/Users/Alek/.meteor/packages/meteor-tool/.1.1.10.kjh7a4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as readFile] (/tools/fs/files.js:1334:20)
    at CordovaBuilder.generateBootstrapPage (/tools/cordova/builder.js:379:24)
    at CordovaBuilder.copyWWW (/tools/cordova/builder.js:359:32)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:159:13)
    at /tools/cli/commands.js:966:24
```

**Comment by MasterJames** [comment]
I hope someone more familiar can sound off here, but I'll just ask if you're updated to meteor 1.2 and using mupx? both things might help here.
Otherwise I'll suggest possibly you want to disable Cordova stuff before deployment. If it is?
https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration

```
 meteor remove-platform ios android
```
