### ISSUE TITLE
mup can't deploy with meteor 1.2.1

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [arunoda/meteor-up-legacy#748]
Hi, I'm using meteor 1.2.1 into Ubuntu 14.04 LTS server and this is my `mup.json` configuration:

``` json
{
  "servers": [
    {
      "host": "SERVER_IP",
      "username": "myapp",
      "pem": "myapp.pem"
    }
  ],
  "setupMongo": false,
  "setupNode": true,
  "nodeVersion": "0.10.40",
  "setupPhantom": false,
  "enableUploadProgressBar": false,
  "appName": "myapp",
  "app": ".",
  "env": {
    "ROOT_URL": "DOMAIN",
    "MONGO_URL": "mongodb://localhost:27017/myapp",
    "DISABLE_WEBSOCKETS": "1"
  },
  "deployCheckWaitTime": 120
}

```

I setup the server with `mup setup` and it's fine, but when I run `mup deploy`, it shows this error:

``` bash
Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
     args   '-Dnode_lib_file=node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    chalk@0.5.1 node_modules/chalk

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    has-ansi@0.1.0 node_modules/has-ansi

    strip-ansi@0.3.0 node_modules/strip-ansi

    supports-color@0.2.0 node_modules/supports-color

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    myapp start/running, process 22270
    Waiting for 120 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
```

I'm using only three npm modules via `meteorhacks:npm` (which is running normally with meteor 1.2 localhost) and this is the `packages.json`:

``` json
{
  "formidable":"1.0.17",
  "xml2js":"0.4.10",
  "twit":"2.1.0"
}
```

This is the error when I run `mup logs -f`:

``` bash
/opt/myapp/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
[SERVER_IP] Cannot find module 'formidable'[SERVER_IP]
[SERVER_IP] error: Forever detected script exited with code: 8[SERVER_IP]
[SERVER_IP] error: Script restart attempt #2976[SERVER_IP]
[SERVER_IP]
[SERVER_IP] /opt/myapp/app/programs/server/node_modules/fibers/future.js:245[SERVER_IP]
[SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP] throw(ex);[SERVER_IP]
[SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]     [SERVER_IP]  [SERVER_IP]  [SERVER_IP]  [SERVER_IP]  [SERVER_IP]  [SERVER_IP]  [SERVER_IP] ^[SERVER_IP]
[SERVER_IP] Error: [SERVER_IP] Cannot find module 'formidable'[SERVER_IP]
[SERVER_IP] error: Forever detected script exited with code: 8[SERVER_IP]
[SERVER_IP] error: Script restart attempt #2977[SERVER_IP]
```

Could anyone help me solve this problem?

**Comment by loongmxbt** [comment]
```
[104.236.176.112] x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
         at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-57-generic
    gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /opt/axmath/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    rs
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    chalk@0.5.1 node_modules/chalk

    strip-ansi@0.3.0 node_modules/strip-ansi

    supports-color@0.2.0 node_modules/supports-color

    has-ansi@0.1.0 node_modules/has-ansi

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    axmath start/running, process 9313
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'axmath' (linux)
```

Same problem, no npm modules. Meteor 1.2.1.

**Comment by MasterJames** [comment]
Changing to node version 0.10.40  should fix this.

**Comment by caio-ribeiro-pereira** [comment]
I'm using `0.10.40`, and we solve the problem removing from `.gitignore` the folder `packages` to send the `node_modules` we are using.

**Comment by caio-ribeiro-pereira** [comment]
It seens that mup does not run fine with `meteorhacks:npm` into Meteor 1.2.1

**Comment by MasterJames** [comment]
I advocate mupx 
Your log shows

```
gyp ERR! node -v v0.10.36
```

Glad it's working and thanks for the tips.

**Comment by loongmxbt** [comment]
I update node, npm and install mupx, find a problem in my seed.js when app inits, fix it and now deploy successfully.

**Comment by MasterJames** [comment]
Oh double posters. I thought it was one. My apologies for any confusion. 
I'm glad they're both working now!

**Comment by surielmx** [comment]
the only file inside .gitignore is "local", packages not exits. This error appears:
/opt/leaderboard/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: /opt/leaderboard/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/leaderboard/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/leaderboard/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8.

If I try use node 0.10.40, "Meteor requires Node v0.10.40 or later."

**Comment by pythoneer** [comment]
looks like the same problem here. Whats the recommend way to fix this? In my mup.json i specified `"nodeVersion": "0.10.40",` and `node -v` shows `0.10.40` on the server. But why is it complaining about 0.10.36 ?

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    t_dir=/root/.node-gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=/opt/myproject/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    odules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    chalk@0.5.1 node_modules/chalk

    supports-color@0.2.0 node_modules/supports-color

    has-ansi@0.1.0 node_modules/has-ansi

    strip-ansi@0.3.0 node_modules/strip-ansi

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    myproject stop/waiting
    myproject start/running, process 28266
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    myproject stop/waiting
    myproject start/running, process 28327
    ----------------------------------------------------------------------------
```

**Comment by MasterJames** [comment]
I would suggest trying mupx and see if it works better for your deployment target.

**Comment by pythoneer** [comment]
@MasterJames is mupx now to be preffered over mup so that i should consider to migrate any time soon in general? I will try that tomorrow and give feedback.

**Comment by MasterJames** [comment]
From what I can tell. (Not official opinion).
It seems that mupx will move to the kadirahq suite and be the way forward. (Actually this was mentioned by Arunoda but not officially yet... soon)
Mupx didn't work better for every situation but I think meteorhacks support will be depreciated for the cleaner kadirahq projects of which mupx will be joining.
There's always galaxy! And I'm sure other players in meteor deployment shaping up for different situations and providers.

**Comment by surielmx** [comment]
mup works, but only from scratch wit aws, try creating a new instance (in aws case), and then configure your mup file:

``` javascript
    {
      // Server authentication info
      "servers": [
        {
          "host": "ec2-0-0-0-0.us-west-1.compute.amazonaws.com",
          "username": "ubuntu",
          "pem": "~/Downloads/your-pem_file.pem"
        }
      ],

      // Install MongoDB in the server, does not destroy local MongoDB on future setup
      "setupMongo": true,

      // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
      "setupNode": true,

      // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
      "nodeVersion": "0.10.40",

      // Install PhantomJS in the server
      "setupPhantom": true,

      // Application name (No spaces)
      "appName": "project-name-folder",

      // Location of app (local directory)
      "app": "/Users/Username/Documents/projects/project-name-folder",

      // Configure environment
      "env": {
        "PORT": 80,
        "ROOT_URL": "http://ec2-0-0-0-0.us-west-1.compute.amazonaws.com"
      },

      // Meteor Up checks if the app comes online just after the deployment
      // before mup checks that, it will wait for no. of seconds configured below
      "deployCheckWaitTime": 15
    }
```

run `mup setup` and `mup deploy`.

It worked for me

**Comment by Goawayjose** [comment]
@caio-ribeiro-pereira I'm confused, so you deleted the .gitignore file from your meteor project to make mup deploy work?

**Comment by caio-ribeiro-pereira** [comment]
@Goawayjose I just removed from `.gitignore` the `packages` folder and it worked for me.
