### ISSUE TITLE
Site not reachable with EADDRINUSE error

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#757]
Hi
I'm deploying to a Linux server Ubuntu14.04.3 running Node 0.10.40, am using Meteor 1.2.1 and deploying using mup. Mup.json specifies port 80

After deploy the site isn't reachable. The 'mup logs' give me this:
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #7

The EADDRINUSE error suggests that the port is already taken for another site or app. However there is definitely no other web server or meteor application running. Changing the port to (say) 8000 has the desired effect, ie. all is well. But of course the site then isn't reachable for the public. A reboot, redeploy, reconfigure etc all hasn't helped.

Any advice is welcome!

E.g. How can I check the mup/meteor settings on the server? Are there any other library dependencies I need to be aware of?

Thanks
Mark

**Comment by MasterJames** [comment]
If you SSH into the target machine and wget or curl that conflicting port (locslhost) it might reveal that in fact there is something already running there? Before and after deploy? 
Im also thinking maybe trying mupx will make a difference for you.
