### ISSUE TITLE
mupx deploy error when using MONGO_URL

### ISSUE THREAD

**Issue by scsirdx** [arunoda/meteor-up-legacy#766]
Hello!

I installed local mongo, configured it to listen 172.17.42.1:27018 (172.17.42.1 is ip address from ifconfig for docker0 interface). Then i added

```
"MONGO_URL": "mongodb://172.17.42.1:27018/staging"
```

and

```
"MONGO_OPLOG_URL": "mongodb://172.17.42.1:27018/local"
```

but deploy failed. Tried mupx logs, but often it just shows:

```
[x.x.x.x] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[x.x.x.x] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[x.x.x.x] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[x.x.x.x] => Starting meteor app on port:80
```

or sometimes:

```
    [object Object]
        at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
        at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
        at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
        at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
        at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
        at new Mongo.Collection (packages/mongo/collection.js:102:1)
        at AccountsServer.AccountsCommon (accounts_common.js:23:18)
        at new AccountsServer (accounts_server.js:16:5)
        at Package (globals_server.js:5:12)
        at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80
```

What i'm doing wrong?

**Comment by MasterJames** [comment]
Maybe the port connection is blocked.
Try SSHing  into your target machine and see it you can telnet/test the port and ip where Mongo is running is reacchable.

**Comment by scsirdx** [comment]
Totally my fault. Forgot to add docker subnet to iptables exception.
Thank you for pointing it!
