### ISSUE TITLE
Failed to Deploy

### ISSUE THREAD

**Issue by innocube** [arunoda/meteor-up-legacy#774]
After trying to make it work for a full day, I almost given up now.
I virtually tried everything from what  I found by googling, but nothing worked!

This is what I am getting:
45.55.1.143] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added '45.55.1.143' (ECDSA) to the list of known hosts.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
stop: Unknown instance: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

```
> fibers@1.0.5 install /opt/portal/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
fibers@1.0.5 node_modules/fibers
portal start/running, process 6575
Waiting for MongoDB to initialize. (5 minutes)
connected
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
portal stop/waiting
portal start/running, process 6645
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'portal'

If you can help to figure out what is wrong and fix it, it would be greatly appreciated. 
Thank you!

**Comment by innocube** [comment]
And this is mup log:

45.55.1.143] Warning: Permanently added '45.55.1.143' (ECDSA) to the list of known hosts.
[45.55.1.143] tail: [45.55.1.143] cannot open ‘300’ for reading[45.55.1.143] : No such file or directory
[45.55.1.143] ==> /var/log/upstart/portal.log <==
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/portal/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
[45.55.1.143] error: Script restart attempt #1216
[45.55.1.143] 
[45.55.1.143] module.js:340
[45.55.1.143]     throw err;[45.55.1.143] 
[45.55.1.143]  [45.55.1.143]  [45.55.1.143]  [45.55.1.143]        ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/portal/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
[45.55.1.143] error: Script restart attempt #1217[45.55.1.143] 

module.js:340
    throw err;
   [45.55.1.143]        ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/portal/app/programs/server/boot.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[45.55.1.143]     at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
[45.55.1.143] error: Script restart attempt #1218[45.55.1.143]

**Comment by innocube** [comment]
Any idea how resolve this?

**Comment by innocube** [comment]
I have tested with Leaderboard example. But I am getting the same result.
Any idea?

**Comment by innocube** [comment]
This is my mup.json settings:

{
  // Server authentication info
  "servers": [
    {
      "host": "45.55.1.143",
      "username": "user",
      "password": "pass",
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/mup_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.26 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Application name (No spaces)
  "appName": "portal",

  // Location of app (local directory)
  "app": "/path/to/the/source/",

  // Configure environment
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://45.55.1.143",
    "MONGO_URL": "mongodb://login:pass@localhost:27017/portal"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

**Comment by MasterJames** [comment]
Try extending the deployCheckWaitTime to 120
So it's Ubuntu 14 target?  Maybe you should try mupx if your stuck with mup.
Is this on AWS or Digital Ocean,  etc.?
You can try a default empty meteor app too another provider. Once you have a working example you can inject your app and see what breaks it or at least remove that from the issue initially.

**Comment by vangorra** [comment]
Having the same problem with Ubuntu 14 in AWS. My config is almost the same at OP's. Any ideas?

**Comment by MasterJames** [comment]
Firewall ingress maybe? 
If you ssh into the target and can curl the local host port but can't on the outside then that's packets being blocked.
The problem is it will role back if it can't detect it.
In such a case one way is to put an exit() call in the code where it checks and reverts and then check locally via ssh.
If you need more clarity after some more deep thought and tries then I'll explain better but I think you're following.

**Comment by vangorra** [comment]
Perhaps. I reran "mup setup && mup deploy" and it's all working. I probably had the wrong network security group or something.
