### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#787]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mupx/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout (timers.js:92:15)

I'm getting this error. How to fix this?

**Comment by MasterJames** [comment]
Hopefully someone else knows this problem but until then I'll make a few suggestions.
That error is coming from deep inside a 3rd party library for ssh2. You should post all your settings files and full DEBUG log.
Otherwise you could double check your SSH is working properly. 
Also it seems like it could be an intermittent networking problem.
It would also be useful to run updates and check installed versions and your target image is Ubuntu 14.

**Comment by ghost** [comment]
@MasterJames Thanks for replying man, I can't access my server right now (down probably) so maybe that's the reason for the error. I'm using google cloud and the UI suddenly changed and some pop up saying that I should sign up for trial when going over the platform. I can't even see my instances, just the numbers of instances running then that pop up..

**Comment by a4xrbj1** [comment]
Having the same problem whilst deploy to DO:

- Installing Node.js
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout (timers.js:93:15)

I followed this excellent tutorial: http://meteortips.com/deployment-tutorial/digitalocean-part-1/ but I get this error when executing `mup setup`

This is my mup.json file
`{
  // Server authentication info
  "servers": [
    {
      "host": "45.55.82.45",
      "username": "root",
      // "password": "password"
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "gtools",

  // Location of app (local directory)
  "app": ".",

  // Configure environment
  "env": {
    "ROOT_URL": "http://45.55.82.45"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}`

**Comment by a4xrbj1** [comment]
I'm getting the same error when I'm using mupx instead:

Started TaskList: Setup (linux)
[45.55.82.45] - Installing Docker
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mupx/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout (timers.js:93:15)

so it doesn't seem to be a mup or mupx problem.

**Comment by MasterJames** [comment]
Might be the pem setup too. Maybe try with just password and no pem initially after confirming your hosting target account is setup etc.

**Comment by krtrice** [comment]
I'm having the exact same issue and error message.. My computer recently had the hard drive wiped and a fresh OS installed. I installed meteor, npm and mup all fresh and now cannot admin my server at all with mup. I'm able to SSH manually into the server without any issues.

**Comment by MasterJames** [comment]
Sounds like you should try mupx if your using mup?
