### ISSUE TITLE
Deploy failing on Amazon EC2

### ISSUE THREAD

**Issue by alextondello** [arunoda/meteor-up-legacy#790]
I'm updating my website weekly for over a moth now and then this week mup started failing me. I can't update my website anymore. Can anyone figure out what could be happening?
I'm using Meteor 1.2.1 and Node 0.10.40.

```
Invoking deployment process: FAILED
    -----------------------------------STDERR-----------------------------------
    e.lib',
    gyp info spawn args   '-Dmodule_root_dir=/opt/testapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ing
    ansi-regex@0.2.1 node_modules/ansi-regex
    ansi-styles@1.1.0 node_modules/ansi-styles
    chalk@0.5.1 node_modules/chalk
    escape-string-regexp@1.0.3 node_modules/escape-string-regexp
    strip-ansi@0.3.0 node_modules/strip-ansi
    supports-color@0.2.0 node_modules/supports-color
    has-ansi@0.1.0 node_modules/has-ansi
    eachline@2.3.3 node_modules/eachline
    type-of@2.0.1 node_modules/type-of
    amdefine@1.0.0 node_modules/amdefine
    asap@2.0.3 node_modules/asap
    underscore@1.5.2 node_modules/underscore
    meteor-promise@0.5.0 node_modules/meteor-promise
    promise@7.0.4 node_modules/promise
    source-map-support@0.3.2 node_modules/source-map-support
    semver@4.1.0 node_modules/semver
    source-map@0.1.32 node_modules/source-map
    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    testapp start/running, process 2927
    Waiting for 7 seconds while app is booting up
    Checking is app booted or not?
    testapp stop/waiting
    testapp start/running, process 2956
    ----------------------------------------------------------------------------
```

Mup log has this:

```
/opt/testapp/app/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: ENOENT, no such file or directory '/opt/testapp/app/programs/server/packages/cfs_http-methods.js'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at /opt/testapp/app/programs/server/boot.js:138:19
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/testapp/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/testapp/app/programs/server/boot.js:137:5
error: Forever detected script exited with code: 8
error: Script restart attempt #1

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/testapp/app/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
    at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:22:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
```

"cfs_http-methods.js" is inside "/opt/testapp/app/programs/server/packages", so I have no idea what is the problem.

Thanks,
Alex

**Comment by alextondello** [comment]
I've found out the problem. Calling "var http = Npm.require("https");" in multiple files was causing the problem. I think this should not happen, but... anyway, I'm glad that my deploy is working again.

**Comment by devdudeio** [comment]
set your node version to x.x.`40`

then
`mup setup`
`mup deploy`

when you change something in settings you have to do the `setup` again

you using ubuntu 14 lts?

**Comment by alextondello** [comment]
Thanks! Apparently the problem was happening due to a lack of memory on the server. Upgrading my machine solved the problem.

**Comment by devdudeio** [comment]
rule of thumb for meteor is get max RAM and get max single core CPU speed (more cores are useless) when you scale vertically. 

how much RAM you need for your project? I still use free tier on AWS EC2 and have no problems

**Comment by alextondello** [comment]
Well, I was using the free tier on AWS EC2 (1Gb RAM). With an empty or near empty mongo database everything worked just fine. When more than 500 users registered my deploy problem started. Upgrading to 2Gb RAM solved this problem.
I use a few observers, like Meteor.users.observe( { filter }, { fields } ) in my server, thats probably why bigger database needs more RAM.
But another problem I'm having are CPU spikes every 10s or so, it goes up to 30% and I can't find out why this is happening. It's the observers, but I'm watching only a few objects from database, it should not use that much CPU I guess. If it continues like this, when my database gets bigger I'll need a bigger machine really soon.
