### ISSUE TITLE
Error on "mup deploy" Building process

### ISSUE THREAD

**Issue by cyclops24** [arunoda/meteor-up-legacy#813]
Hi,

When I try to deploy my app I got this error:

```
Building Started: /media/userName/Projects/Projects/appName

/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'split' of undefined
  at Object.parse (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/parse-stack.js:23:26)
  at Object.exception (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:480:29)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:871:22
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
  at ClientTarget.minifyJs (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:866:18)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:530:17
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
  at ClientTarget.make (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:492:18)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2083:14
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2169:20
  at Array.forEach (native)
  at Function._.each._.forEach (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2168:7
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.capture (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:245:19)
  at Object.exports.bundle (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2070:31)
  at buildCommand (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:834:30)
  at Command.main.registerCommand._.extend.name [as func] (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:728:10)
  at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/main.js:1227:23


=> Build Error. Check the logs printed above.
```

Please help me to fix this or if it's mup bug say me.

**Comment by MasterJames** [comment]
My first guess is you should remove Cordova? from the build targets (only while deploying) if you have ios or android added? 
meteor remove ios android
Or something like that. There are various threads/discussions and PRs to that end.

Try the dev branch mupx if mup doesn't seem to fit your situation.

Also note mupx is in the process of transisioning to kadirahq (not ready), [so there's unfortunately limited support for this varient precivably now and in the future].

**Comment by cyclops24** [comment]
Thanks for your attention. But I didn't use Cordova. This is my project "meteor list" output:

```
accounts-password            1.1.4  Password support for accounts
alanning:roles               1.2.14  Authorization package for Meteor
aldeed:autoform              5.8.1  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2           2.8.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema         1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
blaze-html-templates         1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                        1.1.0  Check whether a value matches a pattern
dburles:collection-helpers   1.0.4  Transform your collections with helpers that you define
ejson                        1.0.7  Extended and Extensible JSON library
gadicohen:sitemaps           0.0.23  functions to easily output valid sitemaps
ian:accounts-ui-bootstrap-3  1.2.84  Bootstrap-styled accounts-ui with multi-language support.
insecure                     1.0.4  (For prototyping only) Allow all database writes from the client
iron:router                  1.0.12  Routing specifically designed for Meteor
jquery                       1.11.4  Manipulate the DOM using CSS selectors
logging                      1.0.8  Logging facility.
matteodem:easy-search        2.0.0  Easy-to-use search with Blaze Components (+ Elastic Search support)
maximum:server-transform     0.4.1  Meteor package to transform documents on publish
meteor-base                  1.0.1  Packages that every Meteor app needs
meteorhacks:npm              1.5.0  Use npm modules with your Meteor App
mobile-experience            1.0.1  Packages for a great mobile user experience
mongo                        1.1.3  Adaptor for using MongoDB and Minimongo over DDP
npm-container                1.2.0+ Contains all your npm dependencies
random                       1.0.5  Random number generator and utilities
reactive-dict                1.1.3  Reactive dictionary
reload                       1.1.4  Reload the page while preserving application state.
sacha:spin                   2.3.1  Simple spinner package for Meteor
session                      1.1.1  Session variable
spacebars                    1.0.7  Handlebars-like template language for Meteor
standard-minifiers           1.0.2  Standard minifiers used with Meteor apps by default.
tracker                      1.0.9  Dependency tracker to allow reactive callbacks
twbs:bootstrap               3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.


+ These packages are built locally from source.
```

**Comment by MasterJames** [comment]
It's in the .meteor/platforms file
Here is the other thread.
https://github.com/arunoda/meteor-up/issues/676
Anyway it should just have 
server
browser
No ios android etc.
If that is how it is then it wasn't the problem and just an initial hunch to check.

**Comment by cyclops24** [comment]
Unfortunately only server and browser there.This is my .meteor/platforms file content:

```
server
browser
```

I deploy this project some days ago without any problem. But after meteor update and add [maximum:server-transform package](https://atmospherejs.com/maximum/server-transform) package deploy error appear. I also try to remove maximum:server-transform package and test again but it isn't fix.
Please help me to troubleshoot this error if it's possible. How to find that where is the error?? How to trace build process?? :cry: 

I also try `DEBUG=* mup deploy` for verbose mode but it isn't new detail about error.

I test and found that same error also return when use meteor build command. How to find that in which file TypeError: Cannot call method 'split' of undefined happened??

**Comment by cyclops24** [comment]
I think it's a meteor CLI bug. Please see updated question in [StackOverflow](http://stackoverflow.com/questions/34554990/error-in-building-meteor-app).

**Comment by MasterJames** [comment]
Maybe you should post the mupx settings files, if setting your node js version value to 0.10.40 in the same settings file does not fix it.
It's the one that is compatible with current meteor release 1.2.1

**Comment by MasterJames** [comment]
I had this kind of error.
https://github.com/meteor/meteor/issues/4933
and simply closing my editor enabled the build/launch to complete when prior it got Error:EPREM readdir'ed.
It might have happen with the change of the year?

**Comment by MichaelJCole** [comment]
`meteor remove-platform android` worked for me.

**Comment by faridescate** [comment]
Thanks MichaelJCole, also i've used
$ meteor remove-platform ios
