### ISSUE TITLE
JFYI - Error: spawn meteor ENOENT - how did i fix this on linux

### ISSUE THREAD

**Issue by isbjorn** [arunoda/meteor-up-legacy#825]
I am using Linux + nvm 0.29 + node 5.4.0 + meteor 1.2.1 + mupx 1.5.3

I have error on `mupx deploy`:

```
Meteor app path    : /mnt/ssd/home-fast/coder/work/ip/grant
Using buildOptions : {"debug":true}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:1003:3
```

After short investigation i found that...
node environment does not love:
1. symlinks
2. tildas `~` in path

I had:
1. symlinked ~/.nvm
2. ~/.meteor in my PATH

I replaced symlinks with actual dir/files and fixed path in ~/.bashrc

```
export PATH="$PATH:$HOME/.meteor"
```

I can run `mupx deploy` now )))

I hope it will be useful )
## Summary
1. don't use symlinks
2. don't use `~` in path

**Comment by laran** [comment]
This was good to see. It gave me something new to try. But I don't have either symlinks or tildas in my path and I'm still seeing the error. It has me dead in the water. Writing my own deploy script because I can't get off the ground with mup right now. Would love to see this issue resolved.
