### ISSUE TITLE
Does mupx work with Meteor 1.3? Encountering problems

### ISSUE THREAD

**Issue by ffxsam** [arunoda/meteor-up-legacy#841]
Output of `mupx logs --tail=all` below:

```
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: failed to connect to [myApp:NaN]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
  [truncated]
```

First there's a strange deprecation warning with npm, and then it fails to connect to MongoLab. Is this a known issue? I should also mention the ios platform is added to this project, so there's a Cordova build. I obviously only need the server aspect installed, if that's even possible.

**Comment by tjmonsi** [comment]
@arunoda This is what I am afraid of... I was already playing with Meteor 1.3 and has forgotten that I would use mupx. Should we use kadirahq/meteor-up already or still can use this one for a Meteor 1.3-beta?

**Comment by ffxsam** [comment]
I should point out this was using a remote Mongo DB via `MONGO_URL`. If you let mupx set up your app and DB on the same machine, it works fine.

**Comment by katopz** [comment]
mupx is work for me [here](https://medium.com/@katopz/digitalocean-meteor-1-3-781ea6ea9b14) and yes with some platform removal need.

**Comment by clayne11** [comment]
I'm having this same problem as well.

**Comment by MasterJames** [comment]
New version improvements PRs etc. will only be performed over at the new kadirahq port, since it depreciates this one.

**Comment by clayne11** [comment]
I tried deploying using kadirahq/meteor-up and ran into the same issue. I'll make a new issue over there.

**Comment by tjmonsi** [comment]
Just a thought...what is the version of the remote mongodb that you are trying to connect to?

**Comment by clayne11** [comment]
Mongo version 3.0.9

**Comment by tjmonsi** [comment]
Hmmm i was thinking it might be the mongo driver issue

**Comment by ckiely91** [comment]
I'm getting a similar issue but it doesn't appear to be mongo-related. Instead my error is saying that fibers.node is missing.

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Deploying from Ubuntu using mupx. I get the same error regardless of whether it's using local or remote mongo.

**Comment by ckiely91** [comment]
Strangely enough it just worked when using the debug mode:
`DEBUG=* mupx deploy`

No idea why.

**Comment by ahmay98** [comment]
yes, same problem here...  (also same problem with kadira/meteor-up)

trying to deploy Meteor 1.3beta 12

[45.55.31.183]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[45.55.31.183]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[45.55.31.183]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[45.55.31.183]=> Starting meteor app on port:80
[45.55.31.183]
[45.55.31.183]/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[45.55.31.183]  throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
[45.55.31.183]Error:`/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`is missing. Try reinstalling`node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by MasterJames** [comment]
The new version still being ported to kadirahq it has custom docker images but its likely they will already have an image to handle that version there. I'm pretty certain it's the only way forward. You could try to patch the fiber version etc. but it's better to see if they can help yet with that problem in the new version (still being worked on, this one's being depreciated by it).

**Comment by ahmay98** [comment]
thanks @MasterJames

**Comment by patrickml** [comment]
same here 

```
/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
[104.236.247.44]     at Module.load (module.js:356:32)
[104.236.247.44]     at Function.Module._load (module.js:312:12)
[104.236.247.44]     at Module.require (module.js:364:17)
[104.236.247.44]     at require (module.js:380:17)
[104.236.247.44]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[104.236.247.44]     at Module._compile (module.js:456:26)
[104.236.247.44]     at Object.Module._extensions..js (module.js:474:10)
```

**Comment by andreasteffanoni** [comment]
I had the same problem, solved by setting "deployCheckWaitTime": 60 in mup.json

**Comment by andreasteffanoni** [comment]
It actually takes about 20 seconds to verify the deployment, so probably 60 is too much but for sure 15 is not enough

**Comment by mattiLeBlanc** [comment]
Unfortunately setting the checkWaitTime to 60 is not a fix for all of us. Can this be resolved quickly? We are trying to deploy our staging and production version and now we can't. This is not acceptable from a business perspective.

**Comment by ffxsam** [comment]
> Can this be resolved quickly? We are trying to deploy our staging and production version and now we can't. This is not acceptable from a business perspective.

Keep in mind this is an open source, non-profit project. If your app needs to be deployed onto a production environment for which you need support and reliability, you may want to check out [Galaxy](http://galaxy.meteor.com).

**Comment by mattiLeBlanc** [comment]
@ffxsam It's not about support. It's about trusting something works and that there is transparency. Deciding to run on Amazon, Azure or Galaxy has nothing to do with it in my opinion.
If I decide to use mupx because it works, and then for some reason it stops working.. it kind is out of my control. But by now I am relying on it to work. And I have to answer to it in our (.net) organisation because I chose the technology stack.

I know that is the big downside of open source compared to proprietary but I do love the flexibility of open source.
In most cases issues like these with popular packages are resolved really quickly so that is great.
But this deploy issue related to node has been around for a while, maybe in different versions but still.

**Comment by MasterJames** [comment]
Please let us know if the new kadirahq mup port works for you,  there is where you'll find support too.
This version is basically depreciated by it. It's not built for meteor 1.3 and PRs are no longer incorporated here. I believe the way forward is the kadirahq version.

**Comment by mattiLeBlanc** [comment]
@MasterJames  So I shoudn't use mupx anymore? I thought that was bleeding edge. I think I am running 1.5.3

**Comment by MasterJames** [comment]
Well last time and officially before the hammer finally dropped on the release of 1.3 the official word (not mine) was the development branch version mupx here is your best choice (for 1.2?) but since I'd like to know if the port is now prefered at least by way of asking people to test if it'still working/ready for most people or not, since there are lots of different situations to affect the support.
So I guess try the new one report you issues with them if it's still not ready I'd report back here and see what thing people are doing to get satisfaction. 
In general I would start with a fresh deployment of meteor 1.3 demo app with this mupx or first the new kadirahq version for deploying it and add in your code or maybe just packages first. Start by getting a current version of npm although in theory you can use " meteor npm install " I'd avoid it, use new separately installed npm.
Anyway drop your code into this totally clean route.
From what I can gather you want the major changes in meteor 1.3 and should start clean. Other techniques say delete the node_modules folder etc. But starting fresh is the best way to remove unknowns.
Mupx is docker centric as is the port and I suppose the new meteor uses version 4? of node so you get TLS aka SSL built into node and less reason for nginx potrntially so you can imagine the docker images should be different etc. and so changes are need in mup. Since this version is depreciated and not accepting new PRs kadirahq is you way forward.

**Comment by mattiLeBlanc** [comment]
okay.....sigh...I am so busy building our app with an April deadline and Meteor 1.3 and all is great but it's given me a major headache with stuff breaking (first issues with Angular Meteor). Finally got it back to work and now the deployment system is broken and I have to figure out if I can get it back up and running. I am in a sprint and this was not part of the sprint lol.
Thanks for offering to check the issues, I removed mup and mupx and followed the instructions of installing kadirahq's mup using npm install and link. Right now it is not working, not even an error message. Just nothing on the console.

The readme is a bit limited too. When you do a mup init it creates a mup.js file with require commands that are breaking the build and are not in the readme. There is also a source map lol.
Then it is not really clear which dockerImage we should use. I liked the mupx docker setup.

Well back to try and fiddle around to get it to work, or at least throw an error.

**Comment by clayne11** [comment]
I have Meteor 1.3 deploying fine with mupx for what it's worth.

**Comment by MasterJames** [comment]
The new version I believe has custom docker images and hooks at all points etc. so it's more likely to get you there I figured especially with 1.3.
It uses a js file for settings i believe so watch for that, and is better for multi app deployments, etc.
Well it's great to see some positive feedback that it's not totally broken and so there is hope.
I think it's typically problems with binary package dependencies.
If you can post your settings and logs I'd be happy to make some suggestions to isolate what's glitching out.
@clayne11 what packages are you using?  Please and thank you.

**Comment by mattiLeBlanc** [comment]
@clayne11 I think I saw one successful deployment today with mupx and meteor 1.3. However, that was one out of 6 attempts and I haven't had a successful deployment since. I also see the node-future error thingy on verifying deployment.

@MasterJames
I started a thread on the kadirahq site with issue I have with kadira's  @mup:
https://github.com/kadirahq/meteor-up/issues/93
We are also looking at the Demeteorizer (https://github.com/onmodulus/demeteorizer) as an option to just get a node app and host in somewhere together with a separate MongoDB. 
We need to be able to be in control of our deployment to prevent drama's :).

I would love to keep on using Mup, its great. But for now it is causing issues. I am actually debugging the npm package to see where it breaks.

**Comment by MasterJames** [comment]
If you really need to deploy, it might be a temporary solution to just run meteor as its intended on the target machine without using mup. Larger file size but it should run.
If you can SSH in you can use SSHFS or rcp to transfer files and run commands from there. Maybe you need to learn Docker and use it. One as a way to deploy and also to build your custom image etc.
For me studying mupx as if it is a guideline is a good way to look at it since there's such diverse needs.
Manually stepping through the scripts and processes is the best way to find where it breaks.
You can make a fork (or jack the npm install folder) and put in a stop / exit at a point your not sure about and then check it worked or run that next step manually. Also note the docker exec command you can run a bash and then your in the docker image with shell access. Also the docker volume command reveals where the Mongo image files are stored etc. These are just some pointers in topics that might save you some time thinking how it works, or point you into the challange you hoped you personally won't have to. Also remember Galaxy you can use it if you have problems without.

**Comment by mattiLeBlanc** [comment]
Yeah, I am already console logging into the npm package to see how far it comes and where is silently breaks.
I know docker a little bit, when i used mupx I have played around with the images a bit.

We can't use Galaxy (i think)(, we are running most of our stuff on Azure, so getting the noses to point away from Azure for this is going to be a company decision. right now I am already happy that they accepted Meteor for this application.

**Comment by AGTGreg** [comment]
I've successfully deployed my meteor app on DigitalOcean with mupx. My app connects to an external Mongodb. The db I connect to is in another DigitalOcean droplet. I also updated all the packages I use.

Although it failed to verify the deployment, the app deployed just fine.
Then I doubled the "deployCheckWaitTime" in mup.json and the deployment was verified.

**Comment by MasterJames** [comment]
Good to know thank you for posting you success with mupx deploying meteor 1.3!

**Comment by myrtleTree33** [comment]
+1 for  setting "deployCheckWaitTime" to 60

**Comment by asidiali** [comment]
Doubling 'deployCheckWaitTime' from 30 to 60 worked for me as well :+1: (digital ocean)

**Comment by pepepaez** [comment]
same for me, it was 15 seconds, changed to 60 and verification step completes without a problem, I didn't get any errors but I would get the npm warning message

**Comment by xauxatz** [comment]
I can successfully deploy meteor 1.3 with mupx to a digitalocean droplet.
But I get the npm deprecated warning as well. Even when increasing the time from 15 to 60.
npm is updated to version 3.8.5 on both the client and server, so it is really strange.
This is the error message I get:

```
[104.131.23.139] npm WARN deprecated This version of npm lacks support for important features,
[104.131.23.139] npm WARN deprecated such as scoped packages, offered by the primary npm
[104.131.23.139] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[104.131.23.139] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[104.131.23.139] npm WARN deprecated 
[104.131.23.139] npm WARN deprecated   npm -g install npm@latest-2
[104.131.23.139] npm WARN deprecated 
[104.131.23.139] npm WARN deprecated To upgrade to the latest stable version, run:
[104.131.23.139] npm WARN deprecated 
[104.131.23.139] npm WARN deprecated   npm -g install npm@latest
[104.131.23.139] npm WARN deprecated 
[104.131.23.139] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[104.131.23.139] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[104.131.23.139] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[104.131.23.139] npm WARN deprecated 
[104.131.23.139] npm WARN deprecated If you're running the version of npm bundled with
[104.131.23.139] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[104.131.23.139] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[104.131.23.139] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[104.131.23.139] npm WARN deprecated semver behavior.
[104.131.23.139] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[104.131.23.139] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[104.131.23.139] npm WARN package.json meteor-dev-bundle@0.0.0 No README data

```

The app works well so apparently the warning is not too important but in any case it would be nice to get rid of it.

**Comment by TomasMolnar** [comment]
After 14 hours of debugging and trying multiple suggestions I successfuly deployed Meteor 1.3 app using MUPX to my production UBUNTU server! yeeeah
I had to set debug option to TRUE in mup.json. However without setting it to TRUE the deployment runs OK, just the app does not work (strange).
//build options

```
  "buildOptions": {
    // build with the debug mode on
    "debug": true,
    },
```

**Comment by MasterJames** [comment]
Well congratulation! Seems strange for sure. Can't be the full story. Is debug really not disable-able now? 
What versions?

**Comment by luisreyes** [comment]
Adding the buildOptions debug flag fixed it for me! Thanks @thomasmolnar

**Comment by Cu4rach4** [comment]
i have olmost the same error:

## `Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

[devapp.vita-fx.org] 

> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/bundle/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory`/bundle/bundle/programs/server/node_modules/fibers/build'
Installed in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
ansi-regex@0.2.1 node_modules/ansi-regex

ansi-styles@1.1.0 node_modules/ansi-styles

escape-string-regexp@1.0.5 node_modules/escape-string-regexp

chalk@0.5.1 node_modules/chalk

supports-color@0.2.0 node_modules/supports-color

has-ansi@0.1.0 node_modules/has-ansi

strip-ansi@0.3.0 node_modules/strip-ansi

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

underscore@1.5.2 node_modules/underscore

meteor-promise@0.5.1 node_modules/meteor-promise

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.8 node_modules/fibers
=> Starting meteor app on port:80
Kadira: completed instrumenting the app
Kadira: Successfully connected
[devapp.vita-fx.org] npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)`

all works, but doesn't send emails...is not work with debug flag!!! can you help me?

**Comment by MasterJames** [comment]
Does Kadira help to track memory usage and errors when you send emails? 
Maybe try another way of sending emails if that's the only problem? 
Could be you want karidahq/meteor-up with npm3?  Or something.
Maybe you can be clearer on what you think the problem or the issue is or explain the email module code setup better thanks?

**Comment by Cu4rach4** [comment]
@MasterJames kadira doesn't show any error...

the problem is when i use random function on server side, i create anothers emails and all of them are working fine...so i think is a problem with accounts-password or something like that.

im running on meteor 1.3.2.4 and node: 0.10.44.- on ubuntu 14.04.

thanks...

**Comment by MasterJames** [comment]
Kadira is suppose to be able to help with debugging on the server side too.
https://kadira.io/academy/meteor-performance-101/content/understanding-your-meteor-app
Various articles on that.
http://stackoverflow.com/questions/11034941/meteor-debug-on-server-side

Anyway are these functions on the server side called from the client as remote calls?
Like they discuss various patterns here?
https://forums.meteor.com/t/how-to-return-value-on-meteor-call-in-client/1277/7
Or some email cron like timer?

**Comment by torayeff** [comment]
+1 for deployCheckWaitTime

**Comment by MasterJames** [comment]
Some say yes but is not 1.4 out? 
So with kadirahq/meteor-up you can customize the docker image so that new version really seems the only way forward. This one is depreciated.

**Comment by ghost** [comment]
Some people would think that each new meteor version tries to break mupx in some new original way...

I start to be tired of all this.

**Comment by torayeff** [comment]
@pykiss honestly i start to be tired of meteor

**Comment by MasterJames** [comment]
Should get easier will the new version at kadirahq. 
Personally I've moved on with what Meteor has taught me.
You never know though I might come crawling back one day.

**Comment by hems** [comment]
I get exactly the same error as @patrickml :
````
/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
````

Funny enough it was working perfect and i did hundreds of deploys and the last one is the one that this happened.

Out of the blue!
