### ISSUE TITLE
Mongo SSL & Verifying deployment: FAILED

### ISSUE THREAD

**Issue by haunguyen90** [arunoda/meteor-up-legacy#857]
I have a trouble problem with mongo ssl, mupx deploy is not working, 

```
[192.241.249.56] - Uploading bundle
[192.241.249.56] - Uploading bundle: SUCCESS
[192.241.249.56] - Sending environment variables
[192.241.249.56] - Sending environment variables: SUCCESS
[192.241.249.56] - Initializing start script
[192.241.249.56] - Initializing start script: SUCCESS
[192.241.249.56] - Invoking deployment process
[192.241.249.56] - Invoking deployment process: SUCCESS
[192.241.249.56] - Verifying deployment
[192.241.249.56] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        rror: Could not locate any valid servers in initial seed list
            at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
            at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
            at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
            at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
            at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
            at new Mongo.Collection (packages/mongo/collection.js:102:1)
            at AccountsServer.AccountsCommon (accounts_common.js:23:18)
            at new AccountsServer (accounts_server.js:16:5)
            at Package (globals_server.js:5:12)
            at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
            - - - - -
            at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:329:26
            at process._tickCallback (node.js:448:13)

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------
```

Bellow is my config

mup.json

```
{
  // Server authentication info
  "servers": [
    {
      "host": "xxxxxxxx",
      "username": "xxxxx",
      "password": "xxxxxx"
    },
    {
      "host": "xxxxxxxx",
      "username": "xxxxxxxx",
      "password": "xxxxxxxx"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Application name (No spaces)
  "appName": "schedule-production",

  // Location of app (local directory)
  "app": "../../",

  // Configure environment
  "env": {
    "PORT": 3000,
    "ROOT_URL": "http://app.mdshifts.com",
    "MONGO_URL": "mongodb://mongo-0.abixa.com,mongo-1.abixa.com,mongo-2.abixa.com/schedule-production?ssl=true",
    "MONGO_OPLOG_URL": "mongodb://mongo-0.abixa.com,mongo-1.abixa.com,mongo-2.abixa.com/local?authSource=admin",
    "DISABLE_WEBSOCKETS": "1",

    "CLUSTER_DISCOVERY_URL": "mongodb://mongo-0.abixa.com,mongo-1.abixa.com,mongo-2.abixa.com/schedule-production",
    "CLUSTER_SERVICE": "web"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 120
}
```

Can anyone tell me what's wrong ?

P/S: I set Replica for my mongo (using private network between the primary and secondary) and SSL for mongo

**Comment by haunguyen90** [comment]
@arunoda

**Comment by MasterJames** [comment]
I guess you should begin debugging.
First I would make sure the path is absolute. 
Second try a running your Mongo locally.
Basically strip it down to a default test and start adding in your settings. 
Maybe your Mongo needs updating or has the issue. 
You should log into the target and try to run the steps locally.
I'm sorry I've no answers but somewhere to start to isolate where the fault is.

**Comment by joncursi** [comment]
I've run into the same issue when deploying to a replica set that resides on the same server (it's a staging environment). My mup.json:

```
  "env": {
    "ROOT_URL": "https://xx.xx.xxx.xx",
    "MONGO_URL": "mongodb://staging:27017,staging:27018,staging:27019/staging?replicaSet=rs0",
    "MONGO_OPLOG_URL": "mongodb://staging:27017,staging:27018,staging:27019/local?authSource=admin",
    "MAIL_URL": "smtp://localhost:25",
    "CLUSTER_WORKERS_COUNT": "auto",
    "KADIRA_PROFILE_LOCALLY": 1
  },
```

`staging` is the hostname of the Linux server I am deploying to. I've tried replacing this with the server's IP address to no avail.

Replica set status is healthy:

```
{
    "set" : "rs0",
    "date" : ISODate("2016-04-12T10:23:45.887Z"),
    "myState" : 1,
    "members" : [
        {
            "_id" : 0,
            "name" : "staging:27017",
            "health" : 1,
            "state" : 1,
            "stateStr" : "PRIMARY",
            "uptime" : 41791,
            "optime" : Timestamp(1460455377, 2),
            "optimeDate" : ISODate("2016-04-12T10:02:57Z"),
            "electionTime" : Timestamp(1460414921, 1),
            "electionDate" : ISODate("2016-04-11T22:48:41Z"),
            "configVersion" : 1,
            "self" : true
        },
        {
            "_id" : 1,
            "name" : "staging:27018",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 41706,
            "optime" : Timestamp(1460455377, 2),
            "optimeDate" : ISODate("2016-04-12T10:02:57Z"),
            "lastHeartbeat" : ISODate("2016-04-12T10:23:45.670Z"),
            "lastHeartbeatRecv" : ISODate("2016-04-12T10:23:43.927Z"),
            "pingMs" : 0,
            "syncingTo" : "staging:27017",
            "configVersion" : 1
        },
        {
            "_id" : 2,
            "name" : "staging:27019",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 41706,
            "optime" : Timestamp(1460455377, 2),
            "optimeDate" : ISODate("2016-04-12T10:02:57Z"),
            "lastHeartbeat" : ISODate("2016-04-12T10:23:45.344Z"),
            "lastHeartbeatRecv" : ISODate("2016-04-12T10:23:45.343Z"),
            "pingMs" : 0,
            "syncingTo" : "staging:27017",
            "configVersion" : 1
        }
    ],
    "ok" : 1
}
```

Error logs reported by `mupx logs --tail=300`:

```
[45.79.139.28] => Starting meteor app on port:80
[45.79.139.28] 
[45.79.139.28] /bundle/bundle/programs/server/node_modules/fibers/future.js:300
[45.79.139.28]                      throw(ex);
[45.79.139.28]                            ^
[45.79.139.28] Error: Could not locate any valid servers in initial seed list
[45.79.139.28]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
[45.79.139.28]     at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
[45.79.139.28]     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[45.79.139.28]     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[45.79.139.28]     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[45.79.139.28]     at new Mongo.Collection (packages/mongo/collection.js:102:40)
[45.79.139.28]     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[45.79.139.28]     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[45.79.139.28]     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[45.79.139.28]     at fileEvaluate (packages/modules-runtime.js:158:9)
[45.79.139.28]     - - - - -
[45.79.139.28]     at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:329:26
[45.79.139.28]     at process._tickCallback (node.js:458:13)
[45.79.139.28] npm WARN deprecated This version of npm lacks support for important features,
[45.79.139.28] npm WARN deprecated such as scoped packages, offered by the primary npm
[45.79.139.28] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[45.79.139.28] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[45.79.139.28] npm WARN deprecated 
[45.79.139.28] npm WARN deprecated   npm -g install npm@latest-2
[45.79.139.28] npm WARN deprecated 
[45.79.139.28] npm WARN deprecated To upgrade to the latest stable version, run:
[45.79.139.28] npm WARN deprecated 
[45.79.139.28] npm WARN deprecated   npm -g install npm@latest
[45.79.139.28] npm WARN deprecated 
[45.79.139.28] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[45.79.139.28] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[45.79.139.28] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[45.79.139.28] npm WARN deprecated 
[45.79.139.28] npm WARN deprecated If you're running the version of npm bundled with
[45.79.139.28] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[45.79.139.28] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[45.79.139.28] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[45.79.139.28] npm WARN deprecated semver behavior.
[45.79.139.28] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[45.79.139.28] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[45.79.139.28] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
```
- I am using MongoDB `3.0.7`.
- Project runs fine locally.
- Using mupx `1.5.3`.

Any additional ideas? Thanks!

**Comment by joncursi** [comment]
So I've come to the conclusion that mupx no longer supports locally-hosted replica sets as configured above, due to the way in which Docker is set up. @MasterJames does that sound about right? The below line sort of says this, I think.

> If you decided to use MongoDB, it'll be also running as a Docker conatiner. It's bound to the local interface and port 27017 (you cannot access from the outside)

I was only able to deploy successfully until I shut down my replica set and edited mup.json with `setupMongo: true` and removing `MONGO_URL` and `MONGO_OPLOG_URL`. So I had to throw the replica set entirely out the window to make deployment work, which is not exactly what I want to do.

**Comment by MasterJames** [comment]
I'm not sure about that you can use your own mongo deployment. Also remember that kadirahq/meteor-up has all kinds of new features etc.
The quote seems wrong because with docker you can call docker exec bash and get a shell open in any container if the shell is not installed then call something like mongodb with the docker exec command.
In the end if you can spare the drive space on the deployment target machine you can just run meteor as you would in development mode. Just rcp or ftpssh to transfer files and it should hot push from the server itself, or ssh in to rerun or whatever.
The dev team is over at kadirahq if you need help getting things going with that new ported version which should be pretty stable for most and the way forward for meteor 1.3 and onwards.

**Comment by c9s** [comment]
Same here.
