### ISSUE TITLE
Error while mup setup

### ISSUE THREAD

**Issue by SandeepFourtek** [arunoda/meteor-up-legacy#867]
**mup.json file**
{
  // Server authentication info
  "servers": [
    {
      "host": "52.--.--.--.--",
      "username": "ubuntu",
      // "password": "password",
      // or pem file (ssh based authentication)
      "pem": "/home/fourtek/Downloads/Fourtekpem.pem",
      "sshOptions": { "Port" : 12345 }

```
}
```

  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "meteormanager",

  // Location of app (local directory)
  "app": "/home/fourtek/Documents/TestGraph",

  // Configure environment
  "env": {
    "ROOT_URL": "http://ec2-52-49-141-129.eu-west-1.compute.amazonaws.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

when we type on terminal it givesa Error Like

**Error In Console**

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Started TaskList: Setup (linux)
[52.49.141.129] - Installing Node.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Timed out while waiting for handshake
    at null._onTimeout (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Please provide solution as soon as possible i had seen previous post but not get right solution**

**Comment by MasterJames** [comment]
Changing the nodejs Version to 0.10.40 not 36 is required for Meteor 1.2 would be the first thing to suggest trying.

**Comment by edu2969** [comment]
Issue resolved. I was using public IP addres, then I replace for internal IP addres.
So, I replace mi public IP

"host": "172.xx.xx.xx"

by internal IP getting throw ifconfig like

"host": "192.168.x.xxx"

Im using Meteor 1.4.3.2 in Debian 8, with Node 4.6.2 y NPM 2.15.11

Good luck!
