### ISSUE TITLE
MongoError: driver is incompatible with this server version

### ISSUE THREAD

**Issue by yourcontainer** [arunoda/meteor-up-legacy#884]
How to fix it?

```
MongoError: driver is incompatible with this server version
[XXX.XXX.XX.XXX]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
[XXX.XXX.XX.XXX]     at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
[XXX.XXX.XX.XXX]     at packages/aldeed_schema-index/lib/indexing.js:17:1
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/boot.js:249:5
[XXX.XXX.XX.XXX]     - - - - -
[XXX.XXX.XX.XXX]     at Object.toError (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
[XXX.XXX.XX.XXX]     at __executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
[XXX.XXX.XX.XXX]     at Db._executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
[XXX.XXX.XX.XXX]     at Server.Base._callHandler (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
[XXX.XXX.XX.XXX]     at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
[XXX.XXX.XX.XXX]     at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

```

i do not change anything

**Comment by yourcontainer** [comment]
i fix this problem, i add unique: true prop to my field (using collection2 package)

**Comment by jykae** [comment]
We are getting the same error from our "_ensureIndex" function calls, mupx seems to install the latest mongo container (currently 3.2.6), and in development we have 2.6.7 (that Meteor currently provides). @yourcontainer You mean that you added "unique: true" to simple-schema field, right?

Do you know if there is anyway to select MongoDB version in mupx ?

**Comment by yourcontainer** [comment]
@jykae not, I deployed with "unique" key and get the error, without key no prob

**Comment by jykae** [comment]
@yourcontainer Thanks for fast answer!
We also took away "_ensureIndex" unique checks and deployment went then fine. 
Defining docker container versions in config would be really nice for nodeJS and mongoDB for mupx.

Waiting curiously for this: https://github.com/meteor/meteor/issues/6957
And also this: https://github.com/meteor/meteor/pull/6923

**Comment by yourcontainer** [comment]
@jykae sure, but meteor works only with specific versions, unfortunately

**Comment by MasterJames** [comment]
It would be wise to investigate a little deeper the new version ported to kadirahq/meteor-up and see if that helps.
The devs are there and can help resolve these new version issues with that version only. 
Otherwise you can deploy Mongo separately.

**Comment by jykae** [comment]
Made mup.json configuration option for selecting exact MongoDB version, https://github.com/arunoda/meteor-up/pull/1023 

Kadira has same default here, https://github.com/kadirahq/meteor-up/blob/master/src/modules/mongo/assets/mongo-start.sh

So trying that out would not solve database driver incompatibility.

**Comment by MasterJames** [comment]
Oh maybe your ready for the ApolloStack by Meteor. It's in Alpha though people are able to integrate different multiple database storeage systems.

**Comment by MasterJames** [comment]
No I think I was thinking you can customize the container with the new version.

**Comment by MasterJames** [comment]
[■ Sorry I was totally distracted by long weekend away.■]
Right 1023 Unfortunately I don't think any PRs have been acepted here for probably a year or 2. No devs with access are really monitoring this much.
These versions are depreciated so you will have to make your request and/or PR with the kadirahq version.
It's an easy fix though.

**Comment by jykae** [comment]
@MasterJames Yep, I can see that this repo is not quite monitored anymore. I could point out this issue and PR for kadirahq.
