### ISSUE TITLE
Bundling error on deployment

### ISSUE THREAD

**Issue by thekavish** [arunoda/meteor-up-legacy#885]
Hello @arunoda 
Many thanks for this great deployment tool. I however came across following error while deploying an application on digital ocean server.

```
Building Started: .
Bundling Error: code=2, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
23)
at defaultConfig
(/home/deligence/.meteor/packages/mquandalle_bower/.1.5.2_1.1vigcp2++os+web.browser+web.cordova/plugin.bower.os/npm/bower/node_modules/bower/lib/config.js:11:24)
at Object.<anonymous>
(/home/deligence/.meteor/packages/mquandalle_bower/.1.5.2_1.1vigcp2++os+web.browser+web.cordova/plugin.bower.os/npm/bower/node_modules/bower/lib/index.js:40:32)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1324:22)
at packages/bower/plugin/bower.js:1:1
at <runJavaScript-33>:38:4
at <runJavaScript-33>:326:3


/usr/local/lib/node_modules/mup/lib/build.sh: line 42: cd: /tmp/d7cc7948-c1cc-4a7c-b785-5aa1e617a710: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors26:3


/usr/local/lib/node_modules/mup/lib/build.sh: line 42: cd: /tmp/d7cc7948-c1cc-4a7c-b785-5aa1e617a710: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

I have installed certain applications to the droplets before, and never had this issue earlier. 
Please help with this "code=2" error. 
Thanks in advance.

**Comment by iboxgithub** [comment]
Same here, first time it happens...
