### ISSUE TITLE
Problems installing MUP on Mac

### ISSUE THREAD

**Issue by acamarata** [arunoda/meteor-up-legacy#909]
$ sudo npm install -g mup
npm http GET https://registry.npmjs.org/mup
npm http 304 https://registry.npmjs.org/mup
npm http GET https://registry.npmjs.org/cjson
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/nodemiral
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/archiver
npm ERR! Error: No compatible version found: async@'^0.9.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.18","0.1.19","0.1.20","0.1.21","0.1.22","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.6.1","0.6.2","0.7.0","0.8.0","0.9.0","0.9.2","1.0.0","1.1.0","1.2.0","1.1.1","1.2.1","1.3.0","1.4.0","1.4.1","1.4.2","1.5.0","1.5.1","1.5.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:676:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:591:10
npm ERR!     at RegClient.get_ (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "mup"
npm ERR! cwd /Users/acamarata
npm ERR! node -v v0.8.19
npm ERR! npm -v 1.2.10
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/archiver
npm http 304 https://registry.npmjs.org/nodemiral
npm http 304 https://registry.npmjs.org/cjson
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/acamarata/npm-debug.log
npm ERR! not ok code 0

**Comment by MasterJames** [comment]
I guess it says you need async.
Anyway you should try mupx the development branch. It's docker centric and avoids the kind of problem by using a container with the right things in it.
Also note that this is being ported to kadirahq and that version may work for you already. That's were you will find dev help in the form of fixes if needed.

**Comment by MasterJames** [comment]
Oh I meant to say only Ubuntu 14+ is officially supported.

**Comment by acamarata** [comment]
I tried installing async then mup again but the versions called by mup were
not compatible unless I change the installer to use a more recent version
like 1.5 or such.  It did seem that mup has not had any updates and I was
hoping it was not dropped or abandoned.  I will look at mupx since I want
something more recent.
