### ISSUE TITLE
mupx logs failing with meteor 1.3

### ISSUE THREAD

**Issue by snajjar** [arunoda/meteor-up-legacy#934]
Hello,

since the upgrade to meteor 1.3, mupx logs command is failing:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 46.101.222.35:22
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

**Comment by jujes** [comment]
I have the same issue ....
:(

**Comment by MasterJames** [comment]
Updating today should get you to 1.3.2.2 an official release, that is finally working better with the intended module npm plan.
Maybe redo your mupx completely with running setup again. 
Also try the official mupx port at kadirahq/meteor-up this version is depreciating and it was only built for meteor 1.2 anyway.

**Comment by yuyangchee98** [comment]
Hey, I'm having the same issue here, have you found your error?
