### ISSUE TITLE
MUPX Deployment Fails

### ISSUE THREAD

**Issue by jaycsjaycee** [arunoda/meteor-up-legacy#956]
Hi,

I'm not sure what's going on here. So I have deployed 8 droplets in digitalocean. 1 is mainly for database and the rest is for load balancing. On verifying deployment, I'm getting this error:

-----------------------------------STDERR-----------------------------------
    8)
        at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
        at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
        at fileEvaluate (packages/modules-runtime.js:158:9)
        - - - - -
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
        at [object Object].emit (events.js:106:17)
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:458:13)

```
=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

Here's my mup.json file:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "xxx",
      "username": "xx",
      "password": "xxx"
    },
    {
      "host": "xxx",
      "username": "xx",
      "password": "xxx"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  //"setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  //"nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  //"setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "appname",

  // Location of app (local directory)
  "app": "/Users/jayceec/desktop/MeteorApps/unify_2.0_new",

  // Configure environment
  "env": {
    "ROOT_URL": "http://appname.com",
    "MONGO_URL": "mongodb://123.45.67.89:27017/appname",
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 600
}
```

I tried setting the mongo to 'true' and it deployed successfully. However, it's not using the database on the other server.I'm not sure what I'm missing. TIA!

**Comment by MeXaaR** [comment]
hey,

did you find how to fix that? i'm facing the exact same thing and it's driving me crazy :)

thx

**Comment by jaycsjaycee** [comment]
I wasn't able to fix it. But for some weird reason, I used MUP instead of MUPX and it works.

**Comment by MeXaaR** [comment]
ha.... weird but... i'll try that and let you know!

**Comment by MeXaaR** [comment]
ok thanks, it's connecting corretly with mongodb now. i'd just like to know witch version of nodejs did you use with MUP please?
 Because i've got a problem of compatibility :/
