### ISSUE TITLE
MUPX Deployment Fails

### ISSUE THREAD

**Issue by mrk-i** [arunoda/meteor-up-legacy#957]
I have managed to setup mupx on two aws instances:
$ mupx setup

```

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Setup (linux)
[xx.xx.xx.xx] - Installing Docker
[xx.xx.xx.xx] - Installing Docker: SUCCESS
[xx.xx.xx.xx] - Setting up Environment
[xx.xx.xx.xx] - Setting up Environment: SUCCESS
[xx.xx.xx.xx] - Copying MongoDB configuration
[xx.xx.xx.xx] - Copying MongoDB configuration: SUCCESS
[xx.xx.xx.xx] - Installing MongoDB
[xx.xx.xx.xx] - Installing MongoDB: SUCCESS
```

Now when I try to deploy I am getting this error:
$ DEBUG=\* mupx deploy

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/me/my-meteor-deployment/app
Using buildOptions : {}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3

```

**Comment by mrk-i** [comment]
I managed to find out myself, it was not an issue with mupx :) .meteor directory was missing from application directory, I used finder (MAC) to copy files from uziped directory to application directory, it didn't copy hidden directories :(  ...when I used $meteor to run application, it didn't run...I figured out later that .meteor was missing from app directory.
