### ISSUE TITLE
mup fails to work with bcrypt

### ISSUE THREAD

**Issue by reduxdj** [arunoda/meteor-up-legacy#959]
I am not using npm-bcrypt and i get the same error - wow, deployments that don't work how infuriating. 

invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)[52.27.235.189] 
    at bindings (/opt/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt//app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[52.27.235.189] error: Forever detected script exited with code: 8
[52.27.235.189] error: Script restart attempt #13

**Comment by cranesandcaff** [comment]
Confirming. It's only an issue when I include Kadira.

**Comment by MasterJames** [comment]
https://github.com/kadirahq/meteor-up

**Comment by c9s** [comment]
I forked this repo and started a new project from this basis,  the deploy script will fix the bcrypt issue automatically

You can just install the mup from here https://github.com/c9s/meteor-up
