### ISSUE TITLE
mupx deploy ERROR ENOENT events.js:141

### ISSUE THREAD

**Issue by jujes** [arunoda/meteor-up-legacy#980]
After reinstall my OS and try whit node V5 and V4 
some one can tell how fix it? 
Production Quality Meteor Deployment??? but don't give any requisite for base deploy such as node v or npm tested version... 

**node v4.4.3**
**npm 2.15.1**

**mupx deploy**
**Error: spawn meteor ENOENT**
*_events.js:141
      throw er; // Unhandled 'error' event
      ^
*_

```
me@mux:~/up/dev/mup/x$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /home/me/up/dev/mup/dpl
Using buildOptions : {}
**events.js:141
      throw er; // Unhandled 'error' event
      ^
**
**Error: spawn meteor ENOENT**
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
me@mux:~/up/dev/mup/x$ **node -v
v4.4.3**
me@mux:~/up/dev/mup/x$ **npm -v
2.15.1**
me@mux:~/up/dev/mup/x$ ls -al
```

**Comment by MasterJames** [comment]
Kind of Strange because a meteor update today will install 1.3.2.2 and it's always bundled nodejs with it. It unfortunately doesn't have the newer version yet I don't think. Just Uninstaller nodejs and reinstall meteor and test the blank default project out.
There must be something else wrong possible the development OS itself ?  If you run docker with an Ubuntu 14+ instance it will remove ambiguity just for testing or tracking down your real problem.
Also please be aware of the current official mupx port at kadirahq/meteor-up as this version is depreciating.

**Comment by noyez** [comment]
Just as an FYI ... i ran into this error. My platform was OS X and i installed npm through macports. I Solved this error by installing meteor. For some inexplicable reason, i thought mupx installed meteor, but that isn't the case. Some kind of output information about the child process that failed would have been useful. I hope this helps anyone else that gets this error.

**Comment by gaurav999** [comment]
check your node version in mup.json file and replace it with your local node version
use node --version to check your node version in terminal/cmd
