### ISSUE TITLE
Error after updating to Node 6.0

### ISSUE THREAD

**Issue by ixdi** [arunoda/meteor-up-legacy#985]
Yesterday I deployed my app to AWS with mupx deploy without problems. 
Today after updating to Nodejs 6.0 on linux deploy failed with the error:

Using buildOptions : {}
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Readable.<anonymous> (/usr/lib/node_modules/mupx/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I thought that node version of linux system where independent of Meteor app node version. The app I'm deploing is the same, nothing changed between yesterday and today. Any suggestion? Thanks

**Comment by sizovilya** [comment]
use node 0.10.43

**Comment by ixdi** [comment]
Not necessary, Node 5.11 is ok but Node 6.0 is not, something broke mupx. Meteor is planning to go for Node 6.0 (LTS) so it would be great to resolve this issue.

**Comment by MasterJames** [comment]
What version of meteor are you using?  Maybe try updating Meteor to 1.3.2.2/4?

**Comment by ixdi** [comment]
I'm using Meteor 1.3.2.4 so this is not the cause.

**Comment by MasterJames** [comment]
Okay I see ;-( well try you luck with the port at kadirahq/meteor-up and maybe report back!
Otherwise this version is depreciated, and that one is the only way forward, so please make your issue known there, thanks.

**Comment by yubozhao** [comment]
I have open an issue in the new mup, here is the link
https://github.com/kadirahq/meteor-up/issues/113

**Comment by wdhif** [comment]
I can also confirm this issue for mupx https://github.com/arunoda/meteor-up/tree/mupx

**Comment by ghost** [comment]
I was getting this error, too.
(I am using differential:vulcanize package, btw. I was getting error while vulcanizing)

Solution -worked in my case-:
Installed nvm.
On server -> nvm install 0.10.36 (I am installing node manually)
On local -> nvm install 0.10.36

And mup setup is works now. -Deploying just now-

[EDIT]

> After deployment:
> [seabey.com] - Uploading bundle
> [seabey.com] - Uploading bundle: SUCCESS
> [seabey.com] - Setting up Environment Variables
> [seabey.com] - Setting up Environment Variables: SUCCESS
> [seabey.com] - Invoking deployment process
> [seabey.com] x Invoking deployment process: FAILED
> 
> sudo: npm: command not found

Anyway, i guess i passed this level. See you next issue.

[EDIT FROM TRANSOCEANIC]

I got some errors like `sudo npm command not found`,  `/var/../lock cannot be found`
Installing nodejs to server with mup now. I came back, again.
