### ISSUE TITLE
MONGO_URL not found; but it's there

### ISSUE THREAD

**Issue by dheerajbhaskar** [arunoda/meteor-up-legacy#989]
Hi guys,
Any help will be really appreciated. Feel free to ask for more info.
# Contents

1. [What I'm trying to do](#what-im-trying-to-do)
2. [Issue](#issue)
3. [Terminal output](#terminal-output)
4. [mup.js](#mupjs)
5. [settings.json](#settingsjson)

<a name="what-im-trying-to-do"></a>
# What I'm trying to do

I'm deploying from a windows machine using MingW32 and deployment is to a Ubuntu 16.04 LTS on Google Cloud.

I'm using mupx from https://github.com/arunoda/meteor-up/tree/mupx

<a name="issue"></a>
# Issue

My MONGO_URL is not getting picked up.

<a name="terminal-output"></a>
# Terminal output

Here's what I see in my command prompt; **Error at the end**:

```
Dheeraj@DESKTOP-P9VSJPN MINGW32 /c/my-home/ide-home/WebStormProjects/ibmh (adding-home-page)
$ mupx setup
\
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[<ip redacted>] - Installing Docker
[<ip redacted>] - Installing Docker: SUCCESS
[<ip redacted>] - Setting up Environment
[<ip redacted>] - Setting up Environment: SUCCESS

Dheeraj@DESKTOP-P9VSJPN MINGW32 /c/my-home/ide-home/WebStormProjects/ibmh (adding-home-page)
$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : C:\my-home\ide-home\WebStormProjects\ibmh
Using buildOptions : {}
packages/reactioncommerce_core-theme/ibmh/css/master.css: warn: @charset rules in this file will be ignored as UTF-8 is the only encoding supported

Started TaskList: Deploy app 'ibmh' (linux)
[<ip redacted>] - Uploading bundle
[<ip redacted>] - Uploading bundle: SUCCESS
[<ip redacted>] - Sending environment variables
[<ip redacted>] - Sending environment variables: SUCCESS
[<ip redacted>] - Initializing start script
[<ip redacted>] - Initializing start script: SUCCESS
[<ip redacted>] - Invoking deployment process
[<ip redacted>] - Invoking deployment process: SUCCESS
[<ip redacted>] - Verifying deployment
[<ip redacted>] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        eor-promise

        promise@7.0.4 node_modules/promise

        source-map-support@0.3.2 node_modules/source-map-support

        semver@4.1.0 node_modules/semver

        source-map@0.1.32 node_modules/source-map

        fibers@1.0.5 node_modules/fibers
        => Starting meteor app on port:80

        /bundle/bundle/programs/server/node_modules/fibers/future.js:245
                                                        throw(ex);
                                                              ^
        Error: MONGO_URL must be set in environment
            at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
            at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
            at new Mongo.Collection (packages/mongo/collection.js:102:1)
            at AccountsServer.AccountsCommon (accounts_common.js:23:18)
            at new AccountsServer (accounts_server.js:16:5)
            at Package (globals_server.js:5:12)
            at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
            at /bundle/bundle/programs/server/packages/accounts-base.js:1825:3
            at /bundle/bundle/programs/server/boot.js:242:10
            at Array.forEach (native)
        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------

Dheeraj@DESKTOP-P9VSJPN MINGW32 /c/my-home/ide-home/WebStormProjects/ibmh (adding-home-page)
$ mupx logs --tail

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[<ip redacted>] docker: "logs" requires 1 argument.
See 'docker logs --help'.
[<ip redacted>]
Usage:  docker logs [OPTIONS] CONTAINER[<ip redacted>]

Fetch the logs of a container

Dheeraj@DESKTOP-P9VSJPN MINGW32 /c/my-home/ide-home/WebStormProjects/ibmh (adding-home-page)
$ mupx logs --tail=50

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[<ip redacted>] => Starting meteor app on port:80
[<ip redacted>] Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
    at /bundle/bundle/programs/server/packages/accounts-base.js:1825:3
    at /bundle/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/bundle/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
    at /bundle/bundle/programs/server/packages/accounts-base.js:1825:3
    at /bundle/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)

Dheeraj@DESKTOP-P9VSJPN MINGW32 /c/my-home/ide-home/WebStormProjects/ibmh (adding-home-page)
$
```

<a name="mupjs"></a>
# mup.js

```
{
  // Server authentication info
  "servers": [
    {
      "host": "<ip redacted>",
      "username": "ibmh",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      "pem": "~/.ssh/id_rsa_ibmh_gcloud",
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,

  // Application name (no spaces).
  "appName": "ibmh",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "C:\\my-home\\ide-home\\WebStormProjects\\ibmh",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://<ip redacted>/"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

<a name="settingsjson"></a>
# settings.json

```
{
  "ROOT_URL": "",
  "MONGO_URL": "<redacted>",
  "MAIL_URL": "<redacted>",
  "reaction": {
    "REACTION_USER": "ibmh",
    "REACTION_AUTH": "ibmh",
    "REACTION_EMAIL": "ibmh@ibidmyhome.com"
  },
  "isDebug": "info",
  "public": {}
}
```

**Comment by dheerajbhaskar** [comment]
Just checked the env vars on the VM:

```
dheerajthe1@ibmh-prod-1:~$ echo $MONGO_URL
dheerajthe1@ibmh-prod-1:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dheerajthe1@ibmh-prod-1:~$ echo $MAIL_URL
dheerajthe1@ibmh-prod-1:~$ 
```

Looks like none of the vars got set. Is this weirdly because I set `"setupMongo": false,` ?

This is the output of `printenv`:

```
XDG_SESSION_ID=7
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=173.194.93.100 60656 22
SSH_TTY=/dev/pts/0
USER=dheerajthe1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41
:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*
.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;3
1:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*
.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;
31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp
=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:
*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm
=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*
.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35
:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=0
0;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.
spx=00;36:*.xspf=00;36:
SSH_AUTH_SOCK=/tmp/ssh-oosdRzqmFg/agent.17841
MAIL=/var/mail/dheerajthe1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/dheerajthe1
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/dheerajthe1
LOGNAME=dheerajthe1
SSH_CONNECTION=173.194.93.100 60656 10.240.0.2 22
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1003
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
```

**Comment by dheerajbhaskar** [comment]
I tried deployment from commandline (cmd.exe). Same issue. Here's the output:

```
C:\my-home\ide-home\WebStormProjects\ibmh>mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : C:\my-home\ide-home\WebStormProjects\ibmh
Using buildOptions : {}
packages/reactioncommerce_core-theme/ibmh/css/master.css: warn: @charset rules in this file will be ignored as UTF-8 is the only
 encoding supported

Started TaskList: Deploy app 'ibmh' (linux)
[<ip redacted>] - Uploading bundle
[<ip redacted>] - Uploading bundle: SUCCESS
[<ip redacted>] - Sending environment variables
[<ip redacted>] - Sending environment variables: SUCCESS
[<ip redacted>] - Initializing start script
[<ip redacted>] - Initializing start script: SUCCESS
[<ip redacted>] - Invoking deployment process
[<ip redacted>] - Invoking deployment process: SUCCESS
[<ip redacted>] - Verifying deployment
[<ip redacted>] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------


        source-map-support@0.3.2 node_modules/source-map-support

        semver@4.1.0 node_modules/semver

        source-map@0.1.32 node_modules/source-map

        fibers@1.0.5 node_modules/fibers
        => Starting meteor app on port:80

        /bundle/bundle/programs/server/node_modules/fibers/future.js:245
                                                        throw(ex);
                                                              ^
        Error: MONGO_URL must be set in environment
            at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
            at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
            at new Mongo.Collection (packages/mongo/collection.js:102:1)
            at AccountsServer.AccountsCommon (accounts_common.js:23:18)
            at new AccountsServer (accounts_server.js:16:5)
            at Package (globals_server.js:5:12)
            at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
            at /bundle/bundle/programs/server/packages/accounts-base.js:1825:3
            at /bundle/bundle/programs/server/boot.js:242:10
            at Array.forEach (native)

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------
```

**Comment by dheerajbhaskar** [comment]
I'm going to manually set the env vars to get this to work, but I hope you understand that that's not at all ideal.

Edit: Oh wait! I totally forgot that mupx uses docker; also I don't think I explicitly mentioned that I'm using mupx, let me edit my 1st comment

**Comment by dheerajbhaskar** [comment]
I tried to fiddle with the containers, this output was unexpected. What am I doing wrong?

```
dheerajthe1@ibmh-prod-1:~$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by dheerajbhaskar** [comment]
I was checking the setup-env.sh and checked the env vars file generated. Here it is:

```
ROOT_URL=<redacted>
#it is possible to override above env-vars from the user-provided values
  ROOT_URL=<redacted>
  METEOR_SETTINGS=<redacted>
  CLUSTER_ENDPOINT_URL=<redacted>
```

As expected, the MONGO_URL was missing. This must be a script error somewhere. For the time being I'm planning to edit this file to add MONGO_URL.

**Comment by dheerajbhaskar** [comment]
Adding MONGO_URL manually to env.list made the app work. I plan to figure out why it wasn't there in the first place. I will give a PR if I figure out.

Please help out if possible.

**Comment by MasterJames** [comment]
Ya I was just going to say "env" but you should know the new version is at kadirahq/meteor-up if you plan to submit any PRs. These are depreciated by it.

**Comment by dheerajbhaskar** [comment]
Would you suggest I use the new version?
Is it usable enough for production?
Also, Is this bug fixed there?

**Comment by MasterJames** [comment]
I'm uncertain. Let me know your experience but it's certainly the way forward.
It's in flux so it's not as "stable" in a sense, as it is in a state of transformation.
They're are the devs so they will be able to help sort out what issue is at fault.

**Comment by dheerajbhaskar** [comment]
Okay, let me check out the new version then.

Thanks for the quick replies so far James.

**Comment by ianmartorell** [comment]
You're setting your environment variables in `settings.json`, and you should be setting them under `env` in `mup.js`, along with the `PORT` and `ROOT_URL`. That's why it's not picking them up.

**Comment by dheerajbhaskar** [comment]
@ianmartorell Oh, I thought that was if we needed any custom env for a particular server. That's because the comment reads as follows:

```
  // server specific environment variables
  "env": {}
```

I shall try this. Thanks.

**Comment by dheerajbhaskar** [comment]
This worked. Thanks
