### ISSUE TITLE
Forever detected script exited with code: 8

### ISSUE THREAD

**Issue by wrichman** [arunoda/meteor-up-legacy#997]
[107.170.31.236]     at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/production/app/programs/server/boot.js:182:18)
    at Package (packages/npm-bcrypt/wrapper.js:1:1)
    at packages/npm-bcrypt/wrapper.js:1:1
    at packages/npm-bcrypt/wrapper.js:1:1
error: Forever detected script exited with code: 8
error: Script restart attempt #96
[107.170.31.236]
[107.170.31.236] /opt/production/app/programs/server/node_modules/fibers/future.js:267[107.170.31.236]
[107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236] throw(ex);[107.170.31.236]
[107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236] ^[107.170.31.236]
[107.170.31.236] Error: /opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[107.170.31.236]
[107.170.31.236]     at Module.load (module.js:356:32)[107.170.31.236]
[107.170.31.236]     at Function.Module._load (module.js:312:12)[107.170.31.236]
[107.170.31.236]     at Module.require (module.js:364:17)[107.170.31.236]
[107.170.31.236]     at require (module.js:380:17)[107.170.31.236]
[107.170.31.236]     at bindings (/opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)[107.170.31.236]
[107.170.31.236]     at Object.<anonymous> (/opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[107.170.31.236]
[107.170.31.236]     at Module._compile (module.js:456:26)[107.170.31.236]
[107.170.31.236]     at Object.Module._extensions..js (module.js:474:10)[107.170.31.236]
[107.170.31.236]     at Module.load (module.js:356:32)[107.170.31.236]
[107.170.31.236]     at Function.Module._load (module.js:312:12)[107.170.31.236]
[107.170.31.236]     at Module.require (module.js:364:17)[107.170.31.236]
[107.170.31.236]     at require (module.js:380:17)[107.170.31.236]
[107.170.31.236]     at Object.Npm.require (/opt/production/app/programs/server/boot.js:182:18)[107.170.31.236]
[107.170.31.236]     at Package (packages/npm-bcrypt/wrapper.js:1:1)[107.170.31.236]
[107.170.31.236]     at packages/npm-bcrypt/wrapper.js:1:1[107.170.31.236]
[107.170.31.236]     at packages/npm-bcrypt/wrapper.js:1:1[107.170.31.236]
[107.170.31.236] error: Forever detected script exited with code: 8[107.170.31.236]
[107.170.31.236] error: Script restart attempt #97[107.170.31.236]
[107.170.31.236]
[107.170.31.236] /opt/production/app/programs/server/node_modules/fibers/future.js:267[107.170.31.236]
[107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236] throw(ex);[107.170.31.236]
[107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]    [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236]  [107.170.31.236] ^[107.170.31.236]
[107.170.31.236] Error: /opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[107.170.31.236]
[107.170.31.236]     at Module.load (module.js:356:32)[107.170.31.236]
[107.170.31.236]     at Function.Module._load (module.js:312:12)[107.170.31.236]
[107.170.31.236]     at Module.require (module.js:364:17)[107.170.31.236]
[107.170.31.236]     at require (module.js:380:17)[107.170.31.236]
[107.170.31.236]     at bindings (/opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)[107.170.31.236]
[107.170.31.236]     at Object.<anonymous> (/opt/production/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[107.170.31.236]
[107.170.31.236]     at Module._compile (module.js:456:26)[107.170.31.236]
[107.170.31.236]     at Object.Module._extensions..js (module.js:474:10)[107.170.31.236]
[107.170.31.236]     at Module.load (module.js:356:32)[107.170.31.236]
[107.170.31.236]     at Function.Module._load (module.js:312:12)[107.170.31.236]
[107.170.31.236]     at Module.require (module.js:364:17)[107.170.31.236]
[107.170.31.236]     at require (module.js:380:17)[107.170.31.236]
[107.170.31.236]     at Object.Npm.require (/opt/production/app/programs/server/boot.js:182:18)[107.170.31.236]
[107.170.31.236]     at Package (packages/npm-bcrypt/wrapper.js:1:1)[107.170.31.236]
[107.170.31.236]     at packages/npm-bcrypt/wrapper.js:1:1[107.170.31.236]
[107.170.31.236]     at packages/npm-bcrypt/wrapper.js:1:1[107.170.31.236]
[107.170.31.236] error: Forever detected script exited with code: 8[107.170.31.236]

**Comment by focused** [comment]
I get the same error

**Comment by c9s** [comment]
I forked this repo and started a new project from this basis,  the deploy script will fix the bcrypt issue automatically

You can just install the mup from here https://github.com/c9s/meteor-up
